# -*- coding: utf-8 -*-
# 리노베이션 사례(reno1~3 + the-mills-hk, bluecity-rotterdam) 공식 홈페이지 — 2026-10-04 접속 확인
H = {
    "tate-modern": [{"t": "Tate Modern (Tate 공식)", "u": "https://www.tate.org.uk/visit/tate-modern"}],
    "zeitz-mocaa": [{"t": "Zeitz MOCAA (공식 사이트)", "u": "https://zeitzmocaa.museum/"}],
    "elbphilharmonie": [{"t": "Elbphilharmonie Hamburg (공식 사이트)", "u": "https://www.elbphilharmonie.de/"}],
    "musee-dorsay": [{"t": "Musée d'Orsay (공식 사이트)", "u": "https://www.musee-orsay.fr/"}],
    "caixaforum-madrid": [{"t": "CaixaForum Madrid (공식 사이트)", "u": "https://caixaforum.org/es/madrid"}],
    "fondazione-prada": [{"t": "Fondazione Prada (공식 사이트)", "u": "https://www.fondazioneprada.org/"}],
    "the-silo-copenhagen": [{"t": "The Silo (공식 분양 사이트)", "u": "http://thesilo.dk/"},
                            {"t": "By & Havn (노르하운 개발공사)", "u": "https://byoghavn.dk/"}],
    "westergasfabriek": [{"t": "Westergas (공식 사이트)", "u": "https://westergas.nl/"}],
    "sapporo-factory": [{"t": "サッポロファクトリー (공식 사이트)", "u": "https://sapporofactory.jp/"}],
    "lingotto": [{"t": "Lingotto Fiere", "u": "https://www.lingottofiere.it/"},
                 {"t": "Pinacoteca Agnelli", "u": "https://www.pinacoteca-agnelli.it/"},
                 {"t": "Centro Commerciale Lingotto", "u": "https://www.centrocommercialelingotto.it/"}],
    "zollverein": [{"t": "UNESCO-Welterbe Zollverein (공식 사이트)", "u": "https://www.zollverein.de/"}],
    "battersea-power-station": [{"t": "Battersea Power Station (공식 사이트)", "u": "https://batterseapowerstation.co.uk/"}],
    "grand-parc-r": [{"t": "aquitanis (보르도 메트로폴 공공임대주택청, 발주·운영)", "u": "https://www.aquitanis.fr/"}],
    "de-hallen": [{"t": "De Hallen Amsterdam (공식 사이트)", "u": "https://www.dehallen-amsterdam.nl/"}],
    "ndsm": [{"t": "NDSM-Werf Amsterdam (공식 사이트)", "u": "https://www.ndsm.nl/"}],
    "chq-epic": [{"t": "EPIC The Irish Emigration Museum (공식 사이트)", "u": "https://epicchq.com/"}],
    "viaduc-des-arts": [{"t": "Le Viaduc des Arts (공식 사이트)", "u": "https://www.leviaducdesarts.com/"}],
    "bercy-village": [{"t": "Bercy Village (공식 사이트)", "u": "https://www.bercyvillage.com/"}],
    "matadero-madrid": [{"t": "Matadero Madrid (공식 사이트)", "u": "https://www.mataderomadrid.org/"}],
    "vienna-gasometers": [{"t": "Gasometer Wien (공식 사이트)", "u": "https://gasometer.at/"}],
    "huashan-1914": [{"t": "華山1914文化創意產業園區 (공식 사이트)", "u": "https://www.huashan1914.com/"}],
    "tai-kwun": [{"t": "Tai Kwun 大館 (공식 사이트)", "u": "https://www.taikwun.hk/"}],
    "chelsea-market": [{"t": "Chelsea Market (공식 사이트)", "u": "https://www.chelseamarket.com/"}],
    "ponce-city-market": [{"t": "Ponce City Market (공식 사이트)", "u": "https://poncecitymarket.com/"}],
    "mass-moca": [{"t": "MASS MoCA (공식 사이트)", "u": "https://massmoca.org/"}],
    "landschaftspark-duisburg": [{"t": "Landschaftspark Duisburg-Nord (공식 사이트)", "u": "https://www.landschaftspark.de/"}],
    "yokohama-red-brick": [{"t": "横浜赤レンガ倉庫 (공식 사이트)", "u": "https://www.yokohama-akarenga.jp/"}],
    "coal-drops-yard": [{"t": "Coal Drops Yard (King's Cross 공식)", "u": "https://www.kingscross.co.uk/coal-drops-yard"},
                        {"t": "King's Cross (공식 사이트)", "u": "https://www.kingscross.co.uk/"}],
    "seonyudo-park": [{"t": "선유도공원 (서울의 공원 · 서울시)", "u": "https://parks.seoul.go.kr/content.do?key=2604300019"}],
    "oil-tank-culture-park": [{"t": "문화비축기지 (서울의 공원 · 서울시)", "u": "https://parks.seoul.go.kr/content.do?key=2604300014"}],
    "bourse-de-commerce": [{"t": "Bourse de Commerce — Pinault Collection (공식 사이트)", "u": "https://www.pinaultcollection.com/fr/boursedecommerce"}],
    "palais-de-tokyo": [{"t": "Palais de Tokyo (공식 사이트)", "u": "https://palaisdetokyo.com/"}],
    "frac-dunkerque": [{"t": "Frac Grand Large — Hauts-de-France (공식 사이트)", "u": "https://www.fracgrandlarge-hdf.fr/"}],
    "gemini-residence": [{"t": "E/F Gemini Residence (입주자 소유자회 사이트)", "u": "https://www.geminiresidence.dk/"}],
    "high-line": [{"t": "The High Line (Friends of the High Line 공식)", "u": "https://www.thehighline.org/"}],
    "gasholders-kings-cross": [{"t": "Gasholders London (공식 사이트)", "u": "https://gasholderslondon.co.uk/"},
                               {"t": "King's Cross (공식 사이트)", "u": "https://www.kingscross.co.uk/"}],
    "granary-building": [{"t": "Central Saint Martins (UAL 공식)", "u": "https://www.arts.ac.uk/colleges/central-saint-martins"},
                         {"t": "King's Cross (공식 사이트)", "u": "https://www.kingscross.co.uk/"}],
    "la-fabrica-bofill": [{"t": "Bofill Taller de Arquitectura — La Fábrica", "u": "https://www.bofill.com/la-fabrica/"}],
    "sesc-pompeia": [{"t": "Sesc Pompeia (Sesc São Paulo 공식)", "u": "https://www.sescsp.org.br/unidades/pompeia/"}],
    "lx-factory": [{"t": "LX Factory (공식 사이트)", "u": "https://lxfactory.com/"}],
    "ghirardelli-square": [{"t": "Ghirardelli Square (공식 사이트)", "u": "https://www.ghirardellisq.com/"}],
    "seoullo-7017": [{"t": "Seoullo 7017 (서울특별시 영문 안내)", "u": "https://english.seoul.go.kr/seoullo-7017-3/"}],
    "culture-station-seoul-284": [{"t": "문화역서울284 (공식 사이트)", "u": "https://www.seoul284.org/"}],
    "mmca-seoul": [{"t": "국립현대미술관 (공식 사이트)", "u": "https://www.mmca.go.kr/"}],
    "songshan-park": [{"t": "松山文創園區 (공식 사이트)", "u": "https://www.songshanculturalpark.org/"}],
    "pmq-hong-kong": [{"t": "PMQ 元創方 (공식 사이트)", "u": "https://www.pmq.org.hk/"}],
    "silo-468": [{"t": "Kruunuvuorenranta (Helsingin kaupunki)", "u": "https://www.hel.fi/en/urban-environment-and-traffic/urban-planning-and-construction/urban-development/kruunuvuorenranta"}],
    "the-mills-hk": [{"t": "The Mills 南豐紗廠 (공식 사이트)", "u": "https://www.themills.com.hk/"}],
    "bluecity-rotterdam": [{"t": "BlueCity (공식 사이트)", "u": "https://www.bluecity.nl/"}],
}

NOTE = {
    "neues-museum-r": "smb.museum(베를린 국립박물관) 이 컴퓨터에서 접속 시간 초과 — 확인 못 해 뺌",
    "hamburger-bahnhof": "smb.museum · hamburgerbahnhof.de 접속 시간 초과 — 확인 못 해 뺌",
    "dia-beacon": "diaart.org 가 Cloudflare 봇 확인 화면만 보여 내용 확인 못 함 — 뺌",
    "kraanspoor": "kraanspoor.nl 접속 안 됨(연결 실패), 다른 공식 사이트 없음",
    "old-millfun-1933": "옛 공식 1933laochangfang.com.cn 도메인 소멸, 1933shanghai.com 도 접속 안 됨",
    "seoullo-7017": "전용 사이트 seoullo7017.seoul.go.kr 폐쇄(도메인 없음) — 서울시 영문 안내 페이지로 대체",
    "the-silo-copenhagen": "thesilo.dk 는 https 안 되고 http 만 열림(분양 안내 페이지)",
    "grand-parc-r": "사업 전용 사이트 없음 — 발주·운영 기관(aquitanis) 첫 화면",
    "silo-468": "시설 전용 사이트 없음 — 헬싱키시 지구 개발 페이지(Öljysäiliö 468 언급)",
    "gemini-residence": "사업 사이트 없음 — 건물 소유자회(E/F) 사이트만 있음",
}
