# -*- coding: utf-8 -*-
# 도시재생 사례 공식 홈페이지 (2026-10-04 직접 열어 확인)
H = {
 "22at-barcelona": [{"t": "22@Barcelona: The innovation district (Ajuntament de Barcelona)", "u": "https://www.barcelona.cat/internationalwelcome/en/do-business/strategic-sectors-and-areas/22barcelona-innovation-district"}],
 "strijp-s": [{"t": "Strijp-S (공식 사이트)", "u": "https://www.strijp-s.nl/"}],
 "hafencity": [{"t": "HafenCity Hamburg GmbH", "u": "https://www.hafencity.com/"}],
 "kings-cross": [{"t": "King's Cross (공식 사이트)", "u": "https://www.kingscross.co.uk/"}],
 "london-docklands": [{"t": "Canary Wharf (공식 사이트)", "u": "https://canarywharf.com/"},
                      {"t": "London Museum Docklands", "u": "https://www.londonmuseum.org.uk/docklands/"}],
 "dublin-docklands": [{"t": "EPIC The Irish Emigration Museum (CHQ)", "u": "https://epicchq.com/"}],
 "abandoibarra": [{"t": "Bilbao Ría 2000", "u": "https://www.bilbaoria2000.org/"},
                  {"t": "Itsasmuseum Bilbao", "u": "https://www.itsasmuseum.eus/"}],
 "lyon-confluence": [{"t": "Lyon Confluence (SPL Lyon Confluence)", "u": "https://www.lyon-confluence.fr/"}],
 "vastra-hamnen": [{"t": "Västra Hamnen (Malmö stad)", "u": "https://malmo.se/Stadsutveckling/Stadsutvecklingsomraden/Vastra-Hamnen.html"}],
 "minato-mirai-21": [{"t": "みなとみらい21 (公式)", "u": "https://minatomirai21.com/"},
                     {"t": "横浜みなとみらい21 (一般社団法人)", "u": "https://ymm21.jp/"}],
 "g-valley": [{"t": "G밸리산업박물관 (서울시)", "u": "https://www.seoul.go.kr/museumg/"},
              {"t": "G-밸리 (금천구청)", "u": "https://www.geumcheon.go.kr/portal/contents.do?key=2268"}],
 "brooklyn-navy-yard": [{"t": "Brooklyn Navy Yard", "u": "https://brooklynnavyyard.org/"},
                        {"t": "Newlab", "u": "https://www.newlab.com/"}],
 "adlershof": [{"t": "Adlershof (WISTA Management)", "u": "https://www.adlershof.de/"}],
 "kendall-square": [{"t": "Kendall Square Association", "u": "https://kendallsquare.org/"}],
 "one-north": [{"t": "one-north (JTC)", "u": "https://www.jtc.gov.sg/find-land/jtc-key-estates/one-north/"}],
 "west-bund": [{"t": "西岸 WEST BUND", "u": "https://www.westbund.com/"}],
 "beijing-798": [{"t": "798艺术区 798 Art District (北京七九八)", "u": "https://www.798artdistrict.com.cn/"}],
 "seongsu": [{"t": "성수동 도시재생사업 (성동구)", "u": "https://www.sd.go.kr/main/contents.do?key=4013"}],
 "emscher-park": [{"t": "Route der Industriekultur", "u": "https://www.route-industriekultur.ruhr/"},
                  {"t": "UNESCO-Welterbe Zollverein", "u": "https://www.zollverein.de/"},
                  {"t": "Landschaftspark Duisburg-Nord", "u": "https://www.landschaftspark.de/"}],
 "m4h-rdm-rotterdam": [{"t": "M4H Rotterdam", "u": "https://m4hrotterdam.nl/"},
                       {"t": "RDM Rotterdam", "u": "https://www.rdmrotterdam.nl/"}],
 "kowloon-east": [{"t": "Energizing Kowloon East Office (起動九龍東)", "u": "https://www.ekeo.gov.hk/"}],
 "paris-rive-gauche": [{"t": "SEMAPA (Paris Rive Gauche)", "u": "https://www.semapa.fr/"}],
 "ile-de-nantes": [{"t": "Île de Nantes (SAMOA)", "u": "https://www.iledenantes.com/"},
                   {"t": "Les Machines de l'île", "u": "https://www.lesmachines-nantes.fr/"}],
 "nordhavn": [{"t": "Nordhavn (By & Havn)", "u": "https://byoghavn.dk/nordhavn/"}],
 "hammarby-sjostad": [{"t": "Stadsutvecklingsområde Hammarby sjöstad (Stockholms stad)", "u": "https://vaxer.stockholm/omraden/stadsutvecklingsomraden/stadsutvecklingsomrade-hammarby-sjostad"}],
 "port-vell": [{"t": "Port de Barcelona", "u": "https://www.portdebarcelona.cat/"}],
 "ancoats-manchester": [{"t": "Ancoats (Manchester City Council)", "u": "https://www.manchester.gov.uk/planning-and-regeneration/regeneration/projects-outside-the-city-centre/ancoats"}],
 "granville-island": [{"t": "Granville Island", "u": "https://granvilleisland.com/"}],
 "pearl-district": [{"t": "Pearl District Neighborhood Association", "u": "https://pearldistrict.org/"}],
 "south-lake-union": [{"t": "South Lake Union Community Council", "u": "https://www.slucommunitycouncil.org/"}],
 "shougang-park": [{"t": "首钢园区 (首钢集团)", "u": "https://www.shougang.com.cn/p1/sgyq.html"}],
 "yangpu-riverside": [{"t": "杨浦滨江公共空间 (上海市杨浦区人民政府)", "u": "https://www.shyp.gov.cn/shypq/tzypkjbj/20241127/468963.html"}],
 "mullae": [{"t": "문래예술공장 (서울문화재단)", "u": "https://www.sfac.or.kr/artspace/artspace/mullae_main.do"},
            {"t": "문래창작촌 (영등포구 문화관광)", "u": "https://www.ydp.go.kr/tour/contents.do?key=5313"}],
 "oct-loft": [{"t": "华侨城创意文化园 OCT-LOFT", "u": "https://www.octloft.cn/"}],
 "duisburg-inner-harbour": [{"t": "Duisburger Innenhafen (Stadt Duisburg)", "u": "https://www.duisburg.de/tourismus/stadt_erleben/industriekultur/duisburger-innenhafen"}],
 "toyosu": [{"t": "豊洲2・3丁目地区まちづくり協議会", "u": "https://www.toyosu.org/"}],
 "zorrotzaurre": [{"t": "Zorrotzaurre (Comisión Gestora)", "u": "https://www.zorrotzaurre.com/"}],
 "albert-dock-liverpool": [{"t": "Royal Albert Dock Liverpool", "u": "https://albertdock.com/"}],
 "castlefield-manchester": [{"t": "Castlefield Forum", "u": "https://www.ourcastlefield.co.uk/"},
                            {"t": "Castlefield Viaduct (National Trust)", "u": "https://www.nationaltrust.org.uk/visit/cheshire-greater-manchester/castlefield-viaduct"},
                            {"t": "Science and Industry Museum", "u": "https://www.scienceandindustrymuseum.org.uk/"}],
 "titanic-quarter": [{"t": "Titanic Quarter Belfast", "u": "https://titanicquarter.com/"},
                     {"t": "Titanic Belfast", "u": "https://www.titanicbelfast.com/"}],
 "lowell-mills": [{"t": "Lowell National Historical Park (NPS)", "u": "https://www.nps.gov/lowe/"}],
 "singapore-river-quays": [{"t": "Singapore River One", "u": "https://www.singapore-river.sg/"},
                           {"t": "Singapore River One (URA BID)", "u": "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"}],
 "distillery-district": [{"t": "The Distillery Historic District", "u": "https://www.thedistillerydistrict.com/"}],
 "incheon-gaehangjang": [{"t": "인천아트플랫폼", "u": "https://inartplatform.kr/"}],
 "gunsan-old-town": [{"t": "시간여행마을 (군산시 문화관광)", "u": "https://www.gunsan.go.kr/tour/m2748"}],
 "parco-dora-turin": [{"t": "Parco Dora Spina 3 (Città di Torino)", "u": "https://www.comune.torino.it/schede-informative/monitoraggi-ambientali-parco-dora-spina-3"}],
 "kelham-island": [{"t": "Sheffield Museums Trust (Kelham Island Museum)", "u": "https://www.sheffieldmuseums.org.uk/"}],
 "liberty-village": [{"t": "Liberty Village BIA", "u": "https://www.libertyvillagebia.com/"}],
 "m50-shanghai": [{"t": "M50 Creative Park (上海市人民政府)", "u": "https://english.shanghai.gov.cn/en-ScenicSpots/20231208/4a9c2830891541c68fb5b3143964eec8.html"},
                  {"t": "M50 Creative Park (普陀区)", "u": "https://english.shpt.gov.cn/living/entertainment/994.shtml"}],
 "bridge8-shanghai": [{"t": "The Bridge 8 (黄浦区人民政府)", "u": "https://english.shhuangpu.gov.cn/2021-04/26/c_433.htm"}],
 "redtown-shanghai": [{"t": "Redtown: A Creative Park (长宁区人民政府)", "u": "https://www.shcn.gov.cn/english/col1666/20220106/1208625.html"}],
 "ndsm-amsterdam-noord": [{"t": "NDSM-werf", "u": "https://www.ndsm.nl/"}],
 "high-tech-campus-eindhoven": [{"t": "High Tech Campus Eindhoven", "u": "https://www.hightechcampus.com/"}],
}
NOTE = {
 "22at-barcelona": "22barcelona.com 은 SSL 오류(503)로 열리지 않음 — 시청 페이지만 넣음",
 "dublin-docklands": "dublindocklands.ie (DCC 도클랜즈 사무소) 접속 시간 초과 — CHQ 의 EPIC 만 넣음",
 "eastern-docklands-amsterdam": "사업 전용 공식 사이트 없음 (amsterdam.nl 일반 페이지뿐)",
 "false-creek-north": "vancouver.ca 가 봇 차단(Cloudflare)으로 열어 확인 못 함 — 비움",
 "tianzifang": "공식 사이트 없음 (tianzifang.cn 접속 안 됨)",
 "incheon-gaehangjang": "icjg.go.kr(옛 중구) 개항장 페이지가 영종구청 첫 화면으로 넘어감 (2026 구 분리) — 아트플랫폼만",
 "pearl-district": "explorethepearl.com (상인회) 접속 안 됨",
 "shougang-park": "shougangpark.com 접속 안 됨 — 수도강철 그룹 페이지로",
 "kelham-island": "simt.co.uk 박물관 페이지 접속 안 됨 — 운영 재단 첫 화면",
 "m50-shanghai": "m50.com.cn 은 404 — 시·구 정부 소개 페이지로",
 "bridge8-shanghai": "bridge8.com 은 다른 사이트(스포츠 점수)로 넘어감 — 황푸구 정부 페이지로",
 "redtown-shanghai": "redtown570.com 접속 안 됨 — 창닝구 정부 페이지로",
 "eka-shanghai": "공식 사이트 못 찾음 (eka.com.cn 접속 안 됨)",
 "2577-shanghai": "공식 사이트 없음 (2577.com.cn 접속 안 됨)",
 "shangjie-loft-shanghai": "공식 사이트 없음 (sjloft.cn 은 사무실 임대 중개 사이트)",
 "singapore-river-quays": "clarkequay.com.sg 접속 안 됨",
}
