# -*- coding: utf-8 -*-
# 나라별 노후 산업지역 재생 · 활용 지원정책 — 배정 04 : 미국 · 캐나다
P = [
{"nat": "미국", "en": "United States",
 "summary": "연방 정부는 오염 부지 정화 보조금 (EPA 브라운필드), 역사건물 재생 세액공제, 기회특구 양도차익 과세 이연처럼 \"돈과 세금\"으로 노후 산업지역 재생을 거들고, 토지이용 규제는 시 · 주 정부가 맡습니다. 그래서 도시마다 접근이 갈립니다 — 시카고 · 포틀랜드 · 시애틀 · 뉴욕은 남은 산업용지를 조닝으로 지키면서 일부 전환지에는 부담금 · 보너스를 걸어 산업 쪽으로 돈과 공간을 되돌리는 방식을 쓰고, 케임브리지 켄들 스퀘어처럼 옛 공업지를 혁신지구로 바꾸면서 창업 공간 의무를 붙이는 곳도 있습니다.",
 "items": [
  {"name": "연방 브라운필드 프로그램 (EPA Brownfields Program)", "year": "1995 (2002 법제화, 2021 인프라법 증액)", "level": "국가 (연방 환경보호청 EPA)",
   "law": "소기업 책임완화 및 브라운필드 재활성화법 (Small Business Liability Relief and Brownfields Revitalization Act, Public Law 107-118, 2002.1.11) · CERCLA 제104조(k) · 인프라 투자 및 일자리법 (Bipartisan Infrastructure Law, 2021)",
   "what": "옛 공장 · 주유소처럼 오염이 의심돼 쓰이지 못하는 땅 (브라운필드)을 조사 · 정화해 다시 개발 시장에 내놓도록 지자체 · 주 · 비영리단체에 보조금과 회전대출 재원을 줍니다. 2002년 법은 정화 책임을 지지 않을 \"선의의 장래 매수인 (bona fide prospective purchaser)\" 보호를 만들어 민간이 오염 부지를 사들일 수 있게 했습니다.",
   "tools": ["보조금: 2002년 법이 조사 · 정화에 연 최대 2억 달러, 주 · 부족 대응 프로그램에 연 5,000만 달러를 승인",
             "2027 회계연도 공모 기준 — 지역 단위 조사 최대 50만 달러 (4년) · 조사 연합 최대 100만 달러 · 회전대출기금 (RLF) 최대 100만 달러 (5년) · 정화 최대 50만 달러 (4년)",
             "정화 · 회전대출 보조금은 수혜 기관이 20% 자부담 (cost share)",
             "인프라법 (2021)으로 브라운필드 프로그램에 15억 달러 추가",
             "책임 면제: 선의의 장래 매수인 · 인접 토지 소유자 보호 — 매수 전 오염 책임 부담을 줄여 거래를 엶"],
   "cases": [], "u": "https://www.epa.gov/brownfields/summary-small-business-liability-relief-and-brownfields-revitalization-act",
   "note": "EPA 는 1995년 이후 보조금 약 23억 7천만 달러로 정화 · 재개발 투자 360억 달러 이상, 일자리 약 26만 개를 끌어냈다고 밝힙니다 (2023.5 보도자료, 기관 자체 집계). 2027 회계연도에는 다목적 (Multipurpose) 보조금 공모를 하지 않습니다."},
  {"name": "연방 역사건물 재생 세액공제 (Federal Historic Tax Credit, 20% Rehabilitation Credit)", "year": "1976 (2017 개정)", "level": "국가 (국립공원청 NPS · 국세청 IRS · 주 역사보존국 SHPO 공동)",
   "law": "내국세입법 제47조 (Internal Revenue Code §47) · 2017년 감세 및 일자리법 (Tax Cuts and Jobs Act, Public Law 115-97) 제13402조",
   "what": "국가 사적 (National Register)에 올랐거나 등록 역사지구 안에서 역사적 가치를 인정받은 건물을 임대 · 상업 · 공업 등 수익용으로 \"상당한 규모로\" 고칠 때, 적격 공사비의 20% 를 연방 소득세에서 빼 줍니다. 옛 방직공장 · 창고를 주택 · 사무실로 바꾸는 사업의 대표 재원입니다.",
   "tools": ["세액공제율 20% (적격 재생 공사비 기준)",
             "2017년 개정 뒤 공제액을 건물 사용 개시 연도부터 5년에 나눠 청구 · 비역사 건물 (1936년 이전) 10% 공제는 경과 규정만 남음",
             "공사는 내무장관 재생 기준 (Secretary of the Interior's Standards for Rehabilitation)을 지켜야 하고 NPS 가 인증",
             "저소득주택 세액공제 (LIHTC) 등과 겹쳐 쓰는 경우가 많음"],
   "cases": ["lowell-mills"], "u": "https://www.irs.gov/businesses/small-businesses-self-employed/rehabilitation-credit",
   "note": "NPS 는 1976년 이후 이 제도로 민간 투자 1,271억 2천만 달러가 들어가 역사 건물 5만 채 이상이 보존됐다고 밝힙니다. 2017년 개정으로 공제를 한 해에 다 받지 못하고 5년에 나눠 받게 됐습니다."},
  {"name": "기회특구 (Opportunity Zones)", "year": "2017 (2025 영구화)", "level": "국가 (재무부 · 국세청, 주지사가 지역 지정)",
   "law": "2017년 감세 및 일자리법 (Public Law 115-97) — 내국세입법 제1400Z-1조 · 제1400Z-2조, 2025년 개정 (Public Law 119-21)",
   "what": "주지사가 추천한 저소득 인구조사구역 (census tract)을 기회특구로 지정하고, 투자자가 다른 곳에서 낸 양도차익을 \"적격 기회펀드 (QOF)\"에 넣어 특구에 투자하면 세금을 미루거나 줄여 줍니다. 낡은 산업 · 상업 지역의 부동산 · 사업 투자를 민간 자본으로 끌어오려는 장치입니다.",
   "tools": ["양도차익을 180일 안에 기회펀드에 넣으면 과세 이연 — 원 제도는 2026.12.31 까지",
             "원 제도: 5년 보유 시 이연 이익의 10%, 7년 보유 시 15% 비과세 · 10년 이상 보유 시 펀드 투자 평가이익 전액 비과세",
             "펀드는 자산의 90% 이상을 특구 자산으로 보유 · 기존 건물은 30개월 안에 취득가 이상을 추가 투자하는 \"실질적 개량\" 요건",
             "2025년 개정: 10년 단위 재지정 (지정 결정일 2026.7.1 부터 10년마다, 지정 효력은 다음 해 1월 1일부터 10년) · 2027년 이후 투자는 투자일부터 5년 뒤 과세 · 5년 보유 시 10% (농촌 펀드 30%) 기준가 상향 · 평가이익 비과세는 투자 후 30년까지",
             "저소득 지역 기준 강화: 중위 가구소득이 주 · 대도시권의 70% 이하, 또는 빈곤율 20% 이상이면서 중위소득 125% 이하"],
   "cases": [], "u": "https://www.irs.gov/credits-deductions/opportunity-zones-frequently-asked-questions",
   "note": "첫 지정은 2018.4.9. 2025년 개정으로 제도가 상설화되고 저소득 지역 기준이 좁혀졌으며, 농촌 펀드 우대가 새로 생겼습니다."},
  {"name": "시카고 계획제조지구 · 산업회랑 체계 · 산업회랑 시스템 기금 (Planned Manufacturing Districts · Industrial Corridor System · Industrial Corridor System Fund)", "year": "1988 (PMD) · 1992 (산업회랑 지정) · 2017 (기금 · 전환 부담금)", "level": "시카고 (일리노이주)",
   "law": "시카고 조닝 조례 (Chicago Zoning Ordinance, 2004) 제17-13-0400조 · 「산업회랑 시스템 기금 조례 (Industrial Corridor System Fund Ordinance)」 시 법전 제16-8장 (2017.7) · 「노스 브랜치 프레임워크 (North Branch Framework)」 (시카고 계획위원회 2017.5.18 채택)",
   "what": "1980년대 주거 붐으로 노스 브랜치 강변 공장이 로프트 · 대형 상가로 바뀌자, 시는 1988~1990년 주거를 막는 계획제조지구 (PMD) 3곳을 만들고 1992년부터 산업회랑을 공식 지정했습니다. 현재 26개 산업회랑 (70~3,500에이커)이 시 공업 조닝 땅의 3분의 2를 담고, 그 안에 PMD 15곳 (1988~2007)이 있습니다. 2017년에는 노스 브랜치 회랑 760에이커 일부를 \"전환 구역\"으로 풀어 주는 대신, 비공업 용도로 재조닝하는 개발자에게 부담금을 물려 다른 산업회랑의 공업 투자 기금으로 돌리는 제도를 만들었습니다.",
   "tools": ["PMD: 핵심부 · 완충부로 나눠 주거를 금지하고 완충부에만 상업 허용 — 산업회랑 안의 비공업 재조닝은 계획위원회 공청회 · 권고를 거쳐야 함 (2004 조례)",
             "전환 부담금 = 순부지면적 (ft²) × 산업용지 대체비용 (ft²당) × 개발자 몫 25% — 대체비용은 시 전역 공업용지 매입 중위값 + 건물 개조 · 부지 정비비 + 오염 정화비 + 공업 도로 보수비로 산정",
             "2017년 제안 당시 대체비용 ft²당 49달러 (개발자 몫 25% 적용 시 ft²당 약 12.25달러) · 최소 5년마다 갱신 · 첫 건축허가 전에 전액 납부 (단계 개발은 연면적 비율로 분납) · 미납 시 유치권 (lien)",
             "기금 100% 를 23개 \"수용 회랑 (receiving corridors)\" — 아미티지 · 캘루멧 · 리틀 빌리지 · 풀먼 · 스톡야즈 등 — 에만 사용: 토지 · 건물 매입, 오염 조사 · 정화, 노후 건물 철거 · 개조, 기반시설 (운영비는 기금의 5% 이내)",
             "현물 대체 허용: 개발자가 수용 회랑에 대체 공장 부지를 직접 매입 · 정화 · 개조 가능 · 우선순위는 신규 · 확장 공업 시설, 시민 고용, 오염 같은 장기 장애 해소 등",
             "시 모니터링 자료 (2023.1.3 기준): 16개 사업 약정 5,454만 5,280달러 (링컨 야즈 북 1,682만 달러 · 남 1,154만 달러 · 발리스 카지노 1,451만 달러 등) 중 실제 수납 399만 6,731달러"],
   "cases": [], "u": "https://www.chicago.gov/content/dam/city/depts/dcd/supp_info/industrial/Proposed_Industrial_Corridor_System_Fee_Overview.pdf",
   "note": "PMD 첫 3곳 (클라이번 · 구스 아일랜드 · 엘스턴)은 일자리를 지켰지만 업종은 전통 제조업에서 다른 사업으로 바뀌었다는 평가가 있습니다 (시 보고서가 인용한 위스콘신-밀워키대 연구). 기금은 약정액에 비해 실제 수납이 늦어, 대형 사업 (링컨 야즈 등)이 지연되면 공업 쪽 재투자도 늦어지는 구조입니다."},
  {"name": "뉴욕 산업업무지구 (Industrial Business Zones, IBZ) · 산업 · 상업 재산세 감면 (ICAP)", "year": "2005 (IBZ 이전 세액공제 기준일) · ICAP (옛 ICIP 후속)", "level": "뉴욕시",
   "law": "뉴욕시 일반법인세 (양식 9.6) · 비법인사업세 (양식 114.6)의 IBZ 이전 세액공제 · 뉴욕시 재무국 (Department of Finance)이 운영하는 ICAP (예비 신청 2029.3.1 까지)",
   "what": "공업 · 제조업이 모여 있는 지역을 산업업무지구 (IBZ)로 정해 제조업체의 이전 · 정착을 세액공제와 상담 서비스로 돕고, 공장 · 상업 건물을 새로 짓거나 고치면 재산세를 최대 25년 깎아 줍니다. 브루클린 네이비 야드 · 롱아일랜드 시티 · 헌츠 포인트 등 21개 IBZ 가 있습니다.",
   "tools": ["IBZ 이전 세액공제: 이전 직원 1인당 1,000달러 1회 — 실제 이전비와 10만 달러 중 적은 금액 한도, 2005.7.1 이후 이전 · 이전 직전 24개월 영업 · 이전 후 5년 이상 점유 조건",
             "ICAP: 산업 · 상업 건물 신축 · 개량 시 재산세 최대 25년 감면 — 건축허가 후 4년 안에 과세평가액의 30% 이상 투자, 주거는 임대면적의 20% 이하",
             "옛 ICIP (최대 25년 면제 · 공업용 부분 감면 12년 · 공업은 평가액 25% 이상 개량 조건)의 후속 제도",
             "산업 이전 보조금 (IRG: 이전비의 90% · ft²당 4달러 · 3만 달러 중 적은 금액) 등 시 산업 지원 패키지"],
   "cases": ["brooklyn-navy-yard"], "u": "https://www.nyc.gov/html/imb/downloads/pdf/ibz_tax_credit_simple_solution.pdf"},
  {"name": "시애틀 산업 · 해양 전략 (Industrial and Maritime Strategy)", "year": "2023", "level": "시애틀 (워싱턴주)",
   "law": "시애틀 종합계획 개정 · 시애틀 시 법전 제23.50A장 신설 (산업 조닝) 등 조례 5건 (시의회 2023.7.18 의결)",
   "what": "시 면적의 약 12% 인 두 제조 · 산업 센터 (MIC: 그레이터 두와미시 · 발라드-인터베이)에 일자리 약 10만 개 (시 전체의 약 15%)가 있는데, 전환 압력이 커지자 산업 조닝을 셋으로 다시 짰습니다. 핵심 공업 · 항만지는 더 강하게 지키고, 경전철역 주변에서는 \"공업 공간을 지으면 사무 · 연구 공간을 더 주는\" 보너스로 다층 산업 건물을 유도합니다.",
   "tools": ["해양 · 제조 · 물류 (MML) 지구: 대형 소매 · 미니창고 억제, 최대 용적률 2.5 중 비공업 용도는 0.4 이하로 제한 (필지 쪼개기 방지)",
             "산업 · 혁신 (II) 지구: 경전철역 반경 약 0.8km 에 적용, 공업 공간 1ft² 마다 비공업 공간 5ft² 보너스 — 예) II 160 지구는 공업 0.5 로 시작해 최대 용적률 6 (2단계 6.5: 매스 팀버 50% 이상 또는 비보강 조적 건물 개량용 용적이전), 같은 MIC 안 다른 곳에 공업 건물을 지어도 인정",
             "도시 산업 (UI) 지구: 공업지와 주거지 사이 전이 지대 — 소규모 제조 · 예술 공간, 조건부로 소량 근로자 주택 허용 (MIC 면적의 4~5%)",
             "20년간 신규 일자리 약 3만 5천 개 예상 (시의회 발표)"],
   "cases": [], "u": "https://council.seattle.gov/2023/07/18/seattle-city-council-passes-industrial-and-maritime-zoning-legislation-updating-the-citys-land-use-code-and-buoying-the-local-economy/",
   "note": "보너스를 받으려면 공업 공간이 \"진정한 공업 공간 (bona fide industrial space)\" 건축 기준을 갖추고 지정 공업 용도로 쓰여야 하며, 다른 곳에 짓는 경우 보너스 건물보다 먼저 완공해야 합니다."},
  {"name": "포틀랜드 핵심 산업용지 중첩지구 (Prime Industrial Overlay Zone)", "year": "2018", "level": "포틀랜드 (오리건주)",
   "law": "포틀랜드 시 법전 제33편 제33.471장 (조례 188177호, 2018.5.24 시행) · 「2035 종합계획 (2035 Comprehensive Plan)」의 핵심 산업용지 (Prime Industrial) 지정",
   "what": "오리건 최대 항만 · 철도 허브 · 공항이 있는 포틀랜드 하버 · 컬럼비아 코리도어 · 브루클린 야드 산업지구를 \"대체하기 어려운\" 산업용지로 정해 장기 보전합니다. 반대로 시내 펄 디스트릭트 같은 옛 창고 지역은 조세증가분 금융 (TIF)과 개발 협약으로 주거 · 상업 혼합지로 전환했습니다.",
   "tools": ["공업 개발 용량을 줄이는 다른 용도 · 지구로의 전환을 금지하거나 상쇄 (off-set)를 요구",
             "토지 소유자가 개별 종합계획 지도 변경을 신청할 수 없음 (복합 고용 → 산업 보호구역으로 바꾸는 경우만 예외)",
             "셀프스토리지 · 대형 이벤트 시설 금지, 실외 상업 레크리에이션 2만 ft² 이하, 공원 · 녹지는 2에이커 이하 · 자연보호 · 산책로 등만 허용"],
   "cases": ["pearl-district"], "u": "https://portland.gov/sites/default/files/code/33.471-prime-industrial-overlay-zone.pdf",
   "note": "펄 디스트릭트는 이 중첩지구의 대상이 아니라, 같은 도시가 \"전환할 곳 (도심 창고지)\"과 \"지킬 곳 (항만 · 물류 산업지)\"을 나눈 사례로 함께 볼 만합니다."},
  {"name": "케임브리지 켄들 스퀘어 도시재생계획 · MXD 지구 혁신 공간 의무 (Kendall Square Urban Renewal Plan · MXD Innovation Space)", "year": "2015 (재생계획 제10차 개정)", "level": "케임브리지 (매사추세츠주) — 보스턴권",
   "law": "켄들 스퀘어 도시재생계획 (KSURP) 제10차 개정 (케임브리지 재개발청 CRA 2015.12.16 · 시의회 2015.12.21 승인) · 케임브리지 조닝 조례 제14장 MXD 지구 (제14.32.5조 혁신 공간)",
   "what": "옛 공장 · 창고 지대였던 켄들 스퀘어를 공공 재개발청 (CRA)이 도시재생계획으로 관리하며 연구 · 바이오 · 사무 단지로 바꿔 왔습니다. 2015년 개정은 상업 연면적 상한을 늘리는 대신, 주택 (저렴주택 포함)과 스타트업용 소규모 \"혁신 공간\"을 의무로 묶었습니다.",
   "tools": ["MXD 지구 총 연면적 상한 333만 3천 ft² → 427만 3천 ft² (그중 60만 ft² 는 주거 전용, 최소 주거 20만 → 60만 ft²)",
             "혁신 공간: 신규 비주거 연면적의 5% 이상 — 한 건물 안 1만 ft² 이상, 임대 단위 약 1개월, 한 업체는 2,000ft² 또는 전체의 10% 이하 · 절반까지 연면적 상한에서 제외",
             "신규 주택의 15% 이상을 지역 중위소득 60% 가구용 저렴주택으로 · 중간소득 (80~120%) 주택을 넣으면 주거 높이 350ft 까지",
             "지구 토지 (도로 제외)의 15% 이상을 공공 개방 공간으로 · 블록 1층의 75% 를 활성 용도로"],
   "cases": ["kendall-square"], "u": "https://www.cambridgema.gov/-/media/Files/CDD/ZoningDevel/Amendments/2015/CRAMXD/zngamend_cramxd_petitiontext.pdf",
   "note": "공업 보호보다 \"공업지 → 연구 · 혁신지구\" 전환에 공공기여 (주택 · 창업 공간)를 붙인 모델로, 한국의 공업지역 용도 전환 시 공공기여 설계와 비교할 만합니다."},
 ],
 "refs": [
  {"t": "Summary of the Small Business Liability Relief and Brownfields Revitalization Act — US EPA", "u": "https://www.epa.gov/brownfields/summary-small-business-liability-relief-and-brownfields-revitalization-act"},
  {"t": "Multipurpose, Assessment, RLF and Cleanup (MARC) Grant Application Resources — US EPA", "u": "https://www.epa.gov/brownfields/multipurpose-assessment-rlf-and-cleanup-marc-grant-application-resources"},
  {"t": "EPA announces more than $315 million for brownfields (2023.5.25) — US EPA", "u": "https://www.epa.gov/newsreleases/biden-harris-administration-announces-more-315-million-through-investing-america"},
  {"t": "Rehabilitation Credit — IRS", "u": "https://www.irs.gov/businesses/small-businesses-self-employed/rehabilitation-credit"},
  {"t": "20% Tax Credit Basics — Historic Preservation Tax Incentives (NPS)", "u": "https://www.nps.gov/subjects/taxincentives/tax-credit-basics.htm"},
  {"t": "Federal Historic Preservation Tax Incentives — NPS", "u": "https://www.nps.gov/subjects/taxincentives/index.htm"},
  {"t": "Opportunity Zones — IRS", "u": "https://www.irs.gov/credits-deductions/businesses/opportunity-zones"},
  {"t": "Opportunity Zones Frequently Asked Questions — IRS", "u": "https://www.irs.gov/credits-deductions/opportunity-zones-frequently-asked-questions"},
  {"t": "26 U.S. Code § 1400Z-1 · § 1400Z-2 (Cornell LII)", "u": "https://www.law.cornell.edu/uscode/text/26/1400Z-2"},
  {"t": "Industrial Corridor System Fee — Overview (City of Chicago DPD, 2017.6.28)", "u": "https://www.chicago.gov/content/dam/city/depts/dcd/supp_info/industrial/Proposed_Industrial_Corridor_System_Fee_Overview.pdf"},
  {"t": "Industrial Corridor System Fee + North Branch Bonus Fee monitoring database (City of Chicago, 2023.1.3)", "u": "https://www.chicago.gov/content/dam/city/depts/dcd/supp_info/industrial/ic-system-fee-monitoring-database-12-22.pdf"},
  {"t": "The Geography of Production: Chicago and its Industrial Corridor System — Chicago DPD", "u": "https://www.chicago.gov/content/dam/city/depts/zlup/Industrial_Modernization/UpdatedCaseforIndustrialCorridorSystem.pdf"},
  {"t": "Industrial Corridor Modernization Initiative — City of Chicago", "u": "https://www.chicago.gov/city/en/depts/dcd/supp_info/repositioning-chicago-s-industrial-corridors-for-today-s-economy.html"},
  {"t": "North Branch Framework (City of Chicago DPD, 2017)", "u": "https://www.chicago.gov/content/dam/city/depts/dcd/supp_info/industrial/NBIC_Adopted_Final_For-Web.pdf"},
  {"t": "Industrial Business Zone Relocation Tax Credit — NYC (PDF)", "u": "https://www.nyc.gov/html/imb/downloads/pdf/ibz_tax_credit_simple_solution.pdf"},
  {"t": "Industrial Business Zone Relocation Credit — NYC Business", "u": "https://nyc-business.nyc.gov/nycbusiness/description/industrial-business-zone-relocation-credit"},
  {"t": "Industrial & Commercial Abatement Program (ICAP) — NYC Department of Finance", "u": "https://www.nyc.gov/site/finance/property/benefits-industrial-and-commercial-abatement-program-icap.page"},
  {"t": "NYC industrial incentives summary (PDF)", "u": "https://www.nyc.gov/html/imb/downloads/pdf/imb_incentives.pdf"},
  {"t": "Seattle City Council passes industrial and maritime zoning legislation (2023.7.18)", "u": "https://council.seattle.gov/2023/07/18/seattle-city-council-passes-industrial-and-maritime-zoning-legislation-updating-the-citys-land-use-code-and-buoying-the-local-economy/"},
  {"t": "Industrial and Maritime Strategy — Final Director's Report (Seattle OPCD, 2023)", "u": "https://seattle.gov/documents/departments/opcd/ongoinginitiatives/industrialmaritimestrategy/industrialmaritimefinaldirectorsreport2023.pdf"},
  {"t": "Chapter 33.471 Prime Industrial Overlay Zone — Portland Zoning Code", "u": "https://portland.gov/sites/default/files/code/33.471-prime-industrial-overlay-zone.pdf"},
  {"t": "CRA MXD Zoning Petition and KSURP Amendment (Cambridge Redevelopment Authority, 2015)", "u": "https://www.cambridgema.gov/-/media/Files/CDD/ZoningDevel/Amendments/2015/CRAMXD/zngamend_cramxd_petitiontext.pdf"},
  {"t": "Chapple, K. (2014) The Highest and Best Use? Urban Industrial Land and Job Creation. Economic Development Quarterly 28(4)", "u": "https://doi.org/10.1177/0891242413517134"},
  {"t": "Leigh, N.G. & Hoelzel, N.Z. (2012) Smart Growth's Blind Side: Sustainable Cities Need Productive Urban Industrial Land. JAPA 78(1)", "u": "https://doi.org/10.1080/01944363.2011.645274"},
  {"t": "Lester, T.W., Kaza, N. & Kirk, S. (2013) Making Room for Manufacturing: Understanding Industrial Land Conversion in Cities. JAPA 79(4)", "u": "https://doi.org/10.1080/01944363.2014.915369"},
  {"t": "Davis, J. & Renski, H. (2020) Do Industrial Preservation Policies Protect and Promote Urban Industrial Activity? JAPA 86(4)", "u": "https://doi.org/10.1080/01944363.2020.1753563"},
 ],
 "missing": ["뉴욕시 「산업 실행계획 (Industrial Action Plan, 2015)」 원문 (시장실 보도자료)은 현재 시 웹사이트에서 열리지 않아, IBZ 내 주거 재조닝 불허 방침 · 산업개발기금 규모는 확인된 자료를 찾지 못했습니다.",
             "시카고 산업회랑 시스템 기금의 2023년 이후 수납 · 집행 실적 (연간 보고서)과 현재 적용 중인 ft²당 대체비용 갱신값은 확인된 자료를 찾지 못했습니다.",
             "일리노이 조세증가분 금융법 (TIF) 원문은 주 의회 사이트 접속이 되지 않아 확인된 자료를 찾지 못했습니다.",
             "기회특구 2027년 재지정 결과 (지정 구역 수)는 확인된 자료를 찾지 못했습니다.",
             "시애틀 산업 · 해양 조례의 시장 서명일 · 시행일과 조례 번호는 시 공식 페이지에서 확인된 자료를 찾지 못했습니다 (시의회 의결일 2023.7.18 만 확인).",
             "매사추세츠 지정 항만구역 (Designated Port Areas, 301 CMR 25.00)은 원문을 확인했으나 이번 목록에는 넣지 않았습니다 (보스턴 항만 공업용지 보호 제도)."]},

{"nat": "캐나다", "en": "Canada",
 "summary": "캐나다에서 토지이용은 주 (州) 권한이어서, 온타리오는 주 계획지침 (Provincial Planning Statement)과 계획법으로 \"고용지역 (employment area)\" 전환을 엄격히 묶고, 오염 부지는 환경보호법의 대지 상태 기록 (RSC) 제도로, 재생 투자는 시의 지역개선계획 (CIP) 보조금으로 다룹니다. 밴쿠버권은 광역 성장전략 (Metro 2050)이 산업 · 고용용지를 지정해 지키고, 연방은 토론토 워터프런트 · 밴쿠버 그랜빌 아일랜드처럼 옛 항만 · 공업 지대 재생에 공공 소유 · 공동 출자로 직접 나섰습니다.",
 "items": [
  {"name": "온타리오 브라운필드 제도 — 대지 상태 기록 (Record of Site Condition, RSC)", "year": "2001 (규칙 2004.10.1 시행)", "level": "주 (온타리오)",
   "law": "브라운필드 법령 개정법 (Brownfields Statute Law Amendment Act, 2001) · 환경보호법 (Environmental Protection Act) 제15.1부 · 온타리오 규칙 153/04 (O. Reg. 153/04)",
   "what": "공업 · 상업 용지를 주거 · 학교 · 공원처럼 더 민감한 용도로 바꾸려면 오염 조사 · 정화를 거쳐 대지 상태 기록 (RSC)을 주 환경부 온라인 등록부에 올려야 합니다. 등록하면 일정 범위의 환경 명령으로부터 소유자를 보호해, 옛 공장 부지 전환의 법적 불확실성을 줄입니다.",
   "tools": ["용도 전환 요건: 공업 · 상업 · 공동체 용도 → 주거 · 기관 · 공원 · 농업 용도로 바꾸기 전 RSC 제출 의무",
             "용도별 토양 · 지하수 · 퇴적물 기준 또는 부지별 위해성 평가 (risk assessment)",
             "환경 대지 등록부 (Environmental Site Registry)에 공개",
             "책임 보호: RSC 등록 시 환경보호법 제168.7조에 따라 일부 명령 면제 (허위 기재 · 긴급 상황 등은 예외)"],
   "cases": [], "u": "https://www.ontario.ca/page/guide-site-assessment-cleanup-brownfields-filing-records-site-condition",
   "note": "정화 비용 자체를 대 주는 제도는 아니어서, 비용 지원은 시의 지역개선계획 (CIP) 보조금과 결합해 씁니다."},
  {"name": "지역개선계획 (Community Improvement Plan, CIP) · 토론토 IMIT 재산세 환급 보조금", "year": "계획법 제28조 · IMIT 2012 (2018 개편안 채택)", "level": "주 법률 → 토론토 시",
   "law": "온타리오 계획법 (Planning Act) 제28조 · 토론토 시 조례 1324-2012 (사우스 오브 이스턴 CIP) 등 시 전역 · 워터프런트 CIP",
   "what": "시는 공식계획에 근거해 \"지역개선 사업구역\"을 정하고 그 안의 소유자 · 임차인에게 보조금 · 대출 · 세금 지원을 줄 수 있습니다. 토론토의 IMIT (상상 · 제조 · 혁신 · 기술) 프로그램은 제조 · 기술 등 목표 고용 업종의 신축 · 대수선과 브라운필드 정화에 대해, 개발로 늘어난 재산세의 일부를 10년간 되돌려 줍니다.",
   "tools": ["계획법 제28조(7): 환경 조사 · 정화 · 재건축 · 에너지 개량 비용에 보조금 · 대출 — 제365.1조 세금 지원과 합쳐 재생 적격 비용을 넘을 수 없음",
             "IMIT: 늘어난 시 재산세의 통상 60% 를 10년에 걸쳐 환급 (브라운필드 정화 시 최대 12년 · BRTA 추가 보조), 공사비 100만 캐나다달러 이상 · 주 건축허가 전 신청",
             "공사비 1억 5,000만 캐나다달러 초과 사업은 시의회 승인 필요",
             "2023년 12월까지 74건 승인 · 지급 또는 적립 2억 6,945만 캐나다달러, 2037년까지 약정 포함 누적 약 7억 2,900만 캐나다달러"],
   "cases": [], "u": "https://www.toronto.ca/legdocs/mmis/2024/ex/bgrd/backgroundfile-242209.pdf",
   "note": "2024년 1월 시 직원은 이스트 하버 사무 개발 3건 (예상 보조금 10년 2억 3,000만 캐나다달러)에 대해 외부 검토 (Hemson)를 거쳐 거부를 권고했습니다 — 대형 사업에 대한 재산세 환급의 필요성 · 재정 부담이 쟁점."},
  {"name": "온타리오 주 계획지침 2024 — 고용지역 보호와 전환 요건 (Provincial Planning Statement, 2024 — Employment Areas)", "year": "2024 (2024.10.20 시행)", "level": "주 (온타리오)",
   "law": "주 계획지침 2024 (Provincial Planning Statement, 2024) 정책 2.8.2 · 계획법 제1조(1.1) \"고용지역 (area of employment)\" 정의 (개정 정의 2024.10.20 시행)",
   "what": "시는 공식계획에 고용지역을 지정해 제조 · 제조 관련 연구개발 · 창고 · 물류 용도로 장기 보호해야 하고, 그 안의 주거 · 상업 · 공공 · 기관 용도와 주 용도와 무관한 소매 · 사무를 금지해야 합니다. 이전 광역 성장계획 (Growth Plan)은 전환을 시 전체 계획 검토 (MCR) 때만 허용했지만, 2024년 지침은 아래 네 요건을 증명하면 그때그때 고용지역에서 땅을 뺄 수 있게 했습니다.",
   "tools": ["보호: 주요 화물 시설 · 회랑 인근 고용지역 우선 보호, 인접 비고용지와의 전이 지대 요구",
             "전환 요건 ① 전환 필요성이 있고 장기적으로 고용지역 용도에 필요 없는 땅 ② 고용지역 전체의 존속성을 해치지 않음 (영향 회피 · 완화, 화물 접근 유지) ③ 기반시설 · 공공시설 확보 ④ 공식계획 목표 연도까지 고용 성장에 충분한 고용용지가 남음",
             "고용지역 정의 축소: 사무 · 기관 · 독립 상업 (소매) 용도는 주 고용 용도에 딸린 경우가 아니면 제외"],
   "cases": [], "u": "https://www.ontario.ca/files/2024-10/mmah-provincial-planning-statement-en-2024-10-23.pdf"},
  {"name": "토론토 고용지역 정책 — 핵심 · 일반 고용지역 (OPA 231) 과 「우리 계획 토론토」 전환 심사 (OPA 591)", "year": "2013 (OPA 231) · 2022 (OPA 591)", "level": "토론토 시",
   "law": "토론토 공식계획 개정 231호 (Official Plan Amendment 231, 시의회 2013.12.16 채택 · 2014 주 승인) · 공식계획 개정 591호 (2022)",
   "what": "토론토는 첫 시 전체 계획 검토 (MCR)로 고용지역을 \"핵심 (Core)\" — 제조 · 창고 · 운송 · 연구개발 위주, 소매 · 식당 크게 제한 — 과 \"일반 (General)\"로 나누고, 비허용 용도를 넣는 것 자체를 \"전환\"으로 보아 심사하게 했습니다. 두 번째 검토 (Our Plan Toronto)에서는 1년간 전환 신청을 한꺼번에 받아 심사했습니다.",
   "tools": ["전환 신청 창구: 2020.8.4 ~ 2021.8.3 — 공식계획 개정 신청 또는 2만 캐나다달러 수수료의 서면 요청, 양립성 · 완화 연구 (외부 검증) 필수",
             "접수 약 140건 · 고용지역 약 685ha (전체 고용지역의 8.5%) — 예비 평가 133건을 4차례 (2022.1~4) 공개",
             "핵심 → 일반 고용지역 재지정도 \"전환\"으로 심사"],
   "cases": [], "u": "https://www.toronto.ca/legdocs/mmis/2022/ph/bgrd/backgroundfile-227762.pdf",
   "note": "OPA 231 은 2014년 주 승인 때 로어 돈 특별정책구역 일부를 제외하고 승인됐습니다. 고용지 보호와 주택 공급 요구가 부딪치는 지점입니다."},
  {"name": "워터프런트 토론토 (Waterfront Toronto) — 3개 정부 공동 재생 법인", "year": "2001 (2002 법정 법인)", "level": "연방 · 온타리오 주 · 토론토 시 공동",
   "law": "토론토 워터프런트 재활성화 법인법 (Toronto Waterfront Revitalization Corporation Act, 2002)",
   "what": "옛 항만 · 철도 · 정유 · 시멘트 공장이 있던 토론토 호숫가 800ha (2,000에이커)를 재생하려고 연방 · 주 · 시가 2001년 11월 공동 법인을 세웠고, 2002년 12월 주 법으로 영구 지위를 주었습니다. 웨스트 돈 랜즈 · 포트 랜즈 등 공업 지대를 홍수 방어 · 공원 · 저렴주택이 있는 새 동네로 바꾸는 계획 · 기반시설을 맡습니다.",
   "tools": ["초기 자본: 3개 정부가 각각 5억 캐나다달러 (합계 15억)",
             "이사회: 정부마다 최대 4명 임명, 의장은 공동 임명",
             "성과 (기관 발표): 공원 · 공공공간 43ha, 저렴주택 576호, 호숫가 접근로 26km, 민간 투자 132억 5천만 캐나다달러 이상 유발"],
   "cases": ["west-don-lands"], "u": "https://www.waterfrontoronto.ca/about-us/history-heritage"},
  {"name": "메트로 밴쿠버 광역 산업용지 전략 · Metro 2050 산업 · 고용용지 지정 (Regional Industrial Lands Strategy · Metro 2050)", "year": "2020 (전략) · 2023 (Metro 2050 채택)", "level": "광역 (메트로 밴쿠버 지역구)",
   "law": "광역 산업용지 전략 (Regional Industrial Lands Strategy, 메트로 밴쿠버 이사회 2020.7.3 승인) · 광역 성장전략 「Metro 2050」 (2023.2 채택)",
   "what": "산업용지는 지역 면적의 4% 지만 일자리의 27%, 지역 총생산의 30% 를 맡는데 북미에서 가장 비싼 수준이라, 광역 정부가 필지 단위 \"산업 (Industrial)\" · \"고용 (Employment)\" 지정을 두고 바꾸려면 광역 차원의 협의 · 결정을 거치게 했습니다. 산업 지정지에는 주거를 허용하지 않고, 남은 땅은 다층화로 집약적으로 쓰게 합니다.",
   "tools": ["전략: 34개 권고 · 10개 우선 과제 · 4대 방향 (남은 산업용지 보호 / 집약 · 최적화 / 미개발지 시장 공급 / 조정)",
             "Metro 2050 신설 \"교역 지향 토지 중첩 (Trade-Oriented Lands Overlay)\" — 항만 · 물류 대형 부지는 구분소유 · 소필지 분할을 허용하지 않음",
             "고용용지는 원칙적으로 주거 불허 — 단, 도시 중심 · 빈번 대중교통 개발지역 안 고속철도역 200m 이내에서는 상층부 저렴 임대주택 허용 (저층은 상업 · 경공업)",
             "다층 산업 건물 유도: 높이 · 용적 제한 등 규제 장벽 완화, 미개발 · 저활용 산업용지의 시장 공급 전략"],
   "cases": [], "u": "https://metrovancouver.org/services/regional-planning/Documents/metro-2050-implementation-guideline-industrial-and-employment-lands.pdf",
   "note": "밴쿠버 시 자체 조닝 (마운트 플레전트 I-1 · I-1C 산업지 집약화 등)은 시 웹사이트 보안 확인 때문에 원문을 열지 못해 넣지 않았습니다."},
  {"name": "연방 공공 소유 · 직접 운영 — 그랜빌 아일랜드 (CMHC)", "year": "1970년대 (CMHC 관리)", "level": "국가 (캐나다 모기지주택공사 CMHC)",
   "law": "연방 정부 소유지 — 캐나다 모기지주택공사 (Canada Mortgage and Housing Corporation)가 연방 정부를 대신해 관리",
   "what": "밴쿠버 폴스 크리크의 옛 공업 섬을 연방이 소유한 채 CMHC 가 직접 임대 · 운영하며 시장 · 공방 · 극장 · 가동 공장이 섞인 공공 장소로 바꿨습니다. 땅을 팔지 않고 임차인을 골라 업종 구성을 관리하는 공공 토지 운영 방식입니다.",
   "tools": ["공공 토지 장기 임대 · 임차인 선정으로 업종 관리 (300여 개 사업체)",
             "운영상 자립 — 어느 단계 정부의 재정 지원도 받지 않는다고 운영 주체가 밝힘 (임대 수입)"],
   "cases": ["granville-island"], "u": "https://granvilleisland.com/about-us",
   "note": "연방 소유지라 차입 · 대규모 재투자가 어렵다는 거버넌스 한계가 있습니다."},
 ],
 "refs": [
  {"t": "Guide: site assessment, cleanup of brownfields, filing of records of site condition — Government of Ontario", "u": "https://www.ontario.ca/page/guide-site-assessment-cleanup-brownfields-filing-records-site-condition"},
  {"t": "O. Reg. 153/04 Records of Site Condition — CanLII", "u": "https://www.canlii.org/en/on/laws/regu/o-reg-153-04/latest/o-reg-153-04.html"},
  {"t": "Applications to the IMIT Property Tax Incentive Program — City of Toronto report (2024.1.15)", "u": "https://www.toronto.ca/legdocs/mmis/2024/ex/bgrd/backgroundfile-242209.pdf"},
  {"t": "Provincial Planning Statement, 2024 — Government of Ontario", "u": "https://www.ontario.ca/page/provincial-planning-statement-2024"},
  {"t": "Provincial Planning Statement, 2024 (PDF)", "u": "https://www.ontario.ca/files/2024-10/mmah-provincial-planning-statement-en-2024-10-23.pdf"},
  {"t": "Our Plan Toronto: Recommended OPA for City-wide Employment Policies and Conversion Requests — Final Report (2022.6.20)", "u": "https://www.toronto.ca/legdocs/mmis/2022/ph/bgrd/backgroundfile-227762.pdf"},
  {"t": "About Us — Waterfront Toronto", "u": "https://www.waterfrontoronto.ca/about-us"},
  {"t": "History & Heritage — Waterfront Toronto", "u": "https://www.waterfrontoronto.ca/about-us/history-heritage"},
  {"t": "Government Partners — Waterfront Toronto", "u": "https://www.waterfrontoronto.ca/about-us/accountability/government-partners"},
  {"t": "Regional Industrial Lands Strategy — Executive Summary (Metro Vancouver, 2020)", "u": "https://metrovancouver.org/services/regional-planning/Documents/regional-industrial-lands-strategy-executive-summary.pdf"},
  {"t": "Metro 2050 Implementation Guideline — Industrial and Employment Lands (Metro Vancouver, 2023.11)", "u": "https://metrovancouver.org/services/regional-planning/Documents/metro-2050-implementation-guideline-industrial-and-employment-lands.pdf"},
  {"t": "About Metro 2050: Regional Growth Strategy — Metro Vancouver", "u": "https://metrovancouver.org/services/regional-planning/metro-2050-the-regional-growth-strategy"},
  {"t": "About Granville Island — granvilleisland.com", "u": "https://granvilleisland.com/about-us"},
  {"t": "Adams, D., De Sousa, C. & Tiesdell, S. (2010) Brownfield Development: A Comparison of North American and British Approaches. Urban Studies 47(1)", "u": "https://doi.org/10.1177/0042098009346868"},
 ],
 "missing": ["밴쿠버 시 산업 조닝 개정 (마운트 플레전트 I-1 · I-1C, 고용용지 · 경제 검토 ELER) 원문은 시 웹사이트 보안 확인 (자동 접속 차단) 때문에 열지 못해 확인된 자료를 찾지 못했습니다.",
             "온타리오 브라운필드 재정 세제 인센티브 (BFTIP)의 현재 운영 여부 · 규모는 확인된 자료를 찾지 못했습니다.",
             "워터프런트 토론토 포트 랜즈 홍수 방어 사업 (2018) 등 추가 정부 출자 금액은 공식 자료에서 확인된 자료를 찾지 못했습니다.",
             "OPA 591 이후 실제 전환이 승인된 고용지역 면적 합계는 확인된 자료를 찾지 못했습니다.",
             "CMHC 가 그랜빌 아일랜드 관리를 맡은 정확한 근거 문서 (1972년 추밀원령)의 원문은 확인된 자료를 찾지 못했습니다."]},
]
