# -*- coding: utf-8 -*-
# 나라별 노후 산업지역 재생 · 활용 지원정책 — 배정 03 (유럽: 영국 · 독일 · 네덜란드 · 벨기에 브뤼셀 · 프랑스 · 스페인 · 덴마크 · 아일랜드 · 이탈리아)
#  각 나라 언어의 원문 (법령 · 정부 · 시 공식 문서)을 직접 열어 확인한 사실만 적었습니다. 확인하지 못한 것은 missing 에 적었습니다.
P = [
{"nat": "영국", "en": "United Kingdom",
 "summary": "영국 (잉글랜드)은 국가 차원에서 용도 분류를 넓히고 (Class E) 상업 · 업무 건물의 주거 전환을 허가 없이 허용하는 쪽으로 규제를 풀어 왔고, 브라운필드 (기존 개발지) 등록 · 정비 기금으로 주택 공급을 앞세웠습니다. 반면 런던은 2021년 런던 플랜에서 산업용지를 \"관리된 쇠퇴\"에서 \"유지 · 집약화\"로 바꾸어 전략 산업지 (SIL)를 지키되, 집약화 · 공동입지 (co-location) 절차를 거친 경우에만 주거 등으로 일부 풀어 주도록 했습니다.",
 "items": [
  {"name": "상업 · 업무 · 서비스 통합 용도 「클래스 E (Class E — Commercial, business and service)」",
   "year": "2020 (2020.9.1 시행)", "level": "국가 (잉글랜드)",
   "law": "The Town and Country Planning (Use Classes) (Amendment) (England) Regulations 2020 (SI 2020/757)",
   "what": "옛 A1 (상점) · A2 (금융 · 전문서비스) · A3 (식당) · B1 (업무 — 사무 · 연구개발 · 경공업)을 하나의 클래스 E 로 묶었습니다. 같은 클래스 안의 용도 변경은 계획허가 (planning permission)가 필요 없어, 옛 경공업 · 연구 공간이 사무 · 상업으로 자유롭게 바뀔 수 있게 되었습니다.",
   "tools": ["용도 통합 — A1 · A2 · A3 · B1 → 클래스 E (2020.8.31 기준 그 용도로 쓰던 건물은 2020.9.1부터 클래스 E 로 간주)",
             "B1 (업무) 삭제 — 클래스 E 의 경공업 (sub-paragraph (g))과 겹치지 않는 공정만 B2 (일반 공업)로 남김",
             "경과 기간 (material period) 2020.9.1~2021.7.31"],
   "cases": [], "u": "https://www.legislation.gov.uk/uksi/2020/757/made",
   "note": "도심 경공업 · 작업장이 사무 · 상업으로 바뀌어도 허가 단계에서 막을 수단이 줄었다는 점이 산업 보호 쪽의 우려입니다."},
  {"name": "상업 → 주거 허가 없는 용도 전환 「클래스 MA (Class MA)」",
   "year": "2021 (2021.8.1 시행) · 2024 개정 (2024.3.5 시행)", "level": "국가 (잉글랜드)",
   "law": "The Town and Country Planning (General Permitted Development etc.) (England) (Amendment) Order 2021 (SI 2021/428) · Amendment Order 2024 (SI 2024/141)",
   "what": "클래스 E 건물을 주택 (C3)으로 바꾸는 것을 \"허가 의제 개발 (permitted development)\"로 정해, 계획허가 대신 사전승인 (prior approval)만 받으면 되게 했습니다. 빈 상업 · 업무 건물의 주거 전환을 빠르게 하려는 제도입니다.",
   "tools": ["2021 조건 — 최소 2년간 클래스 E 용도, 신청 직전 3개월 이상 공실, 전환 연면적 누계 1,500㎡ 이하",
             "2024 개정 — 3개월 공실 요건과 1,500㎡ 상한을 모두 삭제",
             "제외 — 등록 건축물 · 특별과학관심지역 · 국립공원 · 세계유산 등"],
   "cases": [], "u": "https://www.legislation.gov.uk/uksi/2021/428/made",
   "note": "허가 절차를 건너뛰므로 공공 기여 · 주거 품질 · 주변 산업과의 충돌을 개별 심사하기 어렵다는 한계가 있습니다."},
  {"name": "브라운필드 토지 등록부 「Brownfield Land Register」",
   "year": "2017 (2017.4.16 시행)", "level": "국가 (잉글랜드) — 지방계획청",
   "law": "The Town and Country Planning (Brownfield Land Register) Regulations 2017 (SI 2017/403)",
   "what": "모든 지방계획청이 주택 개발에 알맞은 기존 개발지 (previously developed land)를 찾아 공개 등록부로 관리하게 했습니다. 등록부 2부 (Part 2)에 올린 땅에는 \"원칙 허가 (permission in principle)\"를 줄 수 있습니다.",
   "tools": ["등록 기준 — 0.25ha 이상 또는 주택 5호 이상 가능, 주거 개발에 적합 · 가용 · 15년 안 실현 가능",
             "2부 (Part 2) 등재 → 원칙 허가로 개발 불확실성 축소",
             "등록부 공개 열람 의무"],
   "cases": [], "u": "https://www.legislation.gov.uk/uksi/2017/403/made"},
  {"name": "브라운필드 토지 방출 기금 2 「Brownfield Land Release Fund 2 (BLRF2)」",
   "year": "2022 (3년 기금) · 2024 추가 배분", "level": "국가 (잉글랜드) — 지방정부",
   "law": "주택 · 지역사회 · 지방정부부 (MHCLG) · 지방정부협회 (LGA) 「원 퍼블릭 에스테이트 (One Public Estate)」 사업",
   "what": "지방정부 소유의 막힌 브라운필드 (옛 주차장 · 산업용지 등)를 주택용지로 풀기 위해 정비 비용을 보조합니다.",
   "tools": ["총 1억 8천만 파운드 (2022.7 출범, 3년)",
             "보조 대상 — 오염 정화 · 폐건물 철거 · 인터넷 · 상하수도 · 전력 기반시설",
             "2024년 배분 — 6,800만 파운드, 54개 지방정부, 주택 5,200호 용지 확보 (정부 발표)"],
   "cases": [], "u": "https://www.gov.uk/government/news/thousands-of-new-homes-to-be-built-as-government-unlocks-brownfield-sites"},
  {"name": "런던 플랜 산업용지 정책 — 전략 산업지 (SIL) · 지역 중요 산업지 (LSIS) · 집약화 · 공동입지 (Policy E4 · E5 · E7)",
   "year": "2021 (국무장관 수정 지시 2020)", "level": "광역 (런던 광역시 GLA)",
   "law": "The London Plan 2021 — Policy E4 (Land for industry, logistics and services) · E5 (Strategic Industrial Locations) · E6 · E7 (Industrial intensification, co-location and substitution)",
   "what": "런던 산업용지를 전략 산업지 (SIL) · 지역 중요 산업지 (LSIS) · 비지정 산업지의 세 단계로 나누어 지키고, 산업 연면적 용량의 순감소가 없도록 계획 · 관리하게 합니다. 산업용지를 다른 용도로 풀 때는 반드시 집약화 · 공동입지 · 대체 (substitution) 절차를 거치도록 했습니다.",
   "tools": ["\"순감소 없음 (no net loss)\" — 지정 SIL · LSIS 의 산업 연면적 용량을 유지, 용량 = 기존 산업 연면적 또는 대지의 65% 플롯 비율 (plot ratio)로 지을 수 있는 연면적 중 큰 값",
             "SIL 에 주거 · 소매 · 종교 · 여가 시설은 원칙적으로 불허 — 개발계획 · 계획 체계로 정한 통합 (consolidation) 구역만 예외",
             "공동입지 조건 — 산업 용량 증가 (또는 최소 유지) · 야드 공간 확보, 산업 부분을 주거 입주 전에 완공, 주거 쪽 설계로 소음 · 진동 · 대기질 대응 (agent of change 원칙)",
             "공실률이 런던 평균보다 크게 높은 곳은 다른 용도로 방출을 검토하고, 수요가 높은 곳으로 대체 권장"],
   "cases": ["kings-cross"], "u": "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/924467/Letter_to_the_Mayor_of_London_Annex.pdf",
   "note": "런던 시장 안의 \"순감소 없음\" 원칙은 국무장관 지시로 \"용량 기준 · 지정 산업지 한정\"으로 약해졌고, 산업용지가 주택 목표 (대형 부지 주택 용량의 약 40%)의 공급원으로도 쓰이는 긴장이 있습니다 (Ferm 2023). 런던시 정책 원문 페이지 (london.gov.uk)는 접속이 막혀 직접 열지 못했고, 정부 수정 지시 부록으로 확인했습니다."},
  {"name": "\"변화 유발자\" 원칙 「Agent of Change」 — 국가계획정책체계 (NPPF) 정책 P4",
   "year": "2026 (NPPF 17장, 2026.9.29 게시)", "level": "국가 (잉글랜드)",
   "law": "National Planning Policy Framework, Chapter 17: Pollution, public protection and security (P1–6)",
   "what": "기존 사업장 · 산업 · 폐기물 시설 옆에 새 개발 (용도 변경 포함)이 들어설 때, 기존 시설의 운영에 부당한 제한이 가지 않도록 새로 들어오는 쪽 (agent of change)이 소음 등 영향을 파악하고 완화책을 마련하게 합니다.",
   "tools": ["신청자가 기존 이용자와 미리 협의해 영향 범위 파악",
             "최초 입주 전 완화 조치 실현을 입증 — 계획 조건 · 계획 의무 (obligation)로 확보",
             "신축뿐 아니라 용도 변경에도 적용, 기존 시설의 현재 · 허가된 운영 수준 모두 고려"],
   "cases": [], "u": "https://www.gov.uk/guidance/national-planning-policy-framework-chapter-17-pollution-public-protection-and-security-p1-6"},
  {"name": "시장 개발공사 · 개발구역 「Mayoral Development Corporation / Mayoral development area」",
   "year": "2011", "level": "광역 (런던 시장 · 광역 단체장)",
   "law": "Localism Act 2011, Part 8 Chapter 2 (s.196~) — s.197 Designation of Mayoral development areas",
   "what": "시장이 특정 지역을 \"시장 개발구역\"으로 지정하고 그 지역의 재생을 맡는 개발공사를 세울 수 있게 한 제도입니다. 대규모 옛 산업 · 철도 부지 재생을 한 기관이 계획 · 시행하도록 하는 수단입니다.",
   "tools": ["시장 개발구역 지정 (떨어진 필지도 하나의 구역으로 묶을 수 있음)", "개발공사 설립 — 구역 재생 전담"],
   "cases": [], "u": "https://www.legislation.gov.uk/ukpga/2011/20/section/197"},
 ],
 "refs": [
  {"t": "legislation.gov.uk — SI 2020/757 Use Classes Amendment", "u": "https://www.legislation.gov.uk/uksi/2020/757/made"},
  {"t": "legislation.gov.uk — SI 2021/428 (Class MA)", "u": "https://www.legislation.gov.uk/uksi/2021/428/made"},
  {"t": "legislation.gov.uk — SI 2024/141 (Class MA 개정)", "u": "https://www.legislation.gov.uk/uksi/2024/141/made"},
  {"t": "legislation.gov.uk — SI 2017/403 Brownfield Land Register Regulations", "u": "https://www.legislation.gov.uk/uksi/2017/403/made"},
  {"t": "GOV.UK — Thousands of new homes to be built as government unlocks brownfield sites (BLRF)", "u": "https://www.gov.uk/government/news/thousands-of-new-homes-to-be-built-as-government-unlocks-brownfield-sites"},
  {"t": "Secretary of State — Direction: Intention to Publish London Plan Policy (Annex, E4 · E5 · E7 수정)", "u": "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/924467/Letter_to_the_Mayor_of_London_Annex.pdf"},
  {"t": "GOV.UK — NPPF Chapter 17 (P1–6)", "u": "https://www.gov.uk/guidance/national-planning-policy-framework-chapter-17-pollution-public-protection-and-security-p1-6"},
  {"t": "legislation.gov.uk — Localism Act 2011 s.197", "u": "https://www.legislation.gov.uk/ukpga/2011/20/section/197"},
  {"t": "Ferm, J. (2023) Hyper-Competitive Industrial Markets, Urban Planning 8(4)", "u": "https://doi.org/10.17645/up.v8i4.7114"},
  {"t": "Ferm, J. & Jones, E. (2016) Mixed-use 'Regeneration' of Employment Land in the Post-industrial City, European Planning Studies", "u": "https://doi.org/10.1080/09654313.2016.1209465"},
 ],
 "missing": ["런던 플랜 2021 원문 페이지 (london.gov.uk)는 접속 차단으로 직접 열지 못했습니다 — 정책 내용은 국무장관 수정 지시 부록과 공개 논문으로 확인했습니다.",
             "브라운필드 하우징 펀드 · 투자구역 (Investment Zones) · 프리포트 (Freeports)의 산업용지 관련 세부는 확인된 자료를 찾지 못했습니다."]},

{"nat": "독일", "en": "Germany",
 "summary": "독일은 연방 건설법전 (BauGB)의 도시정비 (Sanierung) · 개발조치 (Entwicklungsmaßnahme) · 도시 개조 (Stadtumbau) 수단과, 연방 · 주가 함께 내는 도시건설 지원금 (Städtebauförderung)으로 옛 산업지를 정비해 왔습니다. 2017년에는 주거와 영업이 섞이는 \"도시 지구 (Urbanes Gebiet, MU)\"를 용도지역에 새로 넣었고, 2025년에는 주택 건설을 위해 계획 규정에서 벗어날 수 있는 한시 특례 (\"Bau-Turbo\")를 도입했습니다.",
 "items": [
  {"name": "도시 지구 「Urbanes Gebiet (MU)」",
   "year": "2017 (2017.5.13 시행)", "level": "국가 (연방)",
   "law": "Baunutzungsverordnung (BauNVO) § 6a — Gesetz zur Umsetzung der Richtlinie 2014/52/EU im Städtebaurecht und zur Stärkung des neuen Zusammenlebens in der Stadt (BGBl. I S. 1057)",
   "what": "주거와 함께 영업 (Gewerbe) · 사회 · 문화 시설을 둘 수 있는 새 용도지역입니다. 기능 혼합이 \"같은 비율일 필요가 없어\" 옛 공장 · 영업지를 주거 · 업무 혼합지로 바꾸기 쉬워졌습니다.",
   "tools": ["밀도 상한 지침 — 건폐율 (GRZ) 0.8 · 용적률 (GFZ) 3.0 (혼합지구 MI 는 0.6 · 1.2)",
             "층별 용도 지정 가능 — 가로변 1층 주거 제한, 특정 층 위 주거 전용, 연면적 중 주거 · 영업 비율 지정",
             "허용 — 주택 · 사무 · 소매 · 숙박 · 기타 영업 · 공공시설"],
   "cases": [], "u": "https://www.gesetze-im-internet.de/baunvo/__6a.html"},
  {"name": "도시정비 조치와 개발이익 정산금 「Städtebauliche Sanierungsmaßnahmen · Ausgleichsbetrag」",
   "year": "건설법전 §§ 136 ff. (현행)", "level": "국가 (연방) — 시 시행",
   "law": "Baugesetzbuch (BauGB) §§ 136 ff., § 154 Ausgleichsbetrag des Eigentümers",
   "what": "시가 정비구역 (Sanierungsgebiet)을 정식으로 지정해 낡은 시가지 · 영업지를 정비하고, 정비로 오른 땅값만큼을 소유자에게서 정산금으로 받아 정비 재원으로 씁니다.",
   "tools": ["정산금 — 정비로 생긴 토지가치 상승분 전액 (§ 154 (1))", "정비구역 지정 · 시 주도 시행"],
   "cases": [], "u": "https://www.gesetze-im-internet.de/bbaug/__154.html",
   "note": "최초 도입 연도는 연방 원문에서 확인하지 못했습니다."},
  {"name": "도시 개발조치 「Städtebauliche Entwicklungsmaßnahme」",
   "year": "건설법전 § 165", "level": "국가 (연방) — 시 · 주 시행",
   "law": "BauGB §§ 165 ff.",
   "what": "시 · 지역에 특별히 중요한 지역을 처음 개발하거나 \"도시적 재편 (Neuordnung)\"으로 새 개발에 넘길 때, 시가 개발구역을 지정해 한꺼번에 · 빠르게 시행합니다. 옛 비행장 · 산업 부지를 과학기술단지로 바꾼 베를린 아들러스호프가 이 제도로 개발되었습니다.",
   "tools": ["개발구역 공식 지정 (§ 165 (3))", "시의 토지 취득 · 재편 · 매각으로 일괄 개발"],
   "cases": ["adlershof"], "u": "https://www.gesetze-im-internet.de/bbaug/__165.html"},
  {"name": "도시 개조 조치 「Stadtumbaumaßnahmen」",
   "year": "건설법전 § 171a (현행)", "level": "국가 (연방) — 시 시행",
   "law": "BauGB § 171a",
   "what": "건물 과잉 공급 · 기후 대응 미흡 등 \"상당한 도시 기능 손실\"을 겪는 지역을 지속가능한 구조로 바꾸는 조치입니다. 더 이상 필요 없는 건물을 새 용도로 바꾸고, 놀고 있는 · 비워진 땅 (Brachflächen)을 새로 쓰게 하는 것이 법에 목적으로 적혀 있습니다.",
   "tools": ["불필요한 건축물의 새 용도 전환 (§ 171a (3) 4호)", "전환 불가 건축물 철거 (5호)", "유휴 · 비워진 땅의 지속가능한 재이용 (6호)"],
   "cases": [], "u": "https://www.gesetze-im-internet.de/bbaug/__171a.html",
   "note": "최초 도입 연도는 연방 원문에서 확인하지 못했습니다."},
  {"name": "도시건설 지원금 「Städtebauförderung」 — 「성장과 지속가능한 재생 (Wachstum und nachhaltige Erneuerung)」 등 3개 프로그램",
   "year": "2026 (연방 10억 유로, 기후 조건 2020~)", "level": "국가 (연방 · 주 공동)",
   "law": "Verwaltungsvereinbarung Städtebauförderung 2026/2027 (연방 · 주 행정협약), BauGB § 164a f.",
   "what": "연방이 주와 시에 도시 재생 사업비를 지원합니다. 「성장과 지속가능한 재생」 프로그램은 도심의 빈 주택 · 유휴지 (Brachflächen) 등 기능 손실 지역의 구조 전환을 지원하며, 2020년부터 세 프로그램 모두 기후 보호 · 적응 조치가 지원 조건입니다.",
   "tools": ["2026 연방 예산 10억 유로 — 활력 있는 중심지 (Lebendige Zentren) 3억 8천만 · 사회적 결속 (Sozialer Zusammenhalt) 2억 5천만 · 성장과 지속가능한 재생 3억 7천만 유로",
             "연방 지원금은 2025년까지 7억 9천만 유로 → 2026년 10억 유로, 2029년까지 약 16억 유로로 증액 예정",
             "신청 — 시 · 군이 주 담당 부처에 신청, 주가 사업 선정"],
   "cases": ["zollverein"], "u": "https://www.bmwsb.bund.de/DE/stadtentwicklung/foerderprogramme-stadtentwicklung/staedtebaufoerderung/staedtebaufoerderung-artikel.html"},
  {"name": "주택 건설 한시 특례 「Bau-Turbo」 (§ 246e BauGB)",
   "year": "2025 (2025.10.30 시행, 2030.12.31까지)", "level": "국가 (연방) — 시 동의",
   "law": "Gesetz zur Beschleunigung des Wohnungsbaus und zur Wohnraumsicherung — BauGB § 246e Befristete Sonderregelung für den Wohnungsbau",
   "what": "시가 동의하면 2030년 말까지 건설법전 · 관련 규정에서 벗어나 주택을 짓거나, 기존 건물을 주거로 용도 변경할 수 있게 했습니다. 지구상세계획 (Bebauungsplan)을 새로 만들거나 고치지 않고도 영업 건물의 주거 전환이 가능해졌습니다.",
   "tools": ["적용 대상 — 주거용 신축 · 증축으로 새 주택 확보 · 기존 건물의 주거 용도 변경", "조건 — 이웃 이익을 고려해 공익과 양립할 것, 시 동의"],
   "cases": [], "u": "https://www.gesetze-im-internet.de/bbaug/__246e.html",
   "note": "영업 · 산업지 옆 주거 전환이 늘면 기존 사업장과의 소음 갈등이 생길 수 있습니다."},
  {"name": "노르트라인베스트팔렌 토지기금 「Grundstücksfonds NRW」 (옛 Grundstücksfonds Ruhr)",
   "year": "1980~", "level": "주 (노르트라인베스트팔렌)",
   "law": "주 토지기금 — 현재 NRW.URBAN 이 신탁 관리",
   "what": "주가 탄광 · 철강 · 공장 폐부지를 직접 사들여 정화 · 정비한 뒤 기업 · 주거 · 공원 용지로 되파는 기금입니다. 루르 지역 산업 구조조정의 핵심 토지 수단이었습니다.",
   "tools": ["1980년 이후 184개 사업, 약 2,672ha 매입 · 정화 · 개발", "약 2,437ha 매각, 그중 1,003ha 에 기업 입주",
             "대표 사례 — 도르트문트 피닉스 서부 (PHOENIX West, 마이크로 · 나노 기술), 레버쿠젠 혁신단지, 겔젠키르헨 샬커 페어라인"],
   "cases": ["emscher-park"], "u": "https://nrw-urban.de/der-grundstuecksfonds-nrw-ideenschmiede-fuer-erfolgreiche-flaechenentwicklung/"},
  {"name": "내부 개발 우선 · 빠른 절차 「Innenentwicklung · beschleunigtes Verfahren」",
   "year": "건설법전 § 1a · § 13a", "level": "국가 (연방)",
   "law": "BauGB § 1a (2) · § 13a Bebauungspläne der Innenentwicklung",
   "what": "땅을 아껴 쓰도록 유휴지 재이용 (Wiedernutzbarmachung) · 내부 고밀화를 먼저 고려하게 하고, 내부 개발용 지구상세계획은 간이 절차로 세울 수 있게 했습니다.",
   "tools": ["§ 1a (2) — 유휴지 재이용 · 고밀화 등 내부 개발 우선 고려", "§ 13a — 바닥면적 2만㎡ 미만 (환경영향 검토 시 7만㎡ 미만) 지구상세계획은 빠른 절차"],
   "cases": [], "u": "https://www.gesetze-im-internet.de/bbaug/__13a.html"},
 ],
 "refs": [
  {"t": "gesetze-im-internet.de — § 6a BauNVO Urbane Gebiete", "u": "https://www.gesetze-im-internet.de/baunvo/__6a.html"},
  {"t": "gesetze-im-internet.de — § 17 BauNVO (밀도 상한)", "u": "https://www.gesetze-im-internet.de/baunvo/__17.html"},
  {"t": "dejure.org — § 6a BauNVO 도입 법률 (BGBl. I S. 1057, 2017.5.13 시행)", "u": "https://dejure.org/gesetze/BauNVO/6a.html"},
  {"t": "gesetze-im-internet.de — § 154 BauGB", "u": "https://www.gesetze-im-internet.de/bbaug/__154.html"},
  {"t": "gesetze-im-internet.de — § 165 BauGB", "u": "https://www.gesetze-im-internet.de/bbaug/__165.html"},
  {"t": "gesetze-im-internet.de — § 171a BauGB", "u": "https://www.gesetze-im-internet.de/bbaug/__171a.html"},
  {"t": "gesetze-im-internet.de — § 246e BauGB", "u": "https://www.gesetze-im-internet.de/bbaug/__246e.html"},
  {"t": "gesetze-im-internet.de — § 1a · § 13a BauGB", "u": "https://www.gesetze-im-internet.de/bbaug/__13a.html"},
  {"t": "BMWSB — Städtebauförderung", "u": "https://www.bmwsb.bund.de/DE/stadtentwicklung/foerderprogramme-stadtentwicklung/staedtebaufoerderung/staedtebaufoerderung-artikel.html"},
  {"t": "BMWSB Pressemitteilung (2026.4.15) — Städtebauförderung 2026: 1 Milliarde Euro", "u": "https://www.bmwsb.bund.de/SharedDocs/pressemitteilungen/DE/2026/04/TdS_2026.html"},
  {"t": "BMWSB — Gesetzgebungsverfahren Bau-Turbo (2025.10.29 공포)", "u": "https://www.bmwsb.bund.de/SharedDocs/gesetzgebungsverfahren/DE/ge-bauturbo/bauturbo.html"},
  {"t": "NRW.URBAN — Der Grundstücksfonds NRW", "u": "https://nrw-urban.de/der-grundstuecksfonds-nrw-ideenschmiede-fuer-erfolgreiche-flaechenentwicklung/"},
 ],
 "missing": ["§ 136 정비조치 · § 171a 도시 개조의 최초 도입 연도는 연방 원문에서 날짜를 직접 확인하지 못했습니다.",
             "국제건축전시회 엠셔파크 (IBA Emscher Park)의 주 정부 공식 원문 자료는 이번에 확인하지 못했습니다."]},

{"nat": "네덜란드", "en": "Netherlands",
 "summary": "네덜란드는 2010년 위기 · 회복법 (Crisis- en herstelwet)으로 기존 시가지 · 산업단지를 \"개발 지역\"으로 지정해 환경 기준을 유연하게 다루는 실험을 허용했고, 2024년 환경계획법 (Omgevingswet)으로 여러 법을 하나로 묶어 시의 환경계획 (omgevingsplan) 안에서 용도 · 비용 회수를 다루게 했습니다. 국가는 주택 부족 대응으로 옛 사무 · 공장 건물의 주거 전환에 대출 · 보조금을 줍니다.",
 "items": [
  {"name": "환경계획법 「Omgevingswet」 — 시 환경계획 · 비용 회수 (kostenverhaal) · 우선매수권 (voorkeursrecht)",
   "year": "2024 (2024.1.1 시행)", "level": "국가 — 시 환경계획",
   "law": "Omgevingswet (BWBR0037885) — Hoofdstuk 9 Voorkeursrecht, Afdeling 13.6 Kostenverhaal",
   "what": "공간 · 환경 관련 법들을 하나로 묶은 법입니다. 옛 산업지에 새 기능을 줄 때 시가 기반시설 비용을 개발자에게서 회수하도록 의무화했고, 개발 예정지에 시 · 주 · 국가의 우선매수권을 둘 수 있습니다.",
   "tools": ["비용 회수 의무 (13.11조) — 새로 부여된 기능으로 건축 · 사용하는 자에게 시가 비용을 회수 (귀속성 · 비례성 기준), 납부 전 행위 금지 (13.12조)",
             "사법적 계약 (13.13조) 또는 공법적 회수 (환경계획 · 허가에 기간을 정해 회수)",
             "우선매수권 (9장) — 시 · 주 · 국가 명의로 설정"],
   "cases": ["m4h-rdm-rotterdam"], "u": "https://wetten.overheid.nl/BWBR0037885/"},
  {"name": "위기 · 회복법의 \"개발 지역\" 「Crisis- en herstelwet — ontwikkelingsgebieden」",
   "year": "2010 (2010.3.18 법률) — 2024.1.1 폐지 (환경계획법으로 흡수)", "level": "국가 — 시 · 지역",
   "law": "Crisis- en herstelwet (BWBR0027431) art. 2.2 · 2.3",
   "what": "기존 시가지 · 기존 산업단지 (bestaand bedrijventerrein) · 로테르담 항만 확장지를 실험으로 최대 10년간 \"개발 지역\"으로 지정해, 그 안의 용도계획이 환경 이용 여유 (milieugebruiksruimte)를 최적화하도록 했습니다. 산업 소음 등 환경 기준 때문에 막힌 산업지 전환을 풀기 위한 특례입니다.",
   "tools": ["실험 지정 — 장관 고시, 최대 10년", "개발 지역 용도계획 — 환경 이용 여유 최적화 · 환경 개선 조치를 함께 담음"],
   "cases": ["m4h-rdm-rotterdam", "strijp-s"], "u": "https://wetten.overheid.nl/BWBR0027431/2023-07-01"},
  {"name": "주택 건설 촉진금 「Woningbouwimpuls (Wbi)」",
   "year": "2020 (1차 배분)", "level": "국가 → 시",
   "law": "국가 주택 정책 (volkshuisvestingnederland.nl, RVO 집행)",
   "what": "공공 재정 부족 (publiek financieel tekort)이 입증된 주택 사업에 국가가 시의 기반시설 · 질소 저감 · 토지 정비 비용 일부를 보조합니다. 옛 산업지 전환 주택 사업에도 쓰입니다.",
   "tools": ["대상 — 주택 200호 이상 (또는 합산 200호 이상)", "조건 — 최소 절반이 \"감당 가능한 (betaalbaar)\" 주택, 3년 안 착공 · 10년 안 마지막 착공",
             "실적 — 8차례, 주택 23만 2천여 호 지원 (평균 3분의 2 감당 가능), 5년간 국가 10억 유로 이상"],
   "cases": [], "u": "https://www.volkshuisvestingnederland.nl/onderwerpen/aanpak-woningnood/woningbouwimpuls"},
  {"name": "전환 대출 기금 「Transformatiefaciliteit」",
   "year": "2019 (초)", "level": "국가 (내무 · 왕국관계부 BZK) — 주택촉진기금 SVn 운영",
   "law": "SVn · BZK 공동 기금 (회전형)",
   "what": "옛 업무 · 상업 · 공장 건물과 빈 땅을 (감당 가능한) 주택으로 바꾸려는 개발자에게 착공 전 매입 · 준비 단계 비용을 단기 대출합니다.",
   "tools": ["대출 50만~350만 유로, 총 매입 · 개발비의 50%까지", "목표 — 주택의 3분의 2 이상을 사회 · 중간 임대 또는 감당 가능 분양 (2025.1.1 기준 상한 40만 5천 유로)", "시장 금리 · 국가보조 규정 안에서 운영"],
   "cases": [], "u": "https://www.svn.nl/transformatiefaciliteit/"},
 ],
 "refs": [
  {"t": "wetten.overheid.nl — Omgevingswet", "u": "https://wetten.overheid.nl/BWBR0037885/"},
  {"t": "rijksoverheid.nl — Omgevingswet (2024.1.1 시행)", "u": "https://www.rijksoverheid.nl/onderwerpen/omgevingswet"},
  {"t": "wetten.overheid.nl — Crisis- en herstelwet (2023.7.1 판)", "u": "https://wetten.overheid.nl/BWBR0027431/2023-07-01"},
  {"t": "wetten.overheid.nl — Crisis- en herstelwet (원 공포 2010.3.18)", "u": "https://wetten.overheid.nl/BWBR0027431/2010-03-31"},
  {"t": "Volkshuisvesting Nederland — Woningbouwimpuls", "u": "https://www.volkshuisvestingnederland.nl/onderwerpen/aanpak-woningnood/woningbouwimpuls"},
  {"t": "SVn — Transformatiefaciliteit", "u": "https://www.svn.nl/transformatiefaciliteit/"},
 ],
 "missing": ["암스테르담 하번스타트 (Haven-Stad) · 로테르담 시의 산업용지 보호 · 혼합 정책 원문은 이번에 확인하지 못했습니다.",
             "산업단지 재정비 (herstructurering bedrijventerreinen) 국가 · 주 보조 제도의 현행 원문은 찾지 못했습니다."]},

{"nat": "벨기에 (브뤼셀)", "en": "Belgium (Brussels-Capital Region)",
 "summary": "브뤼셀 수도권 지역은 2001년 지역 토지이용계획 (PRAS)을 블록 단위로 정하고, 인구 급증에 대응해 2013년 \"인구 PRAS\"로 생산활동 전용지 일부를 주거와 섞는 \"도시 기업 지구 (ZEMU)\"를 만들었습니다. 운하 지역 마스터플랜 (Plan Canal)은 인구 증가 · 생산적 도시 경제 · 공공 공간을 함께 목표로 삼았고, 공공 개발사 시티데브 (citydev.brussels)가 생산 공간을 직접 지어 임대합니다. 10년 평가에서는 주거가 늘고 생산 공간은 줄었다는 결과가 나와 현재 PRAS 전면 개정 (Share The City)이 진행 중입니다.",
 "items": [
  {"name": "도시 기업 지구 「Zones d'entreprises en milieu urbain (ZEMU)」 — 「인구 PRAS (PRAS démographique)」",
   "year": "2013 (2013.12.21 시행)", "level": "광역 (브뤼셀 수도권 지역)",
   "law": "Plan régional d'affectation du sol (PRAS) 개정 — PRAS démographique",
   "what": "주거가 금지되던 생산활동 지역 (약 3분의 2)을 포함한 200ha (지역 면적의 약 1%, 45개 블록 · 500여 필지)를 생산활동과 주거가 함께 들어서는 혼합 지구로 바꿨습니다. 1만㎡ 넘는 대형 사업은 혼합이 의무입니다.",
   "tools": ["용도 — 생산활동 · 기업 연계 서비스 (2,000㎡ 미만), 주거 (상한 없음), 상업 (1,000㎡ 미만) · 도매 (2,500㎡ 미만) · 대형 전문점 (3,500㎡ 미만) · 공공시설",
             "1만㎡ 초과 사업 — 대지 바닥면적의 90% 이상을 생산 · 기업 서비스 · 상업에, 연면적의 40% 이상을 주거에",
             "1층은 생산 · 기업 서비스 · 상업 (주거는 허가 시에만)"],
   "cases": [], "u": "https://perspective.brussels/sites/default/files/documents/260324_zemu_texte_fr.pdf",
   "note": "브뤼셀 지역청 (perspective.brussels) 10년 평가 (2026.3): 2014년 이후 연면적 +23만 5천㎡ (+20%) · 허가 48만㎡, 허가 연면적의 약 4분의 3이 주거 (약 3,000호, 80% 민간 분양), 생산활동 면적은 6만 5천㎡ (−13%) 줄고 사무 (+19%) · 상업 (+22%)이 늘었습니다. 대형 사업은 70%가 주거여서 \"40% 최소 주거\" 규정이 지금 시장에서는 필요 없다고 평가했습니다. 학계도 ZEMU 에서 공공이 주거를 들여 산업 젠트리피케이션이 일어난다고 지적합니다 (De Boeck · Ryckewaert 2020)."},
  {"name": "지역 토지이용계획 전면 개정 「Share The City — modification du PRAS」",
   "year": "2001 (첫 PRAS) → 현재 개정 진행", "level": "광역 (브뤼셀 수도권 지역)",
   "law": "Plan régional d'affectation du sol (PRAS)",
   "what": "지역 안 모든 필지의 건축 가능 여부와 허용 용도를 정하는 법정 계획 (2001년 첫 시행)을 기후 · 사회 · 경제 과제에 맞게 전면 개정하는 작업입니다. ZEMU 10년 평가 등 보완 연구가 개정 근거로 쓰입니다.",
   "tools": ["블록 단위 용도 지정 — 주거 지역 생산 공간 250㎡, 혼합 지역 1,000㎡, 강 혼합 지역 1,500㎡까지 (공개 조사 거치면 500 · 1,500㎡) — De Boeck · Ryckewaert 2020 정리", "산업 지역 · 항만 · 운송 지역은 단일 산업 용도"],
   "cases": [], "u": "https://sharethecity.brussels"},
  {"name": "운하 지역 마스터플랜 「Plan Canal」",
   "year": "2012 국제 공모 → 2015.2.5 구상 확정", "level": "광역 (브뤼셀 수도권 지역, 7개 기초자치단체)",
   "law": "지역 정부 전략 계획 (Plan directeur, 알렉상드르 셰메토프 Alexandre Chemetoff 안)",
   "what": "14km 운하 지역 (옛 산업 · 물류 지대)을 대상으로 2025년까지 인구 급증 대응 · 생산적 도시 경제 발전 · 공공 공간 질 향상의 세 가지를 함께 추구했습니다.",
   "tools": ["실행 팀 — 지역 총리실 · 도시개발공사 (SAU) · 건축 총괄 (BMA) · urban.brussels · perspective.brussels", "경관 품질 계획 (BKP) 수립"],
   "cases": [], "u": "https://perspective.brussels/fr/projets/poles-strategiques/territoire-du-canal-bkp-et-plan-canal"},
  {"name": "지역 개발 기본계획 「Plan d'Aménagement Directeur (PAD)」",
   "year": "브뤼셀 국토계획법전 (CoBAT) 개혁 이후", "level": "광역 (브뤼셀 수도권 지역)",
   "law": "Code bruxellois de l'aménagement du territoire (CoBAT)",
   "what": "전략과 규제를 한 번에 정하는 지역 계획입니다. 용도와 용도별 면적 · 공공 공간 · 건축 특성 · 교통 · 문화재 보호를 정하고, 그 구역 안에서는 PRAS · 상세계획 (PPAS) · 건축 규칙 중 어긋나는 규정을 대체합니다.",
   "tools": ["전략편 + 규제편 (민간 · 공공 모두 구속)", "환경영향보고서 (RIE) · 60일 공개 조사"],
   "cases": [], "u": "https://perspective.brussels/fr/outils-de-planification/plans-et-programmes-dinitiative-regionale/pad"},
  {"name": "도시 재생 계약 「Contrat de rénovation urbaine (CRU)」",
   "year": "지역 재생 프로그램", "level": "광역 — 여러 기초자치단체 경계 지역",
   "law": "도시 재활성화 지역 (Zone de Revitalisation Urbaine, ZRU) 안의 지역 프로그램",
   "what": "여러 동네 · 기초자치단체에 걸친 지역에 공공 공간 · 주택 · 환경 · 경제 재활성화 사업을 묶어 기간을 정해 집중 투자합니다.",
   "tools": ["지역 예산 2,200만 유로 + 공공 · 민간 투자", "시행 기간 7.5년 (동네 계약 CQD 는 6.5년)", "사업 — 공공 공간 · 사회주택 · 환경 · 경제 재활성화 · 사회 결속"],
   "cases": [], "u": "https://perspective.brussels/fr/outils-de-planification/plans-et-programmes-dinitiative-regionale/cru"},
  {"name": "공공 생산 공간 개발 · 임대 「citydev.brussels」",
   "year": "운영 중", "level": "광역 공공 개발사",
   "law": "브뤼셀 지역 공공 부동산 개발사",
   "what": "옛 산업 부지를 사들여 중소기업 단지 · 작업장을 짓고 임대 · 매각합니다. 생산 공간을 시장에 맡기지 않고 공공이 공급 · 관리하는 수단입니다.",
   "tools": ["옛 산업 부지를 중소기업 단지로 재생 — 캐널시티 (CanalCity, 안데를레흐트) · 스테빈 (Stevin, 몰렌베이크) · 코페르니크 (Copernic, 하런 — 10번째 생산활동 단지)",
             "작업장 · 사무 · 상업 공간 · 땅을 임대 · 매각"],
   "cases": [], "u": "https://www.citydev.brussels/fr",
   "note": "De Boeck · Ryckewaert (2020)는 시티데브의 산업단지가 2016년 2만 4천여 개 일자리를 품었고 100㎡ 안팎 소형 작업장의 공실률이 10% 미만이라고 정리했습니다 (영문 논문, 시티데브 원문 수치는 따로 확인하지 못함)."},
 ],
 "refs": [
  {"t": "perspective.brussels (2026.3) — Les ZEMU ont 10 ans", "u": "https://perspective.brussels/sites/default/files/documents/260324_zemu_texte_fr.pdf"},
  {"t": "Share The City — La modification du PRAS", "u": "https://sharethecity.brussels"},
  {"t": "perspective.brussels — Territoire du Canal (BKP et Plan Canal)", "u": "https://perspective.brussels/fr/projets/poles-strategiques/territoire-du-canal-bkp-et-plan-canal"},
  {"t": "perspective.brussels — PAD", "u": "https://perspective.brussels/fr/outils-de-planification/plans-et-programmes-dinitiative-regionale/pad"},
  {"t": "perspective.brussels — CRU", "u": "https://perspective.brussels/fr/outils-de-planification/plans-et-programmes-dinitiative-regionale/cru"},
  {"t": "citydev.brussels", "u": "https://www.citydev.brussels/fr"},
  {"t": "De Boeck, S. & Ryckewaert, M. (2020) The Preservation of Productive Activities in Brussels, Urban Planning 5(3)", "u": "https://doi.org/10.17645/up.v5i3.3092"},
 ],
 "missing": ["PAD 제도의 도입 연도 (CoBAT 개혁 시행일)는 원문에서 직접 확인하지 못했습니다.",
             "플랑드르 브라운필드 협약 (brownfieldconvenanten) · 왈롱 재정비 대상지 (SAR)는 이번 범위 (브뤼셀)에서 확인하지 않았습니다."]},

{"nat": "프랑스", "en": "France",
 "summary": "프랑스는 공공이 땅을 모아 정비하는 협의 개발지구 (ZAC)로 옛 산업 · 항만 부지를 재생해 왔고, 2021년 기후 · 회복력법으로 2050년 \"순 토지 인공화 제로 (ZAN)\"를 목표로 정해 유휴지 (friche) 재활용을 국가 우선 과제로 삼았습니다. 이를 위해 유휴지 기금 (Fonds friches, 7억 5천만 유로)을 만들었고, 산업 재건을 위해 「산업 지역 (Territoires d'industrie)」과 「즉시 입주 가능 부지 (sites clés en main)」를 지정해 지원합니다.",
 "items": [
  {"name": "협의 개발지구 「Zone d'aménagement concerté (ZAC)」",
   "year": "도시계획법전 L. 311-1 (현행)", "level": "국가 제도 — 시 · 공공기관 시행",
   "law": "Code de l'urbanisme art. L. 311-1 et s.",
   "what": "공공 (시 · 공공기관)이 땅을 사들이거나 사들일 땅을 정비 · 기반시설을 갖춘 뒤 공공 · 민간 이용자에게 매각 · 양여하는 구역 개발 방식입니다. 옛 산업 · 철도 · 항만 부지 재생의 대표 수단입니다.",
   "tools": ["창설 → 실현 두 단계 (창설 시 주민 협의 · 영향평가 · 전자 공개 참여)", "공공시설 계획 승인 · 개발자와 재정 분담 협약 (participation)", "개발 사업자에게 시행 위탁 가능"],
   "cases": ["paris-rive-gauche", "lyon-confluence", "ile-de-nantes"], "u": "https://outil2amenagement.cerema.fr/sites/outils2am/files/fichiers/2023/08/Fiche_outils_ZAC.pdf",
   "note": "법전 원문 (Légifrance)은 접속 차단으로 직접 열지 못했고, 정의 · 절차는 국가 (Cerema · 부처) 도구 안내서로 확인했습니다. 도입 연도는 확인하지 못했습니다."},
  {"name": "순 토지 인공화 제로 「Zéro artificialisation nette (ZAN)」",
   "year": "2021 (기후 · 회복력법 2021.8.22)", "level": "국가 → 지역 · 시 계획",
   "law": "Loi n° 2021-1104 du 22 août 2021 « Climat et résilience »",
   "what": "2050년까지 순 토지 인공화를 0으로 하고, 2021~2031년 자연 · 농지 · 산림 (ENAF) 소비를 직전 10년의 절반으로 줄이게 했습니다. 기존 시가지 재생과 유휴지 · 빈 건물 재활용이 우선 수단이 되었습니다.",
   "tools": ["2011~2021년 소비 24만 3,136ha → 2021~2031년 국가 목표 12만 1,568ha", "프랑스 유휴지 17만ha 재활용 · 빈집 110만 호 활용 강조",
             "공공토지기관 (EPF)이 국토의 80%를 담당 — 토지 감시 · 연구 공동 재원 · 유휴지 발굴 지원"],
   "cases": [], "u": "https://artificialisation.developpement-durable.gouv.fr/sites/artificialisation/files/fichiers/2024/07/ZAN%20DP%2027nov23_VF-17_0.pdf",
   "note": "산업단지 확장 수요와 충돌해 지역 배분 · 국가 중요 사업 예외 문제가 계속 논의되고 있습니다."},
  {"name": "유휴지 재활용 기금 「Fonds friches (fonds pour le recyclage des friches)」",
   "year": "2021 (프랑스 회복 계획 France Relance) → 녹색 기금 (Fonds vert)으로 이어짐", "level": "국가 → 지역 지사 공모",
   "law": "France Relance — 유휴지 재활용 기금 (3차 공모)",
   "what": "옛 산업 · 상업 부지 등 유휴지를 정화 · 정비해 주거 · 경제 · 공공시설로 다시 쓰는 사업의 적자 부분을 보조했습니다. 지금은 녹색 기금 (Fonds vert)의 한 항목으로 이어집니다.",
   "tools": ["3차례 공모에 2,999건 신청, 1,382건에 7억 5천만 유로 지원 (2021.5 3억 5천만, 2022.1 1억 유로 증액 포함)",
             "기대 효과 — 유휴지 3,375ha 재활용, 주거 약 670만㎡ (3분의 1 이상 사회주택) · 경제 공간 500만㎡ 이상 · 공공시설 400만㎡ 이상"],
   "cases": [], "u": "https://www.cerema.fr/fr/actualites/recyclage-friches-quels-enseignements-centaines-projets"},
  {"name": "산업 지역 「Territoires d'industrie」",
   "year": "2018 (1기 149곳) → 2023.11.9 2기 (2023~2027, 183곳)", "level": "국가 (국토결속청 ANCT · 기업총국 DGE) → 기초자치단체 연합",
   "law": "국가 산업 재건 프로그램",
   "what": "지역 정치인과 기업이 함께 산업 재건 사업을 세우도록 지역을 지정해 지원합니다. 2기에서는 \"산업 용지 확보\"가 4대 축의 하나입니다.",
   "tools": ["4대 축 — 혁신 · 인력 · 산업 용지 · 생태 · 에너지 전환", "2024년 녹색 기금 1억 유로", "1기 1,800여 사업 지원"],
   "cases": [], "u": "https://anct.gouv.fr/actualites/territoires-d-industrie-entree-dans-la-phase-ii-un-nouveau-temps-pour-l-industrie"},
  {"name": "즉시 입주 가능 산업 부지 「Sites clés en main France 2030」",
   "year": "2024 (2024.4.16 1차 55곳)", "level": "국가 → 시 · 공공개발사",
   "law": "France 2030 · Territoires d'industrie 연계",
   "what": "인허가 · 정비를 미리 끝내 기업이 바로 공장을 지을 수 있는 산업 부지를 지정 · 지원합니다. 토지 절약을 위해 유휴지 재활용 부지를 우선했습니다.",
   "tools": ["55곳 · 총 3,342ha (평균 60ha, 3~340ha)", "30곳이 일부 · 전부 유휴지 (recyclage foncier)", "ANCT · Cerema 기술 지원, 행정 절차 앞당김"],
   "cases": [], "u": "https://agence-cohesion-territoires.gouv.fr/sites/default/files/2024-04/DP_TI_siteclesenmain_VF%2018%20avril%202024.pdf"},
 ],
 "refs": [
  {"t": "Cerema · 부처 — Fiche outils ZAC", "u": "https://outil2amenagement.cerema.fr/sites/outils2am/files/fichiers/2023/08/Fiche_outils_ZAC.pdf"},
  {"t": "생태전환부 — Zéro Artificialisation Nette, guide synthétique (2023.11.27)", "u": "https://artificialisation.developpement-durable.gouv.fr/sites/artificialisation/files/fichiers/2024/07/ZAN%20DP%2027nov23_VF-17_0.pdf"},
  {"t": "Cerema — Recyclage des friches : quels enseignements … du fonds Friches", "u": "https://www.cerema.fr/fr/actualites/recyclage-friches-quels-enseignements-centaines-projets"},
  {"t": "ANCT — Territoires d'industrie : entrée dans la phase II", "u": "https://anct.gouv.fr/actualites/territoires-d-industrie-entree-dans-la-phase-ii-un-nouveau-temps-pour-l-industrie"},
  {"t": "ANCT — Territoires d'industrie, lancement du temps II 2023-2027 (dossier de presse)", "u": "https://media.anct.gouv.fr/s3fs-public/2023-11/TI_DP_AG_web_1.pdf"},
  {"t": "Sites clés en main France 2030 — dossier de presse (2024.4.16)", "u": "https://agence-cohesion-territoires.gouv.fr/sites/default/files/2024-04/DP_TI_siteclesenmain_VF%2018%20avril%202024.pdf"},
 ],
 "missing": ["법령 원문 사이트 (Légifrance)는 접속이 막혀 ZAC (L. 311-1) · 유휴지 정의 (L. 111-26) · 공공토지기관 (EPF, L. 321-1) 조문을 직접 열지 못했습니다.",
             "국가 중요 사업 (OIN) · 유로메디테라네 등 국가 개발기구의 산업지 재생 제도는 확인된 자료를 찾지 못했습니다."]},

{"nat": "스페인", "en": "Spain",
 "summary": "스페인은 국가 토지 · 도시재생법 (TRLSRU 2015)이 도시 변환 사업에서 개발이익 일부 (5~15%)의 공공 환수와 기반시설 부담을 정하고, 실제 산업지 재생은 시 · 자치주의 계획과 공공 회사가 맡습니다. 바르셀로나는 2000년 공업지역 22a 를 지식기반 혼합지구 22@ 로 바꾸고 2022년 주거 · 녹지를 늘리는 쪽으로 다시 고쳤으며, 빌바오는 1992년 국가 · 바스크 정부가 반씩 출자한 공공 회사 「빌바오 리아 2000」으로 옛 산업 · 항만 · 철도 부지를 재생했습니다.",
 "items": [
  {"name": "토지 · 도시재생법 통합본 「Texto refundido de la Ley de Suelo y Rehabilitación Urbana (TRLSRU)」",
   "year": "2015 (2015.10.30 왕령)", "level": "국가",
   "law": "Real Decreto Legislativo 7/2015, de 30 de octubre",
   "what": "도시 변환 사업 (actuaciones de transformación urbanística)을 정의하고, 이미 도시화된 땅의 재정비 · 용적 증가 사업에도 공공시설 확충과 개발이익 환수 의무를 지웁니다. 옛 공업지를 고밀 혼합지로 바꿀 때의 기본 틀입니다.",
   "tools": ["변환 사업 유형 — 신규 도시화 · 기존 도시지 재정비 (reforma o renovación) · 용적 · 새 용도에 따른 시설 보강 (actuaciones de dotación)",
             "개발이익 환수 — 가중 평균 용적의 5~15% 해당 땅을 공공 토지 재산으로 무상 이전 (예외적으로 최대 20%)",
             "도로 · 녹지 · 공공시설 용지 기부 · 기반시설 비용 부담"],
   "cases": [], "u": "https://www.boe.es/buscar/act.php?id=BOE-A-2015-11723"},
  {"name": "바르셀로나 22@ 계획 「Pla 22@ — Modificació del Pla General Metropolità (MPGM)」",
   "year": "2000", "level": "도시 (바르셀로나)",
   "law": "Modificació del PGM per a la renovació de les zones industrials del Poblenou — districte d'activitats 22@BCN",
   "what": "산 마르티 구의 공업지 약 200ha 를 지식기반 경제 활동과 주거 · 시설이 섞인 혼합 지구로 바꿨습니다. 공업 전용 용도 (22a)를 지식집약 활동 (22@)으로 바꾸고 용적 인센티브를 공공 기여와 맞바꿨습니다.",
   "tools": ["용도 전환 22a → 22@ (지식집약 \"@활동\" 포함)", "용적 상향을 공공주택 · 지식시설 (7@) · 녹지 용지 기부와 교환", "기존 주택 합법화 · 공업 유산 보존"],
   "cases": ["22at-barcelona"], "u": "https://ajuntament.barcelona.cat/ecologiaurbana/mpgm22@/ca/",
   "note": "세부 용적 단계 · 기부 비율은 사례 노트에 정리했고, 시 원문에서는 \"200ha 공업지의 경제활동 거점 전환\"까지 확인했습니다."},
  {"name": "더 포용적 · 지속가능한 22@ 계획 개정 「MpPGM per un 22@ més inclusiu i sostenible」",
   "year": "2022 (2022.5.31 최종 승인)", "level": "도시 (바르셀로나)",
   "law": "Modificació puntual del PGM — Subcomissió d'Urbanisme de Barcelona 승인",
   "what": "2017년 「22@ 다시 생각하기 (Repensem el 22@)」 (1,000명 이상 참여) · 2018 협약을 거쳐, 아직 개발되지 않은 22@ 땅 40%를 대상으로 주거 · 녹지 · 근린시설을 늘리고 허용 용도를 넓혔습니다.",
   "tools": ["감당 가능한 주택 1만 2천 호 (2000년 계획의 2배 이상), 전체 잠재 1만 7천 호", "남은 100만㎡ 연면적으로 일자리 6만 개 목표",
             "거리 셋 중 하나를 녹색 축으로 — 보행 · 녹지 10ha 이상 회복, 근린시설 용지 3만 5천㎡", "허용 용도 확대 — 문화 · 스포츠 · 교육 · 예술 창작 · 사회연대경제 · 녹색경제"],
   "cases": ["22at-barcelona"], "u": "https://ajuntament.barcelona.cat/premsa/2022/02/09/un-22-ple-de-vida-amb-mes-habitatge-i-activitat-economica-equipaments-de-barri-i-verd/",
   "note": "업무 · 호텔 위주 개발과 주거 부족, 산업 젠트리피케이션 비판 (Charnock 등 2014 · Camerin 2019 — De Boeck · Ryckewaert 2020 재인용)이 개정 배경입니다."},
  {"name": "도심 신축 · 대수선 주택 30% 공공 보호주택 의무 (바르셀로나 PGM 개정)",
   "year": "2018 (2018.12.5 자치주 최종 승인)", "level": "도시 (바르셀로나) — 카탈루냐 자치주 승인",
   "law": "Modificació del PGM — Llei 18/2007 del dret a l'habitatge 근거",
   "what": "도시지역에서 주거 연면적 600㎡ 넘는 신축 · 대수선 사업은 주거 연면적의 30%를 공공 보호주택 (HPO)으로 짓게 했습니다. 공업지 전환 주거 사업에도 적용되는 공공 기여 수단입니다.",
   "tools": ["대상 — 도시지 필지 최대 주거 연면적 600㎡ 초과", "의무 — 주거 연면적 30% 보호주택"],
   "cases": [], "u": "https://govern.cat/gov/notes-premsa/315482/aprovada-la-modificacio-de-planejament-a-barcelona-per-destinar-el-30-percent-de-les-noves-promocions-o-rehabilitacions-a-habitatge-protegit",
   "note": "2016년 7월 이후 땅을 산 사업에 적용하는 경과 규정이 있습니다 (자치주 보도자료)."},
  {"name": "빌바오 공공 재생 회사 「BILBAO Ría 2000」",
   "year": "1992 (1992.11.19 설립)", "level": "도시권 (빌바오 대도시권) — 국가 · 바스크 공동",
   "law": "공공 자본 주식회사 (Sociedad Anónima de capital público, 비영리)",
   "what": "옛 산업 지대 회복을 이끌기 위해 국가 (SEPES · 빌바오 항만청 · ADIF)와 바스크 정부 · 비스카야 주 · 빌바오 · 바라칼도 시가 반씩 출자해 만든 회사입니다. 주주가 가진 유휴지의 용도를 시와 조정해 바꾸고, 그 매각 수익으로 도시 재생 · 교통 · 환경 사업을 합니다.",
   "tools": ["지분 — 국가 50% · 바스크 행정기관 50%", "초기 자본 180만 유로 — 이후 주주 예산 없이 토지가치 상승 · 매각 수익으로 재정 균형",
             "사업 — 아반도이바라 · 아메솔라 · 바라칼도 · 바수르토-산마메스 · 철도 기반시설 등"],
   "cases": ["abandoibarra"], "u": "https://www.bilbaoria2000.org/bilbao-ria-2000/que-es-bilbao-ria-2000/"},
 ],
 "refs": [
  {"t": "BOE — Real Decreto Legislativo 7/2015 (TRLSRU)", "u": "https://www.boe.es/buscar/act.php?id=BOE-A-2015-11723"},
  {"t": "Ajuntament de Barcelona — MpPGM 22@: Un Poblenou més inclusiu, sostenible i productiu", "u": "https://ajuntament.barcelona.cat/ecologiaurbana/mpgm22@/ca/"},
  {"t": "Ajuntament de Barcelona (2022.2.9) — Un 22@ ple de vida amb més habitatge i activitat econòmica", "u": "https://ajuntament.barcelona.cat/premsa/2022/02/09/un-22-ple-de-vida-amb-mes-habitatge-i-activitat-economica-equipaments-de-barri-i-verd/"},
  {"t": "Govern.cat — Aprovada la modificació de planejament a Barcelona per destinar el 30% … a habitatge protegit", "u": "https://govern.cat/gov/notes-premsa/315482/aprovada-la-modificacio-de-planejament-a-barcelona-per-destinar-el-30-percent-de-les-noves-promocions-o-rehabilitacions-a-habitatge-protegit"},
  {"t": "BILBAO Ría 2000 — ¿Qué es BILBAO Ría 2000?", "u": "https://www.bilbaoria2000.org/bilbao-ria-2000/que-es-bilbao-ria-2000/"},
 ],
 "missing": ["2000년 22@ 계획의 관보 (DOGC) 원문은 직접 열지 못했습니다 — 시 공식 페이지로 확인했습니다.",
             "마드리드 · 국가 차원의 산업지 재생 보조 (예: 회복 · 전환 · 회복력 계획 PRTR 의 동네 단위 재생 프로그램) 원문은 확인하지 못했습니다."]},

{"nat": "덴마크", "en": "Denmark",
 "summary": "덴마크는 2003년 계획법 개정으로 공업 · 항만 기능이 끝나 가는 지역을 \"도시 전환 지역 (byomdannelsesområde)\"으로 지정해, 소음이 남아 있어도 일정 기간 안에 없어진다는 조건으로 주거 계획을 허용했습니다. 코펜하겐은 2007년 법으로 시 (95%) · 국가 (5%)가 소유한 개발회사 「By & Havn」을 세워 항만 · 외레스타드 땅을 개발 · 매각하고 그 수익으로 지하철 등 기반시설 부채를 갚는 구조를 만들었습니다.",
 "items": [
  {"name": "도시 전환 지역 「byomdannelsesområde」 (계획법)",
   "year": "2003 (2003.7.1 계획법 개정)", "level": "국가 → 시 계획 (kommuneplan · lokalplan)",
   "law": "Planloven § 11 d · § 15 a, stk. 2 — 환경청 지침 「Ekstern støj i byomdannelsesområder」 (Vejledning nr. 3, 2003)",
   "what": "환경 부담 공업 · 항만 등의 이용이 대부분 끝났거나 끝나 가는 지역만 도시 전환 지역으로 정할 수 있습니다. 그 안의 상세계획은 소음이 남아 있는 땅도 소음 민감 용도 (주거 등)로 지정할 수 있습니다.",
   "tools": ["지정 요건 — 환경 부담 공업 · 항만 이용이 지역 대부분에서 끝났거나 정리 중 (§ 11 d)",
             "소음 특례 — 소음이 한정된 전환 기간 (상세계획 공고 뒤 대체로 8년을 크게 넘지 않음) 안에 없어진다는 확신이 있을 때 주거 지정 허용 (§ 15 a, stk. 2 · 환경청 지침)"],
   "cases": [], "u": "https://www.retsinformation.dk/eli/lta/2020/1157",
   "note": "도입일 (2003.7.1)은 환경청 지침 (2003)과 검색 요약으로 확인했고, 개정 법률 원문은 따로 열지 않았습니다."},
  {"name": "개발회사 「Udviklingsselskabet By & Havn I/S」",
   "year": "2007 (법 제551호, 2007.6.6)", "level": "도시 (코펜하겐) · 국가",
   "law": "Lov om Metroselskabet I/S og Udviklingsselskabet By & Havn I/S (현행 공고 LBK nr. 569 af 19. maj 2025)",
   "what": "코펜하겐 시와 교통부 장관이 함께 세운 개발회사로, 회사 소유 땅 (외레스타드 · 노르하운 · 코펜하겐 항만)의 개발과 항만 운영을 맡습니다. 옛 항만 · 공업지 땅값 상승을 지하철 투자 재원으로 돌리는 구조입니다.",
   "tools": ["지분 — 코펜하겐 시 95% · 교통부 장관 5% (§ 2)", "목적 — 회사 땅의 개발과 코펜하겐 항만 운영 (§ 15)", "이사회 8명"],
   "cases": ["nordhavn", "the-silo-copenhagen"], "u": "https://www.retsinformation.dk/eli/lta/2025/569/pdf",
   "note": "공공 토지를 시장가로 팔아 부채를 갚아야 해 고밀 · 고가 개발 압력이 생긴다는 비판이 있습니다 (사례 노트 참조)."},
 ],
 "refs": [
  {"t": "Retsinformation — Planloven (LBK nr. 1157 af 1. juli 2020)", "u": "https://www.retsinformation.dk/eli/lta/2020/1157"},
  {"t": "Miljøstyrelsen — Ekstern støj i byomdannelsesområder (Vejledning nr. 3, 2003)", "u": "https://www2.mst.dk/udgiv/publikationer/2003/87-7972-771-9/pdf/87-7972-771-9.pdf"},
  {"t": "Retsinformation — Bekendtgørelse af lov om Metroselskabet I/S og Udviklingsselskabet By & Havn I/S (2025)", "u": "https://www.retsinformation.dk/eli/lta/2025/569/pdf"},
 ],
 "missing": ["스웨덴 (함마르비 셰스타드 · 베스트라 함넨 관련) 국가 · 시의 산업지 전환 지원 제도는 스웨덴어 원문을 확인하지 못했습니다.",
             "덴마크 국가 차원의 유휴 산업지 정비 보조금 제도는 확인된 자료를 찾지 못했습니다."]},

{"nat": "아일랜드", "en": "Ireland",
 "summary": "아일랜드는 1997년 더블린 도크랜드 개발청 (DDDA)을 법으로 세워 옛 항만 지역의 사회 · 경제 재생을 맡겼고, 2000년 계획법의 전략 개발구역 (SDZ)으로 국가가 중요한 개발지를 지정해 계획 · 허가를 빠르게 했습니다. 2015년에는 빈 땅 부담금 (vacant site levy)과 재생 용지 지정을, 국가 계획 「프로젝트 아일랜드 2040」에서는 20억 유로의 도시 재생 · 개발 기금 (URDF)을 도입했습니다.",
 "items": [
  {"name": "더블린 도크랜드 개발청 「Dublin Docklands Development Authority (DDDA)」",
   "year": "1997 (2016 해산)", "level": "국가 — 더블린",
   "law": "Dublin Docklands Development Authority Act, 1997 (No. 7 of 1997) · Dissolution Act 2015 (No. 55 of 2015)",
   "what": "더블린 도크랜드 지역의 지속가능한 사회 · 경제 재생과 물리 환경 개선, 세관 부두 (Custom House Docks) 지역의 금융 서비스 발전을 맡은 법정 기구입니다. 마스터플랜과 계획 체계 (planning scheme)를 세우고, 승인된 계획에 맞는 개발은 허가 면제 개발 (exempted development)로 다뤘습니다.",
   "tools": ["마스터플랜 (24조) · 계획 체계 (25조) — 계획에 맞는 개발은 허가 면제", "토지 취득 권한", "해산 뒤 기능 · 토지는 더블린 시의회로 이관 (2015법)"],
   "cases": ["dublin-docklands", "chq-epic"], "u": "https://www.irishstatutebook.ie/eli/1997/act/7/enacted/en/print"},
  {"name": "전략 개발구역 「Strategic Development Zone (SDZ)」",
   "year": "2000", "level": "국가 지정 → 개발기관 · 계획청",
   "law": "Planning and Development Act 2000, Part IX (ss. 165–171)",
   "what": "정부가 국가에 경제 · 사회적으로 중요하다고 보는 개발지를 SDZ 로 지정하고, 개발기관이 계획 체계 (planning scheme)를 세웁니다. 승인된 계획 체계에 맞는 신청은 빠르게 허가됩니다. 더블린 도크랜드 (노스 로츠 · 그랜드 캐널 독)가 SDZ 로 지정되었습니다.",
   "tools": ["정부 명령으로 지정 — 개발기관 · 허용 개발 유형 · 사유 명시 (166조)", "부지 취득 (167조) · 계획 체계 (168~169조)"],
   "cases": ["dublin-docklands"], "u": "https://www.irishstatutebook.ie/eli/2000/act/30/enacted/en/print",
   "note": "도크랜드 SDZ 지정일 (2012.12.18) · 계획 체계 승인 (2014)은 검색 요약으로만 보아 확정하지 않았습니다 (사례 노트 참조)."},
  {"name": "빈 땅 부담금 · 재생 용지 「Vacant Site Levy · regeneration land」",
   "year": "2015", "level": "국가 → 지방 계획청",
   "law": "Urban Regeneration and Housing Act 2015 (No. 33 of 2015), Part 2",
   "what": "지방 계획청이 주거 용지 · 재생 용지 (regeneration land — 재생이 필요한 지역으로 계획에 정한 땅)의 빈 땅을 등록하고, 소유자에게 부담금을 물려 개발을 재촉합니다.",
   "tools": ["부담금 — 빈 땅 시장가치의 3% (대출 잔액 비율에 따라 0~1.5% 감경)", "빈 땅 등록부 · 시장가치 결정 · 이의 절차"],
   "cases": [], "u": "https://www.irishstatutebook.ie/eli/2015/act/33/enacted/en/print",
   "note": "현행 부담률은 이후 개정 · 주거 용지세 (Residential Zoned Land Tax) 도입으로 바뀌었을 수 있으나 확인하지 못했습니다."},
  {"name": "도시 재생 · 개발 기금 「Urban Regeneration and Development Fund (URDF)」",
   "year": "2018 (프로젝트 아일랜드 2040)", "level": "국가 → 5대 도시 · 큰 읍",
   "law": "Project Ireland 2040 — National Development Plan",
   "what": "큰 도시 · 읍의 새 주거 · 상업 개발을 북돋우는 재생 사업에 국가가 사업비를 나눠 냅니다.",
   "tools": ["예산 20억 유로 (2027년까지)", "목적 — 압축 성장 (Compact Growth)"],
   "cases": [], "u": "https://assets.gov.ie/8343/103a14d264e6493a8e88f663f5215d34.pdf",
   "note": "정부 URDF 안내 페이지 (gov.ie)는 접속이 막혀, 지역별 「Project Ireland 2040」 자료로 예산만 확인했습니다. 보조율 (최대 75%) 등은 확인하지 못했습니다."},
 ],
 "refs": [
  {"t": "Irish Statute Book — Dublin Docklands Development Authority Act, 1997", "u": "https://www.irishstatutebook.ie/eli/1997/act/7/enacted/en/print"},
  {"t": "Irish Statute Book — Dublin Docklands Development Authority (Dissolution) Act 2015", "u": "https://www.irishstatutebook.ie/eli/2015/act/55/enacted/en/print.html"},
  {"t": "Irish Statute Book — Planning and Development Act 2000 (Part IX SDZ)", "u": "https://www.irishstatutebook.ie/eli/2000/act/30/enacted/en/print"},
  {"t": "Irish Statute Book — Urban Regeneration and Housing Act 2015", "u": "https://www.irishstatutebook.ie/eli/2015/act/33/enacted/en/print"},
  {"t": "gov.ie — Project Ireland 2040 in the Mid-West (URDF 20억 유로)", "u": "https://assets.gov.ie/8343/103a14d264e6493a8e88f663f5215d34.pdf"},
  {"t": "Dublin City Council — Development Plan 2022-2028, SDRA 6 Docklands", "u": "https://www.dublincity.ie/dublin-city-development-plan-2022-2028/written-statement/chapter-13-strategic-development-regeneration-areas/138-sdra-6-docklands"},
 ],
 "missing": ["토지개발청 (Land Development Agency Act 2021) · 주거 용지세 (Residential Zoned Land Tax)의 원문은 이번에 확인하지 못했습니다."]},

{"nat": "이탈리아", "en": "Italy",
 "summary": "이탈리아는 국가가 주거 · 도시 재생 공모 사업 (PINQuA, 28억 유로)을 펴고, 토지 · 재생 규칙은 주 (Regione)가 정합니다. 에밀리아로마냐 주는 2017년 법으로 2050년 \"토지 소비 제로\"와 시가지 안 재생 사업의 건축 부담금 감면을 정했고, 밀라노는 2017년 프로그램 협약 (Accordo di Programma)으로 옛 철도 화물역 7곳을 녹지 65% 의 혼합 지구로 바꾸고 있습니다.",
 "items": [
  {"name": "주거 질 혁신 국가 프로그램 「Programma Innovativo Nazionale per la Qualità dell'Abitare (PINQuA)」",
   "year": "2019 법 근거 (Legge 160/2019, comma 437) · 2021~ 국가회복계획 (PNRR M5C2 투자 2.3)", "level": "국가 (인프라 · 교통부) → 시 · 주",
   "law": "Legge 27 dicembre 2019, n. 160, art. 1, comma 437 — PNRR Missione 5 Componente 2, Investimento 2.3",
   "what": "공공 · 사회주택과 공공 공간 · 유휴 건물의 재기능화를 묶은 도시 재생 사업에 국가가 재원을 줍니다. \"토지 소비 제로\" 원칙을 평가 기준으로 삼았습니다.",
   "tools": ["총 28억 유로, 159개 사업 선정 (남부 약 40%)", "일반 사업 최대 1,500만 유로 · 시범 사업 최대 1억 유로",
             "기대 효과 — 주택 1만 6,500호, 공공 주거 면적 130만㎡, 녹지 840만㎡"],
   "cases": [], "u": "https://www.mit.gov.it/nfsmitgov/files/media/notizia/2022-04/Rapporto_Pinqua_web.pdf"},
  {"name": "에밀리아로마냐 주 국토관리법 — 토지 소비 제로 · 재생 인센티브",
   "year": "2017 (주법 24/2017)", "level": "주 (에밀리아로마냐)",
   "law": "Legge regionale Emilia-Romagna 21 dicembre 2017, n. 24 — art. 5 · 6 · 7 · 8",
   "what": "2050년까지 \"토지 소비 순증 제로\"를 목표로 정하고, 새 토지 소비를 기존 시가지 면적의 3% 안으로 묶었습니다. 대신 시가지 안의 재이용 · 재생 (유휴 · 저이용지 재편 포함)에는 부담금 감면 등 인센티브를 줍니다.",
   "tools": ["토지 소비 한도 — 기존 도시화 지역 면적의 3%", "시가지 안 재생 사업 — 특별 부담금 (contributo straordinario) 미적용, 건축 부담금 35% 이상 감면 (시가 전액 면제까지 가능, 토양 정화 · 석면 제거 사업 등)",
             "도시 재편 (ristrutturazione urbanistica) — 필지 · 블록 재구성, 위험 시설 이전, 용적 이전"],
   "cases": [], "u": "https://demetra.regione.emilia-romagna.it/al/articolo?urn=er:assemblealegislativa:legge:2017;24&dl_t=text/xml&dl_a=y&ev=1&art=art5"},
  {"name": "밀라노 철도 화물역 프로그램 협약 「Accordo di Programma Scali ferroviari」",
   "year": "2017 (2017.7.13 시의회 비준, 2022 말 적법 판결)", "level": "도시 (밀라노) · 주 · 국영철도",
   "law": "Accordo di Programma — Comune di Milano · Regione Lombardia · Ferrovie dello Stato Italiane · FS Sistemi Urbani · RFI · Savills IM",
   "what": "쓰이지 않는 철도 화물역 7곳 (파리니 · 포르타 로마나 · 포르타 제노바 · 그레코-브레다 · 람브라테 · 로고레도 · 산 크리스토포로)을 녹지와 주거 · 비주거가 섞인 지구로 바꾸는 협약입니다. 땅값 상승분을 철도 기반시설에 재투자합니다.",
   "tools": ["대상 약 120만㎡, 녹지 평균 65%", "주거 중 사회주택 · 학생 주거 30%", "재투자 — 순환 철도 (Circle Line) 등 철도 사업"],
   "cases": [], "u": "https://www.fssistemiurbani.it/content/dam/fsisistemiurbani_nd/Scali%20Milano.%20Costruire%20la%20trasformazione%202024.pdf",
   "note": "비준일 (2017.7.13)과 7개 역 이름은 밀라노 시 영문 페이지 · 검색 요약으로 보았고, 이탈리아어 원문 (FS Sistemi Urbani 2024)에서는 \"2017년 여름 서명 · 2022년 말 적법 판결 · 120만㎡ · 녹지 65% · 사회주택 30%\"를 확인했습니다."},
 ],
 "refs": [
  {"t": "MIMS (2022) — Programma Innovativo Nazionale per la Qualità dell'Abitare: progetti e prime evidenze", "u": "https://www.mit.gov.it/nfsmitgov/files/media/notizia/2022-04/Rapporto_Pinqua_web.pdf"},
  {"t": "Regione Emilia-Romagna (Demetra) — L.R. 24/2017", "u": "https://demetra.regione.emilia-romagna.it/al/articolo?urn=er:assemblealegislativa:legge:2017;24&dl_t=text/xml&dl_a=y&ev=1&art=art5"},
  {"t": "FS Sistemi Urbani (2024) — Scali Milano. Costruire la trasformazione", "u": "https://www.fssistemiurbani.it/content/dam/fsisistemiurbani_nd/Scali%20Milano.%20Costruire%20la%20trasformazione%202024.pdf"},
  {"t": "Comune di Milano — Railway Yards Program Agreement (AdP)", "u": "https://www.comune.milano.it/en/argomenti/rigenerazione-urbana/mappa-dei-progetti-di-rigenerazione-urbana/scali-ferroviari-accordo-di-programma-adp-per-la-trasformazione-urbanistica-delle-aree-ferroviarie-dismesse-e-in-dismissione-e-il-potenziamento-del-sistema-ferroviario-milanese"},
 ],
 "missing": ["롬바르디아 주 재생법 (L.R. 18/2019) · 밀라노 국토관리계획 (PGT Milano 2030) 원문은 사이트 접속이 막혀 확인하지 못했습니다.",
             "토리노 스피나 3 (Spina 3) · 국가 교외 재생 공모 (Bando periferie, L. 208/2015) 원문은 확인하지 못했습니다."]},
]
