# -*- coding: utf-8 -*-
# 도시재생 노트 심화 — 배정 09 (영국 4곳 + 암스테르담 동부 항만)
#  castlefield-manchester, kelham-island, london-docklands, albert-dock-liverpool, eastern-docklands-amsterdam
D = {
"castlefield-manchester": {
 "spec": [
  ["위치", "영국 그레이터 맨체스터, 맨체스터 도심 남서쪽 — 브리지워터 운하 (Bridgewater Canal) 종점 · 어웰강 (River Irwell)변, 로마 요새 마무키움 (Mamucium) 터"],
  ["면적", "맨체스터에서 가장 큰 보존지구의 하나 (시의회) — 정확한 면적은 확인하지 못했습니다"],
  ["기간", "1978년 그레이터 맨체스터 의회 부지 매입 → 1979년 보존지구 → 1982년 「도시 유산 공원」 → 1988~1996년 중앙 맨체스터 개발공사 → 2022년 캐슬필드 고가 공원"],
  ["원래 용도", "운하 하역장 · 운하 창고 (그로서스 창고 c.1771~1775, 머천츠 창고 c.1827, 미들 창고 1831) · 세계 최초의 여객 철도 종착역 리버풀 로드역 (1830) · 철도 고가교 · 시장"],
  ["변경 용도", "과학산업박물관 (1983) · 전시장 (G-Mex, 1986 → 현 맨체스터 센트럴) · 사무 · 아파트 · 펍 · 식당 · 야외 공연장 (1993) · 유스호스텔 · 고가 공원 (2022)"],
  ["원래 용도지구", "운하 · 철도 물류, 창고 · 저급 공업 (콘크리트 공장 · 고철장)"],
  ["변경 용도지구", "보존지구 (Conservation Area, 1979 지정 · 1980 「특별 보존지구 (outstanding)」 · 1985 확장) + 비법정 「도시 유산 공원 (Urban Heritage Park)」 + 1988~1996 도시개발구역"],
  ["개발공사 성과 (CMDC 전체 구역)", "주택 2,583호 · 비주거 약 14만㎡ · 일자리 약 4,944개 · 민간투자 3억 300만 파운드 · 버려진 땅 약 35만㎡ 정비"],
 ],
 "from": "운하 · 철도 창고, 세계 최초 여객역",
 "to": "박물관 · 주거 · 사무 · 여가 · 관광",
 "zoneFrom": "운하 · 철도 물류 · 창고 (쇠퇴)",
 "zoneTo": "보존지구 (Conservation Area) · 도시 유산 공원 (Urban Heritage Park)",
 "tenants": [
  ["문화 · 박물관", "과학산업박물관 (Science and Industry Museum)", "1983 개관 — 1830년 리버풀 로드역 · 창고 · 옛 시장 (항공우주관)에 입주, 과학박물관 그룹 소속, 2023-24 방문 42만 9천 회", "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"],
  ["문화 · 공연 · 행사장", "캐슬필드 야외 공연장 (Castlefield Arena)", "1993 조성 — 메워진 운하 지류와 콘크리트 공장 터를 복원한 야외 행사장"],
  ["문화 · 공원", "캐슬필드 고가 공원 (Castlefield Viaduct, 내셔널 트러스트)", "2022.7 시범 개방 — 1892년 철도 고가교 330m, 2025.4 전 구간 2단계 계획 허가"],
  ["업무 · 전시 · 컨벤션", "맨체스터 센트럴 (Manchester Central, 옛 G-Mex)", "1986 옛 센트럴역에 약 10만 sq ft 전시장으로 개관, 2001 800석 컨벤션 시설 (2,300만 파운드) 추가", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["문화 · 공연장", "브리지워터 홀 (Bridgewater Hall)", "1996 개관 콘서트홀 — 중앙 맨체스터 개발공사의 대표 사업", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["상업 · 영화관 · 여가", "그레이트 노던 (Great Northern) 여가 단지", "옛 그레이트 노던 창고를 1억 파운드 들여 상점 · 바 · 클럽 · 식당 · 주차장으로, 16개관 멀티플렉스 영화관 신축 (2012 안내서 기준)", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["상업 · 호텔", "힐튼 호텔 (비섬 타워, Beetham Tower)", "2006 완공 타워의 1~23층 호텔, 24~47층 아파트 (2012 안내서 기준)", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["상업 · 숙박", "유스호스텔 (1994) · YMCA 캐슬필드 호텔 (1990)", "포테이토 워프 옆 유스호스텔, 피터 스트리트에서 옮겨 온 YMCA (2012 안내서 기준)", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["상업 · 식음", "듀크스 92 (Dukes 92) · 잭슨스 워프 (1998) 등 운하변 펍", "로치데일 운하 92번 갑문 옆 펍 — 기업가 짐 램스보텀이 운영 시작", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["업무 · 사무", "머천츠 창고 (1996) · 게일 하우스 이스트게이트 (1992) 사무 단지", "짐 램스보텀이 불탄 1827년 창고와 새 사무 단지를 사무 공간으로 공급", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["주거 · 운하변 아파트", "캐슬 키 · 슬레이트 워프 (102호, 1994~96) · 울럼 플레이스 (66호) · 디앤스게이트 키 (102호, 2000) · 시티게이트 (2002)", "창고 개조와 신축 아파트 — 도심 주거 부흥의 출발점", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
  ["문화 · 미디어 (철수)", "그라나다 스튜디오 투어 (Granada Studios Tours)", "(1988~, 폐쇄) — 그라나다 TV 촬영 세트를 관광지로 공개, 한때 연 70만~80만 명 방문", "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"],
 ],
 "timeline": [
  ["1761", "브리지워터 운하가 캐슬필드에 도착 — 「세계 최초의 진정한 산업 운하」"],
  ["1830", "리버풀-맨체스터 철도 종착역 리버풀 로드역 개통 — 세계 최초의 여객 철도역 (1844년 여객 영업 종료)"],
  ["1960", "맨체스터 최초의 운하 창고인 그로서스 창고 (Grocers' Warehouse) 철거"],
  ["1969", "센트럴역 · 그레이트 노던 창고 폐쇄"],
  ["1975", "리버풀 로드 화물역 폐쇄 — 보존 운동이 일어남"],
  ["1978", "그레이터 맨체스터 의회 (Greater Manchester Council)가 센트럴역과 리버풀 로드 부지를 매입"],
  ["1979.10.13", "맨체스터 시의회, 캐슬필드 보존지구 지정"],
  ["1980.1", "환경부가 「특별 보존지구 (outstanding conservation area)」로 격상 (이 제도는 뒤에 폐지)"],
  ["1982", "영국 최초의 「도시 유산 공원 (Urban Heritage Park)」 선언"],
  ["1983", "옛 화물역에 과학산업박물관 개관 · 로마 정원 조성"],
  ["1985.6.26", "보존지구 확장 (엘즈미어 가 · 헐름홀 로드 · 어웰강 사이)"],
  ["1986", "옛 센트럴역에 G-Mex 전시장 개관 · 그로서스 창고 부분 복원"],
  ["1988~1996", "중앙 맨체스터 개발공사 (CMDC)가 캐슬필드를 포함한 도심 남부를 관할"],
  ["1992~1996", "미들 창고 → 캐슬 키 (상가 · 사무 · 아파트, 1992) · 머천츠 창고 → 사무 (1996)"],
  ["1993", "야외 공연장 (Castlefield Arena) 조성 · 방문자센터 개관"],
  ["2022.7", "내셔널 트러스트가 1892년 철도 고가교 (2등급 등록)를 시범 고가 공원으로 개방"],
 ],
 "problem": [
  "운하와 철도 물류가 끝나며 센트럴역 · 그레이트 노던 창고 (1969), 리버풀 로드 화물역 (1975)이 차례로 문을 닫았습니다.",
  "1970년대 캐슬필드는 도심 주변부의 전형적인 쇠퇴 지역으로, 운하 지류가 메워지고 오래된 주택이 헐렸으며 남은 산업은 콘크리트 공장 · 고철장 같은 열악한 것이었습니다.",
  "1830년 역사 · 운하 창고 · 로마 요새 터 같은 국가적 유산이 철거 위기에 놓였고, 실제로 맨체스터 최초의 운하 창고인 그로서스 창고는 1960년에 헐렸습니다.",
  "도심 바로 옆에 버려진 땅이 넓게 남아 맨체스터 도심 재생의 걸림돌이 되었습니다.",
 ],
 "overview": [
  "캐슬필드는 먼저 \"보존\"으로 시작한 재생입니다. 1975년 화물역이 문을 닫자 시민들이 역 보존 운동을 벌였고, 1980년 리버풀-맨체스터 철도 150주년을 앞두고 그레이터 맨체스터 의회가 1978년 부지를 사들였습니다. 1979년 보존지구, 1982년 영국 최초의 \"도시 유산 공원\" 선언이 이어졌습니다. 도시 유산 공원은 법정 지정이 아니라, 1975년 미국 매사추세츠주 로웰의 사례에서 영감을 얻은 비공식 명칭 · 브랜드입니다.",
  "공공이 박물관 (1983) · 전시장 G-Mex (1986)라는 앵커를 먼저 세웠고, 1988~1996년 중앙 맨체스터 개발공사가 토지 정비 · 기반시설 · 환경 개선에 공공 재원(위키백과 기준 약 4천만 파운드)을 넣어 민간 투자를 이끌었습니다. 기업가 짐 램스보텀 (Jim Ramsbottom)이 펍 「듀크스 92」, 불탄 머천츠 창고의 사무 개조(1996)를 이끈 것이 대표적입니다.",
  "방문 명소를 늘리는 일은 기대보다 어려웠고, 그 자리를 운하변 아파트 · 사무 · 스튜디오와 바 · 식당이 채웠습니다. 1992년 비영리 「캐슬필드 관리회사」가 레인저 서비스와 함께 지구를 관리했고, 오늘날에는 주민 단체 캐슬필드 포럼과 내셔널 트러스트가 철도 고가교를 고가 공원으로 바꾸고 있습니다.",
 ],
 "actors": [
  ["주관 기관", "맨체스터 시의회 (Manchester City Council)", "보존지구 지정 (1979)과 확장 (1985) · 보존지구 개발 지침 · 계획 허가"],
  ["주관 기관", "그레이터 맨체스터 의회 (Greater Manchester Council, 당시 광역의회)", "1978년 센트럴역 · 리버풀 로드 부지 매입, 1970년대 로마 요새 발굴 · 박물관 · 전시장 사업"],
  ["관련 기관", "환경부 (Department of the Environment)", "1980년 「특별 보존지구」 격상"],
  ["사업 시행", "중앙 맨체스터 개발공사 (Central Manchester Development Corporation, CMDC, 1988~1996)", "도시개발공사 — 캐슬필드 · 포모나 · 피카딜리 등 6개 구역의 토지 정비 · 기반시설 · 투자 유치"],
  ["관리", "캐슬필드 관리회사 (Castlefield Management Company, 1992)", "비영리 — 공공공간 유지 · 레인저 서비스"],
  ["앵커", "과학산업박물관 (Museum of Science and Industry)", "1830년 역 · 창고 · 시장 건물을 박물관으로 (1983~)"],
  ["민간", "짐 램스보텀 · 캐슬필드 에스테이츠 (Castlefield Estates)", "듀크스 92 펍, 머천츠 창고 사무 개조 (1996), 게일 하우스 사무 단지 (1992)"],
  ["민간", "그라나다 텔레비전 (Granada Television)", "1956년부터 인근에 스튜디오 — 1988년 「그라나다 스튜디오 투어」 개장"],
  ["시민단체", "캐슬필드 포럼 (Castlefield Forum)", "주민 자원봉사 자선단체 — 잭슨스 워프 개발 반대에서 출발, 시의회 · 주민 · 사업체 사이의 창구, 녹지 · 안내판 · 로마 정원 정비"],
  ["시민단체 · 보존", "내셔널 트러스트 (National Trust) · 내셔널 하이웨이스 (National Highways)", "1892년 철도 고가교를 고가 공원으로 (2022 시범 개방, 2025.4 2단계 계획 허가)"],
 ],
 "laws": [
  ["지방정부 · 계획 · 토지법 1980 제16부 (Local Government, Planning and Land Act 1980, Part XVI)", "도시개발구역 지정 (제134조) · 도시개발공사 설립 (제135조) · 토지 이전 · 수용 (제141~142조) · 계획 통제 (제148~149조). 중앙 맨체스터 개발공사의 근거", "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"],
  ["중앙 맨체스터 개발공사 설립 · 해산 명령 (CMDC (Area and Constitution) Order · (Dissolution) Order 1996)", "개발구역 지정과 공사 설립, 1996년 해산 — 계획 권한을 시의회로 되돌림"],
  ["캐슬필드 보존지구 (Castlefield Conservation Area, 1979 지정 · 1985 확장)", "보존지구 안의 철거 · 신축을 통제하고, 새 건물은 높이 · 규모 · 재료를 기존 건물에 맞추도록 한 시의회 지침", "https://www.manchester.gov.uk/parks-leisure-and-the-arts/parks-playgrounds-allotments-and-open-spaces/conservation-areas/introduction11"],
  ["계획 (등록건축물 · 보존지구) 법 1990 (Planning (Listed Buildings and Conservation Areas) Act 1990)", "현행 보존지구 지정 (제69조) · 등록 건축물 변경 허가 (제7~8조)의 근거 — 리버풀 로드역은 1963년 1등급 등록", "https://www.legislation.gov.uk/ukpga/1990/9/contents"],
  ["도시 유산 공원 (Urban Heritage Park, 1982)", "법정 지정이 아닌 비공식 명칭 — 보존 · 계획 의견 · 관광 재원 확보를 목표로 한 이해관계자 위원회의 브랜드"],
 ],
 "lawsNote": ["규제완화보다 \"보존 규제 + 공공 선투자\"가 중심입니다. 보존지구 지침은 창고의 주거 · 사무 전환과 현대식 신축을 막지 않고 \"품질이 높으면 환영\"한다는 입장이었고, 1988년부터는 도시개발공사가 시의회 대신 계획 권한과 재원을 가지고 빠르게 정비했습니다."],
 "tools": [
  ["공공 토지 매입", "1978년 그레이터 맨체스터 의회가 센트럴역 · 리버풀 로드 부지 매입 → 박물관 · 전시장으로"],
  ["문화 앵커", "과학산업박물관 (1983) · 항공우주관 · G-Mex 전시장 (1986) · 그라나다 스튜디오 투어 (1988)"],
  ["도시개발공사 재원", "CMDC 기간 공공 재원 약 4천만 파운드 (위키백과), CMDC 전체 구역에서 민간투자 3억 300만 파운드 유치"],
  ["토지 정비 · 기반시설", "버려진 운하 지류 복원, 야외 공연장 (1993) · 카탈란 광장 · 머천츠 다리 (1995)"],
  ["창고 용도 전환", "미들 창고 → 상가 · 사무 · 아파트 (1992), 머천츠 창고 → 사무 (1996)"],
  ["지구 관리 조직", "1992년 비영리 관리회사 · 레인저 서비스"],
  ["유산 브랜드", "「도시 유산 공원」 이름과 축제 (캐슬필드 카니발)로 관광 · 여가 지구 이미지 구축"],
 ],
 "zoning": [
  ["지정", "캐슬필드 보존지구 — 1979.10.13 지정, 1980.1 특별 보존지구, 1985.6.26 확장"],
  ["도시개발구역", "1988~1996 중앙 맨체스터 개발공사 구역 (캐슬필드 · 포모나 · 센트럴 · 가이소른 · 피카딜리 등 6개 지역)"],
  ["관리 주체 · 방식", "맨체스터 시의회 (보존지구 지침 · 계획 허가) + 캐슬필드 관리회사 (1992, 공공공간 관리)"],
  ["보존 관리", "리버풀 로드역 1등급 등록 (1963.12.18), 철도 고가교 2등급 등록 · 로마 요새 일부 복원"],
 ],
 "result": [
  "CMDC 전체 구역 성과 (1988~1996): 주택 2,583호, 비주거 약 14만㎡, 일자리 약 4,944개, 민간투자 3억 300만 파운드, 버려진 땅 약 35만㎡ 정비.",
  "과학산업박물관은 2012년 방문객 100만 명을 넘을 것으로 예상되었습니다 (지리학회 답사 안내서).",
  "캐슬필드는 맨체스터 도심 주거 부흥의 출발점이 되었고, 지금은 운하변 주거 · 여가 지구입니다.",
 ],
 "lesson": [
  "보존지구 지정과 공공의 부지 매입으로 \"철거를 먼저 멈춘\" 다음, 문화 앵커와 개발공사 재원으로 민간 개조를 이끈 순서가 핵심입니다.",
  "법정 구속력이 없는 \"도시 유산 공원\" 같은 이름도 지역 이미지를 바꾸는 데 효과가 컸습니다.",
  "방문 명소보다 주거 · 사무 수요가 재생을 지탱했다는 점은, 산업 유산 재생에서 관광만 바라보면 안 된다는 교훈입니다.",
 ],
 "funding": [
  ["공공 재원 (토지 매입)", "1978년 그레이터 맨체스터 의회가 센트럴역 · 리버풀 로드 부지를 매입 — 매입 금액은 확인하지 못했습니다"],
  ["중앙정부 · UDC 재정", "중앙 맨체스터 개발공사 (1988~1996)가 캐슬필드에 공공 재원 약 4천만 파운드 투입 (위키백과)"],
  ["민간 투자", "CMDC 전체 구역에서 민간투자 3억 300만 파운드 유치 (1988~1996)"],
  ["민간 투자", "그레이트 노던 창고 여가 단지 1억 파운드 · 배스 키 바 200만 파운드 (1998) — 캐슬필드 주변 민간 사업 (지리학회 답사 안내서)"],
  ["보조금 · 모금 (고가 공원)", "내셔널 트러스트 캐슬필드 고가 공원 2단계 — 재원의 75% 이상, 275만 파운드 확보 (2025)"],
 ],
 "famous": [
  "1982년 영국 최초의 「도시 유산 공원 (Urban Heritage Park)」 — 이 용어 자체가 캐슬필드에서 처음 쓰였습니다.",
  "1830년 리버풀 로드역은 세계 최초의 여객 철도 종착역이고, 1761년 브리지워터 운하는 \"세계 최초의 진정한 산업 운하\"로 불립니다.",
  "1980년 환경부가 「특별 보존지구 (outstanding conservation area)」로 격상한 곳입니다.",
  "2022년 내셔널 트러스트가 뉴욕 하이라인에서 영감을 받아 1892년 철도 고가교를 고가 공원으로 연 곳입니다.",
 ],
 "operation": [
  ["운영 주체 (지구)", "캐슬필드 관리회사 (Castlefield Management Company, 1992) — 비영리, 공공공간 유지 · 레인저 서비스"],
  ["운영 주체 (앵커 박물관)", "과학산업박물관 — 2012년 국립 과학박물관과 합병해 과학박물관 그룹 (Science Museum Group)의 일부, 문화 · 미디어 · 스포츠부 (DCMS)의 비부처 공공기관"],
  ["운영 성과", "과학산업박물관 방문객 421,488명 (2025, 위키백과 · ALVA)"],
  ["운영 주체 (고가 공원)", "내셔널 트러스트 — 예약 없이 걸어 들어가는 개방, 기부 호소 · 자원봉사로 운영하며 2단계 재원 마련", "https://www.nationaltrust.org.uk/visit/cheshire-greater-manchester/castlefield-viaduct"],
  ["지역 단체", "캐슬필드 포럼 — 주민 자원봉사 자선단체, 재원을 모아 안내판 · 녹지 · 로마 정원 정비"],
  ["공공 운영 보조금 (그룹 전체)", "과학박물관 그룹 (과학산업박물관 포함 6곳) 2023-24 국고 운영 보조금 (Resource Grant in Aid) 3,578만 1천 파운드 — 전년 4,736만 5천 파운드보다 감소", "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"],
  ["자립도 (그룹 전체)", "2023-24 비제한 수입 7,267만 1천 파운드 중 자체 수입 3,689만 파운드 (약 51%) — 그룹은 2030년까지 국고 외 비제한 수입 50% 초과를 목표로 제시 (FY23 40.8%)", "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"],
  ["수입 구성 (그룹 전체)", "2023-24 관람객 기부 217만 3천 · 후원회원 34만 1천 · 기업 회원 45만 6천 파운드 등", "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"],
  ["운영 성과 (시설 하나)", "과학산업박물관 방문 2019-20 53만 9천 → 2022-23 38만 → 2023-24 42만 9천 회 (부지 상당 부분이 보존 공사로 닫힌 상태)", "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"],
 ],
 "operationNote": [
  "캐슬필드는 개발공사 해산 뒤 하나의 운영기관이 수익사업을 하는 구조가 아닙니다. 지구 공공공간은 1992년 비영리 관리회사가, 핵심 앵커인 과학산업박물관은 문화부 산하 국립 박물관 그룹이, 새 고가 공원은 내셔널 트러스트가 기부 · 모금으로 운영합니다. 창고 개조 건물은 민간 소유주가 임대 · 분양으로 운영합니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (그레이트 노던 영화관 운영사, 힐튼 · 유스호스텔 등의 현재 영업 여부)는 2012년 안내서 이후 확인된 자료를 찾지 못했습니다.",
  "캐슬필드 관리회사의 재원 구조와 현재 존속 여부, 과학산업박물관 한 곳만의 보조금 · 자체 수입 비율은 확인된 자료를 찾지 못했습니다 (그룹 전체 수치만 확인).",
  "캐슬필드 지역의 BID (업무개선지구) 등 지역 관리 부담금은 확인된 자료를 찾지 못했습니다.",
  "마스터플랜 · 설계를 맡은 도시계획가 · 건축가는 확인된 자료를 찾지 못했습니다.",
  "캐슬필드 보존지구의 정확한 면적은 확인된 자료를 찾지 못했습니다.",
  "용적률 완화 수치는 확인된 자료를 찾지 못했습니다.",
  "CMDC 가 캐슬필드에만 쓴 공공 재원의 공식 수치(시기 포함)는 확인된 자료를 찾지 못했습니다 — 위키백과는 약 4천만 파운드로 적고 있습니다.",
 ],
 "refs": [
  {"t": "Science Museum Group — Annual Report and Accounts 2023–24 (PDF)", "u": "https://www.sciencemuseumgroup.org.uk/sites/default/files/2024-11/E03091147_Science%20Museum%20Group%20ARA%2023-24%20Accessible.pdf"},
  {"t": "Wikipedia — Science and Industry Museum", "u": "https://en.wikipedia.org/wiki/Science_and_Industry_Museum"},
  {"t": "National Trust — Castlefield Viaduct (visit page)", "u": "https://www.nationaltrust.org.uk/visit/cheshire-greater-manchester/castlefield-viaduct"},
  {"t": "Wikipedia — Castlefield", "u": "https://en.wikipedia.org/wiki/Castlefield"},
  {"t": "Wikipedia — Central Manchester Development Corporation", "u": "https://en.wikipedia.org/wiki/Central_Manchester_Development_Corporation"},
  {"t": "Wikipedia — Urban heritage park", "u": "https://en.wikipedia.org/wiki/Urban_heritage_park"},
  {"t": "Wikipedia — Liverpool Road railway station (Manchester)", "u": "https://en.wikipedia.org/wiki/Liverpool_Road_railway_station_(Manchester)"},
  {"t": "Wikipedia — Castlefield Forum", "u": "https://en.wikipedia.org/wiki/Castlefield_Forum"},
  {"t": "Manchester City Council — Castlefield Conservation Area (Introduction)", "u": "https://www.manchester.gov.uk/parks-leisure-and-the-arts/parks-playgrounds-allotments-and-open-spaces/conservation-areas/introduction11"},
  {"t": "Manchester City Council — Castlefield and its buildings today", "u": "https://www.manchester.gov.uk/parks-leisure-and-the-arts/parks-playgrounds-allotments-and-open-spaces/conservation-areas/introduction11/castlefield-and-its-buildings-today"},
  {"t": "Manchester Geographical Society — Exploring Greater Manchester 1.4 Castlefield (C. M. Law)", "u": "https://www.mangeogsoc.org.uk/egm/1_4_Castlefield.pdf"},
  {"t": "National Trust — Our work at Castlefield Viaduct", "u": "https://www.nationaltrust.org.uk/visit/cheshire-greater-manchester/castlefield-viaduct/our-work-at-castlefield-viaduct"},
  {"t": "legislation.gov.uk — Local Government, Planning and Land Act 1980, Part XVI", "u": "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"},
 ],
},

"kelham-island": {
 "spec": [
  ["위치", "영국 사우스요크셔 셰필드 도심 북쪽 — 돈강 (River Don)과 물방아 수로 (goit) 사이의 인공 섬 (길이 약 750m) 과 니프센드 (Neepsend)"],
  ["면적", "보존지구 전체 면적은 확인하지 못했습니다 — 대표 사업 「리틀 켈햄 (Little Kelham)」 부지 1.5ha"],
  ["기간", "1982년 산업박물관 → 1985년 산업 보존지구 → 1990년대 첫 공장 주거 개조 → 2008~2018 「켈햄 니프센드 실행계획」 → 2025년 보존지구 확장 · 개명"],
  ["원래 용도", "12세기 마을 곡물 방앗간 수로로 생긴 섬 — 18~19세기 셰필드 금속 · 칼 · 은식기 공장, 작은 작업장 (리틀 메스터), 도가니 제강, 1899년 시영 전차 발전소"],
  ["변경 용도", "공장 개조 아파트 · 신축 저층 고밀 주거 · 사무 · 공방 · 스튜디오 · 펍 · 소규모 양조장 · 식당 · 산업박물관"],
  ["원래 용도지구", "일반 공업 (General Industry) · 주변 업무 · 공업 (Fringe Business and Industry) — 단일개발계획 (UDP, 1998)"],
  ["변경 용도지구", "켈햄 강변: 혼합용도 (Mixed Use) → 업무 · 주거 지역 (Business and Housing Area) / 니프센드: 업무 지역 (Business Area) — 셰필드 개발체계 (SDF) 안"],
  ["주민", "약 5천 명 (도시주의 아카데미, 2019)"],
 ],
 "from": "칼 · 철강 공장, 작은 금속 작업장",
 "to": "공장 개조 주거 · 공방 · 펍 · 식당 혼합 지구",
 "zoneFrom": "일반 공업 · 주변 업무 · 공업 (UDP 1998)",
 "zoneTo": "산업 보존지구 (Industrial Conservation Area) + 업무 · 주거 혼합 지역 (Business and Housing Area)",
 "tenants": [
  ["문화 · 박물관", "켈햄 아일랜드 박물관 (Kelham Island Museum, 셰필드 박물관 신탁)", "1982 개관 — 1899년 전차 발전소 건물, 1905년 리버 돈 증기기관 · 리틀 메스터 작업장 · 켄 홀리 공구 컬렉션, 2024.3 새 상설 전시"],
  ["상업 · 양조 · 펍", "켈햄 아일랜드 브루어리 (Kelham Island Brewery) · 팻 캣 (The Fat Cat, 2등급 등록 펍)", "셰필드의 소규모 양조장 중 하나 — 실행계획은 이곳을 \"실 에일 펍 · 양조장\"으로 유명한 지역으로 그림"],
  ["상업 · 펍 (주민 소유)", "가드너스 레스트 (The Gardeners Rest)", "주민이 공동 소유한 펍 (도시주의 아카데미)"],
  ["문화 · 음악 스튜디오", "옐로 아치 스튜디오 (Yellow Arch Studios)", "1997 옛 너트 · 볼트 공장에 설립된 음악 · 공연 스튜디오"],
  ["상업 · 스포츠", "파운드리 클라이밍 센터 (Foundry Climbing Centre)", "1991 개장 — 니프센드 공장 지대의 실내 암벽장"],
  ["주거 · 혼합 단지", "리틀 켈햄 (Little Kelham, 시투 Citu)", "2013 착공 — 옛 이글 웍스 · 그린 레인 웍스 터 1.5ha, 헥타르당 102호 저에너지 주택 · 아파트 · 상점 · 카페, 그린 레인 웍스 상업 공간 4곳 (2018)"],
  ["주거 · 공장 개조", "코니시 플레이스 (Cornish Place, 2*등급)", "1990년대 제임스 딕슨 앤 선스 공장을 아파트로 — 셰필드 도심 주거의 초기 성공 사례"],
  ["업무 · 사무", "글로브 웍스 (Globe Works, 2*등급)", "공장 건물을 사무실로 사용"],
  ["문화 · 공동체", "KINCA · 아트웍스 (ArtWorks) 등", "주민 · 사업체 자선단체 (2000), 박물관 안 공동체 예술 단체 공간"],
 ],
 "timeline": [
  ["12세기", "마을 곡물 방앗간에 물을 대는 수로 (goit)를 파면서 섬이 생김"],
  ["1795", "그린 레인 웍스 (Green Lane Works) 건립 (1860 대개조, 현 2*등급 등록)"],
  ["1899", "셰필드 시영 전차용 발전소 건립 — 1930년대 이후 창고 · 작업장"],
  ["1970~80년대", "철강 · 금속 산업 쇠퇴, 빈 공장 · 범죄 · 성매매 지역으로 전락"],
  ["1982", "옛 발전소에 켈햄 아일랜드 박물관 개관 — 재생의 첫 씨앗"],
  ["1985.5", "켈햄 아일랜드 산업 보존지구 지정 — 영국 최초의 산업 보존지구의 하나"],
  ["1990년대", "코니시 플레이스 (Cornish Place) · 브루클린 웍스가 공장 주거 개조의 첫 사례가 됨"],
  ["2000", "주민 · 사업체가 「켈햄 아일랜드 · 니프센드 공동체 연합 (KINCA)」 결성"],
  ["2006.10", "실행계획을 위한 주민 · 사업체 의견 조사"],
  ["2007.6", "셰필드 홍수 — 박물관 피해 150만 파운드, 18개월 휴관"],
  ["2008", "「켈햄 니프센드 실행계획 2008~2018」 — 10년 재생 계획"],
  ["2013", "시투 (Citu)가 이글 웍스 · 그린 레인 웍스 자리에서 「리틀 켈햄」 착공"],
  ["2019", "도시주의 아카데미 (Academy of Urbanism) 「훌륭한 동네 (Great Neighbourhood)」상 수상"],
  ["2025.10.14", "시의회 계획위원회가 보존지구를 니프센드까지 넓히고 「켈햄 아일랜드 · 니프센드 산업 보존지구」로 개명하는 평가서 승인"],
 ],
 "problem": [
  "20세기 중반 빈민가 철거로 사람이 떠났고, 1970~80년대 철강 · 금속 산업이 쇠퇴하며 공장이 비고 범죄 · 성매매 · 마약 문제가 생겼습니다.",
  "2006년 조사에서 주민 · 사업체는 반사회적 행동과 범죄, 쓰레기, 교통 · 주차, 공터와 공공공간 부족을 문제로 꼽았습니다.",
  "2006~07년 여러 기계 공장이 문을 닫으며 주거 개발 압력이 급증했고, 니프센드의 기존 업체들은 땅값 · 임대료 상승과 주거와의 충돌을 걱정했습니다.",
  "지역 대부분이 홍수 위험 구역으로, 2007년 6월 홍수가 큰 피해를 냈습니다.",
  "코니시 웍스 · 완클리프 웍스 등 등록 건축물 여러 곳이 \"위기에 처한 건물\"로 남아 있었습니다.",
 ],
 "overview": [
  "켈햄 아일랜드는 대규모 개발기구 없이 시의회의 보존 규제와 세밀한 지역 계획, 민간 · 주민의 작은 사업이 \"천천히\" 쌓인 재생입니다. 1982년 산업박물관과 1985년 산업 보존지구 지정이 출발점이었고, 1990년대 코니시 플레이스 · 브루클린 웍스의 주거 개조가 셰필드 도심 거주의 초기 성공 사례가 되었습니다.",
  "2008년 「켈햄 니프센드 실행계획」은 도심 마스터플랜 (2000 · 2007 개정)이 이 지역을 도심으로 편입한 뒤 만든 세밀한 계획입니다. 강변은 주거와 업무를 섞되 대형 단일 주거는 억제하고(워털루 워크 · 딕슨 스트리트는 업무 50% 이상), 니프센드 중심부는 업무 · 경공업을 지키며 새 중공업 (B2)은 막고, 높이는 대체로 5층 이하로 묶었습니다.",
  "민간 개발사 시투의 「리틀 켈햄」(1.5ha, 헥타르당 102호)은 옛 공장을 고치고 저층 고밀 주택을 새로 지었으며, 펍 · 양조장 · 공방 · 클라이밍 센터 · 음악 스튜디오가 함께 섞였습니다. 도시주의 아카데미는 이를 변화가 자연스러운 속도로 일어난 \"천천히 익힌 (slow-cooked)\" 동네라고 평가했습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "캘 아키텍츠 (CAL Architects)", "리틀 켈햄 마스터플랜 (시투 개발, 2012 계획 신청)"],
  ["주관 기관", "셰필드 시의회 (Sheffield City Council)", "보존지구 지정 (1985) · 확장 (1999 · 2008 · 2025), 실행계획 2008~2018, 계획 허가 · 등록 건축물 수리 명령"],
  ["관련 기관", "셰필드 원 (Sheffield 1)", "2000년 시의회와 함께 도심 마스터플랜 발주"],
  ["관련 기관", "유럽연합 사우스요크셔 목표1 프로그램 (South Yorkshire Objective 1 Programme)", "실행계획 수립 비용 일부 지원"],
  ["관련 기관", "환경청 (Environment Agency) · 히스토릭 잉글랜드 (Historic England)", "홍수 위험 관리 / 보존 지원 (2025 문화부 · 히스토릭 잉글랜드 16만 5천 파운드)"],
  ["전문가", "도널드 인솔 어소시에이츠 (Donald Insall Associates)", "2025년 보존지구 평가서 · 관리계획 작성"],
  ["앵커", "셰필드 산업박물관 신탁 (Sheffield Industrial Museums Trust)", "켈햄 아일랜드 박물관 운영 (1982~)"],
  ["민간", "시투 (Citu)", "리틀 켈햄 — 공장 복원 + 저에너지 신축 주거 (2013 착공)"],
  ["시민단체", "켈햄 아일랜드 · 니프센드 공동체 연합 (KINCA, 2000)", "주민 · 사업체 자원봉사 자선단체 — 공동체 사업 관리"],
  ["시민 · 문화", "옐로 아치 스튜디오 (1997) · 파운드리 클라이밍 센터 (1991) · 가드너스 레스트 (주민 소유 펍)", "공장 건물의 문화 · 여가 재사용"],
 ],
 "laws": [
  ["켈햄 아일랜드 산업 보존지구 (Kelham Island Industrial Conservation Area, 1985 지정 · 1999 · 2008 · 2025 확장)", "공장 건물과 거리 형태 보존. 2025년 니프센드로 확장하고 「켈햄 아일랜드 · 니프센드 산업 보존지구」로 개명, 평가서 (2025.10) · 관리계획 승인", "https://www.sheffield.gov.uk/planning-development/conservation-areas/kelham-island"],
  ["켈햄 니프센드 실행계획 2008~2018 (Kelham Neepsend Action Plan 2008-2018)", "10년 비전 · 토지이용 원칙 — 강변 대형 단일 주거 억제, 일부 부지 업무 50% 이상, 니프센드 새 B2 중공업 금지, 높이 대체로 5층 이하, 등록 · 특색 건물 보존 · 재사용, 켈햄 광장 · 강변길 조성", "https://www.sheffield.gov.uk/sites/default/files/docs/planning-and-development/city-wide-plans-and-reports/Kelham-Island-and-Neepsend-Action-Plan.pdf"],
  ["셰필드 단일개발계획 (Unitary Development Plan, UDP, 1998)", "일반 공업 · 주변 업무 · 공업 · 혼합용도 지정, 일부를 특별 성격 지역 (Area of Special Character)으로"],
  ["셰필드 도심 마스터플랜 (City Centre Masterplan, 2000 · 2007 개정)", "2007 개정에서 켈햄 니프센드를 도심에 포함 — 업무 · 연구개발 · 디지털 산업 확대"],
  ["셰필드 개발체계 (Sheffield Development Framework, SDF)", "UDP 를 대체 — 강변은 업무 · 주거 지역, 니프센드는 업무 지역, 우드사이드는 업무 · 공업 지역"],
  ["도심 도시설계 지침 (Urban Design Compendium, 2004) · 도심 주거 전략 (City Centre Living Strategy, 2004)", "건물 규모 · 재료 지침 / 강변 주거지로서의 잠재력 명시"],
  ["부담 가능 주택 임시 지침 (Affordable Housing Interim Planning Guidance, 2006)", "25호 초과 또는 1ha 초과 개발에 부담 가능 주택 협상"],
  ["계획 (등록건축물 · 보존지구) 법 1990", "등록 건축물 (코니시 플레이스 · 글로브 웍스 2*등급 등) 변경 허가 · 수리 명령", "https://www.legislation.gov.uk/ukpga/1990/9/contents"],
 ],
 "lawsNote": ["핵심은 \"공업 용도의 단계적 해제와 공업의 일부 보호\"입니다. 강변은 혼합용도 → 업무 · 주거로 풀어 주거 개조를 허용했지만, 니프센드 중심부는 업무 · 경공업을 지키고 주거를 제한하여 기존 업체를 보호했습니다. 보존지구 규제는 공장 건물 철거를 막고 재사용을 유도했습니다."],
 "tools": [
  ["용도 전환", "공업 → 혼합용도 · 업무 · 주거 (UDP → SDF), 단일 주거는 문화유산 이익이 있을 때만 허용"],
  ["업무 비율 의무", "강변 일부 부지 (워털루 워크 · 딕슨 스트리트) 혼합개발은 업무 (B1) 50% 이상"],
  ["높이 · 형태 규제", "대체로 5층 이하, 중정형 배치, 벽돌 · 돌 · 슬레이트 재료"],
  ["공공기여 (제106조 협약)", "켈햄 광장 · 공원 · 강변길을 민간 개발과 시의회 제106조 협약 재원으로"],
  ["등록 건축물 수리 명령", "위기 건물 (코니시 웍스 · 완클리프 웍스 등)에 대해 수리 명령 등 법적 수단 사용 방침"],
  ["문화 앵커", "산업박물관 (1982), 소규모 양조장 · 펍"],
  ["민간 저에너지 개발", "리틀 켈햄 — 1.5ha, 헥타르당 102호"],
 ],
 "zoning": [
  ["지정", "켈햄 아일랜드 산업 보존지구 — 1985.5 지정, 1999 · 2008 · 2025 확장 → 「켈햄 아일랜드 · 니프센드 산업 보존지구」"],
  ["계획 구역", "켈햄 니프센드 실행계획 구역 — 우드사이드 · 니프센드 중심부 · 켈햄 강변 3개 성격 지역"],
  ["관리 주체 · 방식", "셰필드 시의회 보존팀 — 보존지구 평가서 · 관리계획 (2025~2026 승인)"],
  ["보존 관리", "코니시 플레이스 · 글로브 웍스 · 그린 레인 웍스 2*등급, 팻 캣 펍 2등급, 둑 · 볼 스트리트 다리 등록 · 백투백 주택 긴급 등록"],
 ],
 "result": [
  "주민 약 5천 명이 사는 도심 동네로 바뀌었습니다 (도시주의 아카데미).",
  "2019년 도시주의 아카데미 「훌륭한 동네」상 — 런던 해크니 윅, 맨체스터 앤코츠를 제치고 수상.",
  "1982년 박물관에서 시작해 공장 주거, 소규모 산업, 펍 · 양조장이 함께 있는 혼합 지구가 되었습니다.",
 ],
 "lesson": [
  "대규모 개발기구 없이도 보존지구 + 세밀한 실행계획 + 민간 소규모 개조로 공업지를 재생할 수 있습니다.",
  "공업 용지를 모두 주거로 풀지 않고 업무 비율 · 중공업 금지 같은 장치로 소규모 제조업을 남긴 점은 한국 노후 산단의 \"산업 · 주거 혼합\"에 참고가 됩니다.",
  "주민 단체 (KINCA)가 오래 활동하며 동네 정체성을 지킨 점도 중요합니다.",
 ],
 "funding": [
  ["EU 기금", "유럽연합 사우스요크셔 목표1 프로그램이 「켈햄 니프센드 실행계획 2008~2018」 작성 비용 일부를 지원"],
  ["공공기여 (제106조)", "켈햄 아일랜드 공원 · 켈햄 광장 · 강변길 등은 민간 개발 + 시의회 제106조 협약 재원으로 계획 (실행계획)"],
  ["보조금 (보존)", "문화 · 미디어 · 스포츠부와 히스토릭 잉글랜드가 시의회 보존지구 평가 작업에 16만 5천 파운드 지원 (2025)"],
  ["민간 투자", "시투 (Citu)의 리틀 켈햄 — 민간 개발 (2013 착공), 총사업비는 확인하지 못했습니다"],
  ["보조금 (운영)", "잉글랜드 예술위원회 국가 포트폴리오 (NPO) 2023-26 — 셰필드 박물관 신탁에 연 81만 4,720파운드 (켈햄 아일랜드 박물관 포함 6곳 전체 기준, 더 스타 2022.11.5)"],
 ],
 "famous": [
  "1985년 영국에서 가장 먼저 지정된 「산업 보존지구」의 하나입니다 (셰필드 시의회).",
  "2019년 도시주의 아카데미 「훌륭한 동네 (Great Neighbourhood)」상 — 해크니 윅 (런던) · 앤코츠 (맨체스터)를 제치고 수상했습니다.",
  "큰 개발기구 없이 자연스러운 속도로 바뀐 \"천천히 익힌 (slow-cooked)\" 동네로 평가받습니다 (도시주의 아카데미).",
  "1905년 12,000마력 「리버 돈 증기기관」과 작은 칼 작업장 (리틀 메스터)을 보여 주는 켈햄 아일랜드 박물관 (1982)이 있습니다.",
 ],
 "operation": [
  ["운영 주체 (박물관)", "셰필드 박물관 신탁 (Sheffield Museums Trust) — 2021년 셰필드 산업박물관 신탁과 뮤지엄스 셰필드가 합병한 독립 자선단체, 켈햄 아일랜드 박물관 등 6곳 운영"],
  ["공공 운영 보조금", "주요 후원 기관은 잉글랜드 예술위원회 (Arts Council England)와 셰필드 시의회 (연차보고서 2023/24)", "https://www.sheffieldmuseums.org.uk/media/bfmlx51z/sheffield-museums-annual-review-2023-24.pdf"],
  ["수입 구성 (2023/24, 신탁 전체)", "총수입 523만 5천 파운드 — 기부 · 유증 154만 7천, 관리 서비스 수수료 210만 1천, 기타 상업 활동 106만 9천, 자선 활동 31만 6천, 기타 20만 2천 파운드 / 총지출 589만 7천 파운드", "https://www.sheffieldmuseums.org.uk/media/bfmlx51z/sheffield-museums-annual-review-2023-24.pdf"],
  ["재무 상태", "2024.3.31 순자산 954만 8천 파운드, 자유 적립금 97만 6천 파운드 — 장기적으로 균형 예산을 목표"],
  ["보조금 (사업)", "문화부 (DCMS) · 울프슨 박물관 개선 기금으로 켈햄 아일랜드 박물관 진열장 구입 (2023/24)"],
  ["운영 성과", "신탁 6개 시설 방문객 757,596명 (2023/24) — 코로나 이전 수준 미회복"],
  ["민간 운영", "리틀 켈햄 — 개발사 시투 (Citu)의 민간 사업, 그린 레인 웍스 상업 공간 4곳을 분양 (2018)"],
  ["지역 단체", "KINCA (2000) — 주민 · 사업체 자원봉사 자선단체가 공동체 사업 관리"],
  ["행사 수입원", "켈햄 아일랜드 박물관 「빅토리아 크리스마스 마켓」 (2023.12.2~3) — 80여 개 노점, 방문객 6,557명", "https://www.sheffieldmuseums.org.uk/media/bfmlx51z/sheffield-museums-annual-review-2023-24.pdf"],
 ],
 "operationNote": [
  "켈햄 아일랜드에는 지구 전체를 운영하는 기관이 없습니다. 정체성의 중심인 산업박물관은 시의회 · 예술위원회 지원과 기부 · 상업 수입을 섞어 운영하는 자선 신탁이 맡고, 나머지는 민간 소유주의 주택 분양 · 상업 임대와 펍 · 양조장 같은 소규모 사업이 지역을 지탱합니다. 신탁은 2023/24년 지출이 수입보다 많아 균형 예산을 과제로 들고 있습니다.",
 ],
 "missing": [
  "켈햄 지역 입주 기업 · 업체의 현재 목록 (특히 첨단산업 · 창업 기업)은 확인된 자료를 찾지 못했습니다.",
  "켈햄 아일랜드 박물관 단독의 수입 · 방문객과 시의회 보조금 금액은 확인된 자료를 찾지 못했습니다.",
  "켈햄 지역의 BID 등 지역 관리 부담금은 확인된 자료를 찾지 못했습니다.",
  "보존지구와 실행계획 구역의 면적은 확인된 자료를 찾지 못했습니다.",
  "용적률 완화 수치는 확인된 자료를 찾지 못했습니다 — 높이는 대체로 5층 이하로 규제했습니다.",
  "1990년대 코니시 플레이스 개조를 설계한 건축가는 확인된 자료를 찾지 못했습니다 (AXIS Architecture 페이지를 열 수 없었습니다).",
  "실행계획 2008~2018의 사업비 · 공공투자 총액과 리틀 켈햄 사업비는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "The Star (2022.11.5) — Arts Council grants: Sheffield Museums and Sheffield Theatres set for biggest share of £3million in city", "u": "https://www.thestar.co.uk/news/politics/arts-council-grants-sheffield-museums-and-sheffield-theatres-set-for-biggest-share-of-ps3million-in-city-3906973"},
  {"t": "Sheffield Museums — Annual Review 2023/24 (PDF)", "u": "https://www.sheffieldmuseums.org.uk/media/bfmlx51z/sheffield-museums-annual-review-2023-24.pdf"},
  {"t": "Wikipedia — Sheffield Museums Trust", "u": "https://en.wikipedia.org/wiki/Sheffield_Museums_Trust"},
  {"t": "Sheffield City Council — Kelham Island and Neepsend Industrial Conservation Area", "u": "https://www.sheffield.gov.uk/planning-development/conservation-areas/kelham-island"},
  {"t": "Sheffield City Council — Kelham Neepsend Action Plan 2008-2018 (PDF)", "u": "https://www.sheffield.gov.uk/sites/default/files/docs/planning-and-development/city-wide-plans-and-reports/Kelham-Island-and-Neepsend-Action-Plan.pdf"},
  {"t": "Wikipedia — Kelham Island Museum", "u": "https://en.wikipedia.org/wiki/Kelham_Island_Museum"},
  {"t": "Wikipedia — Green Lane Works", "u": "https://en.wikipedia.org/wiki/Green_Lane_Works"},
  {"t": "The Academy of Urbanism — Kelham Island, Sheffield", "u": "https://www.theaou.org/resources/kelham-island-sheffield"},
  {"t": "HUB-IN Atlas — Kelham Island", "u": "https://atlas.hubin-project.eu/case/kelham-island/"},
  {"t": "Hunter Archaeological Society — Sheffield City Council approves major extensions to Conservation Areas (2025)", "u": "https://www.hunterarchaeologicalsociety.org.uk/news/2025/sheffield-city-council-approves-major-extensions-to-conservation-areas/"},
  {"t": "Housing Design Awards — Little Kelham", "u": "https://hdawards.org/scheme/little-kelham/"},
 ],
},

"london-docklands": {
 "spec": [
  ["위치", "영국 런던 동부 템스강변 — 타워햄리츠 · 뉴엄 · 서더크 3개 자치구 (와핑 · 라임하우스, 아일 오브 독스, 로열 독스 · 벡턴, 서리 독스)"],
  ["면적", "LDDC 관할 약 2,200ha (약 22㎢, 8.5제곱마일)"],
  ["기간", "1981년 LDDC 설립 → 1982~1992 아일 오브 독스 기업구역 → 1998.3.31 LDDC 해산"],
  ["원래 용도", "19세기 런던항 부두 — 세인트 캐서린 · 런던 · 서리 · 웨스트 인디아 · 밀월 · 이스트 인디아 · 로열 부두, 창고 · 제조업"],
  ["변경 용도", "카나리 워프 금융 업무지구 · 주거 · 쇼핑 · 런던 시티 공항 (1987) · DLR (1987) · ExCeL 전시장 · 박물관"],
  ["원래 용도지구", "항만 · 공업 (자치구 계획 관할)"],
  ["변경 용도지구", "도시개발구역 (Urban Development Area — LDDC 가 계획 허가권) + 아일 오브 독스 기업구역 (Enterprise Zone, 1982~1992)"],
  ["공공 · 민간 투자", "LDDC 공공 지출 18억 6천만 파운드 · 민간투자 약 77억 파운드 (LDDC 개요)"],
  ["주택 · 인구", "신규 주택 24,046호 · 인구 약 3만 9,400명 (1981) → 약 8만 명 (1997)"],
  ["일자리 · 기업", "8만 5천 명 근무 · 2,700개 사업체 (LDDC 개요)"],
 ],
 "from": "폐쇄된 항만 · 부두 창고 · 제조업",
 "to": "금융 업무지구 · 주거 · 공항 · 전시장",
 "zoneFrom": "항만 · 공업 (자치구 계획 관할)",
 "zoneTo": "도시개발구역 (Urban Development Area) + 기업구역 (Isle of Dogs Enterprise Zone)",
 "tenants": [
  ["업무 · 금융 본사", "HSBC", "8 캐나다 스퀘어 (2002, 42층) — 글로벌 본사"],
  ["업무 · 금융 본사", "바클리스 (Barclays)", "1 처칠 플레이스 (2005, 32층) — 글로벌 본사"],
  ["업무 · 금융 본사", "씨티그룹 (Citigroup)", "25 · 33 캐나다 스퀘어 「씨티그룹 센터」 — 유럽 · 중동 · 아프리카 본사"],
  ["업무 · 금융 본사", "JP모건 체이스 (JPMorgan Chase)", "25 뱅크 스트리트 — 2012년부터 유럽 본사"],
  ["업무 · 금융 · 전문서비스", "모건 스탠리 · 도이체방크 · 스테이트 스트리트 · 무디스 · KPMG · 언스트 앤 영 · 클리퍼드 챈스 등", "카나리 워프에 세계 · 유럽 본사 (약 10만 5천 명 근무)"],
  ["첨단산업 · IT · 미디어 정보", "인포시스 (Infosys) · 톰슨 로이터 (Thomson Reuters) · 이코노미스트 그룹", "카나리 워프 입주 IT · 정보 · 미디어 기업"],
  ["업무 · 공공기관 (철수)", "유럽의약품청 (EMA) · 유럽은행감독청 (EBA)", "(~2018, 브렉시트로 암스테르담 · 파리 이전)"],
  ["문화 · 영화관", "시네월드 (Cineworld, 웨스트 인디아 키) · 에브리맨 (Everyman Cinemas, 크로스레일 플레이스)", "카나리 워프의 멀티플렉스 영화관 2곳"],
  ["문화 · 공연장", "트루바두르 카나리 워프 극장 (Troubadour Canary Wharf Theatre)", "1,200석 신축 공연장"],
  ["문화 · 공공 도서관", "아이디어 스토어 카나리 워프 (Idea Store, 타워햄리츠 구)", "2006 처칠 플레이스 쇼핑몰 안 개관 — 구의 네 번째 아이디어 스토어"],
  ["문화 · 박물관", "런던 도클랜즈 박물관 (London Museum Docklands)", "2003 개관 — 웨스트 인디아 키 1802년 설탕 창고 (1등급), 2019 방문객 324,438명"],
  ["업무 · 전시 · 컨벤션", "엑셀 런던 (ExCeL London)", "2000.11 로열 빅토리아 독 북쪽 100에이커 부지에 개관 (무슬리 아키텍츠 설계 · 로버트 매캘파인 시공), 2008 아부다비 국립전시회사 인수"],
  ["업무 · 교통 · 공항", "런던 시티 공항 (London City Airport)", "1987.10.26 첫 상업 운항 (로열 독스) — 1988년 승객 13만 3천 명"],
 ],
 "timeline": [
  ["1967", "이스트 인디아 부두를 시작으로 상류 부두 폐쇄 — 부두 직접 고용 약 2만 3천 명 (1967) → 7천여 명 (1979)"],
  ["1973", "중앙정부 · 광역의회의 「런던 도클랜즈 연구팀」 보고서 (트래버스 모건) — 1974년 철회"],
  ["1974~1976", "도클랜즈 합동위원회 (DJC, 자치구 · 항만청 · 노조) 구성 → 1976 「런던 도클랜즈 전략계획 (LDSP)」"],
  ["1980", "지방정부 · 계획 · 토지법 제정 — 도시개발공사 · 기업구역 제도"],
  ["1981.7", "LDDC 설립 명령 상원 통과 (자치구 반대로 특별위원회 심사) — 9월 활동 시작"],
  ["1981", "왕립 부두 · 웨스트 인디아 · 밀월 부두까지 모든 부두 폐쇄 완료"],
  ["1982.4.26", "아일 오브 독스 기업구역 지정 (10년) · 아일 오브 독스 설계 지침 발간"],
  ["1985", "카나리 워프 약 880만 sq ft 사무 계획 발표"],
  ["1987", "DLR 개통 (7.30 공식, 8.31 운행, 7,700만 파운드) · 10월 런던 시티 공항 개항"],
  ["1988", "올림피아 앤 요크가 카나리 워프 착공 (마스터플랜 SOM)"],
  ["1991", "원 캐나다 스퀘어 (시저 펠리) 완공 — 당시 영국 최고층"],
  ["1992", "4.26 기업구역 종료 · 5월 올림피아 앤 요크 파산"],
  ["1993", "라임하우스 링크 도로 개통 (약 3억 4,500만 파운드) · 주빌리선 연장 착공"],
  ["1994~1998", "버몬지 (1994)부터 로열 독스 (1998)까지 단계적으로 계획권을 자치구에 반환 — 1998.3.31 LDDC 해산"],
  ["1999", "주빌리선 연장 개통 (카나리 워프역 — 노먼 포스터)"],
  ["2003", "웨스트 인디아 부두 1802년 창고 (1등급 등록)에 런던 도클랜즈 박물관 개관"],
 ],
 "problem": [
  "컨테이너화와 선박 대형화로 1960~80년 런던의 부두가 모두 문을 닫았고, 부두 직접 고용은 1967~79년 약 2만 3천 명에서 7천여 명으로 줄었습니다.",
  "부두와 함께 제조업도 무너져 1978~81년 도클랜즈 고용이 27% 줄었고, 1930년대부터 이어진 인구 유출이 가속되었습니다.",
  "1976년 전략계획은 공공주택 · 제조업 중심이었지만, 1976년 재정위기로 공공지출이 깎이고 합동위원회에 실질 권한이 없어 진척이 매우 느렸습니다.",
  "아일 오브 독스 주민 1만 3천 명의 90%가 공공임대 세입자일 만큼 민간 시장이 없었고, 버려진 땅이 약 1,100ha (1981)에 달했습니다.",
 ],
 "overview": [
  "중앙정부(환경부 장관 마이클 헤슬타인)가 1980년 법으로 도시개발공사를 만들고, 자치구의 계획 허가권과 공공 토지를 넘겨받아 시장 주도로 개발한 대표 사례입니다. 학계는 이를 공공투자로 민간 부동산 시장을 되살리는 \"레버리지 계획 (leverage planning)\"이라 부릅니다. 초대 사장 레그 워드는 \"개발자 제안에 기회주의적으로 대응할 필요가 있었다\"고 말했고, LDDC 는 종합 마스터플랜 대신 개발 기회를 보여 주는 유연한 설계 지침(1982)을 썼습니다.",
  "LDDC 는 설립 직후 광역의회 · 항만청 · 자치구 땅 수백 에이커를 넘겨받아 최대 지주가 되었고, 지출의 4분의 3 이상을 토지 매입 · 정비 · 기반시설에 썼습니다. 아일 오브 독스 기업구역의 10년 재산세 면제 · 건물 투자비 100% 자본공제가 투자를 끌었고, 값싼 DLR (1987) · 런던 시티 공항 (1987)으로 접근성을 만들었습니다.",
  "1985년 카나리 워프 계획 발표 뒤 올림피아 앤 요크가 1988년 착공, 1991년 원 캐나다 스퀘어를 완공했지만 1992년 부동산 경기 붕괴로 파산했습니다. 이후 주빌리선 연장 (1999, 개발사가 25년간 4억 파운드 분담)과 경기 회복으로 런던 제2의 금융 중심지가 되었습니다.",
  "반면 자치구와 주민은 계획권을 빼앗기고 주거비 상승으로 \"밀려난다\"고 비판했습니다. 1987년 뉴엄 자치구와 LDDC 가 로열 독스 계획에 사회주택 1,500호 · 사회개발 1천만 파운드 · 지역 고용 25% 목표를 합의한 것은 이런 반발의 결과였습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "스키드모어 오윙스 앤 메릴 (Skidmore, Owings & Merrill, SOM) · 요크 로젠버그 마달 (YRM, 영국 자문)", "카나리 워프 마스터플랜"],
  ["도시계획가 · 건축가", "시저 펠리 (César Pelli)", "원 캐나다 스퀘어 (1991)"],
  ["도시계획가 · 건축가", "에드워드 홀램비 (Edward Hollamby)", "LDDC 수석 건축가 · 계획가 — 1982년 아일 오브 독스 설계 지침"],
  ["도시계획가 · 건축가", "노먼 포스터 앤 파트너스 (Foster & Partners)", "주빌리선 카나리 워프역"],
  ["도시계획가 · 건축가", "아럽 어소시에이츠 (Arup Associates) 등", "DLR 설계 컨설턴트 (1983~)"],
  ["주관 기관", "중앙정부 환경부 (장관 마이클 헤슬타인, Michael Heseltine)", "1980년 법 · LDDC 설립 · 보조금 · 기업구역 지정"],
  ["사업 시행", "런던 도클랜즈 개발공사 (London Docklands Development Corporation, LDDC, 1981~1998)", "토지 이전 · 매입 · 정비 · 기반시설, 계획 허가권 — 의장 나이절 브로크스 등, 사장 레그 워드 (Reg Ward) · 에릭 소렌슨 등"],
  ["관련 기관", "런던항만청 (Port of London Authority) · 대런던 의회 (GLC)", "토지 이전 (항만청 280에이커 등)"],
  ["관련 기관", "런던 지역교통 (London Regional Transport)", "DLR 1단계를 LDDC 와 공동 재원"],
  ["관련 기관", "타워햄리츠 · 뉴엄 · 서더크 자치구", "설립 반대 (상원 청문) → 1987 뉴엄-LDDC 사회주택 합의 → 1998 계획권 회수"],
  ["민간", "올림피아 앤 요크 (Olympia & York) → 카나리 워프 그룹", "카나리 워프 개발 (1988~), 1992 파산 · 1995 국제 컨소시엄 인수"],
  ["시민단체", "도클랜즈 공동행동그룹 (Joint Docklands Action Group, JDAG) · 도클랜즈 포럼 (Docklands Forum) · 도클랜즈 협의위원회 (Docklands Consultative Committee)", "민간 주도 재개발 · 주민 배제 비판, LDDC 가 자치구 계획을 무력화한다고 항의"],
  ["시민단체", "라임하우스 개발그룹 (Limehouse Development Group)", "라임하우스 분지 과밀 개발 계획에 대안 제시 (1985)"],
 ],
 "laws": [
  ["지방정부 · 계획 · 토지법 1980 제16부 (Local Government, Planning and Land Act 1980, Part XVI)", "도시개발구역 지정 (제134조) · 도시개발공사 설립 (제135조) · 목적 「지역의 재생」 (제136조) · 공공 토지 이전 (제141조) · 계획 통제 (제148~149조)", "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"],
  ["같은 법 별표 32 — 기업구역 (Schedule 32, Enterprise Zones)", "기업구역 계획(scheme) 자체가 계획 허가를 주어 개별 허가 절차를 생략 · 재산세 면제 근거", "https://www.legislation.gov.uk/ukpga/1980/65/schedule/32"],
  ["LDDC (지역 · 구성) 명령 1980 (London Docklands Development Corporation (Area and Constitution) Order 1980)", "약 8제곱마일을 도시개발구역으로 지정하고 LDDC 설립 — 1981.7 상원 승인, 그리니치 · 루이셤 제외", "https://api.parliament.uk/historic-hansard/lords/1981/jul/01/london-docklands-development-corporation"],
  ["아일 오브 독스 기업구역 (Isle of Dogs Enterprise Zone, 1982.4.26~1992.4.26)", "10년간 사업용 재산세 면제 · 개발토지세 면제 · 상업 · 공업 건물 투자 100% 자본공제 · 간소화된 계획"],
  ["아일 오브 독스 설계 지침 (Isle of Dogs Design Guide, 1982)", "토지이용 규정 대신 \"개발 기회\"를 보여 주는 유연한 지침 (워드 사장이 지나친 규정을 빼도록 수정)"],
  ["런던 도클랜즈 전략계획 (London Docklands Strategic Plan, 1976)", "도클랜즈 합동위원회의 자문 계획 — 공공주택 · 제조업 · 지역 고용 중심, LDDC 출범 뒤 사실상 대체됨"],
  ["LDDC (계획 기능) 명령 1997 (Planning Functions Order 1997)", "1998.1.28 시행 — LDDC 의 계획 허가권을 자치구로 되돌림", "https://www.legislation.gov.uk/uksi/1997/2946/made"],
 ],
 "lawsNote": ["규제완화의 핵심은 두 가지입니다. ① 선출된 자치구의 계획 허가권을 중앙정부가 임명한 개발공사로 옮겨 법정 지역계획과 다른 \"유연한 틀\"로 빠르게 허가했고, ② 기업구역에서는 계획(scheme) 자체가 허가를 주고 재산세 · 개발토지세를 면제하며 건물 투자비를 100% 공제했습니다. 1989년 이코노미스트는 재산세 감면이 연 2,400만 파운드, 1992년까지 세금 감면이 약 15억 파운드에 이를 것으로 추산했습니다."],
 "tools": [
  ["공공 토지 이전 · 수용", "설립 직후 광역의회 · 항만청 · 자치구 땅 약 650에이커 이전 (상원 자료는 약 850에이커), 이후 추가 이전 · 협의 매입 · 강제 수용"],
  ["토지 정비 후 매각", "지출의 4분의 3 이상을 토지 매입 · 정비 · 기반시설에 쓰고, 정비한 땅을 팔아 재투자 — 1987년까지 3억 4천만 파운드 지출, 연 보조금 5,800만 파운드"],
  ["세제 감면 (기업구역)", "10년 재산세 면제 · 개발토지세 면제 · 건물 투자 100% 자본공제"],
  ["계획 절차 간소화", "기업구역 계획 자체가 허가, LDDC 의 유연한 개발 틀"],
  ["교통 투자", "DLR 1단계 7,700만 파운드 (1987), 라임하우스 링크 약 3억 4,500만 파운드 (1993), 주빌리선 연장 약 10억 파운드 (올림피아 앤 요크 25년간 4억 파운드 분담)"],
  ["민간 투자 유치", "공공 1파운드당 민간 4파운드 이상 (LDDC 개요)"],
  ["사회적 합의", "1987 뉴엄-LDDC 합의 — 사회주택 1,500호 · 사회개발 1천만 파운드 · 지역 고용 25% 목표"],
 ],
 "zoning": [
  ["지정", "런던 도클랜즈 도시개발구역 약 2,200ha (1981) — 4개 계획 구역 (와핑 · 라임하우스, 아일 오브 독스, 로열 독스 · 벡턴, 서리 독스)"],
  ["기업구역", "아일 오브 독스 기업구역 (웨스트 인디아 · 밀월 부두 일대, 1982~1992)"],
  ["관리 주체 · 방식", "LDDC 가 구역별 팀으로 계획 허가 · 토지 관리 → 1994~1998 단계적으로 자치구에 반환"],
  ["보존 관리", "웨스트 인디아 부두 1802년 창고 1등급 등록 → 런던 도클랜즈 박물관 (2003)"],
 ],
 "result": [
  "LDDC 기간 (1981~1998): 공공 18억 6천만 파운드, 민간 약 77억 파운드, 신규 주택 24,046호, 8만 5천 명 근무 · 2,700개 사업체, 버려진 땅 1,884에이커 정비 (LDDC 개요).",
  "인구 약 3만 9,400명 (1981) → 약 8만 명 (1997), 민간 주택 비율 5% → 43%, 새 · 개량 도로 113km, 철도 29km (교재 자료).",
  "카나리 워프는 사무 · 상업 약 1,600만 sq ft, 약 10만 5천 명이 일하는 런던 제2의 금융 중심지가 되었습니다 (위키백과).",
  "반면 1991년 2월 기업구역 사무실 공실률이 약 50%에 이르는 등 경기 변동에 크게 흔들렸고, 기존 주민의 주거비 부담 · 소외 문제가 남았습니다.",
 ],
 "lesson": [
  "중앙정부 특별기구 + 토지 이전 + 세제 · 계획 특례는 투자를 빠르게 끌어오지만, 경기 침체기에는 공실 · 개발사 파산 위험이 큽니다.",
  "교통 기반시설 (DLR · 주빌리선)이 없으면 업무지구가 살아나기 어렵다는 점이 분명히 드러났습니다.",
  "주민 참여를 배제한 개발은 강한 반발을 불렀고, 뒤늦게 사회주택 · 지역 고용 합의가 필요했습니다 — 한국의 특구형 재생에 주는 경고입니다.",
 ],
 "funding": [
  ["중앙정부 · UDC 재정", "LDDC 전체 기간 (1981~1998) 공공 지출 18억 6천만 파운드 — 모든 공공 부문 비용은 약 39억 파운드 (LDDC 개요)", "https://silo.tips/download/london-docklands-development-corporation-an-overview"],
  ["중앙정부 · UDC 재정", "1987년까지 LDDC 3억 4천만 파운드 지출, 연 보조금 5,800만 파운드 — 1991년까지 약 10억 파운드 지출 예상, 절반은 정부 보조금 · 절반은 토지 매각"],
  ["토지 매각 수익", "정비한 땅을 팔아 재투자 — 1989년 9월까지 정부 보조금과 토지 매각으로 7억 600만 파운드 지출 (Survey of London)"],
  ["세제 혜택", "아일 오브 독스 기업구역 (1982~1992) 재산세 면제 연 약 2,400만 파운드, 1992년까지 세금 감면 약 15억 파운드 추산 (1989 이코노미스트)"],
  ["교통 투자", "DLR 1단계 7,700만 파운드 (LDDC · 런던 지역교통 공동), 라임하우스 링크 약 3억 4,500만 파운드, 주빌리선 연장 약 10억 파운드 중 올림피아 앤 요크 4억 파운드 (25년간) 분담"],
  ["민간 투자", "민간투자 약 77억 파운드 — 공공 1파운드당 민간 4파운드 이상 (LDDC 개요), 1989년 9월까지 68억 5천만 파운드 (Survey of London)"],
  ["사회 기금", "1987 뉴엄-LDDC 합의 — 사회개발 프로그램 1천만 파운드 · 사회주택 1,500호"],
 ],
 "famous": [
  "1980년 법의 도시개발공사 · 기업구역 제도를 적용한 대표 사례로, 학계가 \"레버리지 계획 (leverage planning)\"이라 부르는 영국 시장 주도 재생의 상징입니다.",
  "카나리 워프는 약 10만 5천 명이 일하는 런던 제2의 금융 중심지가 되었고, 원 캐나다 스퀘어 (1991)는 당시 영국 최고층 건물이었습니다.",
  "버려진 철도 시설을 재사용한 DLR (1987)은 \"놀랄 만큼 저렴한\" 경전철로 평가받았습니다.",
  "반대로 기존 주민이 \"밀려난다\"는 비판과 자치구 · 주민단체 (JDAG 등)의 반대로, 주민 참여 없는 개발의 대표 사례로도 꼽힙니다.",
 ],
 "operation": [
  ["운영 주체 이양", "1998년 LDDC 해산 — 계획권은 타워햄리츠 · 뉴엄 · 서더크 자치구로 반환 (1997 계획 기능 명령)", "https://www.legislation.gov.uk/uksi/1997/2946/made"],
  ["민간 운영사 (카나리 워프)", "카나리 워프 그룹 (Canary Wharf Group) — 약 100에이커 부동산의 소유 · 개발 · 운영, 자회사 카나리 워프 컨트랙터스 (시공) · 버투스 (Vertus, 임대 주택)"],
  ["소유 구조", "2015년 브룩필드 프로퍼티스와 카타르 투자청 (QIA)이 26억 파운드에 인수"],
  ["수입 구성 · 입주율", "임대 수입 중심 — 2012.6.30 기준 소유 부동산 790만 sq ft (가치 49억 파운드)의 95.6% 임대"],
  ["운영상 문제", "1991년 2월 기업구역 사무 공실률 약 50%, 1991~92년 sq ft 당 5~10파운드에 공간 공급 — 1992년 올림피아 앤 요크 파산"],
  ["운영상 문제", "기존 주민의 주거비 상승 · 밀려남 (젠트리피케이션) 비판"],
  ["해산 뒤 이관 (자산 · 부채)", "새 자산 · 기반시설을 넘겨받는 자치구에 10년치 유지관리 비용을 보상 — 라임하우스 링크 등 큰 시설은 신도시위원회 · 잉글리시 파트너십스 · 브리티시 워터웨이스로 이관 (Raco · Freire-Trigo 2025)", "https://www.tandfonline.com/doi/full/10.1080/02665433.2025.2518482"],
  ["지역 관리 재원 (로열 독스)", "LDDC 가 1989년 비영리 「로열 독스 관리청 (RoDMA)」 설립 — 로열 독스 수면 전체 · 갑문 · 다리 5개를 225년 임차, 주변 토지 소유주 · 개발사에게 받는 관리비 (service charge)로 운영", "https://www.tandfonline.com/doi/full/10.1080/02665433.2025.2518482"],
  ["지역 관리 재원 (로열 독스)", "RoDMA — 킹 조지 5세 독 보수 향후 9년 약 500만 파운드를 관리비로 충당 예정, 2022년 활성화 프로그램용 15만 파운드 지원 받음", "https://www.tandfonline.com/doi/full/10.1080/02665433.2025.2518482"],
  ["지역 관리 (카나리 워프)", "카나리 워프 부두벽의 장기 유지 책임은 브리티시 워터웨이스가 맡음", "https://www.tandfonline.com/doi/full/10.1080/02665433.2025.2518482"],
 ],
 "operationNote": [
  "도클랜즈는 공공 개발공사가 땅을 정비해 팔고 해산한 뒤, 업무지구 운영은 민간이 임대 수입으로 지속하는 구조입니다. 카나리 워프는 하나의 민간 그룹이 토지 · 건물을 소유하고 임대 · 개발 · 시공을 함께 하며, 2015년 이후 브룩필드 · 카타르 투자청이 소유합니다. 이 구조는 경기 침체기 공실과 개발사 파산 위험에 그대로 노출된다는 점이 1990년대 초 드러났습니다.",
 ],
 "missing": [
  "카나리 워프의 테크 · 창업 지원 공간과 한국 기업 입주 여부는 확인된 자료를 찾지 못했습니다.",
  "카나리 워프 단지의 관리비 (service charge) 금액 · 구조와 도클랜즈 지역 BID 는 확인된 자료를 찾지 못했습니다.",
  "아일 오브 독스 기업구역의 정확한 면적은 확인된 자료를 찾지 못했습니다.",
  "용적률 완화 수치는 확인된 자료를 찾지 못했습니다 — 기업구역 계획(scheme)이 허가를 대신했습니다.",
  "LDDC 공식 결산 자료 (lddc-history.org.uk)는 사이트에 접속할 수 없어 사본(LDDC 개요)으로 확인했습니다.",
 ],
 "refs": [
  {"t": "Wikipedia — Canary Wharf", "u": "https://en.wikipedia.org/wiki/Canary_Wharf"},
  {"t": "Wikipedia — ExCeL London", "u": "https://en.wikipedia.org/wiki/ExCeL_London"},
  {"t": "Wikipedia — London City Airport", "u": "https://en.wikipedia.org/wiki/London_City_Airport"},
  {"t": "Raco & Freire-Trigo (2025) — Reflections on the institutional afterlife of the LDDC, Planning Perspectives 40(4)", "u": "https://www.tandfonline.com/doi/full/10.1080/02665433.2025.2518482"},
  {"t": "Wikipedia — Canary Wharf Group", "u": "https://en.wikipedia.org/wiki/Canary_Wharf_Group"},
  {"t": "Wikipedia — London Docklands Development Corporation", "u": "https://en.wikipedia.org/wiki/London_Docklands_Development_Corporation"},
  {"t": "Wikipedia — London Docklands", "u": "https://en.wikipedia.org/wiki/London_Docklands"},
  {"t": "Wikipedia — Canary Wharf", "u": "https://en.wikipedia.org/wiki/Canary_Wharf"},
  {"t": "Wikipedia — London Museum Docklands", "u": "https://en.wikipedia.org/wiki/London_Museum_Docklands"},
  {"t": "Survey of London vols 43-44 — Modern Docklands: The background to redevelopment", "u": "https://www.british-history.ac.uk/survey-london/vols43-4/pp686-691"},
  {"t": "Survey of London vols 43-44 — Modern Docklands: Modern commercial developments", "u": "https://www.british-history.ac.uk/survey-london/vols43-4/pp702-707"},
  {"t": "Brindley, Rydin & Stoker, Remaking Planning — 6 Leverage planning: the LDDC (PDF)", "u": "https://southwarknotes.wordpress.com/wp-content/uploads/2012/03/lddc-leverage-planning-remaking-planning-book-1996.pdf"},
  {"t": "LDDC — London Docklands Development Corporation: An Overview (사본)", "u": "https://silo.tips/download/london-docklands-development-corporation-an-overview"},
  {"t": "GeoActive — London Docklands (교재, 1981 · 1997 비교표)", "u": "https://geographillips.weebly.com/uploads/1/0/7/4/107405149/geoactive_london_docklands.pdf"},
  {"t": "Hansard (House of Lords, 1981.7.1) — LDDC (Area and Constitution) Order 1980", "u": "https://api.parliament.uk/historic-hansard/lords/1981/jul/01/london-docklands-development-corporation"},
  {"t": "legislation.gov.uk — Local Government, Planning and Land Act 1980, Part XVI", "u": "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"},
  {"t": "legislation.gov.uk — LDDC (Planning Functions) Order 1997", "u": "https://www.legislation.gov.uk/uksi/1997/2946/made"},
 ],
},

"albert-dock-liverpool": {
 "spec": [
  ["위치", "영국 머지사이드 리버풀 머지강변 — 피어 헤드 남쪽, 옛 세계유산 「리버풀 해양상업도시」의 일부"],
  ["면적", "부두 수면 약 7.75에이커 (약 3.1ha) · 창고 연면적 약 129만 sq ft (약 12만㎡)"],
  ["기간", "1846년 개장 → 1972년 폐쇄 → 1981년 머지사이드 개발공사 → 1984년 1단계 재개장 → 1988년 테이트 리버풀 · 공식 재개장"],
  ["원래 용도", "세계 최초로 나무 없이 주철 · 벽돌 · 돌만으로 지은 불연 보세 창고 5동과 부두 — 배에서 창고로 바로 하역"],
  ["변경 용도", "머지사이드 해양박물관 · 국제노예박물관 · 테이트 리버풀 · 비틀스 스토리 · 상점 · 식당 · 사무 · 호텔 · 아파트"],
  ["원래 용도지구", "항만 (머지 도크 · 하버 보드 소유)"],
  ["변경 용도지구", "도시개발구역 (MDC, 1981~1998) → 등록 건축물군 · 보존지구 · 세계유산 구성요소 (2004~2021)"],
  ["사업비 (원 건설)", "1846년 건설비 78만 2,265파운드 · 벽돌 2,300만 장"],
  ["방문객", "연간 400만 명 이상 (위키백과)"],
 ],
 "from": "항만 보세 창고 · 부두",
 "to": "박물관 · 미술관 · 상업 · 주거 복합",
 "zoneFrom": "항만 (1972 폐쇄 후 방치)",
 "zoneTo": "도시개발구역 → 1등급 등록 건축물군 · 보존지구 (세계유산 2004~2021)",
 "tenants": [
  ["문화 · 미술관", "테이트 리버풀 (Tate Liverpool)", "1988.5.24 개관 (제임스 스털링 개조) — 2023~2027 약 2,970만 파운드 대규모 개보수 (2027 봄 재개장 예정)"],
  ["문화 · 박물관", "머지사이드 해양박물관 (Merseyside Maritime Museum, 국립 리버풀 박물관)", "1980 시범 · 1984 개관 · 1986 확장 — D동 창고, 2019 방문객 836,980명, 2025.1 개보수로 휴관 (2028 재개관 예정)", "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"],
  ["문화 · 박물관", "국제노예박물관 (International Slavery Museum, 국립 리버풀 박물관)", "로열 앨버트 독 — 국립 리버풀 박물관 7곳 중 하나, 확장 계획에 국가복권 유산기금 등 지원", "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"],
  ["문화 · 관광", "비틀스 스토리 (The Beatles Story)", "앨버트 독 상업 입주사", "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"],
  ["상업 · 호텔", "홀리데이 인 (Holiday Inn) · 프리미어 인 (Premier Inn)", "앨버트 독 창고 안 호텔 입주사 (2016 기준)", "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"],
  ["상업 · 식음", "구스토 (Gusto) · 밀러 앤 카터 (Miller & Carter)", "식당 입주사 (2016 기준) — 호텔 · 여가 · 상업 · 사무 약 40만 sq ft 중 일부", "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"],
 ],
 "timeline": [
  ["1841~1846", "부두 · 창고 건설 (제시 하틀리 · 필립 하드윅) — 1846년 앨버트 공 참석 개장"],
  ["1952.6.28", "창고들 1등급 등록 (Grade I)"],
  ["20세기", "증기선이 커지며 좁은 입구 때문에 이용 감소"],
  ["1972", "머지 도크 · 하버 보드 재정위기로 부두 폐쇄 — 진흙이 쌓이고 방치"],
  ["1980", "해양박물관 시범 개관"],
  ["1981", "머지사이드 개발공사 (MDC) 설립 (톡스테스 폭동 직전) — WG 커틴스 구조팀이 건물 상태 조사"],
  ["1983", "개발사 애로크로프트 (Arrowcroft)가 MDC 와 협력 — 상업 · 여가 · 주거 개발 구상"],
  ["1984.7", "1단계 보강 (방수 · 균열 수지 주입) 완료, 부두에 물을 다시 채우고 톨십 레이스 개최 · 재개장 · 해양박물관 정식 개관"],
  ["1984", "리버풀 국제 정원박람회 (MDC 사업)"],
  ["1985.6.19", "등록 내용 개정 (창고별 개별 등록)"],
  ["1988.5.24", "테이트 리버풀 개관 (제임스 스털링 개조) — 앨버트 독 재개장"],
  ["1998", "MDC 해산"],
  ["2004", "「리버풀 해양상업도시」 유네스코 세계유산 등재 (앨버트 독 포함 6개 구역)"],
  ["2012", "리버풀 워터스 개발 승인으로 「위험에 처한 세계유산」 목록에 오름"],
  ["2018", "왕실 칙허로 「로열 앨버트 독」 이름"],
  ["2021.7.21", "세계유산위원회가 등재 취소 — 영국에서 첫 사례"],
 ],
 "problem": [
  "증기선이 커지며 좁은 입구의 앨버트 독은 쓰임이 줄었고, 1972년 머지 도크 · 하버 보드의 재정위기로 폐쇄된 뒤 부두에 진흙이 쌓이고 창고가 버려졌습니다.",
  "리버풀은 항만 · 산업 쇠퇴로 실업과 도시 황폐화가 심각했고, 1981년 톡스테스 폭동이 일어났습니다.",
  "영국 최대의 1등급 등록 건물군을 철거하지 않고 쓸 방법이 필요했지만, 거대한 창고를 고칠 민간 수요가 없었습니다.",
 ],
 "overview": [
  "1981년 중앙정부(마이클 헤슬타인)가 리버풀 · 부틀 · 월러시 · 버컨헤드의 부두 지역을 맡는 머지사이드 개발공사를 세웠습니다. 위원은 장관이 임명했고 지방정부의 계획 통제를 넘어서는 권한을 가져, 노동당이 강한 지역에서 논란이 되었습니다.",
  "MDC 는 1983년부터 개발사 애로크로프트와 손잡고 공공이 먼저 부두를 준설 · 정비하고 창고를 안정화 · 방수 처리한 뒤(1단계, 1984년 톨십 레이스 전 완공), 2단계로 최종 용도로 고쳤습니다. 해양박물관 · 테이트 리버풀 (1988) 같은 국립 문화시설을 앵커로 두고 나머지를 상업 · 사무 · 주거로 채웠습니다.",
  "2004년 리버풀 해양상업도시의 일부로 세계유산이 되었지만, 북쪽 부두의 리버풀 워터스 · 브램리무어 독 경기장 개발 때문에 2021년 등재가 취소되었습니다. 앨버트 독 자체는 1등급 등록 건축물로 보호됩니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "제임스 스털링 (James Stirling)", "테이트 리버풀 창고 개조 설계 (1988 개관)"],
  ["도시계획가 · 건축가", "제시 하틀리 (Jesse Hartley) · 필립 하드윅 (Philip Hardwick)", "원 부두 · 창고 설계 (1841~1846)"],
  ["전문가", "WG 커틴스 (WG Curtins) 구조 엔지니어링", "MDC 를 위한 창고 상태 평가 · 보수 (수지 주입 등)"],
  ["주관 기관", "중앙정부 환경부 (장관 마이클 헤슬타인)", "MDC 설립 (1981)"],
  ["사업 시행", "머지사이드 개발공사 (Merseyside Development Corporation, MDC, 1981~1998)", "도시개발공사 — 부두 준설 · 창고 보강 · 투자 유치, 국제 정원박람회 (1984). 의장 도널드 포스터 · 사장 배질 빈"],
  ["민간", "애로크로프트 그룹 (Arrowcroft Group)", "1983년부터 MDC 와 협력 — 상업 · 여가 · 주거 개발"],
  ["앵커", "테이트 (Tate) · 국립 리버풀 박물관 (National Museums Liverpool)", "테이트 리버풀 · 해양박물관 · 국제노예박물관 운영"],
  ["관련 기관", "리버풀 시의회 (Liverpool City Council)", "MDC 해산 뒤 계획 관리 · 세계유산 관리"],
  ["보존 · 국제기구", "히스토릭 잉글랜드 (Historic England) · 유네스코 세계유산위원회 (UNESCO)", "등록 건축물 관리 / 2004 등재 · 2012 위험 목록 · 2021 취소"],
 ],
 "laws": [
  ["지방정부 · 계획 · 토지법 1980 제16부 (Local Government, Planning and Land Act 1980, Part XVI)", "도시개발구역 지정 · 도시개발공사 설립 · 토지 이전 · 계획 통제 — MDC 의 근거", "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"],
  ["등록 건축물 지정 (Listed Building, 1952.6.28 · 1985.6.19 개정)", "창고 5동 1등급 — 변경 · 철거에 등록 건축물 허가 필요", "https://historicengland.org.uk/listing/the-list/list-entry/1068410"],
  ["계획 (등록건축물 · 보존지구) 법 1990 (Planning (Listed Buildings and Conservation Areas) Act 1990)", "현행 등록 건축물 · 보존지구 보호 근거", "https://www.legislation.gov.uk/ukpga/1990/9/contents"],
  ["리버풀 해양상업도시 세계유산 (Liverpool – Maritime Mercantile City, 2004~2021)", "앨버트 독을 포함한 6개 구역 — 2021년 등재 취소"],
 ],
 "lawsNote": ["규제완화의 핵심은 개발공사가 지방정부의 계획 통제를 넘어 빠르게 결정하고 공공 재원으로 부두 · 창고를 먼저 고친 점입니다. 반대로 건물 자체는 1952년부터 1등급 등록으로 강하게 보호되어, \"철거 없는 개조\"가 전제가 되었습니다."],
 "tools": [
  ["공공 선투자", "MDC 가 부두 준설 · 물 채우기, 창고 안정화 · 방수 · 균열 보수 (1단계)를 먼저"],
  ["민관 협력", "애로크로프트 그룹과 1983년부터 협력 개발"],
  ["문화 앵커", "해양박물관 (1980 · 1984 · 1986), 테이트 리버풀 (1988), 국제노예박물관 (2007)"],
  ["행사 활용", "1984년 톨십 레이스 · 국제 정원박람회로 재개장 홍보"],
  ["혼합 용도 개조", "창고를 상업 · 사무 · 호텔 · 주거로"],
 ],
 "zoning": [
  ["지정", "머지사이드 도시개발구역 (1981~1998, 리버풀 · 부틀 · 월러시 · 버컨헤드 부두)"],
  ["보존 관리", "창고 5동 1등급 등록 (1952) — 영국 최대의 1등급 등록 건물군, 세계유산 구성요소 (2004~2021)"],
  ["관리 주체 · 방식", "MDC (1998까지) → 리버풀 시의회 계획 관리 + 소유 · 운영 회사"],
 ],
 "result": [
  "MDC 전체 성과 (1981~1998): 비주거 약 71만㎡ · 주택 486호 · 일자리 약 22,155개 · 민간투자 6억 9,800만 파운드 · 버려진 땅 약 944에이커 정비.",
  "앨버트 독은 연간 400만 명 이상이 찾는 명소가 되었습니다 (위키백과). 해양박물관 방문객 836,980명 (2019).",
  "반면 2021년 리버풀 해양상업도시 세계유산 등재가 취소되었습니다.",
 ],
 "lesson": [
  "철거 대신 공공이 먼저 구조를 보강하고 국립 문화시설을 앵커로 들인 \"선투자 + 문화 앵커\" 방식은 큰 산업 건물 재생의 본보기입니다.",
  "개별 건물 보호만으로는 경관을 지키기 어렵다는 것을 세계유산 취소가 보여 줍니다 — 주변 개발까지 아우르는 경관 관리가 필요합니다.",
 ],
 "funding": [
  ["민간 투자", "애로크로프트 그룹이 자회사 「앨버트 독 컴퍼니」를 통해 1억 파운드 넘게 투자 (앨버트 독 공식 사이트)", "https://albertdock.com/history/"],
  ["중앙정부 · UDC 재정", "머지사이드 개발공사 (1981~1998)가 부두 준설 · 창고 보강을 공공 재원으로 먼저 시행 — 앨버트 독 투입액은 확인하지 못했습니다"],
  ["민간 투자 (MDC 전체)", "MDC 전체 구역에서 민간투자 6억 9,800만 파운드 유치"],
  ["원 건설비", "1846년 건설비 78만 2,265파운드 (현재 가치 약 4,100만 파운드 — 공식 사이트)"],
 ],
 "famous": [
  "나무 없이 주철 · 벽돌 · 돌만으로 지은 영국 최초의 구조물이자 세계 최초의 불연 보세 창고입니다.",
  "창고 5동은 1952년부터 1등급 등록 — 영국에서 가장 큰 1등급 등록 건물군입니다.",
  "2004년 세계유산 「리버풀 해양상업도시」의 중심이었으나 2021년 등재가 취소되어, 보존과 개발의 균형을 묻는 국제적 사례가 되었습니다.",
  "연간 방문객 600만 명 이상 (2017, 공식 사이트) — 리버풀 최대 명소이며 2018년 「로열」 칭호를 받았습니다.",
 ],
 "operation": [
  ["토지 · 건물 소유 구조", "토지 소유권 (freehold)은 앨버트 독 컴퍼니 (상호 Gower Street Estates)가 보유, 단지의 장기 임차권 (leasehold)은 2016년 애버딘 자산운용이 애로크로프트로부터 4,275만 파운드에 매입", "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"],
  ["민간 운영사", "JLL 이 애버딘을 대신해 상업 공간 전체의 임대 관리 · 상주 사무소 운영 (2016), 외부 공간은 새빌스 (Savills)가 토지 소유주를 대리", "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"],
  ["수입 구성", "호텔 · 여가 · 상업 · 사무 약 40만 sq ft 임대 — 입주사: 테이트 리버풀, 홀리데이 인, 프리미어 인, 비틀스 스토리, 구스토, 밀러 앤 카터 등"],
  ["운영 성과", "연간 방문객 600만 명 이상 (2017, 공식 사이트) · 해양박물관 836,980명 (2019)"],
  ["앵커 운영", "테이트 리버풀 (테이트) · 해양박물관 · 국제노예박물관 (국립 리버풀 박물관) — 국립 기관이 문화시설 운영"],
  ["공공 운영 보조금 (기관 전체)", "국립 리버풀 박물관 (해양박물관 · 국제노예박물관 등 7곳) 2023/24 비제한 수입 2,860만 파운드 중 문화부 국고 보조금 2,140만 파운드 (75%) — 나머지는 변동성이 큰 자체 수입", "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"],
  ["수입 구성 (기관 전체)", "2023/24 총수입 4,313만 2천 파운드 — 기부 · 보조금 · 유증 3,547만, 상업 활동 475만 8천, 자선 활동 266만, 투자 24만 4천 파운드 / 총지출 3,857만 2천 파운드", "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"],
  ["운영 성과 (기관 전체)", "국립 리버풀 박물관 7곳 총 방문 2,372,670회 (2023/24), 모금 590만 파운드", "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"],
 ],
 "operationNote": [
  "앨버트 독은 개발공사 해산 뒤 민간 부동산 소유주가 임대 수입으로 운영합니다. 토지는 앨버트 독 컴퍼니가 갖고, 상업 부분의 장기 임차권은 자산운용사가 사서 전문 관리회사에 맡기는 \"부동산 투자 자산\" 구조이며, 국립 박물관 · 미술관이 방문객을 끌어오는 앵커 역할을 합니다.",
 ],
 "missing": [
  "앨버트 독 입주 업체의 2016년 이후 현재 목록 (사무 · 주거 입주자 포함)은 확인된 자료를 찾지 못했습니다.",
  "앨버트 독의 관리비 · 임대 수입 · 입주율과 BID 등 지역 관리 부담금은 확인된 자료를 찾지 못했습니다.",
  "해양박물관 한 곳만의 수입 · 보조금, 테이트 리버풀의 보조금 · 자체 수입 비율은 확인된 자료를 찾지 못했습니다 (국립 리버풀 박물관 전체 수치만 확인).",
  "1980년대 창고 개조 전체의 마스터플랜 · 설계를 맡은 건축가(테이트 리버풀의 제임스 스털링 외)는 확인된 자료를 찾지 못했습니다.",
  "앨버트 독 복원에 들어간 공공 (MDC) 투입액은 확인된 자료를 찾지 못했습니다 — 민간 (애로크로프트) 1억 파운드 이상만 확인했습니다.",
  "앨버트 독 일대 보존지구의 이름 · 지정 연도는 확인된 자료를 찾지 못했습니다.",
  "MDC 관할 면적 · 설립 명령의 정확한 날짜는 확인된 자료를 찾지 못했습니다 (자료에 따라 1980 · 1981로 다릅니다).",
  "용적률 완화 수치는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "National Museums Liverpool — Annual Report and Accounts 2023-24 (GOV.UK PDF)", "u": "https://assets.publishing.service.gov.uk/media/687a45845f0f5104b9806b94/National_Liverpool_Museum_Annual_Report_and_Accounts_2023-24.pdf"},
  {"t": "Place North West — JLL wins Albert Dock brief (2016.3.24)", "u": "https://www.placenorthwest.co.uk/jll-wins-albert-dock-brief/"},
  {"t": "Royal Albert Dock Liverpool — History", "u": "https://albertdock.com/history/"},
  {"t": "Wikipedia — Royal Albert Dock, Liverpool", "u": "https://en.wikipedia.org/wiki/Royal_Albert_Dock,_Liverpool"},
  {"t": "Wikipedia — Merseyside Development Corporation", "u": "https://en.wikipedia.org/wiki/Merseyside_Development_Corporation"},
  {"t": "Wikipedia — Tate Liverpool", "u": "https://en.wikipedia.org/wiki/Tate_Liverpool"},
  {"t": "Wikipedia — Merseyside Maritime Museum", "u": "https://en.wikipedia.org/wiki/Merseyside_Maritime_Museum"},
  {"t": "Wikipedia — Liverpool Maritime Mercantile City", "u": "https://en.wikipedia.org/wiki/Liverpool_Maritime_Mercantile_City"},
  {"t": "Historic England — Edward Pavilion, Albert Dock (List Entry 1068410)", "u": "https://historicengland.org.uk/listing/the-list/list-entry/1068410"},
  {"t": "A. Clarke — The construction and history of the Albert Dock (AIA · MIHS 2021, PDF)", "u": "https://industrial-archaeology.org/wp-content/uploads/2021/10/The-Albert-Dock_AIA_MIHS_-A-Clarke.pdf"},
  {"t": "legislation.gov.uk — Local Government, Planning and Land Act 1980, Part XVI", "u": "https://www.legislation.gov.uk/ukpga/1980/65/part/XVI"},
 ],
},

"eastern-docklands-amsterdam": {
 "spec": [
  ["위치", "네덜란드 암스테르담 동부 (현 스타츠데일 오스트 Stadsdeel Oost) — IJ 강의 인공 반도들: 오스텔레이커 한덜스카더 · 자바 섬 · KNSM 섬 · 보르네오 · 스포렌뷔르흐 · 레이트란던"],
  ["면적", "KNSM 섬 86ha (땅 12 · 물 74) · 자바 섬 71ha (주거 개발 약 15ha) · 보르네오 섬 27ha — 전체의 약 3분의 2가 물"],
  ["기간", "1874~1927 항만 조성 → 1979 마지막 선사 이전 → 1975 주거 전환 결정 · 1985 구조 스케치 → 1988~2000년대 초 섬별 재개발"],
  ["원래 용도", "동인도 · 남미 교역 항만 — 부두 · 창고 (1883 한덜스카더 창고 등) · 선사 (KNSM 1903~1979) · 도축장 · 이민자 호텔 (로이드 호텔, 1921)"],
  ["변경 용도", "고밀 주거 약 8,000~8,500호 · 학교 · 상점 · 사무 · 식당 · 문화시설 (무지크헤바우 안 헷 IJ) · 호텔"],
  ["원래 용도지구", "항만 (1935 「일반 확장계획 (Algemeen Uitbreidingsplan)」 체계)"],
  ["변경 용도지구", "섬별 「용도계획 (bestemmingsplan)」 — 주거 (Wonen W1 · W2) 중심 혼합 (KNSM 섬 1990 · 자바 섬 1997 등)"],
  ["밀도", "주거 헥타르당 약 100호 (1975 결정) — 보르네오 · 스포렌뷔르흐 2,500호 · 헥타르당 100호"],
  ["인구", "약 1만 7천 명 (2000년대) → 약 2만 555명 (2024) · 주택 약 1만 호 (소유 39% · 임대 61% · 사회주택 32%)"],
 ],
 "from": "동인도 교역 항만 · 부두 창고",
 "to": "고밀 저 · 중층 주거 + 혼합 용도",
 "zoneFrom": "항만 (Haven)",
 "zoneTo": "주거 중심 혼합 용도계획 (bestemmingsplan, Wonen)",
 "tenants": [
  ["문화 · 창작 공간", "로츠 6 (Loods6, 로츠 6 재단)", "KNSM 섬 옛 KNSM 창고 — 아틀리에 · 작업실 232곳, 상점 · 식당, 행사장 (바가허할 · 센트럴 할 · 콤파스잘)", "https://loods6.nl/locations"],
  ["문화 · 창작 공간", "콰란타이너헤바우 (Quarantainegebouw, 레이트란트 공원)", "스타츠헤르스텔 소유 건물 — 아틀리에 12곳 · 음악 스튜디오 2곳 · 카페 식당, 로츠 6 재단 관리", "https://loods6.nl/locations"],
  ["문화 · 공연장", "무지크헤바우 안 헷 IJ (Muziekgebouw aan 't IJ) · 빔하위스 (Bimhuis)", "2005.6.15 개관 (3XN 설계, 건설비 6천만 유로) — 피트 하인카더 IJ 터널 위 콘서트홀, 재즈 공연장 빔하위스가 한 건물에"],
  ["상업 · 호텔", "로이드 호텔 (Lloyd Hotel)", "1921 이민자 호텔 → 2004 호텔 (MVRDV 개조) → 2021 매각 · 2023 재개장"],
  ["상업 · 호텔", "호텔 자카르타 (Hotel Jakarta)", "자바 섬 서쪽 끝 — 2019 암스테르담 건축상"],
  ["주거 · 사회주택 · 분양", "보르네오 · 스포렌뷔르흐 2,500호 (발주 뉴 딜 New Deal)", "1993~2000 — 3층 운하 주택과 「고래」 · 「팩맨」 등 큰 블록"],
 ],
 "timeline": [
  ["1874~1927", "IJ 강에 인공 반도들 조성 — 1883 오스텔레이커 한덜스카더 창고 (유럽 · 아시아 · 아프리카), 1890 둑 · 1896 IJ 부두"],
  ["1903", "KNSM (왕립 네덜란드 증기선 회사)이 동쪽 섬에 자리 잡음 → 「KNSM 섬」"],
  ["1921", "로이드 호텔 (이민자 호텔, 에버르트 브레만 설계) 준공"],
  ["1950~60년대", "인도네시아 독립으로 동방 교역 소멸, 컨테이너 · 벌크 화물에 부두가 맞지 않음 — 서쪽 새 항만으로 이전"],
  ["1975", "시의회가 주거지 조성을 결정 — 헥타르당 100호의 높은 밀도"],
  ["1979", "KNSM 이 마지막 선사로 떠남 — 이후 예술가 · 점거자들이 빈 건물 사용"],
  ["1975~1989", "옛 도축장 부지에 시 설계 사회주택 (첫 사업)"],
  ["1985", "시의회 「구조 스케치 · 기본원칙 문서 (Structuurschets en Nota van Uitgangspunten)」 확정"],
  ["1988", "요 쿠넌 (Jo Coenen)의 KNSM 섬 마스터플랜"],
  ["1989.11", "KNSM 섬 점거 주민 약 250명 강제 퇴거"],
  ["1990", "「기본원칙 문서 1990」 — 반도 구조 유지 · 고밀 · 약 8,500호 · IJ 터널 · 11.1 KNSM 섬 용도계획 확정"],
  ["1993~1996", "KNSM 섬 바르셀로나 (1993) · 피레우스 (1994, 한스 콜호프) · 에메랄드 엠파이어 · 스카이돔 (1996)"],
  ["1993~2000", "보르네오 · 스포렌뷔르흐 — West 8 마스터플랜, 2,500호 · 약 100명의 건축가"],
  ["1997", "자바 섬 용도계획 확정 (쇠르트 수테르스 설계) · 피트 하인 터널 개통"],
  ["2001~2005", "얀 스하퍼르 다리 (2001) · 로이드 호텔 국가기념물 (2001) → 호텔 재개장 (2004, MVRDV) · IJ 트램 (2005)"],
  ["2002", "보르네오 · 스포렌뷔르흐, 하버드 「베로니카 러지 그린 도시설계상」 수상"],
 ],
 "problem": [
  "1935년 일반 확장계획에서 이미 \"역사적 실수\"라 불릴 만큼 동부 항만은 바다 쪽 접근이 나빴고, 컨테이너 · 벌크 화물과 대형 선박에 부두 · 수역이 너무 작았습니다.",
  "인도네시아 독립으로 동방 교역이 사라지고 여객도 항공에 넘어가, 1970년대 항만 활동이 급감하고 1979년 마지막 선사가 떠났습니다.",
  "도심 바로 옆의 넓은 항만이 비면서 점거자 · 예술가가 들어왔고, 시는 도시 안에서 많은 주택을 공급할 땅이 필요했습니다.",
  "부두와 수면을 메울지 남길지, 사회주택과 분양주택을 어떻게 섞을지가 쟁점이었습니다.",
 ],
 "overview": [
  "1975년 시의회가 주거 전환과 헥타르당 100호의 높은 밀도를 정했고, 첫 단계로 옛 도축장 부지에 시가 설계한 사회주택을 지었습니다. 1980년대 말에는 사회주택 위주에서 \"건축적 품질\" 위주로 정책이 바뀌어, 반도마다 다른 설계자에게 계획을 맡겼습니다.",
  "1990년 기본원칙 문서는 부두 수면과 반도 구조를 그대로 남기고, 약 8,500호를 고밀도로 짓고, 반도는 주거 · IJ 대로변은 업무로 나누며, A10 순환도로와 잇는 터널(피트 하인 터널, 1997)을 놓는다는 틀을 정했습니다. KNSM 섬은 요 쿠넌 (1988)의 큰 블록, 자바 섬은 쇠르트 수테르스의 작은 운하 · 다양한 필지 (56필지 · 19명의 건축가), 보르네오 · 스포렌뷔르흐는 West 8 (아드리안 회저)의 3층 운하 주택 2,500호와 큰 조형 블록 3개로 완성되었습니다.",
  "보르네오의 스헤이프스팀메르만스트라트에서는 개인이 직접 건축주가 되어 집을 짓는 「개인 건축주 (particulier opdrachtgeverschap)」 방식이 널리 알려졌습니다. 로이드 호텔 · 로츠 6 · 세관 · 선장 주택 같은 항만 건물 일부를 남겨 새 용도로 썼습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "요 쿠넌 (Jo Coenen)", "KNSM 섬 마스터플랜 (1988) · 에메랄드 엠파이어 (1996)"],
  ["도시계획가 · 건축가", "쇠르트 수테르스 (Sjoerd Soeters)", "자바 섬 도시설계 (1990년대) — 4개 운하 · 5개 블록"],
  ["도시계획가 · 건축가", "West 8 (아드리안 회저 Adriaan Geuze)", "보르네오 · 스포렌뷔르흐 마스터플랜 (1993~2000) · 빨간 보행교 2개"],
  ["도시계획가 · 건축가", "한스 콜호프 · 크리스티안 랍 (Hans Kollhoff & Christian Rapp)", "KNSM 섬 「피레우스 (Piraeus)」 (1994)"],
  ["도시계획가 · 건축가", "브뤼노 알베르트 (Bruno Albert) · 빌 아레츠 (Wiel Arets)", "KNSM 섬 「바르셀로나」 (1993) · 「스카이돔」 (1996)"],
  ["도시계획가 · 건축가", "프리츠 반 동언 · 더 아르히텍턴 시 (Frits van Dongen, de Architekten Cie)", "스포렌뷔르흐 「고래 (The Whale)」"],
  ["도시계획가 · 건축가", "코언 반 벨선 (Koen van Velsen) · 헤르만 헤르츠베르허르 · MVRDV 등", "「팩맨」, 스헤이프스팀메르만스트라트 개인 주택, 로이드 호텔 개조 (MVRDV, 2004)"],
  ["도시계획가 · 건축가", "라포르 · 반 베이크 (Lafour en Van Wijk)", "옛 도축장 부지 사회주택 — 1990 비바우트상"],
  ["주관 기관", "암스테르담 시 (Gemeente Amsterdam) · 시의회", "1975 주거 전환 결정, 1985 구조 스케치 · 기본원칙, 1990 기본원칙 문서, 섬별 용도계획 확정"],
  ["관리", "스타츠데일 제이뷔르흐 → 스타츠데일 오스트 (Stadsdeel Oost)", "용도계획 갱신 (2013 「오스텔레이크 하벤헤비트 노르트」)"],
  ["민간", "뉴 딜 (New Deal)", "보르네오 · 스포렌뷔르흐 발주 · 개발 회사"],
  ["민간 · 주택협회", "더 케이 (De Key)", "로이드 호텔 복원 재원"],
  ["시민단체", "오스텔레이크 하벤헤비트 주민단체 (Bewonersgroep Oostelijk Havengebied) · 점거자 · 예술가", "1980년 레반트카더 창고 점거 등 주거 운동, 재개발 비판 · 산업유산 보존 요구"],
 ],
 "laws": [
  ["시의회 주거 전환 결정 (1975)", "항만 → 주거, 헥타르당 100호의 높은 밀도"],
  ["구조 스케치 · 기본원칙 문서 (Structuurschets en Nota van Uitgangspunten Oostelijk Havengebied, 1985)", "1980년 이후의 여러 재구조화 안을 정리해 시의회가 확정"],
  ["기본원칙 문서 1990 (Nota van Uitgangspunten 1990)", "반도 구조 유지 · 고밀 개발 · 약 8,500호 · 반도는 주거, IJ 대로는 업무 · A10 연결 터널 · 수면의 여가 활용 · 중심 상가 1곳"],
  ["KNSM 섬 용도계획 (Bestemmingsplan KNSM-eiland, 1990.11.1 시의회 확정)", "KNSM 섬 재건의 법적 틀 — 항만 → 주거 · 혼합 (로츠 6 구획만 국가 승인 보류)"],
  ["자바 섬 용도계획 (Bestemmingsplan Java-eiland, 1997.4.2 확정 · 1998 승인)", "도시설계의 법적 번역 — 주거 W1 · W2, 1~2층 근린 용도 허용, 외곽 5~10층 · 중정 3~5층"],
  ["용도계획 「오스텔레이크 하벤헤비트 노르트」 (Bestemmingsplan Oostelijk Havengebied Noord, 2013)", "자바 섬 · KNSM 섬 · 한덜스카더의 옛 용도계획들을 하나로 갱신", "https://www.planviewer.nl/imro/files/NL.IMRO.0363.BP01117-OH01/t_NL.IMRO.0363.BP01117-OH01_index.pdf"],
  ["기념물법 1988 (Monumentenwet 1988)", "국가기념물 (rijksmonument) 보호 — 로이드 호텔 2001 지정"],
 ],
 "lawsNote": ["네덜란드에는 영국식 특별 개발공사 · 세제 특례가 없었습니다. 시가 기본원칙 문서로 큰 틀(밀도 · 반도 · 수면 보존)을 정하고, 섬별 용도계획으로 항만을 주거 · 혼합 용도로 바꾸는 \"계획 주도\" 방식이었습니다. 완화라기보다 용도의 전면 전환과 높은 밀도 목표가 핵심입니다."],
 "tools": [
  ["용도 전환 (용도계획)", "항만 → 주거 중심 혼합, 1~2층 근린 상업 허용"],
  ["고밀 저층 설계", "헥타르당 약 100호 — 보르네오 · 스포렌뷔르흐는 3층 운하 주택 + 조형 블록 3개"],
  ["섬별 설계자 · 다수 건축가", "섬마다 다른 마스터플랜, 자바 섬 56필지 19명 · 보르네오 · 스포렌뷔르흐 약 100명의 건축가"],
  ["개인 건축주 방식", "보르네오 스헤이프스팀메르만스트라트 — 개인이 필지별로 직접 설계 · 시공 발주"],
  ["사회주택 혼합", "민간 70% · 사회주택 30% (온스 에르프데일 2004), KNSM 섬 사회주택 약 600호"],
  ["기반시설", "피트 하인 터널 (1997, A10 연결) · 얀 스하퍼르 다리 (2001) · IJ 트램 (2005)"],
  ["유산 재사용", "로이드 호텔 (국가기념물 → 호텔), 로츠 6 (시 기념물 → 공방 · 갤러리), 세관 · 선장 주택"],
 ],
 "zoning": [
  ["지정", "섬별 용도계획 — KNSM 섬 (1990), 자바 섬 (1997), 한덜스카더 (1998 · 1999), 레이트란던 (1998) → 2013 「오스텔레이크 하벤헤비트 노르트」로 통합 갱신"],
  ["관리 주체 · 방식", "암스테르담 시 (계획 · 토지) → 스타츠데일 (구) 정부가 용도계획 갱신 · 관리"],
  ["보존 관리", "로이드 호텔 국가기념물 (2001), KNSM 섬 로츠 6 · 크레인 · 옛 식당 건물 「에델바이스」 시 기념물, 부두벽 · 선장 주택 보존"],
 ],
 "result": [
  "약 8,000~8,500호의 고밀 주거지 — 인구 약 2만 555명 (2024), 주택 약 1만 호.",
  "보르네오 · 스포렌뷔르흐는 2002년 하버드 베로니카 러지 그린 도시설계상을 받아 세계적 주거 설계 견학지가 되었습니다.",
  "반면 학교 · 어린이집 · 상점 같은 근린시설이 부족하다는 비판이 있었고, 사회주택 비율 (32%)은 암스테르담 평균 (40%)보다 낮아졌습니다.",
 ],
 "lesson": [
  "부두 수면과 반도 구조를 남긴 채 고밀 저층 주거를 만든 방법은 수변 산단 재생의 좋은 참고입니다.",
  "섬마다 다른 설계자, 필지마다 다른 건축가로 대규모 단지의 단조로움을 피했습니다.",
  "근린시설 부족 비판은 주거 위주 전환에서 생활 기반을 함께 계획해야 한다는 교훈입니다.",
 ],
 "funding": [
  ["공공 재원 (적자 추정)", "1985년 5월 시는 주택 1호당 3만 길더의 적자를 예상했고, 중앙정부는 「도시재생 기금 (fonds stadsvernieuwing)」으로 충당하라고 했으나 시는 부족하다고 반발 (오스트 온라인 옛 뉴스)", "https://oost-online.nl/oud-nieuws-amsterdam-wil-tienduizend-woningen-bouwen/"],
  ["주택협회 재원", "로이드 호텔 복원은 주택재단 더 케이 (De Key)가 재원을 댐"],
  ["민간 투자", "보르네오 · 스포렌뷔르흐는 개발회사 뉴 딜 (New Deal)이 발주 — 금액은 확인하지 못했습니다"],
  ["공공 재원 (적자)", "시 개발공사 회고집 「Krassen op de eeuwigheid」의 관계자 회고 — 동부 항만 적자는 \"1호당 4만 3천 길더였던 것 같다\" (기억에 기댄 수치), 시의 대규모 투자가 민간 투자의 신뢰를 끌어냈다는 평가", "https://assets.amsterdam.nl/publish/pages/919482/krassen_op_de_eeuwigheid.pdf"],
  ["재원 구조 (시 전체)", "암스테르담 시는 토지 정비 비용을 토지 장기 임대 수입으로 메우는 「토지 개발 회계 (grondexploitatie)」와, 적자 · 흑자 사업을 서로 메우는 「평준화 기금 (Vereveningsfonds)」을 운영 (같은 회고집)", "https://assets.amsterdam.nl/publish/pages/919482/krassen_op_de_eeuwigheid.pdf"],
  ["주택 구성 변화", "같은 회고집 — 동부 항만은 사회임대 70% · 분양 30%로 시작했으나 결과는 정반대가 되었다는 회고 (담당 시의원 루이스 헤넷 Louis Genet)", "https://assets.amsterdam.nl/publish/pages/919482/krassen_op_de_eeuwigheid.pdf"],
 ],
 "famous": [
  "보르네오 · 스포렌뷔르흐가 2002년 하버드 대학교 「베로니카 러지 그린 도시설계상」을 받았습니다.",
  "저층 위주로 헥타르당 약 100호를 이룬 네덜란드 최고 밀도 주거지의 하나입니다.",
  "약 100명의 건축가가 운하 주택을 하나씩 설계하고, 개인이 직접 건축주가 된 필지 (스헤이프스팀메르만스트라트)로 \"다양성\"의 본보기가 되었습니다.",
  "1990년대 네덜란드 건축의 전성기를 보여 주는 \"건축가 명사록\" 지구로 평가받습니다 (네덜란드어 위키백과).",
 ],
 "operation": [
  ["운영 주체 (문화 · 작업 공간)", "로츠 6 재단 (Stichting Kunstwerk Loods6) — 옛 KNSM 창고를 소유하고 아틀리에 · 작업실 232곳과 식당 · 상점 · 행사장을 운영, 세 건물 약 2만 5천㎡ 관리", "https://loods6.nl/locations"],
  ["토지 · 건물 임대 구조", "재단이 1990년대 시의 장기 토지 임대 (erfpacht)를 2046년까지 일시 선납 — 주택협회 더 케이에서 1,150만 길더를 빌려 2012년 모두 상환 (팔로 더 머니, 2020)"],
  ["수입 구성", "로츠 6 연 임대 수입 약 170만 유로 · 재단 운영 자본 약 1,300만 유로 (팔로 더 머니, 2020)"],
  ["운영상 문제", "1998년부터 재단의 유일한 이사가 된 더 케이가 로츠 6 를 담보로 로이드 호텔 개발용 1,200만 유로 대출을 받고, 2018년 임대권 매각 · 재단 정관 변경을 추진해 입주자들이 반발 (팔로 더 머니, 2020)"],
  ["운영 주체 (호텔)", "로이드 호텔 — 더 케이 재원으로 복원 (2004 호텔), 2021년 매각 뒤 내부 개조해 2023년 재개장"],
 ],
 "operationNote": [
  "동부 항만은 주거 위주라 지구 전체를 운영하는 기관은 없고, 보존한 항만 건물을 비영리 재단 · 주택협회가 임대 사업으로 운영합니다. 로츠 6 는 시의 장기 토지 임대료를 대출로 선납한 뒤 아틀리에 임대 수입으로 갚아 자립했지만, 그 자산을 둘러싸고 주택협회와 입주 예술가 사이의 갈등이 생겼습니다.",
 ],
 "missing": [
  "동부 항만의 업무 · 첨단산업 입주 기업과 상업 시설 목록은 확인된 자료를 찾지 못했습니다.",
  "주거 지구의 관리 재원 (관리조합 · 지구 부담금)과 시의 토지 임대 수입은 확인된 자료를 찾지 못했습니다.",
  "시의 공공 토지 장기임대 (erfpacht) 적용 여부와 조건은 확인된 자료를 찾지 못했습니다 — 기존 내용에서 뺐습니다.",
  "사업 전체를 맡은 시 사업단 (projectbureau)의 공식 이름과 책임자는 확인된 자료를 찾지 못했습니다.",
  "1985 · 1990 기본원칙 문서 원문은 확인된 자료를 찾지 못했습니다 (2013 용도계획 해설에서 내용을 확인했습니다).",
  "전체 사업비 · 공공 투자 총액은 확인된 자료를 찾지 못했습니다 — 호당 적자 (1985 예상 3만 길더, 회고 4만 3천 길더)만 확인했습니다.",
  "용적률 수치는 확인된 자료를 찾지 못했습니다 — 밀도 (헥타르당 약 100호)로만 확인했습니다.",
 ],
 "refs": [
  {"t": "Wikipedia (NL) — Muziekgebouw aan 't IJ", "u": "https://nl.wikipedia.org/wiki/Muziekgebouw_aan_%27t_IJ"},
  {"t": "Gemeente Amsterdam (Ontwikkelingsbedrijf) — De jaren negentig: Amsterdam in ontwikkeling. Krassen op de eeuwigheid (PDF)", "u": "https://assets.amsterdam.nl/publish/pages/919482/krassen_op_de_eeuwigheid.pdf"},
  {"t": "Stichting Kunstwerk Loods6 — Our buildings", "u": "https://loods6.nl/locations"},
  {"t": "Follow the Money — Corporatie-coup op het KNSM-eiland (2020.5.22)", "u": "https://www.ftm.nl/artikelen/corporatie-coup-op-het-knsm-eiland-of-hoe-de-key-stichting-loods-6-leegzuigt"},
  {"t": "Oost-Online — Oud nieuws: Amsterdam wil tienduizend woningen bouwen (1985)", "u": "https://oost-online.nl/oud-nieuws-amsterdam-wil-tienduizend-woningen-bouwen/"},
  {"t": "Wikipedia (NL) — Oostelijk Havengebied", "u": "https://nl.wikipedia.org/wiki/Oostelijk_Havengebied"},
  {"t": "Wikipedia (NL) — KNSM-eiland", "u": "https://nl.wikipedia.org/wiki/KNSM-eiland"},
  {"t": "Wikipedia (NL) — Java-eiland", "u": "https://nl.wikipedia.org/wiki/Java-eiland"},
  {"t": "Wikipedia (NL) — Borneo-eiland", "u": "https://nl.wikipedia.org/wiki/Borneo-eiland"},
  {"t": "Wikipedia (NL) — Lloyd Hotel (hotel)", "u": "https://nl.wikipedia.org/wiki/Lloyd_Hotel_(hotel)"},
  {"t": "Wikipedia — Eastern Docklands", "u": "https://en.wikipedia.org/wiki/Eastern_Docklands"},
  {"t": "Gemeente Amsterdam, Stadsdeel Oost — Toelichting bestemmingsplan 'Oostelijk Havengebied Noord' (2013, PDF)", "u": "https://www.planviewer.nl/imro/files/NL.IMRO.0363.BP01117-OH01/t_NL.IMRO.0363.BP01117-OH01_index.pdf"},
  {"t": "West 8 — Borneo-Sporenburg", "u": "https://www.west8.com/projects/borneo-sporenburg/"},
  {"t": "Ons Erfdeel (2004, DBNL) — Geslaagde stedenbouw: het oostelijk havengebied van Amsterdam", "u": "https://www.dbnl.org/tekst/_ons003200401_01/_ons003200401_01_0046.php"},
  {"t": "ONH.nl — Het Oostelijk Havengebied", "u": "https://onh.nl/verhaal/het-oostelijk-havengebied"},
  {"t": "architectuurgids.nl — Oostelijk Havengebied, Amsterdam", "u": "https://www.architectuurgids.nl/project/list_projects_of_typeofbuilding/typ_id/3/prj_id/507"},
  {"t": "IISG Staatsarchief — Oostelijke eilanden / Havengebied & IJoevers", "u": "https://iisg.nl/staatsarchief/archieven/buurten-amsterdam/oostelijke-eilanden.php"},
 ],
},
}
