# -*- coding: utf-8 -*-
# 도시재생 노트 — 더 자세한 본문 (regen*.py 의 같은 id 를 덮어씀) — 배정 10
#  port-vell, pearl-district, lowell-mills, singapore-river-quays, granville-island
D = {
"port-vell": {
 "spec": [
  ["위치", "스페인 카탈루냐 바르셀로나 — 람블라스 (La Rambla) 끝 콜럼버스 기념탑 앞, 바르셀로나 항 (Port de Barcelona)에서 가장 오래된 구역"],
  ["면적", "특별계획 당시 옛 항구 구역 약 55.6ha (국가 항만공간 이용계획 1999 기준) — 이후 북쪽 새 항구 입구 (Bocana Nord) 14ha 를 더해 현재 약 70ha"],
  ["기간", "1981년 시민 개방 → 1983~1987년 몰 데 라 푸스타 → 1988년 「항만 2000」 도시계획 관리단 설치 · 특별계획 의결 → 1989년 특별계획 승인 → 1994년 람블라 데 마르 → 1995년 마레마그눔 · 아쿠아리움 → 2001년 북쪽 항구 입구 특별계획"],
  ["원래 용도", "19세기부터 화물 하역 부두 · 창고 (tinglados) · 일반 보관창고 (Magatzems Generals de Dipòsit) · 해수욕장 (banys) · 해변 간이식당"],
  ["변경 용도", "마레마그눔 (Maremàgnum) 쇼핑 · 식당 · IMAX · 바르셀로나 아쿠아리움 (Aquàrium) · 람블라 데 마르 (Rambla de Mar, 보행 도개교) · 몰 데 라 푸스타 (Moll de la Fusta) 산책로 · 팔라우 데 마르 (Palau de Mar, 카탈루냐 역사박물관) · 마리나 · 세계무역센터 (WTC Barcelona)"],
  ["원래 용도지구", "국가 항만 서비스 구역 (zona de servicio del puerto) — 상업 항만 · 하역"],
  ["변경 용도지구", "항만 서비스 구역 안의 「포르트 벨 특별계획 (Pla Especial del Port Vell)」 구역 — 11개 사업 구역별로 해양 스포츠 · 여객 · 상업 · 호텔 · 문화 · 레저 용도 지정"],
  ["운영 규모", "마레마그눔 상업면적 22,000㎡ · 연간 방문객 약 1,300만 명 (카탈루냐어 위키), 아쿠아리움 연 150만 명 수준"],
 ],
 "from": "항만 하역 부두 · 창고 · 해수욕장", "to": "수변 상업 · 레저 · 문화 · 마리나",
 "zoneFrom": "항만 서비스 구역 (zona de servicio del puerto)", "zoneTo": "포르트 벨 특별계획 구역 (Pla Especial del Port Vell)",
 "tenants": [
  ["상업 · 대형 쇼핑 · 식음", "마레마그눔 (Maremàgnum) — 클레피에르 (Klépierre)", "1995년 개장 · 에스파냐 부두 (Moll d'Espanya), 개장 때 상업면적 약 2만 2천㎡ · 현재 브랜드 35곳 · 식당 16곳 · 주차 826면, 연중 365일 영업 (2015년부터 클레피에르 소유)", "https://maremagnum.klepierre.es/historia"],
  ["상업 · 식음 (푸드홀)", "타임아웃 마켓 바르셀로나 (Time Out Market Barcelona)", "2024.7.5 개장 · 마레마그눔 2층 · 5,250㎡ · 셰프 · 레스토랑 14곳 · 바 4곳 · 행사 공간 — 스페인 첫 타임아웃 마켓", "https://www.timeout.com/about/latest-news/time-out-market-is-officially-open-from-5-july-2024-bringing-the-best-of-the-city-together-under-one-roof-070424"],
  ["문화 · 아쿠아리움", "바르셀로나 아쿠아리움 (Aquàrium de Barcelona) — 아스프로 파크스 (Aspro Parks)", "1995.9.8 개장 · 에스파냐 부두 · 수조 80개 · 약 600종 1만 1천 마리 · 지름 36m 해양 수조 (2015년 방문 154만 9,480명)", "https://ca.wikipedia.org/wiki/Aquàrium_de_Barcelona"],
  ["문화 · 박물관", "카탈루냐 역사박물관 (Museu d'Història de Catalunya)", "1993년 이후 팔라우 데 마르 (옛 일반 보관창고) — 상설 전시 · 도서관 · 항구 전망 식당", "https://ca.wikipedia.org/wiki/Palau_de_Mar"],
  ["첨단산업 · 창업 · 테크 허브", "테크 바르셀로나 피어 원 (Tech Barcelona Pier01)", "팔라우 데 마르 건물 안 스타트업 · 테크 허브 (입주 연도는 미확인)", "https://ca.wikipedia.org/wiki/Palau_de_Mar"],
  ["업무 · 오피스 · 컨벤션", "월드트레이드센터 바르셀로나 (World Trade Center Barcelona)", "1999.7.22 개장 · 바르셀로나 부두 (Moll de Barcelona) · 원형 타워 4동 — 임대 사무실 40~3,000㎡ · 8~1,500명 컨벤션센터 (설계 헨리 N. 콥)", "https://ca.wikipedia.org/wiki/World_Trade_Center_Barcelona"],
  ["상업 · 호텔", "그랜드 마리나 호텔 (Grand Marina, 5성)", "월드트레이드센터 바르셀로나 안 · 291실", "https://ca.wikipedia.org/wiki/World_Trade_Center_Barcelona"],
  ["상업 · 호텔", "W 바르셀로나 호텔 (Hotel W Barcelona)", "북쪽 새 항구 입구 (Nova Bocana) 지구 — 포르트 벨 공식 사이트 입주 목록 (개장 연도 · 규모는 미확인)", "https://portvellbcn.cat/ca/"],
  ["업무 · 기업 본사", "데시구알 본사 (Desigual Oficines Centrals)", "포르트 벨 공식 사이트의 「산업 · 기업」 입주 목록 (입주 연도 · 위치 상세 미확인)", "https://portvellbcn.cat/ca/"],
  ["문화 · 대학", "바르셀로나 해양대학 (Facultat Nàutica de Barcelona)", "포르트 벨 공식 사이트의 「교육」 입주 목록", "https://portvellbcn.cat/ca/"],
  ["문화 · 박물관", "바르셀로나 해양박물관 (Museu Marítim de Barcelona)", "드라사네스 레이알스 (Drassanes Reials, 옛 왕립 조선소) — 포르트 벨 공식 사이트 목록", "https://portvellbcn.cat/ca/"],
  ["상업 · 마리나", "마리나 벨라 (Marina Vela) · 마리나 포르트 벨 (Marina Port Vell) · 마리나 바르셀로나 92", "요트 정박 · 수리 — 마리나 벨라는 북쪽 새 항구 입구 특별계획 (2001)으로 조성", "https://www.portdebarcelona.cat/ca/port-vell/historia-del-port-vell"],
  ["문화 · 영화관", "마레마그눔 옛 멀티플렉스 영화관 (cinema multisala)", "1995년 개장 때 영화관 · 식당 · 바 · 디스코텍 중심 → 영화관 건물은 이후 철거, 그 자리를 항만청 · 시와 협의해 아메리카스컵 (2024) 시설로 사용 (철수)", "https://www.ejeprime.com/comercial/klepierre-invertira-15-millones-de-euros-en-el-reposicionamiento-de-maremagnum"],
 ],
 "timeline": [
  ["1869", "바르셀로나 항만공사위원회 (Junta de Obras del Port de Barcelona) 설립"],
  ["1978", "바르셀로나 자치항 (Port Autònom de Barcelona) 정관 승인"],
  ["1981", "군의 날 (Dia de les Forces Armades) 행사를 계기로 자치항 이사회가 보슈 이 알시나 부두 (옛 무랄랴 부두, 현 몰 데 라 푸스타)를 시민에게 개방 — 70여 년 만의 첫 개방"],
  ["1982~1987", "항만과 시 (Ajuntament)가 마누엘 데 솔라-모랄레스 (Manuel de Solà-Morales)에게 부두 · 콜롬 거리 교통 재편 설계 의뢰 (1982) → 1983~1985 공사 → 1987.1 파스쿠알 마라갈 (Pasqual Maragall) 시장이 개장"],
  ["1986", "바르셀로나, 1992년 올림픽 개최지로 결정"],
  ["1987", "항만 전략계획 — 항만을 상업 · 물류 · 옛 항구 (Port Vell) 세 구역으로 재편"],
  ["1988", "「항만 2000 도시계획 관리단 (Gerència Urbanística Port 2000)」 설치 — 항만 기술부서 (Serveis Tècnics del Port)와 함께 포르트 벨 특별계획 작성 · 자치항 의결 · 산트 세바스티아 해수욕장 철거"],
  ["1989.5~6", "포르트 벨 특별계획, 카탈루냐 자치정부 도시계획위원회 승인 (5월) · 바르셀로나 도시계획위원회 최종 승인 (6월)"],
  ["1990~1992", "해수욕장 · 해변 간이식당 18곳 철거"],
  ["1992", "옛 일반 보관창고 (1900년 준공)를 행정용으로 1차 개조 → 1993년 카탈루냐 역사박물관 전환 결정 (팔라우 데 마르)"],
  ["1994.9.24", "람블라 데 마르 (설계: 엘리오 피뇬 · 알베르트 비아플라나) 개통"],
  ["1995", "마레마그눔 개장 (설계: 피뇬 · 비아플라나 · 라파엘 콜) · 9월 8일 아쿠아리움 개장"],
  ["2001", "북쪽 새 항구 입구 (Nova Bocana) 특별계획 승인 (2006 · 2011 · 2018 변경)"],
  ["2005.9.23", "마레마그눔, 야간 유흥 중심에서 낮 시간 쇼핑 · 식당 중심으로 리모델링 재개장 (설계: 리카르드 메르카데)"],
 ],
 "problem": [
  "구도심 (시우타트 벨랴)과 바다 사이를 창고 · 철도 · 해안도로가 가로막아, 시민이 70년 넘게 옛 항구에 들어갈 수 없었습니다.",
  "항만 기능이 남쪽 (요브레가트강 하구 쪽)으로 옮겨 가면서 옛 부두와 창고는 쓰이지 않거나 쇠퇴하는 활동만 남았습니다.",
  "해수욕장 · 간이식당 등이 해안을 점유하고 있어 공공 접근이 막혀 있었습니다.",
  "1992년 올림픽을 앞두고 도시를 바다로 다시 여는 (\"obrir la ciutat al mar\") 기반시설 재편이 필요했습니다.",
 ],
 "overview": [
  "바르셀로나 항만청이 소유 · 관리하는 국가 항만 용지 안에서, 항만청 스스로 「특별계획 (Pla Especial)」을 세워 옛 항구 약 56ha 를 해양 스포츠 · 여객 · 상업 · 문화 · 레저 공간으로 바꾼 사업입니다. 항만 기능을 완전히 없애지 않고 \"상업 항만 활동을 해양 스포츠 등 다른 항만 활동으로 대체\"하는 것을 목표로 했습니다.",
  "첫 단계는 시 쪽 해안의 몰 데 라 푸스타 정비(1980년대)로, 해안도로를 정리하고 산책로를 만들었습니다. 이어 1988년 항만청 안에 「항만 2000 도시계획 관리단」을 두고, 1989년 승인된 특별계획에 따라 에스파냐 부두 (Moll d'Espanya)에 마레마그눔 · 아쿠아리움 · IMAX 를 넣고 람블라 데 마르로 람블라스 거리와 직접 이었습니다.",
  "바르셀로나 항만청 (카탈루냐어 공식 연혁)에 따르면 특별계획의 \"시민 항구 (Port Ciutadà)\" 모델은 ① 새 상업 · 관광 · 문화 · 서비스 용도를 에스파냐 부두 끝 (쇼핑센터 · 영화관 · 아쿠아리움)과 바르셀로나 부두 끝 (월드트레이드센터 · 뒤에 호텔)에 모으고, ② 팔라우 데 마르를 고쳐 쓰며, ③ 누 부두 · 카탈루냐 부두는 대형 요트 수리 · 정비 시설로 유지하고, ④ 몰 데 라 푸스타 · 바르셀로네타 부두 등에 큰 공공 공간을 두는 것이었습니다. 계획은 여러 차례 변경 · 개별 협약을 거쳤고 처음부터 시민 · 언론의 논쟁 대상이었습니다.",
  "옛 일반 보관창고는 팔라우 데 마르로 고쳐 카탈루냐 역사박물관 · 식당 · 업무 공간이 되었습니다. 마레마그눔은 개장 뒤 야간 유흥과 폭력 사건으로 이미지가 나빠지자 2005년 낮 시간 쇼핑 · 식당 중심으로 바꿨습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "마누엘 데 솔라-모랄레스 (Manuel de Solà-Morales)", "몰 데 라 푸스타 · 콜롬 거리 교통 재편 설계 (1982 항만 · 시 공동 의뢰, 1983~1985 시공)"],
  ["도시계획가 · 건축가", "항만 2000 도시계획 관리단 · 항만 기술부서 (Gerència Urbanística Port 2000 · Serveis Tècnics del Port)", "포르트 벨 특별계획 (1988~1989) 작성 — 개인 계획가 이름은 공식 연혁에 없음"],
  ["도시계획가 · 건축가", "엘리오 피뇬 (Helio Piñón) · 알베르트 비아플라나 (Albert Viaplana) · 라파엘 콜 (Rafael Coll)", "람블라 데 마르 · 마레마그눔 설계"],
  ["도시계획가 · 건축가", "호안 아리아스 · 호안 솔라 / 조세프 베네딕토 · 아구스티 마테오스", "팔라우 데 마르 개조 — 1992 행정용 (아리아스 · 솔라), 1993~ 박물관 (베네딕토 · 마테오스)"],
  ["도시계획가 · 건축가", "리카르드 메르카데 (Ricard Mercadé)", "마레마그눔 리모델링 (2005 재개장)"],
  ["주관 · 토지 소유", "바르셀로나 항만청 (Port de Barcelona, 옛 Port Autònom de Barcelona)", "항만 용지 소유 · 특별계획 수립 · 사업 구역 양허 (concesión)"],
  ["사업 시행", "항만 2000 도시계획 관리단 (Gerència Urbanística Port 2000 → 현 Gerència Urbanística Port Vell, 1988)", "옛 항구 개발 · 관리 전담 조직"],
  ["관련 기관", "카탈루냐 자치정부 도시계획위원회 (Comissió d'Urbanisme de la Generalitat de Catalunya)", "1989년 5월 특별계획 승인"],
  ["관련 기관", "바르셀로나 시 (Ajuntament de Barcelona) · 바르셀로나 도시계획위원회", "1989년 6월 최종 승인, 마라갈 시정부 — 해안 도로 · 산책로 연결"],
  ["관련 기관", "스페인 공공사업부 (Ministerio de Fomento)", "항만 공간 이용계획 승인 (국가 항만)"],
  ["민간 · 운영", "마레마그눔 운영사 · 아스프로 파크스 (Aspro Parks, 아쿠아리움)", "양허 구역에서 상업 · 레저 시설 운영"],
 ],
 "laws": [
  ["바르셀로나 자치항 정관 (Estatut d'Autonomia del Port, 1978)", "항만을 자치항으로 운영할 수 있는 근거 — 항만청이 자기 용지의 계획 · 개발 주체가 됨"],
  ["바르셀로나 항 전략계획 (Pla Estratègic del Port de Barcelona, 1987)", "항만을 상업 · 물류 · 옛 항구 (Port Vell) 세 구역으로 재편 — 옛 항구를 도시 용도로 돌리는 출발점"],
  ["포르트 벨 특별계획 (Pla Especial del Port Vell, 1988 의결 · 1989 승인)", "옛 항구를 11개 사업 구역으로 나누고 각 구역의 용도를 지정 — 상업 항만 대신 해양 스포츠 · 여객 · 「엄밀히 상업 항만은 아니지만 보완적인」 활동 · 호텔 · 문화 · 레저 허용"],
  ["국가 항만 및 상선법 (Ley 27/1992 de Puertos del Estado y de la Marina Mercante)", "국가 항만의 서비스 구역을 「항만 공간 이용계획」으로 정하고, 공유수면 · 항만 용지의 독점적 이용은 양허 (concesión) · 허가로만 가능", "https://www.boe.es/buscar/doc.php?id=BOE-A-1992-26146"],
  ["바르셀로나 항 항만 공간 이용계획 (Orden de 30 de diciembre de 1999)", "포르트 벨 55.6ha 의 비 (非)상업항만 용도를 국가 차원에서 확인 — 근거: 도시와 맞닿은 입지 · 항만의 남쪽 확장 · 상업 항만 운영에 부정적 영향 없음", "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2000-827"],
  ["북쪽 새 항구 입구 특별계획 (Pla Especial de la Nova Bocana, 2001 · 2006 · 2011 · 2018 변경)", "포르트 벨 남쪽 끝 14ha 추가 정비"],
 ],
 "lawsNote": ["규제완화의 핵심은 \"항만 용지의 용도 전환\"입니다. 땅의 소유 (국가 항만)는 그대로 둔 채, 특별계획과 국가 항만 공간 이용계획으로 상업 항만 전용 용도를 상업 · 레저 · 문화 · 호텔까지 넓혔습니다. 마레마그눔은 관광 지역으로 분류되어 바르셀로나에서 유일하게 연중 365일 영업이 허용된 쇼핑센터입니다."],
 "tools": [
  ["항만 용지 양허 (concesión)", "항만청이 땅을 소유한 채 민간에 일정 기간 이용권을 주어 상업 · 레저 시설을 짓고 운영 — 땅 매각 없음"],
  ["전담 관리 조직", "항만청 안에 「항만 2000 도시계획 관리단」(1988)을 따로 두어 계획 · 개발 · 관리"],
  ["올림픽 연계 기반시설", "1992년 올림픽을 계기로 해안 순환도로 (Ronda Litoral) · 산책로 · 해변 정비"],
  ["옛 창고 재사용", "일반 보관창고 → 팔라우 데 마르 (카탈루냐 역사박물관 · 식당)"],
  ["철거 · 공공공간 확보", "창고 (tinglados) · 해수욕장 · 간이식당 18곳 철거로 해안 공공 공간 확대"],
 ],
 "zoning": [
  ["지정", "포르트 벨 특별계획 구역 — 1989년 승인, 약 56ha (11개 사업 구역) → 2001년 북쪽 항구 입구 추가로 약 70ha"],
  ["관리 주체 · 방식", "바르셀로나 항만청 · 포르트 벨 도시계획 관리단이 토지 소유자 겸 계획 · 관리 주체 — 시설은 양허 계약으로 민간 운영"],
  ["용도 배치 (특별계획 모델)", "에스파냐 부두 끝 — 쇼핑 · 영화관 · 아쿠아리움 / 바르셀로나 부두 끝 — WTC · 호텔 / 누 · 카탈루냐 부두 — 대형 요트 수리 · 정비 (항만 기능 유지) / 몰 데 라 푸스타 · 바르셀로네타 부두 — 공공 공간", "https://www.portdebarcelona.cat/ca/port-vell/historia-del-port-vell"],
  ["보존 관리", "팔라우 데 마르 (옛 일반 보관창고, 1900년 준공) — 지역 문화재 (BCIL, Bé Cultural d'Interès Local) 지정"],
 ],
 "result": [
  "옛 항구 약 70ha 가 시민 · 관광객이 찾는 수변 공간이 되었고, 람블라스 거리에서 바다까지 보행으로 이어졌습니다.",
  "마레마그눔 연간 방문객 약 1,300만 명, 아쿠아리움 2015년 154만 9,480명 (개장 뒤 2016년까지 누적 3,000만 명 이상).",
  "포르트 벨 사업과 함께 4.5km 의 해변이 공공 이용으로 회복되었습니다 (betevé).",
 ],
 "lesson": [
  "토지를 팔지 않고 공공 (항만청)이 소유한 채 양허 방식으로 상업 시설을 유치한 방식 — 국 · 공유 산업용지 재생에서 장기 임대로 공공성을 지키는 모델이 됩니다.",
  "항만 · 산단 관리 기관 안에 \"도시계획 관리단\" 같은 전담 조직을 두어 산업 기능과 도시 기능의 경계를 관리한 점.",
  "대형 국제 행사(올림픽)를 계기로 기반시설을 먼저 바꾸고, 그 뒤 단계적으로 민간 시설을 채운 순서.",
  "야간 유흥 중심의 상업 시설이 치안 문제를 낳자 용도 구성을 바꾼 마레마그눔 사례는, 수변 상업 시설의 업종 관리가 중요함을 보여 줍니다.",
 ],
 "funding": [
  ["토지 · 공공 재원", "바르셀로나 항만청 (국가 항만)이 땅을 소유한 채 사업 구역을 양허 (concesión)로 민간에 내주는 방식 — 땅 매각 없음 (양허 기간 · 사용료 금액은 미확인)", "https://www.boe.es/buscar/doc.php?id=BOE-A-1992-26146"],
  ["민간 투자", "마레마그눔 · 아쿠아리움 (아스프로 파크스) 등 상업 · 레저 시설은 양허를 받은 민간이 짓고 운영 — 2005년 마레마그눔 리모델링도 운영사 사업"],
  ["올림픽 연계 공공 투자", "1992년 올림픽을 앞두고 해안 순환도로 · 산책로 · 해변 정비가 함께 이루어짐 (금액 미확인)"],
  ["민간 투자 (마레마그눔 한 곳)", "클레피에르 (Klépierre) — 2015년 코리오 (Corio) 인수 (회사 전체 72억 유로)로 마레마그눔 소유, 2023년 2월 1,500만 유로 재단장 투자 발표 (상업면적 5,000㎡ 이상 확대 · 2024 타임아웃 마켓)"],
 ],
 "famous": [
  "샌프란시스코 · 볼티모어 · 리버풀 · 런던의 초기 항만 재생 경험을 바탕으로, 1992년 올림픽과 함께 구도심을 다시 바다로 연 바르셀로나 수변 재생의 중심 사업입니다 (바르셀로나 항만청).",
  "람블라스 거리에서 바다 위 보행 도개교 (람블라 데 마르)로 상업 · 레저 부두까지 걸어서 이어지는 구성 — 연간 약 1,600만 명이 찾는다고 소개됩니다 (영어 위키).",
  "바르셀로나 아쿠아리움 (1995)은 유럽 최대의 아쿠아리움으로 소개되며 (영어 위키), 2016년까지 누적 방문객 3,000만 명 이상입니다.",
  "마레마그눔은 관광 지역으로 분류되어 바르셀로나에서 유일하게 연중 365일 영업이 허용된 쇼핑센터입니다.",
 ],
 "operation": [
  ["운영 주체 (토지)", "바르셀로나 항만청 — 포르트 벨 도시계획 관리단 (Gerència Urbanística Port Vell)이 옛 항구 약 70ha 를 관리", "https://portvellbcn.cat/ca/transformacio-portvell/"],
  ["토지 · 건물 임대 구조", "국가 항만 공유지 — 독점적 이용은 양허 (concesión) · 허가로만 가능 (항만법 27/1992), 항만청이 땅을 소유한 채 민간에 사업권 부여", "https://www.boe.es/buscar/doc.php?id=BOE-A-1992-26146"],
  ["민간 운영사 — 상업", "마레마그눔은 현재 클레피에르 그룹 (Grupo Klépierre) 소속 쇼핑센터 — 브랜드 35곳 · 식당 16곳 · 주차 826면, 2024년부터 스페인 첫 타임아웃 마켓, 연중 365일 영업", "https://maremagnum.klepierre.es/historia"],
  ["민간 운영사 — 문화 · 관광", "바르셀로나 아쿠아리움은 아스프로 파크스 (Aspro Parks) 그룹 소속 — 입장료 수입 (2015년 방문객 154만 9,480명)"],
  ["운영상 문제", "개장 초 야간 유흥 중심 → 2002년 살인 사건 등 폭력 문제로 2005년 낮 시간 쇼핑 · 식당 중심으로 리모델링, 2009년까지 유흥업소 폐쇄"],
 ],
 "operationNote": [
  "포르트 벨은 국가 항만청이 땅을 소유한 채 사업권 (양허)을 민간에 내주고, 상업 · 레저 · 문화 시설은 민간 운영사가 입점 임대 · 입장료 · 주차 수입으로 운영하는 구조입니다. 마레마그눔은 클레피에르 그룹이, 아쿠아리움은 아스프로 파크스 그룹이 운영합니다.",
  "공공 운영 보조금의 존재나 금액, 항만청이 받는 양허 사용료 규모는 확인하지 못했습니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (IMAX 영화관의 현재 여부 · 폐관 연도, 마리나 운영사)는 확인된 자료를 찾지 못했습니다.",
  "양허 사용료 · 항만청의 포르트 벨 관련 수입 규모와 공공 운영 보조금은 확인된 자료를 찾지 못했습니다.",
  "포르트 벨 특별계획 (1989)은 항만 2000 도시계획 관리단과 항만 기술부서가 작성했다고만 공식 연혁에 나오며, 계획을 맡은 개인 도시계획가 · 건축가 이름은 확인된 자료를 찾지 못했습니다.",
  "재원 · 보조금 가운데 1980~90년대 총사업비 · 공공 투자액 · 양허 사용료 금액은 확인된 자료를 찾지 못했습니다.",
  "1976년 바르셀로나 광역 일반계획 (PGM) 상의 정확한 원래 용도지구 기호는 확인된 자료를 찾지 못했습니다.",
  "특별계획의 용적률 · 연면적 수치와 11개 사업 구역별 면적은 확인된 자료를 찾지 못했습니다.",
  "총사업비 · 공공 투자액과 양허 기간 · 임대 조건은 확인된 자료를 찾지 못했습니다.",
  "사업에 참여한 시민단체 · 주민협의회는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Time Out Market Barcelona officially open from 5 July 2024 — Time Out", "u": "https://www.timeout.com/about/latest-news/time-out-market-is-officially-open-from-5-july-2024-bringing-the-best-of-the-city-together-under-one-roof-070424"},
  {"t": "World Trade Center Barcelona — Viquipèdia", "u": "https://ca.wikipedia.org/wiki/World_Trade_Center_Barcelona"},
  {"t": "Klépierre invertirá 15 millones de euros en el reposicionamiento de Maremagnum — EjePrime (2023.2)", "u": "https://www.ejeprime.com/comercial/klepierre-invertira-15-millones-de-euros-en-el-reposicionamiento-de-maremagnum"},
  {"t": "Centro comercial Maremagnum — historia (Klépierre)", "u": "https://maremagnum.klepierre.es/historia"},
  {"t": "Transformació Port Vell — Port Vell Barcelona (카탈루냐어)", "u": "https://portvellbcn.cat/ca/transformacio-portvell/"},
  {"t": "Història del Port Vell — Port de Barcelona (카탈루냐어 공식)", "u": "https://www.portdebarcelona.cat/ca/port-vell/historia-del-port-vell"},
  {"t": "Port Vell — El Port Ciutat de Barcelona (공식 사이트 · 입주 목록)", "u": "https://portvellbcn.cat/ca/"},
  {"t": "History of Port Vell — Port de Barcelona", "u": "https://www.portdebarcelona.cat/en/port-vell/history-port-vell"},
  {"t": "El nou Port Vell — Ara, Barcelona 92 (카탈루냐어)", "u": "https://interactius.ara.cat/barcelona-92/cronica/el-nou-port-vell"},
  {"t": "25 anys de la rambla de Mar — betevé (카탈루냐어)", "u": "https://beteve.cat/societat/25-anys-rambla-mar-port-vell-maremagnum/"},
  {"t": "BOE-A-2000-827 Orden de 30 de diciembre de 1999, Plan de utilización de los espacios portuarios del puerto de Barcelona", "u": "https://www.boe.es/diario_boe/txt.php?id=BOE-A-2000-827"},
  {"t": "BOE-A-1992-26146 Ley 27/1992, de 24 de noviembre, de Puertos del Estado y de la Marina Mercante", "u": "https://www.boe.es/buscar/doc.php?id=BOE-A-1992-26146"},
  {"t": "Port Vell de Barcelona — Viquipèdia", "u": "https://ca.wikipedia.org/wiki/Port_Vell_de_Barcelona"},
  {"t": "Maremàgnum — Viquipèdia", "u": "https://ca.wikipedia.org/wiki/Maremàgnum"},
  {"t": "Palau de Mar — Viquipèdia", "u": "https://ca.wikipedia.org/wiki/Palau_de_Mar"},
  {"t": "Aquàrium de Barcelona — Viquipèdia", "u": "https://ca.wikipedia.org/wiki/Aquàrium_de_Barcelona"},
  {"t": "Port Vell — Wikipedia", "u": "https://en.wikipedia.org/wiki/Port_Vell"},
 ],
},

"pearl-district": {
 "spec": [
  ["위치", "미국 오리건주 포틀랜드 도심 북쪽 — 웨스트 번사이드 (W Burnside) ~ 윌래밋강, 노스웨스트 브로드웨이 ~ 405번 고속도로 사이"],
  ["면적", "약 0.47 제곱마일 (1.21㎢) — 그 가운데 핵심인 옛 호이트 스트리트 철도 조차장 (Hoyt Street Railyards) 개발 협약 부지 34에이커 (약 13.8ha)"],
  ["기간", "1980년대 중반 공업 → 혼합 용도 재분류 → 1988년 중심시가지 계획 → 1992 · 1994 리버 디스트릭트 비전 · 개발계획 → 1997년 개발 협약 → 1998년 도시재생 구역 → 2001년 노면전차 → 2002 · 2005 · 2013 공원"],
  ["원래 용도", "벌링턴 노던 (Burlington Northern) 철도 조차장 · 창고 · 경공업, 로브조이 고가 진입로 (Lovejoy Viaduct)"],
  ["변경 용도", "창고 개조 로프트 · 고밀 아파트 · 콘도 · 갤러리 · 식당 · 상점 · 사무 (브루어리 블록스) · 공원 3곳 (제이미슨 스퀘어 · 태너 스프링스 · 더 필즈)"],
  ["원래 용도지구", "일반공업 (IG1) · 중공업 (IH)"],
  ["변경 용도지구", "중심 고용 (EX, Central Employment) · 중심 주거 (RX) · 중심 상업 (CX) + 디자인 오버레이 (d) — 중심시가지 계획지구 (Central City Plan District) 안"],
  ["계획 규모", "리버 디스트릭트 개발계획: 기반시설 투자 1억 5,000만 달러로 개발 7억 5,000만 달러 유도 — 주택 약 5,500호 · 사무 150만 ft² · 상업 50만 ft²"],
  ["인구", "1990년 약 1,500명 → 2000년 1,113명(인구조사 구역 기준) → 2010년 5,997명 → 2020년 11,019명"],
 ],
 "from": "철도 조차장 · 창고 · 경공업", "to": "고밀 주거 · 갤러리 · 상업 · 공원 (노면전차 연결)",
 "zoneFrom": "일반 · 중공업 (IG1 · IH)", "zoneTo": "중심 고용 · 중심 주거 (EX · RX, 디자인 오버레이 d) + 리버 디스트릭트 도시재생 구역 (URA)",
 "tenants": [
  ["상업 · 대형 서점", "파월스 북스 시티 오브 북스 (Powell's City of Books)", "1980년 이전 · W 번사이드 ~ NW 커치, NW 10~11번가 한 블록 전체 · 6,300㎡ (6만 8천 ft²) · 1999년 확장 — \"세계 최대의 독립 신 · 중고 서점\"을 표방", "https://en.wikipedia.org/wiki/Powell%27s_Books"],
  ["상업 · 대형 식료품", "홀푸드 마켓 (Whole Foods Market) — 브루어리 블록스 1블록", "4층 15만 8천 ft² 건물 · 1층 상업 5만 395ft² (현재 영업 여부 미확인)", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["문화 · 공연장", "게르딩 극장 앳 디 아머리 (Gerding Theater at the Armory) — 포틀랜드 센터 스테이지 (Portland Center Stage)", "1891년 무기고를 공연예술센터로 개조 · 5만 6천 ft² · 2006년 완공 · LEED 플래티넘 (브루어리 블록스 3블록)", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["업무 · 오피스", "브루하우스 · 셀러 빌딩 (브루어리 블록스 2블록)", "옛 맥주 공장 건물 + 10층 신축 사무동 · 24만 8천 ft² · A급 사무실 · 1층 상업 · LEED 골드", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["업무 · 금융 사무", "M 파이낸셜 (M Financial) — 브루어리 블록스 4블록", "사무 건물 · LEED 골드 · 외벽 태양광", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["주거 · 콘도", "더 헨리 (The Henry) — 브루어리 블록스 3블록", "15층 · 콘도 123호 · 1층 상업 · LEED 골드", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["주거 · 임대", "더 루이자 (The Louisa) — 브루어리 블록스 5블록", "주거 건물 · LEED 골드 · 10년 재산세 감면 (수익률 10% 상한 조건)", "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"],
  ["상업 · 식음", "헨리스 12번가 태번 (Henry's 12th Street Tavern)", "2004년 브루하우스 건물에 개업 → 2019년 폐업 (2004~2019, 철수)", "https://en.wikipedia.org/wiki/Brewery_Blocks"],
 ],
 "timeline": [
  ["1972", "포틀랜드 도심 계획 (Downtown Plan)"],
  ["1980년대 중반", "공업에서 혼합 용도로 재분류 — 창고를 로프트 · 갤러리로 바꾸기 시작"],
  ["1987.3", "「펄 디스트릭트」라는 이름이 처음 인쇄물에 등장 (갤러리 운영자 토머스 오거스틴이 붙인 이름)"],
  ["1988", "중심시가지 계획 (Central City Plan) — 이 지역을 혼합 용도 중심지로 규정"],
  ["1992", "「리버 디스트릭트 비전 (A Vision for Portland's North Downtown: The River District)」 시의회 제출"],
  ["1994", "리버 디스트릭트 운영위원회가 개발계획 완성 · 시의회 「리버 디스트릭트 주택 실행 전략」 채택 · 호이트 스트리트 프로퍼티스가 철도 부지 매입"],
  ["1995.7", "리버 디스트릭트 계획, 중심시가지 계획에 반영 (조례 168702호)"],
  ["1997.9.8", "포틀랜드 시 — 호이트 스트리트 프로퍼티스 개발 협약 (34에이커) · 로브조이 고가 철거 합의"],
  ["1998.9.25", "리버 디스트릭트 도시재생 계획 (River District Urban Renewal Plan) 채택 — 조세증가분 금융 (TIF) 도입"],
  ["1999~2000", "로브조이 고가 철거 · 재건 (1,300만 달러) · 2000.1 게르딩 에들런, 옛 블리츠-바인하르트 맥주 공장 블록 매입"],
  ["2001.7.20", "포틀랜드 스트리트카 (노면전차) 개통 — 펄 디스트릭트 관통"],
  ["2001.10", "펄 디스트릭트 개발계획 (Pearl District Development Plan) 시의회 승인"],
  ["2002", "제이미슨 스퀘어 (Jamison Square) 개장"],
  ["2005", "태너 스프링스 공원 (Tanner Springs Park) 개장"],
  ["2009 · 현재", "리버 디스트릭트 도시재생 구역 확대 (올드타운/차이나타운 일부) → 이후 신규 TIF 를 마치고 「종료 구역」이 됨 (프로스퍼 포틀랜드)"],
  ["2013", "더 필즈 공원 (The Fields Park) 개장"],
 ],
 "problem": [
  "1980년대까지 철도 조차장 · 창고 · 공장이 대부분 버려져, 도심 바로 옆에 넓은 저이용 공업지가 남아 있었습니다.",
  "로브조이 고가 진입로가 지역을 가로막는 \"장벽이자 쇠퇴 요인 (barrier and blighting influence)\"이었습니다 (1998 도시재생 계획).",
  "철도 부지에는 납 · 크레오소트 오염이 있었고, 당시 조닝은 주택을 에이커당 15호 정도만 요구했습니다.",
  "포틀랜드의 도시성장경계 (UGB) 정책 아래 도심 안에서 주택 · 일자리를 더 수용할 땅이 필요했습니다.",
 ],
 "overview": [
  "펄 디스트릭트는 민간 개발자 · 주민이 먼저 만든 비전(1992 리버 디스트릭트 비전, 1994 개발계획)을 시가 정책으로 받아들이고, 도시재생 구역 (URA)의 조세증가분 금융 (TIF)으로 기반시설을 대는 방식으로 재생되었습니다.",
  "핵심은 1997년 포틀랜드 시 (포틀랜드 개발위원회, PDC)와 철도 부지 소유자 호이트 스트리트 프로퍼티스 (HSP)의 개발 협약입니다. 시가 로브조이 고가 철거 · 노면전차 · 공원을 만들 때마다 HSP 가 지어야 할 최소 주택 밀도가 에이커당 15호 → 87호 → 109호 → 131호로 단계적으로 올라가고, 주택의 15% 는 지역 중위소득 0~50%, 20% 는 51~80% 가구에 맞는 저렴주택으로 짓게 했습니다.",
  "2001년 개통한 포틀랜드 스트리트카와 공원 3곳이 주거 수요를 만들었고, 옛 블리츠-바인하르트 맥주 공장은 게르딩 에들런이 매입해 (2000년, 1,975만 달러) 맥주 공장 건물 · 무기고 · 자동차 판매점 건물을 보존한 「브루어리 블록스」 복합 개발로 바뀌었습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "피터 워커 (Peter Walker) · 피터 워커 앤 파트너스 (조경)", "제이미슨 스퀘어 설계 (2002 개장, 설계비 47만 7,810달러)"],
  ["주관 기관", "포틀랜드 시 (City of Portland) · 시의회", "중심시가지 계획 · 도시재생 계획 · 개발 협약 승인"],
  ["사업 시행", "포틀랜드 개발위원회 (Portland Development Commission, PDC — 현 Prosper Portland, 시 도시재생기관)", "도시재생 구역 운영 · TIF 채권 발행 · 개발 협약 체결"],
  ["관련 기관", "포틀랜드 교통국 (PBOT) · 포틀랜드 스트리트카", "노면전차 소유 · 운영"],
  ["관련 기관", "포틀랜드 도시계획위원회 · 계획지속가능국 (BPS)", "조닝 · 디자인 심의 · 역사자원 보존"],
  ["민간 · 토지 소유", "호이트 스트리트 프로퍼티스 (Hoyt Street Properties, HSP)", "옛 벌링턴 노던 조차장 34에이커 개발 · 협약 이행"],
  ["민간", "게르딩 에들런 (Gerding Edlen) · 호머 윌리엄스 · 패트릭 프렌더개스트 등", "브루어리 블록스 · 초기 로프트 개발"],
  ["시민 · 위원회", "리버 디스트릭트 운영위원회 (River District Steering Committee)", "1994 개발계획 수립 — 시민 · 상인 · 토지 소유자 대표"],
  ["시민단체", "펄 디스트릭트 주민협의회 (Pearl District Neighborhood Association, PDNA)", "디자인 심의 협의 · 역사 자원 선정 의견 · 도시재생 구역 감시"],
 ],
 "laws": [
  ["오리건주 도시재생법 (Oregon Revised Statutes Chapter 457) · 오리건 헌법 제9조 1c", "도시재생 계획 수립과 조세증가분 금융 (ORS 457.420~457.450)의 근거"],
  ["중심시가지 계획 (Central City Plan, 1988) — 정책 17 리버 디스트릭트", "이 지역을 혼합 용도 중심지로 규정, 리버 디스트릭트 개발계획 이행을 정책화 (1995년 조례 168702호)"],
  ["리버 디스트릭트 비전 (A Vision for Portland's North Downtown: The River District, 1992) · 리버 디스트릭트 개발계획 (River District Development Plan, 1994)", "민간 · 시민 운영위원회가 만든 비전과 개발계획 — 기반시설 1억 5,000만 달러로 개발 7억 5,000만 달러 · 주택 약 5,500호 목표"],
  ["리버 디스트릭트 계획 실행표 (River District Plan Action Charts, 1995.4.12, 결의 35384호)", "구속력 없는 시 정책 — 실행 사업 · 프로그램 목록과 담당 기관", "https://www.portland.gov/policies/environment-built/community-neighborhood-planning/enb-1138-river-district-plan-action"],
  ["리버 디스트릭트 주택 실행 전략 (1994)", "신규 주택 소득계층 목표 — 극저 · 저소득 15~25%, 중간 이하 20~30%, 중산 · 상위 50~60% (총 5,555호 목표)"],
  ["리버 디스트릭트 도시재생 계획 (River District Urban Renewal Plan, 1998.9.25)", "최대 부채 한도 2억 2,478만 350달러, 신규 부채는 2020년 10월 1일까지 — 공공 개선 · 주택 지원 · 토지 취득 · 공익 수용 권한", "https://prosperportland.us/wp-content/uploads/2016/07/River-District-Original-URA-Plan.pdf"],
  ["포틀랜드 시 — HSP 개발 협약 (1997 체결)", "공공 기반시설 이행과 연동한 최소 주택 밀도 · 저렴주택 비율 의무"],
  ["펄 디스트릭트 개발계획 (Pearl District Development Plan: A Future Vision for a Neighborhood in Transition, 2001.10)", "26명 운영위원회가 1년간 작성, 시의회 승인 — 주거 · 교통 · 건축환경 · 공원 목표", "https://prosperportland.us/wp-content/uploads/2016/07/Pearl-District-Development-Plan-Appendix-1.pdf"],
  ["리버 디스트릭트 디자인 지침 (River District Design Guidelines, 1998)", "리버 디스트릭트 디자인 심의 기준"],
 ],
 "lawsNote": ["규제완화의 핵심은 공업지 (IG1 · IH)를 중심 고용 (EX) · 중심 주거 (RX) 같은 혼합 용도로 바꾼 것입니다. 중심시가지 계획지구 안의 EX 지역은 최소 주차 의무가 없고 최대 주차 비율만 있어 개발자가 주차장 대신 주거 · 상업 면적을 지을 수 있습니다. 동시에 \"완화\"만 하지 않고, 개발 협약으로 최소 밀도와 저렴주택 비율을 \"의무\"로 걸었다는 점이 특징입니다."],
 "tools": [
  ["조세증가분 금융 (TIF)", "도시재생 구역에서 늘어난 재산세로 채권을 발행해 고가 철거 · 노면전차 · 공원 · 저렴주택 재원 — 1998년 구역 지정 당시 평가액 4억 4,600만 달러 → 2014년 22억 달러"],
  ["단계적 밀도 의무 (개발 협약)", "최소 주택 밀도 15호/에이커 → 고가 철거 뒤 87호 → 노면전차 완공 뒤 109호 → 첫 공원 (제이미슨 스퀘어) 완공 뒤 131호"],
  ["저렴주택 의무", "HSP 주택의 15% 는 중위소득 0~50%, 20% 는 51~80% 가구용 — 합계 35% (실제 달성은 약 30%)"],
  ["공공 기반시설", "로브조이 고가 철거 · 재건 1,300만 달러 (2001), 제이미슨 스퀘어 260만 달러 (2000), 태너 크리크 공원 280만 달러 (2001), 더 필즈 공원 610만 달러 (2013)"],
  ["노면전차 재원", "첫 노선 총 5,700만 달러 (연방 500만 달러) — 3개 도시재생 구역의 TIF 채권 + 지역개선지구 (LID) 부담금"],
  ["용적률 · 보너스", "펄 디스트릭트 용적률 9:1 ~ 2:1 (평균 약 5:1), 주거 · 녹색지붕 · 용적 이전 등에 용적률 보너스"],
  ["주차 규제", "최소 주차 의무 없음 · 최대 주차 비율 (주거 1.5대/호 등)"],
 ],
 "zoning": [
  ["지정", "리버 디스트릭트 도시재생 구역 (River District URA) — 1998년 6월 설립 · 9월 25일 계획 문서, 처음 314.8에이커 (약 127ha) → 2009년 올드타운/차이나타운 일부 편입 확대, 현재 「종료 구역 (closed district)」 — (펄 디스트릭트 · 태너 베이슨 · 터미널 원 · 공업 보호구역 · 유니언역/올드타운 포함)"],
  ["관리 주체 · 방식", "포틀랜드 개발위원회 (현 프로스퍼 포틀랜드)가 TIF 로 사업 시행, 디자인 심의는 주민협의회 협의를 거침"],
  ["보존 관리", "NW 13번가 일대 약 8블록이 국가 사적 역사지구 (National Register Historic District) — 13번가 일대 별도 높이 제한, 브루어리 블록스의 역사 건물 3동은 시 역사자원 프로그램으로 보호"],
  ["공원", "노스 파크 블록스 3.11에이커 · 제이미슨 스퀘어 0.94 · 태너 스프링스 0.92 · 더 필즈 3.2 — 합계 8.17에이커"],
 ],
 "result": [
  "프로스퍼 포틀랜드 집계 — 리버 디스트릭트 구역 평가액이 1999-2000 회계연도 이후 17억 달러 늘었고, 개발 비용의 90% 를 민간이 부담했습니다.",
  "인구 1990년 약 1,500명 → 2010년 5,997명 → 2020년 11,019명.",
  "노면전차 노선 400m 안에서 1998~2015년 2,300만 ft² · 주택 약 1만 8,000호 개발 (노선 전체 기준).",
  "리버 디스트릭트 구역 평가액 1998년 4억 4,600만 달러 → 2014년 22억 달러.",
  "한계 — HSP 는 저렴주택 35% 의무를 다 채우지 못했습니다 (약 30%).",
 ],
 "lesson": [
  "\"공공이 기반시설을 하나 이행할 때마다 민간의 최소 밀도를 올리는\" 연동형 개발 협약은, 한국 산단 재생에서 공공 투자와 민간 개발 의무를 묶는 계약 모델로 참고할 만합니다.",
  "조세증가분 금융으로 미래 세수를 담보해 기반시설을 먼저 놓는 방식.",
  "고가 도로 철거 · 노면전차처럼 지역을 끊던 교통 시설을 바꾸는 것이 재생의 전환점이었습니다.",
  "저렴주택 비율을 계약으로 정해도 이행 감시가 약하면 목표에 못 미칠 수 있다는 점.",
 ],
 "funding": [
  ["조세증가분 금융 (TIF)", "리버 디스트릭트 도시재생 계획 (1998) — 최대 부채 한도 2억 2,478만 350달러, 포틀랜드 개발위원회가 TIF 채권 발행", "https://prosperportland.us/wp-content/uploads/2016/07/River-District-Original-URA-Plan.pdf"],
  ["TIF — 저렴주택 지원", "계획상 약 5,300만 달러 (1998년 달러): 극저 · 저소득 823호 약 2,469만 달러, 중간 소득 1,028호 약 1,850만 5천 달러, 저소득 주택 보존 · 대체 약 1,200만 달러", "https://prosperportland.us/wp-content/uploads/2016/07/River-District-Original-URA-Plan.pdf"],
  ["TIF · 시 재정 — 개발 협약 공공사업", "로브조이 고가 철거 · 재건 1,300만 달러 (2001) · 로브조이 기둥 복원 46만 달러 · 제이미슨 스퀘어 260만 달러 (2000) · 태너 크리크 공원 280만 달러 (2001) · 더 필즈 공원 610만 달러 (2013)"],
  ["연방 · 시 · 지역개선지구 (LID)", "포틀랜드 스트리트카 첫 노선 5,700만 달러 — 연방 500만 달러, 나머지는 지역 재원 (노스 마카담 · 사우스 파크 블록스 · 리버 디스트릭트 3개 구역 TIF 채권 + 지역개선지구 부담금)"],
  ["민간 투자", "호이트 스트리트 프로퍼티스 — 옛 철도 부지 개발 · 저렴주택 의무 / 게르딩 에들런 — 2000년 옛 맥주 공장 블록 1,975만 달러에 매입 (브루어리 블록스)"],
  ["세제 · 대출 · 보조금", "민간 개발에 세제 인센티브 · 세액공제 · 대출 · 보조금 활용 (개별 금액 미확인)"],
 ],
 "famous": [
  "포틀랜드 스트리트카 (2001)는 \"2차 대전 이후 미국에서 처음 새로 만든 노면전차 체계\"로, 2010년대 미국 여러 도시의 노면전차 도입 흐름에 영향을 주었다고 평가됩니다 (영어 위키).",
  "공공 기반시설 이행에 맞춰 민간의 최소 주택 밀도를 15 → 87 → 109 → 131호/에이커로 올리는 1997년 개발 협약 — 이후 포틀랜드 사우스 워터프런트 협약의 모델이 되었습니다 (Energy Innovation 사례연구).",
  "브루어리 블록스 5개 블록이 모두 LEED 인증 (게르딩 극장 LEED 플래티넘 등) — 녹색 복합개발의 사례로 소개됩니다.",
  "노면전차 노선 400m 안에서 1998~2015년 주택 약 1만 8,000호 · 2,300만 ft² 개발 — 대중교통 지향 개발 (TOD)의 대표 사례로 인용됩니다.",
 ],
 "operation": [
  ["운영 주체", "단일 운영 주체 없음 — 일반 시가지로 포틀랜드 시가 관리, 도시재생 사업은 포틀랜드 개발위원회 (현 프로스퍼 포틀랜드)가 TIF 로 시행"],
  ["지역 재원 구조 (TIF)", "리버 디스트릭트 도시재생 계획 — 신규 부채는 2020년 10월 1일 또는 최대 부채 한도 (2억 2,478만 350달러) 도달 중 먼저 오는 때까지", "https://prosperportland.us/wp-content/uploads/2016/07/River-District-Original-URA-Plan.pdf"],
  ["교통 운영", "포틀랜드 스트리트카는 포틀랜드 교통국 (PBOT) 소유 — 건설 재원에 지역개선지구 (LID) 부담금 포함, 노선 단계마다 새 LID 설정"],
  ["교통 운영 예산 (노면전차 전체)", "포틀랜드 스트리트카 운영 예산 2014 회계연도 약 975만 달러 · 인력 70명 (TriMet 51 · PBOT 16 · PSI 3) — 시 감사관 보고서 (2014.12)", "https://portland.gov/sites/default/files/2021/451b-streetcar-published.pdf"],
  ["운영 재원 구성 (노면전차 전체)", "시가 TriMet 에 운영 인력비를 상환하는 계약 수입 2024 회계연도 970만 달러 · 2025 회계연도 1,040만 달러 (TriMet 재무보고) · 2006년부터 시 주차요금 수입 연 30만 달러 추가 배정 (2004 시의회 정책) · 후원 수입 2014 회계연도 실적 34만 4,484달러", "https://trimet.org/about/pdf/finance/fy25-trimet-financials.pdf"],
  ["지역 관리 · 참여", "펄 디스트릭트 주민협의회 (PDNA) — 시 주민참여국이 조정하는 95개 주민협의회의 하나, 디자인 심의 협의 · 도시재생 구역 감시"],
  ["운영 성과", "인구 2010년 5,997명 → 2020년 11,019명 · 주민 약 6,934명 · 일자리 약 1만 1,932개 (직주 비율 1.72, 사례연구 시점)"],
  ["운영상 문제", "저렴주택 의무 35% 가운데 약 30% 만 달성 — 이후 개발로 비율이 더 낮아질 것이라는 주택국 우려"],
 ],
 "operationNote": [
  "펄 디스트릭트는 하나의 운영 조직이 수익사업을 하는 곳이 아니라, 도시재생 구역의 조세증가분 (늘어난 재산세)으로 공공 투자를 회수하는 구조입니다. 노면전차는 시 교통국이 소유하고 지역개선지구 부담금을 건설 재원으로 썼으며, 주민협의회가 디자인 심의와 도시재생 감시에 참여합니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (홀푸드 등 브루어리 블록스 현 임차인의 현재 영업 여부, 대형 테크 · 업무 입주 기업)는 확인된 자료를 찾지 못했습니다.",
  "펄 디스트릭트 자체의 지역 관리 재원 (BID · 관리비)과 노면전차의 요금 수입 비율 (farebox recovery)은 확인된 자료를 찾지 못했습니다.",
  "리버 디스트릭트 개발계획 · 펄 디스트릭트 개발계획의 마스터플랜을 맡은 도시계획가 · 건축가와 브루어리 블록스 설계자는 확인된 자료를 찾지 못했습니다.",
  "1980년대 중반 혼합 용도 재분류의 정확한 연도 · 조례 번호는 확인된 자료를 찾지 못했습니다.",
  "개발 협약에 따른 HSP 의 공원 부지 기부 면적 · 기타 공공기여의 세부 수치는 확인된 자료를 찾지 못했습니다.",
  "NW 13번가 역사지구의 지정 연도는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "River District — Prosper Portland", "u": "https://prosperportland.us/our-work/river-district/"},
  {"t": "Powell's Books — Wikipedia", "u": "https://en.wikipedia.org/wiki/Powell%27s_Books"},
  {"t": "Brewery Blocks — Wikipedia", "u": "https://en.wikipedia.org/wiki/Brewery_Blocks"},
  {"t": "Portland Streetcar: City transit targets unmet, better performance management needed — Portland City Auditor (2014.12)", "u": "https://portland.gov/sites/default/files/2021/451b-streetcar-published.pdf"},
  {"t": "TriMet Annual Comprehensive Financial Report FY2025", "u": "https://trimet.org/about/pdf/finance/fy25-trimet-financials.pdf"},
  {"t": "River District Urban Renewal Plan, September 25, 1998 — Portland Development Commission (PDF)", "u": "https://prosperportland.us/wp-content/uploads/2016/07/River-District-Original-URA-Plan.pdf"},
  {"t": "Pearl District Development Plan — Appendix, October 2001 (PDF)", "u": "https://prosperportland.us/wp-content/uploads/2016/07/Pearl-District-Development-Plan-Appendix-1.pdf"},
  {"t": "ENB-11.38 River District Plan Action Charts — City of Portland", "u": "https://www.portland.gov/policies/environment-built/community-neighborhood-planning/enb-1138-river-district-plan-action"},
  {"t": "The Pearl District: An Urban Development Case Study — Energy Innovation (PDF)", "u": "https://energyinnovation.org/wp-content/uploads/Pearl-District-Case-Study.pdf"},
  {"t": "Sept. 8, 1997: The city agrees to tear down the old viaduct and sell the rail yards — Willamette Week", "u": "https://www.wweek.com/portland/article-23434-sept-8-1997-the-city-agrees-to-tear-down-the-old-viaduct-and-sell-the-rail-yards.html"},
  {"t": "Pearl District, Portland, Oregon — Wikipedia", "u": "https://en.wikipedia.org/wiki/Pearl_District,_Portland,_Oregon"},
  {"t": "Portland Streetcar — Wikipedia", "u": "https://en.wikipedia.org/wiki/Portland_Streetcar"},
 ],
},

"lowell-mills": {
 "spec": [
  ["위치", "미국 매사추세츠주 로웰 — 메리맥강 (Merrimack River)과 콩코드강 합류부, 보스턴 북서쪽"],
  ["면적", "로웰 국립역사공원 141에이커 (57ha) + 그 둘레 로웰 역사보존지구 (부동산 800여 필지) · 동력 운하 5.6마일 (약 9km)"],
  ["기간", "1966년 모델 시티 사업 → 1972년 시의회 「역사공원 구상」 결의 → 1974년 주립 헤리티지 공원 → 1975년 연방 운하지구 위원회 → 1978년 국립역사공원 → 1995년 보존위원회 해산 → 2000년대 공장 주거 전환 계속"],
  ["원래 용도", "1820년대 보스턴 어소시에이츠가 세운 미국 최초의 대규모 계획 방직 도시 — 운하 수력으로 돌리는 면방직 공장 · 여공 기숙사"],
  ["변경 용도", "국립역사공원 (부트 면방직 박물관 · 방문자센터 · 모건 문화센터) · 공장 개조 아파트 (저소득 · 예술가 주택 포함) · 사무 · 매사추세츠 대학 로웰 · 예술가 스튜디오 · 관광 전차"],
  ["원래 용도지구", "공업 (방직 공장 · 운하)"],
  ["변경 용도지구", "로웰 국립역사공원 (Lowell National Historical Park) + 로웰 역사보존지구 (Lowell Historic Preservation District) — 연방법으로 지정"],
  ["인구", "1920년 약 11만 2,759명 (정점) → 1980년 9만 2,418명 → 2020년 11만 5,554명"],
 ],
 "from": "방직 공장 · 운하 · 노동자 기숙사", "to": "국립역사공원 · 공장 개조 주거 · 사무 · 대학",
 "zoneFrom": "공업 (방직)", "zoneTo": "국립역사공원 · 로웰 역사보존지구 (연방법, 1978)",
 "tenants": [
  ["문화 · 박물관", "부트 면방직 박물관 (Boott Cotton Mills Museum) — 국립공원청", "부트 공장 6호동 · 1920년대식 직조실 재현 · 유료 (성인 6달러)", "https://www.nps.gov/lowe/planyourvisit/fees.htm"],
  ["문화 · 교육", "송거스 산업사 센터 (Tsongas Industrial History Center)", "부트 공장 6호동 · 학생 교육 프로그램 (국립공원청 · UMass Lowell 협력)", "https://en.wikipedia.org/wiki/Boott_Cotton_Mills"],
  ["문화 · 공공시설", "로웰 국립역사공원 방문자센터", "마켓 밀스 (1982년 개조) — 저소득 아파트 230호와 한 단지", "https://www.nps.gov/lowe/learn/historyculture/upload/LHPC-FindingAid-2012-UPDATED.pdf"],
  ["문화 · 대학 연구 · 전시", "모건 문화센터 (Mogan Cultural Center) — UMass Lowell 특별 소장 자료관 · 뉴잉글랜드 민속생활센터", "옛 부트 공장 기숙사 — 여공 · 이민 · 노동사 전시", "https://www.nps.gov/lowe/learn/historyculture/upload/LHPC-FindingAid-2012-UPDATED.pdf"],
  ["첨단산업 · 앵커 기업", "왕 연구소 (Wang Laboratories)", "1970년대 로웰 본사 — 부트 공장 6호동을 보존위원회 지원으로 개조해 사용, 뒤에 위원회에 매각 → 공원에 기부 · 1992년 파산 (철수)", "https://www.nps.gov/lowe/learn/historyculture/upload/LHPC-FindingAid-2012-UPDATED.pdf"],
  ["문화 · 갤러리 · 미디어", "어 브러시 위드 히스토리 (A Brush with History) 갤러리 · 로웰 텔레커뮤니케이션 코퍼레이션 (Lowell Telecommunications Corporation)", "마켓 밀스 1층 — 미술 갤러리 · 작업실, 지역 방송 · 미디어 센터, 푸드코트", "https://www.nps.gov/lowe/learn/historyculture/upload/LHPC-FindingAid-2012-UPDATED.pdf"],
  ["문화 · 예술가 작업실", "웨스턴 애비뉴 스튜디오 (Western Avenue Studios)", "옛 매사추세츠 모헤어 공장 (1906) — 작업실 143개 · 저렴 작업 · 주거 겸용 50호", "https://www.nps.gov/lowe/planyourvisit/redevelopment-rove.htm"],
  ["주거 · 예술가 저렴주택", "애플턴 밀스 (Appleton Mills) — 트리니티 파이낸셜 (Trinity Financial)", "2011년 · 130호 로프트 · 1층 갤러리 — 해밀턴 운하 지구 1단계", "https://www.taxcreditadvisor.com/articles/leveraging-on-history-former-textile-mill-in-lowell-being-rehabilitated-into-artist-housing/"],
  ["주거 · 아파트", "더튼 얀 빌딩 (Dutton Yarn Building) 아파트", "2003~2004년 135호 (역사보존 세액공제 1,100만 달러)", "https://www.nps.gov/lowe/planyourvisit/redevelopment-rove.htm"],
  ["문화 · 교통", "국립 노면전차 박물관 (National Streetcar Museum) 정류장 · 로웰 헤리티지 트롤리", "부트 공장 단지 — 관광 전차 (1984년 운행 시작)", "https://en.wikipedia.org/wiki/Boott_Cotton_Mills"],
 ],
 "timeline": [
  ["1823 · 1826", "메리맥 제조회사 설립 · 로웰 타운 설립 (1836년 시 승격)"],
  ["1835", "부트 면방직 공장 (Boott Cotton Mills) 건립"],
  ["1920년대~1950년대", "방직업이 남부로 이전 — 1931년 「불황의 공업 사막」으로 묘사, 2차 대전 뒤 마지막 방직 공장들 폐쇄 (부트 공장 1958년 가동 중단)"],
  ["1966", "패트릭 모건 (Patrick Mogan) 등이 존슨 정부의 모델 시티 (Model Cities) 사업 자금 확보 — 유산을 통한 도시 재생 구상"],
  ["1972", "로웰 시의회, 「역사공원 구상」을 미래 도시개발의 중심으로 삼는 결의 · 첫 역사지구 (Mill and Canal District) 승인"],
  ["1974", "매사추세츠주, 로웰 헤리티지 주립공원 (Lowell Heritage State Park) 조성"],
  ["1975.1.4", "연방 「로웰 역사 운하지구 위원회 (Lowell Historic Canal District Commission)」 설치법 — 위원회 보고서(일명 「브라운 북」)가 국립공원 청사진이 됨"],
  ["1978.6.5", "공법 95-290 — 로웰 국립역사공원 · 로웰 역사보존지구 · 로웰 역사보존위원회 설치 (카터 대통령 서명, 폴 송거스 의원 발의)"],
  ["1980", "보존위원회 보존계획 (Preservation Plan) 수립"],
  ["1982", "마켓 밀스 (Market Mills) — 저소득층 아파트 230호 + 공원 방문자센터로 개조 (보존위원회 첫 대형 사업)"],
  ["1983 · 1984", "보존 대출기금 설치 (1983) · 관광 전차 운행 시작 (1984)"],
  ["1989", "부트 공장 단지 재생 시작 (주 · 연방 지원) — 6호 공장은 왕 연구소 (Wang Laboratories) 사무용으로 개조 뒤 공원에 기부"],
  ["1992", "왕 연구소 파산 — 로웰 경제의 앵커 상실"],
  ["1995", "로웰 역사보존위원회 해산 (법정 존속기간 17년 만료) — 공원이 디자인 심의 · 운하길 사업 승계"],
  ["2003~2004 · 2009~2011", "더튼 얀 빌딩 135호 (역사보존 세액공제 1,100만 달러) · 애플턴 밀스 예술가 주택 130호 (해밀턴 운하 지구 1단계)"],
 ],
 "problem": [
  "1920년대부터 방직업이 남부로 옮겨 가며 공장이 차례로 문을 닫았고, 2차 대전 뒤 마지막 공장까지 폐쇄되면서 1950~60년대 로웰은 빈 공장과 실업이 가득한 도시가 되었습니다.",
  "인구는 1920년 약 11만 3천 명에서 1980년 9만 2천 명으로 줄었습니다.",
  "520만 ft² 에 이르는 빈 공장 공간을 어떻게 쓸지가 도시의 과제였습니다.",
  "공장 · 운하 같은 산업 유산이 방치 · 철거될 위험에 놓여, 유산을 지키면서 동시에 경제를 살릴 방법이 필요했습니다.",
 ],
 "overview": [
  "로웰은 \"도시 전체를 산업혁명의 교실로\" 만든 사례입니다. 교육자 패트릭 모건이 1960년대 말 모델 시티 사업으로 시작한 유산 기반 재생 구상이, 시의회 결의(1972) · 주립공원(1974) · 연방 운하지구 위원회(1975)를 거쳐 1978년 공법 95-290 으로 국립역사공원이 되었습니다.",
  "이 법은 공원 (국립공원청 관리)과 그 둘레의 역사보존지구 (800여 필지)를 함께 정하고, 15명으로 구성된 「로웰 역사보존위원회」를 두었습니다. 위원회는 공원과 달리 매년 예산을 받아 부동산을 임차 · 취득 (필요하면 수용)하고, 보존계획 · 디자인 기준을 정하며, 건물 소유자에게 보조금을, 로웰 개발금융공사를 통해 저리 대출을 주었습니다.",
  "위원회는 마켓 밀스 (저소득 주택 + 방문자센터), 부트 공장 기숙사 → 모건 문화센터, 관광 전차, 운하길 (Canalway) 같은 핵심 사업을 이끌었고, 이후 민간이 연방 · 주 역사건물 세액공제와 저소득주택 세액공제를 활용해 공장을 아파트 · 예술가 주택으로 바꾸었습니다.",
 ],
 "actors": [
  ["주관 기관", "미국 국립공원청 (National Park Service, NPS) · 내무부", "국립역사공원 관리 · 해석 · 부트 공장 6호 박물관 운영"],
  ["사업 시행", "로웰 역사보존위원회 (Lowell Historic Preservation Commission, 1978~1995)", "보존지구 관리 · 보존계획 · 디자인 기준 · 보조금 · 대출 · 부동산 취득 · 개발 사업"],
  ["관련 기관", "로웰 역사 운하지구 위원회 (Lowell Historic Canal District Commission, 1975)", "국립공원 청사진 보고서 (「브라운 북」) 작성"],
  ["관련 기관", "로웰 시 · 시의회", "1972 역사공원 결의 · 디자인 심의 공동 운영 · 위원 추천"],
  ["관련 기관", "매사추세츠주", "로웰 헤리티지 주립공원 (1974) · 위원 추천 · 주 세액공제"],
  ["금융", "로웰 개발금융공사 (Lowell Development and Financial Corporation, LDFC — 주법 chapter 844)", "보존 대출기금 (1983~) 운영 — 저리 대출"],
  ["대학", "매사추세츠 대학 로웰 (UMass Lowell)", "위원 추천 · 공장 건물 활용 · 모건 문화센터에 특별 소장 자료관"],
  ["시민 · 전문가", "패트릭 모건 (휴먼 서비스 코퍼레이션, 로웰 교육자) · 폴 송거스 의원", "유산 기반 재생 구상 · 법 제정 주도"],
  ["민간", "마켓 밀스 어소시에이츠 · 트리니티 파이낸셜 (애플턴 밀스) · 왕 연구소", "공장 개조 개발 · 입주"],
 ],
 "laws": [
  ["로웰 역사 운하지구 위원회 설치법 (1975.1.4 승인)", "역사 운하지구의 보존 · 활용 계획을 연방 위원회가 조사 · 보고"],
  ["공법 95-290 로웰 국립역사공원 설치법 (Public Law 95-290, 1978.6.5)", "국립역사공원 · 로웰 역사보존지구 · 로웰 역사보존위원회 설치 — 운하지구 위원회 보고서의 권고를 가능한 한 이행하도록 규정", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["같은 법 — 위원회 권한 (16 U.S.C. 410cc-31~35)", "보존계획 · 부동산 목록 (Index) 작성, 디자인 기준 제정, 소유자 보조금, LDFC 에 대한 대출, 부동산 취득 (공원 내 · 지정 부동산은 수용 가능, 내무장관 승인)", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["같은 법 — 예산 상한", "공원 취득 · 개발 1,850만 달러 이내, 위원회 보조금 · 대출 · 부동산 취득 · 교통 · 문화 사업 2,150만 달러 이내", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["같은 법 — 존속기간 개정 (Public Law 100-134, 1987)", "위원회 존속을 처음 10년 → 1978.6.5 부터 17년 (1995년)으로 연장 (16 U.S.C. 410cc-31(i))", "https://www.law.cornell.edu/uscode/text/16/410cc-31"],
  ["로웰 역사보존위원회 보존계획 (Preservation Plan, 1980) · 부동산 목록 (Index of Properties)", "보존지구 건물의 역사적 중요도 등급, 보조금 · 대출 프로그램, 시와 함께 만든 디자인 심의 기준"],
  ["연방 · 매사추세츠주 역사건물 재생 세액공제 · 저소득주택 세액공제 (LIHTC)", "공장 개조 주택 사업의 핵심 재원"],
 ],
 "lawsNote": ["로웰의 핵심은 \"규제 완화\"보다 \"연방법으로 만든 한시 공공 개발 조직\"입니다. 국립공원청은 기증으로만 땅을 얻을 수 있었지만, 보존위원회는 매년 예산을 받아 임차 · 매입 · 수용을 할 수 있었고, 디자인 기준을 지키는 조건으로 보조금 · 저리 대출을 주어 민간 투자를 끌어냈습니다. 보존지구 안의 개조는 위원회와 시가 함께 만든 디자인 심의 기준을 따라야 했습니다."],
 "tools": [
  ["보존 대출기금", "1983년 설치, 연방 75만 달러 → 비연방 투자 약 1억 3,030만 달러 유도 (연방 1달러당 173달러 이상) · 역사 건물 21개 사업에 약 250만 달러 대출"],
  ["건물 보조금", "부동산 목록에서 국가적 중요 건물로 분류된 건물에 수천 ~ 수십만 달러 보조 — 디자인 기준 준수 조건"],
  ["공공 선도 개발", "마켓 밀스 (1982, 저소득 아파트 230호 + 방문자센터) · 부트 기숙사 → 모건 문화센터 · 관광 전차 (1984) · 운하길"],
  ["세액공제", "더튼 얀 빌딩 135호에 역사보존 세액공제 1,100만 달러 · 애플턴 밀스 (총 6,400만 달러, 130호)에 역사 · 저소득주택 세액공제 지분 약 4,200만 달러 (사업비의 66%)"],
  ["부동산 취득 · 수용", "위원회는 공원 내 · 법정 지정 부동산을 협상 매입 노력 뒤 수용 가능 (시의회 협의 · 내무장관 승인)"],
  ["문화 프로그램 보조", "이민 · 노동사 · 민속 축제 · 공공 조각 프로그램에 연 1~2회 보조금"],
 ],
 "zoning": [
  ["지정", "로웰 국립역사공원 (141에이커) · 로웰 역사보존지구 (800여 필지) — 1978년 공법 95-290"],
  ["관리 주체 · 방식", "공원 구역은 국립공원청, 보존지구는 보존위원회 (1978~1995) → 해산 뒤 공원이 시와 함께 디자인 심의 참여"],
  ["보존 관리", "보존계획 (1980) · 부동산 중요도 목록 (Index of Properties) · 디자인 심의 기준 — 부트 공장 단지는 \"거의 온전히 남은\" 대표 공장 단지로 보존"],
  ["후속 지구", "해밀턴 운하 지구 (Hamilton Canal District) — 세 운하 합류부 15에이커, 주택 최대 725호 · 상업 42만 5,000ft² 계획 (2009 착공 1단계 애플턴 밀스)"],
  ["후속 지구 (시 계획)", "해밀턴 운하 혁신지구 (Hamilton Canal Innovation District) — 잭슨 · 애플턴 · 미들섹스 (JAM) 도시재생계획의 최대 사업, 15에이커 · 총 8억 달러 민관협력 · 신규 개발 약 200만 ft² · 연 약 400만 달러 신규 세수 예상 (로웰 시) — 로웰 플랜 · 국립역사공원 · 주민상인협회 (JAMBRA) 협력", "https://www.lowellma.gov/731/Hamilton-Canal-District-Plan"],
 ],
 "result": [
  "보존위원회 · 공원 · 시 · 주 · 민간 협력으로 400동 이상 재생, 빈 공장 공간 520만 ft² 가운데 88% 개조 완료 또는 진행 (2012 내무부 증언).",
  "공원 설립 이후 민간 투자 약 10억 달러 추산 (같은 증언).",
  "부트 공장 단지에서만 약 600호의 주택이 만들어졌습니다 (NPS).",
  "2011년 공원 방문객 52만 452명 · 인구는 1980년 9만 2천 명에서 2020년 11만 5천 명으로 회복.",
 ],
 "lesson": [
  "법으로 만든 \"한시 공공 개발 조직\"(보존위원회)이 보조금 · 대출 · 매입 권한을 갖고 먼저 움직여 민간 투자를 끌어낸 방식은, 한국 노후 산단 · 근대산업유산 재생 전담 기구 설계에 참고할 만합니다.",
  "적은 공공 대출기금 (75만 달러)을 회전시켜 큰 민간 투자를 이끈 지렛대 효과.",
  "역사건물 세액공제 + 저소득주택 세액공제의 결합으로 공장을 저렴 · 예술가 주택으로 바꾼 재원 구조.",
  "유산 보존을 \"관광\"만이 아니라 주거 · 교육 · 문화와 묶은 점 — 지역 교육자 · 시민 구상이 국가 정책이 된 과정.",
 ],
 "funding": [
  ["연방 재정 (공원)", "공법 95-290 — 공원 취득 · 개발 · 긴급 지원 예산 상한 1,850만 달러 (1978)", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["연방 재정 (보존위원회)", "보조금 · 대출 · 부동산 취득 · 교통 · 교육문화 사업 예산 상한 2,150만 달러 — 위원회는 매년 별도 예산을 받아 개발 사업 시행", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["보존 대출기금", "1983년 설치 — 연방 75만 달러를 로웰 개발금융공사 (LDFC)가 회전 대출, 비연방 투자 약 1억 3,030만 달러 유도 (연방 1달러당 173달러), 21개 사업에 약 250만 달러 대출", "https://www.doi.gov/ocl/hearings/112/S1215_30715"],
  ["보조금", "국가적 중요 건물에 수천 ~ 수십만 달러의 건물 보조금 · 문화 프로그램 보조금 (연 1~2회)"],
  ["역사보존 · 저소득주택 세액공제", "더튼 얀 빌딩 135호 (2003~2004) 역사보존 세액공제 1,100만 달러 · 애플턴 밀스 130호 총사업비 6,400만 달러 중 세액공제 지분 약 4,200만 달러 (66%, 메트라이프 매입) + 연방 HOME · 주 보조금 · 모기지"],
  ["민간 투자", "공원 설립 이후 민간 투자 약 10억 달러 추산 (2012 내무부 증언)", "https://www.doi.gov/ocl/hearings/112/S1215_30715"],
 ],
 "famous": [
  "미국 최초의 대규모 계획 산업도시 (\"가장 중요한 계획 산업도시\")를 도시 한가운데 그대로 국립역사공원으로 만든 사례입니다.",
  "보존 대출기금이 연방 1달러로 비연방 투자 173달러 이상을 끌어낸 지렛대 효과로 의회 증언에서 소개되었습니다 (2012).",
  "로웰 역사보존위원회는 관광 전차와 수변 개발로 전국적인 상을 받았고, 미국 · 영국의 견학단을 맞았습니다 (NPS 기록).",
  "로웰 포크 페스티벌은 미국 최대의 무료 민속 축제로 소개되며, 2019년 공원은 「아메리카 더 뷰티풀」 25센트 동전의 매사추세츠 대표로 선정되었습니다.",
 ],
 "operation": [
  ["운영 주체", "국립역사공원은 미국 국립공원청 (NPS)이 연방 예산으로 운영 — 보존위원회 (1978~1995) 해산 뒤 공원이 운하길 사업 · 보존지구 디자인 심의 승계"],
  ["공공 운영 예산 (공원 전체)", "국립공원 운영비 (ONPS) 2023 회계연도 실적 943만 7천 달러 · 2024 동일 · 2025 회계연도 요청 1,046만 3천 달러, 정규 인력 (FTE) 기본 60명 · 전체 65명 — NPS 2025 예산 설명서", "https://www.doi.gov/sites/default/files/documents/2024-03/fy2025-508-nps-greenbook.pdf"],
  ["방문객", "2023년 레크리에이션 방문 25만 6,303회 · 연방 소유 30.63에이커 / 전체 143.37에이커 (NPS 2025 예산 설명서)", "https://www.doi.gov/sites/default/files/documents/2024-03/fy2025-508-nps-greenbook.pdf"],
  ["수입 구성", "입장료 없음 — 부트 면방직 박물관 · 투어만 유료 (성인 6달러 · 청소년 · 학생 3달러 · 경로 4달러), 박물관에서 주차권을 받으면 해밀턴 운하 차고 무료 주차", "https://www.nps.gov/lowe/planyourvisit/fees.htm"],
  ["금융 회전 구조", "로웰 개발금융공사 (LDFC)의 보존 대출기금 — 상환금으로 추가 대출을 하도록 법에 규정 (회전 기금)", "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"],
  ["운영 성과", "2016년 방문 54만 1,285회 · 방문객 지출 3,170만 달러 · 일자리 467개 · 경제 산출 4,490만 달러 · 노동소득 1,770만 달러", "https://www.pew.org/en/research-and-analysis/fact-sheets/2018/03/lowell-national-historical-park"],
  ["운영상 문제", "유지보수 적체 1,210만 달러 (2015 회계연도) — 역사 건물 28동 · 수문 · 보행교 · 보행로 수리 재원 부족", "https://www.pew.org/en/research-and-analysis/fact-sheets/2018/03/lowell-national-historical-park"],
  ["민간 운영", "공장 개조 아파트 · 사무는 민간 소유자가 임대 운영 (세액공제로 사업비 조달)"],
 ],
 "operationNote": [
  "로웰 국립역사공원은 입장료 없이 연방 예산으로 운영되고, 박물관 · 투어 소액 요금만 받습니다. 보존위원회가 만든 대출기금은 상환금을 다시 빌려주는 회전 구조로 법에 정해져 있었습니다.",
  "연방 예산만으로는 역사 건물 유지가 버거워 2015 회계연도 기준 1,210만 달러의 유지보수 적체가 쌓였고, 퓨 재단은 민관 협력 · 기부 확대를 제안했습니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (현재 공장 건물에 입주한 기술 기업 · 대학 시설 목록)는 확인된 자료를 찾지 못했습니다.",
  "로웰 국립역사공원의 자체 수입 (박물관 · 투어 요금) 금액과 운영비 중 비율은 확인된 자료를 찾지 못했습니다.",
  "마스터플랜 · 설계를 맡은 도시계획가 · 건축가는 확인된 자료를 찾지 못했습니다.",
  "로웰 시 조닝 상의 원래 용도지구 · 변경 용도지구 이름과 용적률 수치는 확인된 자료를 찾지 못했습니다.",
  "보존위원회 연도별 실제 예산 총액은 확인된 자료를 찾지 못했습니다.",
  "1972년 첫 역사지구의 정확한 지정 주체 (시 · 국가 사적)는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Hamilton Canal Innovation District Plan — City of Lowell", "u": "https://www.lowellma.gov/731/Hamilton-Canal-District-Plan"},
  {"t": "National Park Service FY 2025 Budget Justifications (Greenbook)", "u": "https://www.doi.gov/sites/default/files/documents/2024-03/fy2025-508-nps-greenbook.pdf"},
  {"t": "Lowell National Historical Park fact sheet — Pew (2018)", "u": "https://www.pew.org/en/research-and-analysis/fact-sheets/2018/03/lowell-national-historical-park"},
  {"t": "Fees & Passes — Lowell National Historical Park (NPS)", "u": "https://www.nps.gov/lowe/planyourvisit/fees.htm"},
  {"t": "Public Law 95-290 (92 Stat. 290), June 5, 1978 — GovInfo (PDF)", "u": "https://www.govinfo.gov/content/pkg/STATUTE-92/pdf/STATUTE-92-Pg290.pdf"},
  {"t": "16 U.S. Code § 410cc-31 — Lowell Historic Preservation Commission (Cornell LII)", "u": "https://www.law.cornell.edu/uscode/text/16/410cc-31"},
  {"t": "Lowell Historic Preservation Commission Records Finding Aid — NPS (PDF)", "u": "https://www.nps.gov/lowe/learn/historyculture/upload/LHPC-FindingAid-2012-UPDATED.pdf"},
  {"t": "Making the Park — Lowell National Historical Park (NPS)", "u": "https://nps.gov/lowe/learn/historyculture/making-the-park.htm"},
  {"t": "Redevelopment Rove — Lowell National Historical Park (NPS)", "u": "https://www.nps.gov/lowe/planyourvisit/redevelopment-rove.htm"},
  {"t": "S. 1215 Testimony (2012) — U.S. Department of the Interior", "u": "https://www.doi.gov/ocl/hearings/112/S1215_30715"},
  {"t": "Leveraging on History: Former Textile Mill in Lowell Being Rehabilitated Into Artist Housing — Tax Credit Advisor", "u": "https://www.taxcreditadvisor.com/articles/leveraging-on-history-former-textile-mill-in-lowell-being-rehabilitated-into-artist-housing/"},
  {"t": "Lowell National Historical Park — Wikipedia", "u": "https://en.wikipedia.org/wiki/Lowell_National_Historical_Park"},
  {"t": "Lowell, Massachusetts — Wikipedia", "u": "https://en.wikipedia.org/wiki/Lowell,_Massachusetts"},
  {"t": "Boott Cotton Mills — Wikipedia", "u": "https://en.wikipedia.org/wiki/Boott_Cotton_Mills"},
 ],
},

"singapore-river-quays": {
 "spec": [
  ["위치", "싱가포르 중심부 — 싱가포르강 하류, 보트 키 (Boat Quay) · 클라크 키 (Clarke Quay) · 로버트슨 키 (Robertson Quay)로 이루어진 「싱가포르강 계획구역 (Singapore River Planning Area)」"],
  ["면적", "싱가포르강 항행 가능 길이 2.95km (김셍 다리 ~ 마리나 베이슨), 강폭 보트 키 160m"],
  ["기간", "1977~1987년 강 정화 → 1983년 하역선 이전 → 1986년 보존 마스터플랜 → 1989.7.7 보존지구 고시 · 클라크 키 일괄 매각 → 1989~1993년 보트 키 숍하우스 복원 → 1993.12.10 클라크 키 개장 → 1994 계획구역 보고서 → 2003~2006 클라크 키 재설계"],
  ["원래 용도", "1819년 이후 싱가포르 무역의 중심 하역 항구 — 거룻배 (twakow · 하역선) · 강변 창고 (고다운) · 숍하우스 · 노점 · 무허가 정착지"],
  ["변경 용도", "식당 · 바 · 클럽 · 상점 · 호텔 · 주거 · 예술 시설 · 강변 산책로 · 수상 택시"],
  ["원래 용도지구", "항만 · 창고 · 상업 (마스터플랜 1985 이전 체계)"],
  ["변경 용도지구", "보존지구 (Conservation Area — 보트 키 · 클라크 키, 1989) + 싱가포르강 계획구역 도시설계 지침"],
  ["정화 사업", "약 3억 싱가포르달러 · 무허가 거주자 4만 6,000명 이상 공공주택 이주 · 노점상 약 5,000명 호커센터 이전 (강 · 칼랑 분지 합계)"],
 ],
 "from": "하역 항구 · 창고 (고다운) · 숍하우스", "to": "식당 · 바 · 상업 · 호텔 · 강변 산책로",
 "zoneFrom": "항만 · 창고 · 상업", "zoneTo": "보존지구 (Conservation Area, URA 1989) · 싱가포르강 계획구역",
 "tenants": [
  ["업무 · 금융 본사", "UOB 플라자 1 · 2 (UOB Plaza) — 대화은행 (United Overseas Bank)", "보트 키 맞은편 래플스 플레이스 · 플라자 1 (1995, 280m) · 플라자 2 (1973 · 1995 개조, 162m) — UOB 본사", "https://en.wikipedia.org/wiki/UOB_Plaza"],
  ["상업 · 식음 · 유흥", "CQ @ 클라크 키 (CQ @ Clarke Quay) — 캐피털랜드 통합상업신탁 (CICT)", "1993년 클라크 키 페스티벌 빌리지로 개장 · 보존 창고 블록 — 강변 식당 · 바 · 클럽, 2022~2023 재단장 (순임대면적 70% 이상 사전 계약)", "https://www.capitaland.com/en/about-capitaland/newsroom/news-releases/international/2022/jul/cq---clarke-quay-to-be-transformed-into-a-day-and-night-destinat.html"],
  ["상업 · 쇼핑 · 업무", "클라크 키 센트럴 · 리버사이드 포인트 (Clarke Quay Central · Riverside Point) — 파 이스트 오거니제이션 (Far East Organization)", "클라크 키 구역 상업 · 업무 시설 — 싱가포르강 원 회원", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["상업 · 식료품 · 음악", "페어프라이스 파이니스트 클라크 키 (FairPrice Finest) · 스위 리 클라크 키 (Swee Lee) · 슬링샷 (Slingshot)", "2024 재개장 때 입점 — 그로서 푸드홀 · 악기 매장 겸 카페 · 바 · 라이브 공연장 · 놀이기구", "https://www.timeout.com/singapore/things-to-do/cq-at-clarke-quay-ultimate-guide"],
  ["상업 · 식음", "보트 키 숍하우스 식당 · 바 (홍롱 홀딩스 · 8M 리얼 에스테이트 등 소유)", "1989~1993 복원 뒤 강변 식당 · 바 거리 — 옥외 식음 구역 (Outdoor Refreshment Areas)은 싱가포르강 원이 관리", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["상업 · 쇼핑 · 식음", "로버트슨 워크 (Robertson Walk) — 프레이저스 프로퍼티 (Frasers Property)", "로버트슨 키 강변 상업 시설", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["상업 · 호텔", "M 소셜 싱가포르 · 스튜디오 M 호텔 (M Social Singapore · Studio M Hotel) — 시티 디벨롭먼트 · 홍롱 홀딩스", "로버트슨 키", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["상업 · 호텔", "그랜드 코프손 워터프런트 호텔 (Grand Copthorne Waterfront Hotel) — 밀레니엄 앤 코프손", "로버트슨 키 상류", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
 ],
 "timeline": [
  ["1819 · 1822", "근대 싱가포르 건설 · 래플스 도시계획으로 보트 키 매립"],
  ["1969", "리콴유 총리, 공공사업국 · 공익사업청에 수로 정화 계획 지시"],
  ["1977.2.27", "리콴유 총리, 환경부에 10년 안에 싱가포르강 · 칼랑 분지 정화 과제 부여"],
  ["1983", "강의 마지막 거룻배가 사라지고 하역업 파시르 판장 (Pasir Panjang)으로 이전 — 1983~1989년 보트 키는 빈 상태"],
  ["1986", "도시재개발청 (URA) 보존 마스터플랜 발표 — 싱가포르강을 6개 역사지역의 하나로 지정, 보트 키 숍하우스 보존 결정"],
  ["1987.9.2", "강 정화 완료 선언 · 5일간 기념 행사"],
  ["1989", "계획법 (Planning Act) 대폭 개정 — URA 에 보존지구 지정 · 지침 · 승인 권한 부여"],
  ["1989.7.7", "보트 키 · 클라크 키를 포함한 10개 보존지구 (3,200여 동) 고시"],
  ["1989~1993", "보트 키 숍하우스 복원 · 식당 · 바로 전환"],
  ["1993.12.10", "클라크 키 페스티벌 빌리지 개장 — DBS 랜드 자회사 클라크 키 Pte Ltd 운영 (싱가포르강 최대 보존 사업)"],
  ["1994", "싱가포르강 계획구역 계획 보고서 (개발지침계획, DGP) 발간"],
  ["2000 · 2003", "DBS 랜드 · 피뎀코 랜드 합병으로 캐피털랜드가 관리 · 2003년 영국 올솝 아키텍츠 (Alsop Architects)에 재설계 의뢰"],
  ["2008", "마리나 저수지 댐 (마리나 버라지) 완공 — 강이 담수 저수지 일부가 됨"],
  ["2022~2023", "클라크 키 자산 개선 사업 (6,200만 싱가포르달러) → 「CQ @ Clarke Quay」"],
  ["2024.4.26", "「CQ @ 클라크 키」 재개장 — 창고 (Warehouses) · 서킷 (Circuit) · 리버프런트 (Riverfront) 3개 구역, 낮과 밤 복합 목적지로 전환"],
  ["2025.8.7", "정부, 보트 키 · 클라크 키 활성화 대책 발표 (샨무감 내무장관 · 앨빈 탄 국무장관) — 새 바 · 클럽 · 펍 최대 3년 시범 허가, 목~토 · 공휴일 전날 주류 판매 새벽 4시까지 (1년 시범), 서큘러 로드 차량 통제, 싱가포르강 원이 민간 경비 배치"],
 ],
 "problem": [
  "강변의 무허가 정착지 · 노점 · 돼지 · 오리 농장 · 가내공업 · 하역업이 하수와 쓰레기를 그대로 흘려보내, 싱가포르강은 심한 악취가 나는 \"죽은 강\"이었습니다.",
  "1983년 하역업이 파시르 판장의 새 화물 시설로 옮겨 가자 강변 창고와 숍하우스가 쓸모를 잃고 비었습니다.",
  "보트 키 숍하우스는 사유지라, 처음 복원 계획이 나왔을 때 소유자들이 수익성을 의심했습니다.",
  "도심 고층 재개발 속에서 강변의 역사적 경관 · 정체성을 지킬 제도가 필요했습니다.",
 ],
 "overview": [
  "싱가포르강 재생은 \"환경 정화 → 보존지구 지정 → 민간 복원 · 용도 전환\"의 순서로 국가가 단계적으로 추진한 사례입니다. 1977~1987년 환경부 주도로 무허가 거주자 · 노점 · 하역업을 옮기고 강바닥을 준설해 강을 살렸습니다.",
  "이어 URA 가 1986년 보존 마스터플랜에서 싱가포르강을 역사지역으로 정하고, 1989년 계획법을 고쳐 보존 권한을 갖춘 뒤 7월 7일 보트 키 · 클라크 키를 보존지구로 고시했습니다. 보트 키는 개별 소유자들이 보존 지침에 맞춰 숍하우스를 복원해 식당 · 바 거리로, 클라크 키는 국가 소유 창고 · 숍하우스를 하나의 부지로 묶어 매각 (Sale of Sites)해 DBS 랜드가 「페스티벌 빌리지」로 개발했습니다(1993).",
  "1994년 싱가포르강 계획구역 계획 이후 강변 15m 산책로, 1층 활성 용도, 높이 · 지붕 형태 등 도시설계 지침으로 세 키 (Quay)를 하나의 강변 공간으로 관리하고 있습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "올솝 아키텍츠 (Alsop Architects)", "클라크 키 재설계 (캐노피 · 가로 · 강변 식당)"],
  ["주관 기관", "도시재개발청 (Urban Redevelopment Authority, URA)", "보존 마스터플랜 (1986) · 보존지구 고시 (1989) · 보존 지침 · 국유지 매각 · 계획구역 도시설계 지침"],
  ["관련 기관", "환경부 (Ministry of the Environment, ENV)", "1977~1987 강 정화 주관"],
  ["관련 기관", "주택개발청 (HDB) · 공공사업국 (PWD) · 항만청 (PSA)", "무허가 거주자 공공주택 이주 · 하천 공사 · 하역업 이전"],
  ["정치 지도자", "리콴유 (Lee Kuan Yew) 총리", "1977년 10년 정화 목표 제시"],
  ["민간 · 사업 시행", "DBS 랜드 (DBS Land) → 캐피털랜드 (CapitaLand) · 캐피털랜드 통합상업신탁 (CICT)", "클라크 키 개발 · 운영 (1993~) · 재설계 (2003~) · 자산 개선 (2022~)"],
  ["민간", "보트 키 숍하우스 소유자", "보존 지침에 따른 개별 복원"],
 ],
 "laws": [
  ["계획법 개정 (Planning Act, 1989)", "URA 에 보존지구 지정 · 보존 지침 제정 · 보존지구 개발 승인 권한 부여"],
  ["보존 마스터플랜 (Conservation Master Plan, 1986)", "차이나타운 · 캄퐁글람 · 리틀인디아 · 싱가포르강 · 에메랄드힐 · 헤리티지 링크 6개 역사지역 지정"],
  ["마스터플랜 1985 (Master Plan 1985) 재검토 — 개발지침계획 (Development Guide Plans, 1993~1998)", "전국을 55개 계획구역으로 나눠 구역별 상세 토지이용계획 — 싱가포르강 계획구역 포함"],
  ["보존지구 고시 (1989.7.7)", "보트 키 · 클라크 키 등 10개 보존지구 3,200여 동 — 외관 · 지붕 · 재료 등 보존 원칙 · 계획 기준 · 복원 지침 준수 의무", "https://www.ura.gov.sg/conservation/about-conservation/ura-conservation-programme/"],
  ["보존 지침 (Conservation Guidelines, URA) · 개별 복원 지침 (Specific Restoration Guidelines, SRG)", "숍하우스 · 창고 유형별 계획 기준 · 복원 기준 · 용도 지침 — 모든 증개축 · 용도 변경 전에 보존 허가 (Conservation Permission) 필요", "https://www.ura.gov.sg/Corporate/Guidelines/Conservation"],
  ["싱가포르강 계획구역 계획 보고서 (Singapore River Planning Area: Planning Report, 1994) · 싱가포르강 계획구역 도시설계 지침 (Urban Design Guidelines for Singapore River Planning Area)", "15m 강변 산책로 (보도 · 자전거길 · 조경), 1층 활성 용도 의무, 구역별 높이, 로버트슨 키 점토 기와 박공지붕 등", "https://www.ura.gov.sg/Corporate/Guidelines/Urban-Design/Singapore-River/Singapore-River-Planning-Area"],
 ],
 "lawsNote": ["보존지구 지정은 외관을 엄격히 묶는 대신, 내부 용도를 식당 · 바 · 상업 · 호텔 등으로 바꿀 수 있게 하고, 개발부담금 (land betterment charge) 면제와 주차장 설치 의무 면제 · 주차 부족 부담금 면제 같은 인센티브를 주었습니다. 즉 \"외관 보존 의무 ↔ 용도 · 부담금 완화\"의 교환 구조입니다."],
 "tools": [
  ["환경 정화 선투자", "10년간 약 3억 싱가포르달러 — 무허가 거주자 4만 6,000명 이상 공공주택 이주, 노점상 약 5,000명 호커센터 이전, 강바닥 준설"],
  ["보존 인센티브", "개발부담금 면제 · 주차장 설치 의무 면제 · 주차 부족 부담금 면제"],
  ["국유지 일괄 매각 (Sale of Sites)", "클라크 키의 국가 소유 창고 · 숍하우스를 하나의 부지로 묶어 매각 — 단일 개발자가 일관되게 개발 (DBS 랜드)"],
  ["용도 전환 허용", "하역 창고 · 숍하우스 → 식당 · 바 · 상업 · 유흥"],
  ["도시설계 지침", "15m 강변 산책로, 1층 활성 용도, 건축선 · 높이 통제"],
 ],
 "zoning": [
  ["지정", "보트 키 보존지구 · 클라크 키 보존지구 — 1989년 7월 7일 고시 (같은 날 10개 보존지구 3,200여 동)"],
  ["관리 주체 · 방식", "URA 가 보존 지침 · 개별 복원 지침으로 모든 공사를 심의 · 승인"],
  ["보존 관리", "보트 키 보존지구 숍하우스 100여 동 · 어퍼 서큘러 로드 보존지구 · 클라크 키 창고 · 매거진 로드 보존지구"],
  ["계획구역", "싱가포르강 계획구역 — 보트 키 (상업 중심) · 클라크 키 (상업 · 호텔 · 주거) · 로버트슨 키 (주거 · 호텔 · 예술) 3개 하위 구역"],
 ],
 "result": [
  "죽은 강이 살아나 수달 · 왕도마뱀이 돌아왔고, 2008년 마리나 버라지로 강이 담수 저수지의 일부가 되었습니다.",
  "보트 키 · 클라크 키는 싱가포르의 대표 강변 식당 · 유흥 지구가 되었고, 클라크 키는 재설계 뒤 연간 200만 명 이상이 찾았습니다.",
  "1989년 보존지구 이후 싱가포르의 보존 대상은 약 100개 지구 · 7,000동 이상으로 늘었습니다.",
 ],
 "lesson": [
  "\"환경 정화 → 보존지구 → 용도 완화 · 부담금 면제\"의 순서 — 오염된 하천 · 공업지 재생은 환경 정화가 먼저라는 점.",
  "국가 소유 건물들을 하나로 묶어 단일 개발자에게 매각해 일관된 재생을 이끈 클라크 키 방식.",
  "외관 보존 의무와 용도 · 주차 · 부담금 완화를 교환하는 인센티브 구조는 한국 근대 산업 건축물 보존 · 활용에 참고할 만합니다.",
  "한계 — 유흥 중심 상권이 되면서 낮 시간 활력이 떨어져, 30년 뒤 다시 자산 개선이 필요했습니다.",
 ],
 "funding": [
  ["정부 재정 — 환경 정화", "1977~1987년 싱가포르강 정화 약 3억 싱가포르달러 (정부) — 무허가 거주자 이주 · 호커센터 · 준설"],
  ["보존 인센티브 (재정 지원 대신 부담금 면제)", "개발부담금 (land betterment charge) 면제 · 주차장 설치 의무 면제 · 주차 부족 부담금 면제", "https://www.ura.gov.sg/conservation/about-conservation/ura-conservation-programme/"],
  ["국유지 매각 (Sale of Sites)", "클라크 키 국유 창고 · 숍하우스를 하나의 부지로 묶어 매각 → DBS 랜드가 개발 (매각가는 미확인)"],
  ["민간 투자", "보트 키 숍하우스 소유자 개별 복원 · 클라크 키 DBS 랜드 (1993) → 캐피털랜드 재설계 (2003~) → CICT 자산 개선 6,200만 싱가포르달러 (2022~2023, 그중 약 34% 녹색 설비)", "https://www.capitaland.com/en/about-capitaland/newsroom/news-releases/international/2022/jul/cq---clarke-quay-to-be-transformed-into-a-day-and-night-destinat.html"],
 ],
 "famous": [
  "1977년 리콴유 총리가 내건 \"10년 안에 강 살리기\"를 1987년 실제로 끝낸 도시 하천 정화의 대표 사례 — 무허가 거주자 4만 6,000명 이상 이주, 완료 때 공로자 10명에게 금메달 수여.",
  "1989년 7월 7일 보트 키 · 클라크 키가 차이나타운 등과 함께 싱가포르 최초의 역사지구 (보존지구)로 고시되었고, 이후 보존 대상은 약 100개 지구 · 7,000동 이상으로 늘었습니다.",
  "정화 뒤 수달 · 왕도마뱀이 돌아왔고, 2008년 마리나 버라지로 강이 도심 담수 저수지의 일부가 되었습니다.",
  "클라크 키는 싱가포르강 최대의 보존 사업으로 1993년 개장했고, 올솝 재설계 뒤 연간 200만 명 이상이 찾았습니다.",
 ],
 "operation": [
  ["운영 주체 (지역 관리)", "싱가포르강 원 (Singapore River One, SRO) — 2012년 정식 설립된 민간 주도 조직, 보트 키 · 클라크 키 · 로버트슨 키 전체의 지역 관리자 (Place Manager)", "https://www.ura.gov.sg/place-management/about-place-management/"],
  ["지역 관리 재원 (BID)", "2017년 9월 URA 시범 업무개선지구 (Pilot BID) 프로그램 출범 — SRO 가 첫 시범 BID (2017.4~), 민간 주도의 자립형 지역 관리 체계를 모델로 함", "https://www.ura.gov.sg/place-management/about-place-management/"],
  ["공공 운영 보조금 (BID 매칭)", "시범 BID 출범 지원 — 정부가 회원 분담금 1달러마다 1달러를 맞춰 지원, 연 50만 달러 (URA 표기 $500k) 상한 · 각 시범 BID 는 다년 사업계획 수립과 상당한 자체 분담 필요 (시범 BID 5곳)", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/"],
  ["회원 구성", "회원 42곳 — UOB 플라자 · 숍하우스 소유자 (보트 키), 파 이스트 오거니제이션 · CQ @ 클라크 키 (클라크 키), 프레이저스 · 시티 디벨롭먼트 · 밀레니엄 앤 코프손 (로버트슨 키)", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["사업 구성", "싱가포르강 축제 · 성 패트릭의 날 거리 축제, 보트 키 옥외 식음 구역 (Outdoor Refreshment Areas) 관리, 공공 설치물 · 정부 기관 협업", "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"],
  ["민간 운영사", "CQ @ 클라크 키 — 캐피털랜드 통합상업신탁 (CICT) 소유 · 캐피털랜드 인베스트먼트 관리, 임대 수입 (2022 개선 때 순임대면적 70% 이상 사전 계약)", "https://www.capitaland.com/en/about-capitaland/newsroom/news-releases/international/2022/jul/cq---clarke-quay-to-be-transformed-into-a-day-and-night-destinat.html"],
  ["운영상 문제", "야간 유흥 중심 상권 — 낮 시간 활력을 위해 2022~2023 자산 개선 (6,200만 싱가포르달러) 추진"],
  ["정부 활성화 대책 (2025)", "야간 상권 침체에 대응해 신규 유흥업소 최대 3년 시범 허가 · 목~토 새벽 4시 주류 판매 1년 시범 · 서큘러 로드 통제 — 싱가포르 나이트라이프 사업자협회 · 싱가포르강 원과 협력, SRO 는 민간 경비 · 비상계획 담당", "https://www.meti.gov.sg/newsroom/transcripts-of-doorstop-on-the-revitalisation-measures-at-boat-quay-and-clarke-quay"],
 ],
 "operationNote": [
  "보존 · 정화는 정부가 했지만 운영은 민간에 넘어가 있습니다. 숍하우스 · 창고는 민간 소유자 · 리츠 (CICT)가 임대 수입으로 운영하고, 강 전체는 토지 소유자 · 사업자 42곳이 모인 싱가포르강 원 (SRO)이 지역 관리자로 축제 · 옥외 식음 구역 · 공공 설치물을 맡습니다. SRO 는 2017년 URA 시범 업무개선지구 (BID)의 첫 사례입니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (클라크 키 개별 식음 · 클럽 브랜드, 로버트슨 키의 예술 시설)는 확인된 자료를 찾지 못했습니다.",
  "SRO 의 실제 연간 예산 · 회원 분담금 총액 · 실제 받은 매칭 지원금은 확인된 자료를 찾지 못했습니다.",
  "1993년 클라크 키 첫 개조와 보트 키 복원을 설계한 건축가, 싱가포르강 계획구역 계획의 도시계획가는 확인된 자료를 찾지 못했습니다.",
  "보존지구 고시 이전 마스터플랜 상의 정확한 원래 용도지구 이름은 확인된 자료를 찾지 못했습니다.",
  "클라크 키 매각 가격 · 개발 사업비와 보존지구 면적 (ha)은 확인된 자료를 찾지 못했습니다 (국립도서관 인포피디아 원문을 열지 못함).",
  "보트 키 숍하우스 소유자 협의회 등 시민단체 · 주민 조직의 참여는 확인된 자료를 찾지 못했습니다.",
  "용적률 수치는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Transcripts of Doorstop on the Revitalisation Measures at Boat Quay and Clarke Quay (2025.8.7) — Ministry of Trade and Industry", "u": "https://www.meti.gov.sg/newsroom/transcripts-of-doorstop-on-the-revitalisation-measures-at-boat-quay-and-clarke-quay"},
  {"t": "An ultimate guide to the new CQ @ Clarke Quay — Time Out Singapore", "u": "https://www.timeout.com/singapore/things-to-do/cq-at-clarke-quay-ultimate-guide"},
  {"t": "UOB Plaza — Wikipedia", "u": "https://en.wikipedia.org/wiki/UOB_Plaza"},
  {"t": "Pilot Business Improvement District Programme — URA", "u": "https://www.ura.gov.sg/place-management/business-improvement-district-bid/"},
  {"t": "Singapore River One — URA Pilot BID Programme", "u": "https://www.ura.gov.sg/place-management/business-improvement-district-bid/singapore-river-one/"},
  {"t": "About Place Management — URA", "u": "https://www.ura.gov.sg/place-management/about-place-management/"},
  {"t": "URA Conservation Programme — Urban Redevelopment Authority", "u": "https://www.ura.gov.sg/conservation/about-conservation/ura-conservation-programme/"},
  {"t": "Conservation Guidelines — URA", "u": "https://www.ura.gov.sg/Corporate/Guidelines/Conservation"},
  {"t": "Boat Quay Conservation Area — URA Conservation Portal", "u": "https://www.ura.gov.sg/conservation/find-a-building/conservation-portal/btqy/"},
  {"t": "Guidelines for Singapore River Planning Area — URA", "u": "https://www.ura.gov.sg/Corporate/Guidelines/Urban-Design/Singapore-River/Singapore-River-Planning-Area"},
  {"t": "To Wreck or to Recreate: Giving New Life to Singapore's Built Heritage — BiblioAsia (NLB)", "u": "https://biblioasia.nlb.gov.sg/vol-15/issue-2/jul-sep-2019/preservation-buildings/"},
  {"t": "The Singapore River — Roots.gov.sg (National Heritage Board)", "u": "https://www.roots.gov.sg/stories-landing/stories/The-Singapore-River/story"},
  {"t": "Cleaning of the Singapore River and Kallang Basin — The Singapore Water Story, Ch. 6 (Routledge, PDF)", "u": "https://www.routledge.com/rsc/downloads/Chapter_6_The_Singapore_Water_Story.pdf"},
  {"t": "CQ @ Clarke Quay asset enhancement initiative — CapitaLand (2022)", "u": "https://www.capitaland.com/en/about-capitaland/newsroom/news-releases/international/2022/jul/cq---clarke-quay-to-be-transformed-into-a-day-and-night-destinat.html"},
  {"t": "Clarke Quay — Wikipedia", "u": "https://en.wikipedia.org/wiki/Clarke_Quay"},
  {"t": "Boat Quay — Wikipedia", "u": "https://en.wikipedia.org/wiki/Boat_Quay"},
  {"t": "Singapore River — Wikipedia", "u": "https://en.wikipedia.org/wiki/Singapore_River"},
  {"t": "克拉码头 — 维基百科", "u": "https://zh.wikipedia.org/wiki/克拉码头"},
 ],
},

"granville-island": {
 "spec": [
  ["위치", "캐나다 브리티시컬럼비아주 밴쿠버 — 폴스 크리크 (False Creek) 안 반도, 그랜빌 다리 남단 아래"],
  ["면적", "약 14ha (35~38에이커) — 1915~1916년 모래톱을 준설 · 매립해 만든 인공 섬 (1960년대 중반 반도로 연결)"],
  ["기간", "1972년 연방 재개발 계획 승인 · 1973년 CMHC 이관 → 1975년 재개발 착수 → 1979.7 퍼블릭 마켓 개장 → 1980년 에밀리 카 대학 입주 → 1983년부터 재정 자립 → 2017년 에밀리 카 이전 · 「그랜빌 아일랜드 2040」 계획"],
  ["원래 용도", "「인더스트리얼 아일랜드」 — 제재 · 철공 · 와이어로프 공장 (라이츠 캐나디안 로프스) · 시멘트 공장 등, 1923년 무렵 거의 모든 필지에 공장"],
  ["변경 용도", "퍼블릭 마켓 (식품 판매자 50곳 이상) · 공방 · 갤러리 · 실내 극장 7곳 · 식당 · 양조장 · 60실 호텔 · 마리나 · 아동 시설 · 가동 중인 시멘트 공장 (오션 콘크리트, 1917년부터)"],
  ["원래 용도지구", "연방 항만위원회 관할 공업 용지 (밴쿠버 항만위원회 · 국가항만위원회)"],
  ["변경 용도지구", "연방 소유지 — 밴쿠버 시 조닝 · 규제를 받지 않고 CMHC 가 직접 관리하는 혼합 용도 지구"],
  ["사업비", "연방 정부 1973~1982년 2,470만 캐나다달러 투자 (CMHC 경유)"],
  ["규모", "사업체 300곳 이상 · 종사자 3,000명 이상 · 연간 방문객 약 1,000만 명"],
 ],
 "from": "공업 지대 (제재 · 철공 · 로프 · 시멘트 공장)", "to": "공공 시장 · 공방 · 극장 · 예술 · 일부 공장 유지",
 "zoneFrom": "연방 항만 공업 용지", "zoneTo": "연방 소유 · CMHC 직접 관리 혼합 용도 지구 (시 조닝 적용 제외)",
 "tenants": [
  ["상업 · 시장", "그랜빌 아일랜드 퍼블릭 마켓 (Granville Island Public Market)", "1979.7 개장 · 옛 공장 4동 (5만 ft²) · 독립 식품 판매자 50곳 이상 · 섬 운영 예산의 가장 큰 임대 수입원", "https://admin.granvilleisland.com/about-granville-island/mission-vision/"],
  ["문화 · 공연장", "아츠 클럽 시어터 컴퍼니 (Arts Club Theatre Company) — 그랜빌 아일랜드 스테이지", "1979년 개관 · 440석 (같은 회사 레뷰 스테이지 1983~2015, 193석 — 철수)", "https://en.wikipedia.org/wiki/Arts_Club_Theatre_Company"],
  ["문화 · 공연장", "캐러셀 어린이 · 청소년 극장 (Carousel Theatre for Young People) 등 실내 극장 7곳", "섬 안 공연장 7곳 (즉흥극 · 실험극 포함)", "https://en.wikipedia.org/wiki/Granville_Island_Public_Market"],
  ["문화 · 대학", "에밀리 카 예술디자인대학 (Emily Carr University of Art + Design)", "1980~2017 섬 안 캠퍼스 → 2017년 그레이트 노던 웨이로 이전 (철수)", "https://en.wikipedia.org/wiki/Emily_Carr_University_of_Art_and_Design"],
  ["업무 · 가동 공장", "오션 콘크리트 (Ocean Concrete)", "1917년부터 — 섬에서 가장 오래된 임차인, 지금도 가동 중인 시멘트 공장", "https://en.wikipedia.org/wiki/Granville_Island"],
  ["상업 · 양조 · 식음", "그랜빌 아일랜드 브루잉 (Granville Island Brewing)", "1984년 설립 · 2009년 몰슨 (Molson) 인수", "https://en.wikipedia.org/wiki/Granville_Island"],
  ["상업 · 호텔", "그랜빌 아일랜드 호텔 (Granville Island Hotel)", "60실 부티크 호텔", "https://granvilleisland.com/about-us"],
  ["상업 · 어린이 상가", "키즈 마켓 (Kids Market)", "어린이 전용 상점 · 놀이 시설", "https://en.wikipedia.org/wiki/Granville_Island_Public_Market"],
 ],
 "timeline": [
  ["1915~1916", "밴쿠버 항만위원회가 폴스 크리크 모래톱 둘레에 방벽을 쌓고 약 76만㎥ 를 준설 · 매립해 공업 용지 조성 (매립비 34만 2,000달러)"],
  ["1917", "오션 콘크리트 (Ocean Concrete) 입주 — 지금까지 가장 오래된 임차인"],
  ["1923", "섬의 거의 모든 필지에 골함석 공장 입주"],
  ["1953 · 1956", "최대 공장 라이츠 캐나디안 로프스 화재 → 1956년 이전, 이후 공업 쇠퇴"],
  ["1960년대", "산업 이전 · 지역 노후화, 섬이 반도로 연결"],
  ["1972", "연방 정부가 지역에서 제안된 재개발 계획 승인 · 추밀원령으로 관리를 캐나다 모기지주택공사 (CMHC)에 맡김"],
  ["1973", "CMHC 가 섬의 책임 · 관리 넘겨받음 — 그랜빌 아일랜드 신탁 (Granville Island Trust) 위원 임명 (CMHC 자문)"],
  ["1975", "재개발 착수 — 공장 건물을 공방 · 상점 · 시장 · 식당으로 개조 시작"],
  ["1979.7", "퍼블릭 마켓 (옛 공장 건물 4동, 5만 ft²) 개장"],
  ["1980", "에밀리 카 예술대학 (Emily Carr) 입주"],
  ["1983", "재정 자립 달성 — 이후 운영비 · 시설 투자를 임대 수입으로 충당"],
  ["1984", "그랜빌 아일랜드 양조장 설립 (2009년 몰슨 인수)"],
  ["2014", "에밀리 카 이전 계획 속 관리 주체를 항만공사로 넘기는 방안 논의 (밴쿠버 시 반대)"],
  ["2016~2017", "CMHC 가 「그랜빌 아일랜드 2040」 착수 (2016.2 마이클 스티븐슨 특별자문 임명) · 2017년 계획 발표 · 에밀리 카 대학 그레이트 노던 웨이로 이전"],
  ["2023~2024", "체인 앤 포지 빌딩 (Chain & Forge) — 옛 주차 건물 · 주차장을 상가 · 식당 · 광장으로 (약 1만 7천 ft², 최대 7개 사업체) — CMHC 의 수십 년 만의 첫 대형 재개발"],
 ],
 "problem": [
  "1950~60년대 화재와 산업 이전으로 공장들이 떠나면서, 섬은 낡고 비어 가는 공업 지대가 되었습니다.",
  "폴스 크리크 일대가 공업 오염 · 쇠퇴 지역으로 남아 있어, 연방 정부가 남쪽 폴스 크리크 주거 개발과 함께 재생할 필요가 있었습니다.",
  "시의회는 처음에 섬 전체 (약 38에이커)를 공원으로 만드는 안을 생각했으나, 일자리 · 생산 기능을 잃지 않는 다른 길이 제안되었습니다.",
 ],
 "overview": [
  "그랜빌 아일랜드는 연방 정부가 땅을 소유한 채 국영 주택공사 (CMHC)가 직접 계획 · 임대 · 운영하는 \"공공 소유 · 공공 운영\" 재생 사례입니다. 연방 장관 론 배스퍼드 (Ron Basford)가 예술 중심의 혼합 용도 섬을 구상했고, 지역 시민 지도자 · 도시 전문가로 이루어진 그랜빌 아일랜드 신탁이 CMHC 를 도왔습니다.",
  "건축가 노먼 핫슨 (Norman Hotson) · 요스트 바커 (Joost Bakker)의 계획은 시의 공원안 대신 공업 · 시장 · 예술학교 · 공방 · 극장 · 양조장 · 호텔 · 수상 주택을 섞었습니다. 원칙은 \"사람의 장소\", 가능한 한 기존 건물 재사용, 산업 · 해양 유산 유지, 공공 · 민간 용도 혼합이었습니다.",
  "연방 정부는 지하 설비 · 방벽 · 도로 · 조명 같은 기반시설과 기존 임대권 회수에 돈을 쓰고, 민간 임차인은 장기 임대를 받아 건물을 고쳤습니다. 1983년 이후에는 임대 수입으로 운영비와 시설 투자를 충당해 정부 보조 없이 운영되고 있습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "노먼 핫슨 · 요스트 바커 (Hotson Bakker, 현 DIALOG)", "1970년대 재개발 계획 · 개발 지침 — 시의 공원안 대신 공업 · 시장 · 예술학교 · 극장 · 호텔 혼합안"],
  ["도시계획가 · 건축가", "톰슨 버윅 프랫 앤 파트너스 (Thompson, Berwick, Pratt and Partners)", "초기 개발 방향 보고서"],
  ["주관 · 토지 소유", "캐나다 연방 정부 · 캐나다 모기지주택공사 (Canada Mortgage and Housing Corporation, CMHC — Société canadienne d'hypothèques et de logement, SCHL)", "1973년부터 섬 소유 · 관리 · 임대 · 운영 (비영리 방식)"],
  ["정치 지도자", "론 배스퍼드 (Ron Basford, CMHC 담당 연방 장관)", "예술 기반 혼합 용도 섬 구상 — \"미스터 그랜빌 아일랜드\", 론 배스퍼드 공원에 이름"],
  ["자문 · 위원회", "그랜빌 아일랜드 신탁 (Granville Island Trust)", "지역 시민 지도자 · 도시 전문가로 구성 — CMHC 의 계획 이행 자문"],
  ["관련 기관", "밴쿠버 항만위원회 · 국가항만위원회", "원래 토지 관리 (1916~)"],
  ["관련 기관", "밴쿠버 시", "시 조닝 적용 밖 — 주변 폴스 크리크 계획 연계"],
  ["대학", "에밀리 카 예술디자인대학 (Emily Carr University of Art + Design)", "1980~2017 섬 안 캠퍼스 — 예술 앵커"],
  ["앵커 · 민간", "퍼블릭 마켓 상인 · 공방 · 극장 · 오션 콘크리트 · 그랜빌 아일랜드 양조장", "생산 · 판매 · 문화가 함께하는 임차인 구성"],
 ],
 "laws": [
  ["연방 추밀원령 (Order-in-Council, 1972)", "섬의 관리를 CMHC 에 맡김 — 연방 소유지로 남겨 시 조닝 · 규제의 적용을 받지 않음"],
  ["CMHC 의 직접 관리 (1973~)", "CMHC 가 계획 · 임차인 선정 · 임대 조건을 직접 정함 — 예술가에게는 일반 사업체보다 낮은 임대료"],
  ["핫슨 바커 재개발 계획 · 개발 지침 (Hotson Bakker, 1970년대)", "기존 건물 재사용 · 산업 해양 유산 유지 · 공공 · 민간 용도 혼합 · \"사람의 장소\" 원칙"],
  ["그랜빌 아일랜드 2040 계획 (Granville Island 2040, CMHC, 2017)", "토지이용 · 예술문화 · 교통 · 경제 · 거버넌스 4개 연구 — 퍼블릭 마켓 확장 · 보행 공간 · 700석 극장 등 제안", "https://granvilleisland2040.ca/about/"],
 ],
 "lawsNote": ["그랜빌 아일랜드의 \"규제 완화\"는 조닝 변경이 아니라 소유 구조에서 나옵니다. 연방 소유지라 시 조닝을 받지 않으므로, CMHC 가 공업 · 시장 · 예술 · 숙박 · 수상 주택을 한 섬에 자유롭게 섞을 수 있었고, 대신 입주 업종을 직접 골라 체인점보다 지역 상인 · 공방 · 예술 단체를 우선했습니다. 한편 별도 법인이 아니어서 큰 시설 투자를 위해 차입할 수 없다는 거버넌스 한계가 지적됩니다."],
 "tools": [
  ["공공 소유 · 직접 임대", "연방 소유 토지를 팔지 않고 CMHC 가 장기 임대 — 임차인 선정으로 업종 구성 관리, 예술가 할인 임대료"],
  ["연방 초기 투자", "1973~1982년 2,470만 캐나다달러 — 지하 설비 · 방벽 · 도로 · 조명 등 기반시설과 기존 임대권 회수"],
  ["민간 장기 임대 투자", "예산 (약 2,000만 달러)을 넘는 비용은 민간 임차인이 장기 임대를 받아 건물 개조에 투자"],
  ["기존 건물 재사용", "공장 4동을 퍼블릭 마켓으로 — 골함석 공장 외관 유지"],
  ["공업 유지", "가동 중인 시멘트 공장과 시장 · 관광의 공존"],
  ["재정 자립 구조", "1983년부터 임대 수입으로 운영비 · 시설 투자 충당 — 정부 보조 없음 (팬데믹 초기 예외)"],
 ],
 "zoning": [
  ["지정", "연방 소유지 (약 14ha) — 1972년 추밀원령으로 CMHC 관리, 1973년 이관"],
  ["관리 주체 · 방식", "CMHC 가 섬 전체를 하나의 단지로 비영리 운영 — 밴쿠버 시에 속하지 않음"],
  ["보존 관리", "별도 문화재 지정 대신 \"기존 건물 재사용 · 산업 해양 유산 유지\"를 계획 원칙으로 관리"],
 ],
 "result": [
  "사업체 300곳 이상 · 종사자 3,000명 이상 · 연간 방문객 약 1,000만 명.",
  "1983년 이후 재정 자립 — 운영비 · 시설 투자를 임대 수입으로 충당.",
  "밴쿠버 도시설계사에 큰 영향을 준 \"생산 + 판매 + 문화\" 혼합 재생의 대표 사례가 되었습니다.",
 ],
 "lesson": [
  "공공이 땅을 소유한 채 직접 임대 · 운영하며 업종을 골라, 지역 생산자 · 예술가 · 공장을 함께 지킨 방식 — 한국 국 · 공유 노후 산단의 일부를 \"공공 임대형 생산 · 문화 지구\"로 바꾸는 모델이 됩니다.",
  "가동 중인 공장을 내보내지 않고 시장 · 관광과 공존시킨 \"일하는 섬\" 전략.",
  "초기 공공 투자로 기반시설을 만든 뒤 임대 수입으로 자립하는 재정 구조.",
  "대학 (에밀리 카) 같은 앵커가 떠날 때 공백이 생기고, 별도 법인이 아니어서 차입이 어렵다는 거버넌스 한계도 함께 보아야 합니다.",
 ],
 "funding": [
  ["연방 재정 (CMHC)", "1973~1982년 연방 정부 2,470만 캐나다달러 투자 — 처음 배정 예산 약 2,000만 달러, 지하 설비 · 방벽 · 도로 · 가로등과 만료되는 공업 임대권 회수에 사용"],
  ["민간 투자", "예산을 넘는 비용은 민간 개발자 · 임차인이 장기 임대를 받아 건물 개조에 투자 (금액 미확인)"],
  ["임대 수입 (자립 재정)", "상업 임대료 · 공영 주차 요금만으로 운영비 · 시설 투자 충당 — CMHC 는 1979년부터, 글로브 앤 메일은 1983년부터 재정 자립이라고 서술 / 연방 소유지라 차입 불가", "https://www.newswire.ca/news-releases/granville-island-receives-up-to-21-7-million-for-pandemic-recovery-efforts-in-the-federal-budget-885398357.html"],
  ["연방 긴급 지원", "2021-2022 연방 예산 — 팬데믹 회복 · 필수 유지보수 최대 2,170만 캐나다달러 (2021.8 발표)", "https://www.newswire.ca/news-releases/granville-island-receives-up-to-21-7-million-for-pandemic-recovery-efforts-in-the-federal-budget-885398357.html"],
 ],
 "famous": [
  "도시계획가 · 개발자 · 건축가 · 플레이스메이커들에게 \"브라운필드 재개발의 성공 모델\"로 주목받아 왔습니다 (Project for Public Spaces).",
  "정부 보조 없이 임대 수입으로 수십 년간 자립 운영해 온 공공 소유 재생지입니다 (팬데믹 전까지).",
  "가동 중인 시멘트 공장 (1917년부터)과 공공 시장 · 극장 · 예술이 한 섬에 공존하는 드문 사례입니다.",
  "사업체 300곳 이상 · 종사자 3,000명 이상 · 연간 방문객 약 1,000만 명의 밴쿠버 대표 명소입니다.",
 ],
 "operation": [
  ["운영 주체", "캐나다 모기지주택공사 (CMHC) — 연방 소유지를 비영리 방식으로 직접 운영, 그랜빌 아일랜드 협의회 (Granville Island Council)가 자문", "https://admin.granvilleisland.com/faqs/"],
  ["수입 구성", "섬 안의 상업 임대료 (CMHC 직접 임차인)와 공영 주차 요금 — 연간 운영비 · 시설 투자를 이 수입으로 충당해야 하는 자립 원칙", "https://admin.granvilleisland.com/faqs/"],
  ["토지 · 건물 임대 구조", "CMHC 직접 임대 + 헤드 리스 (Head Lease) 임차인이 다시 임대하는 구조 — 퍼블릭 마켓 장인 프로그램 · 문화 파트너 프로그램 · 버스킹 프로그램 운영", "https://admin.granvilleisland.com/faqs/"],
  ["임대 조건 사례 (2023)", "체인 앤 포지 빌딩 신규 임대 — 연 ft² 당 75달러 + 총매출의 8% + 관리비 ft² 당 60.95달러 (상가 · 식당 약 9,000ft², 점포 727~4,550ft²)", "https://dailyhive.com/vancouver/chain-forge-building-granville-island"],
  ["자립도", "1979년 (CMHC 측 발표) 또는 1983년 (글로브 앤 메일)부터 팬데믹 전까지 정부 보조 없이 자립 — 연방 소유지라 차입 · 부채 불가", "https://www.newswire.ca/news-releases/granville-island-receives-up-to-21-7-million-for-pandemic-recovery-efforts-in-the-federal-budget-885398357.html"],
  ["공공 운영 보조금", "팬데믹 때 연방 긴급 운영자금 승인 (2020.7) · CMHC 임대료 감면 프로그램 (2020.9.14 신청 시작) · 2021-2022 연방 예산 최대 2,170만 캐나다달러", "https://www.newswire.ca/news-releases/granville-island-receives-up-to-21-7-million-for-pandemic-recovery-efforts-in-the-federal-budget-885398357.html"],
  ["운영 성과", "사업체 300곳 이상 · 종사자 3,000명 이상 · 연간 방문객 약 1,000만 명", "https://granvilleisland.com/about-us"],
  ["운영상 문제", "에밀리 카 대학 이전 (2017)과 시설 노후 (유지보수 필요 약 6,000만 달러 추산, 2014 글로브 앤 메일) · 별도 법인이 아니어서 차입 불가 — 관리 주체 변경 논의"],
 ],
 "operationNote": [
  "그랜빌 아일랜드는 CMHC 가 임대료와 주차 요금만으로 운영비와 시설 투자를 충당하는 자립형 공공 운영 모델입니다. 체인점 대신 지역 상인 · 장인 · 문화 단체를 골라 임대하고, 예술가에게는 일반 사업체보다 낮은 임대료를 받습니다.",
  "팬데믹으로 방문객이 줄자 연방 긴급 지원 (최대 2,170만 캐나다달러)을 받았고, 차입을 할 수 없는 구조 때문에 큰 시설 투자 재원이 과제로 남아 있습니다.",
 ],
 "missing": [
  "주요 입주 시설 일부 (극장 7곳 전체 이름, 공방 · 갤러리 대표 입주자)는 확인된 자료를 찾지 못했습니다.",
  "그랜빌 아일랜드의 연간 임대 · 주차 수입과 운영비 금액은 확인된 자료를 찾지 못했습니다.",
  "그랜빌 아일랜드 신탁의 정확한 설립 연도 (1973년설 · 1976년설)와 근거 문서는 확인된 자료를 찾지 못했습니다.",
  "CMHC 와 밴쿠버 시가 함께 만든 「그랜빌 아일랜드 참조 문서 (Reference Document)」(1978년으로 알려짐)의 원문 · 허용 용도 · 면적 기준은 확인된 자료를 찾지 못했습니다 (시의회 페이지 접근 불가).",
  "연면적 · 용적률 수치는 확인된 자료를 찾지 못했습니다.",
  "재개발 당시 참여한 주민단체 · 시민단체는 확인된 자료를 찾지 못했습니다.",
  "연방 정부의 1973년 토지 인수 가격은 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Granville Island's first major retail and restaurant redevelopment near completion — Daily Hive (2023.11)", "u": "https://dailyhive.com/vancouver/chain-forge-building-granville-island"},
  {"t": "Arts Club Theatre Company — Wikipedia", "u": "https://en.wikipedia.org/wiki/Arts_Club_Theatre_Company"},
  {"t": "Granville Island Public Market — Wikipedia", "u": "https://en.wikipedia.org/wiki/Granville_Island_Public_Market"},
  {"t": "Overview (Mission · Vision) — Granville Island Administration", "u": "https://admin.granvilleisland.com/about-granville-island/mission-vision/"},
  {"t": "CMHC Granville Island Rent Relief Program FAQs — Granville Island Administration", "u": "https://admin.granvilleisland.com/faqs/"},
  {"t": "About Granville Island — granvilleisland.com (CMHC 운영 공식 사이트)", "u": "https://granvilleisland.com/about-us"},
  {"t": "How Granville Island Came to Be — Project for Public Spaces", "u": "https://www.pps.org/article/how-granville-island-came-to-be"},
  {"t": "CMHC's Story — Canada Mortgage and Housing Corporation", "u": "https://www.cmhc-schl.gc.ca/about-us/cmhcs-story"},
  {"t": "About — Granville Island 2040", "u": "https://granvilleisland2040.ca/about/"},
  {"t": "Granville Island receives up to $21.7 million for pandemic recovery efforts in the Federal Budget — CMHC/Granville Island (Newswire, 2021)", "u": "https://www.newswire.ca/news-releases/granville-island-receives-up-to-21-7-million-for-pandemic-recovery-efforts-in-the-federal-budget-885398357.html"},
  {"t": "Granville Island enters transition period — The Globe and Mail", "u": "https://www.theglobeandmail.com/news/british-columbia/granville-island-enters-transition-period/article19578293/"},
  {"t": "Opinion: Change of Granville Island's ownership needed for revitalization — Daily Hive", "u": "https://dailyhive.com/vancouver/granville-island-federal-ownership-cmhc-revitalization"},
  {"t": "Granville Island Public Market — Places That Matter (Vancouver Heritage Foundation)", "u": "https://www.placesthatmatter.ca/place-that-matters/granville-island-public-market/"},
  {"t": "Granville Island — Wikipedia", "u": "https://en.wikipedia.org/wiki/Granville_Island"},
  {"t": "Granville Island — Wikipédia (français)", "u": "https://fr.wikipedia.org/wiki/Granville_Island"},
  {"t": "Ron Basford — Wikipedia", "u": "https://en.wikipedia.org/wiki/Ron_Basford"},
  {"t": "Emily Carr University of Art and Design — Wikipedia", "u": "https://en.wikipedia.org/wiki/Emily_Carr_University_of_Art_and_Design"},
 ],
},
}

# ── 보강 (정책 조사 04 : 미국 · 캐나다 제도 원문 확인분, 2026-10) ──────────────────────────
D["lowell-mills"]["laws"].append(
 ["연방 역사건물 재생 세액공제 (Internal Revenue Code §47)", "국가 사적 · 등록 역사지구의 수익용 건물을 내무장관 재생 기준에 맞춰 고치면 적격 공사비의 20% 를 세액공제 — 2017년 감세법 (Public Law 115-97) 이후 5년에 나눠 청구, NPS · IRS · 주 역사보존국 공동 운영", "https://www.irs.gov/businesses/small-businesses-self-employed/rehabilitation-credit"])
D["lowell-mills"]["refs"] += [
 {"t": "Rehabilitation Credit — IRS", "u": "https://www.irs.gov/businesses/small-businesses-self-employed/rehabilitation-credit"},
 {"t": "Federal Historic Preservation Tax Incentives — NPS", "u": "https://www.nps.gov/subjects/taxincentives/index.htm"},
]

D["pearl-district"]["zoning"].append(
 ["시 전체 산업용지와의 관계", "포틀랜드는 도심 창고지 (펄)를 혼합 용도로 바꾼 한편, 항만 · 철도 · 공항이 있는 포틀랜드 하버 · 컬럼비아 코리도어 · 브루클린 야드는 2018년 「핵심 산업용지 중첩지구 (Prime Industrial Overlay, 시 법전 33.471)」로 묶어 공업 개발 용량을 줄이는 전환을 금지하거나 상쇄를 요구합니다", "https://portland.gov/sites/default/files/code/33.471-prime-industrial-overlay-zone.pdf"])
D["pearl-district"]["lesson"].append(
 "같은 도시 안에서 \"전환할 곳 (도심 창고지)\"과 \"지킬 곳 (항만 · 물류 산업지)\"을 지도로 나눈 점 — 한국 노후 공업지역 전환도 지킬 산업용지의 선을 함께 그어야 합니다.")
D["pearl-district"]["refs"] += [
 {"t": "Chapter 33.471 Prime Industrial Overlay Zone — Portland Zoning Code", "u": "https://portland.gov/sites/default/files/code/33.471-prime-industrial-overlay-zone.pdf"},
 {"t": "Lester, Kaza & Kirk (2013) Making Room for Manufacturing: Understanding Industrial Land Conversion in Cities. JAPA 79(4)", "u": "https://doi.org/10.1080/01944363.2014.915369"},
]

D["granville-island"]["lesson"].append(
 "메트로 밴쿠버에서 산업용지는 지역 면적의 4% 지만 일자리의 27% 를 맡고 땅값이 북미 최고 수준이어서, 광역 정부가 「광역 산업용지 전략 (2020)」 · 「Metro 2050 (2023)」으로 산업용지를 지키고 다층화를 권합니다 — 시장 · 예술과 가동 공장을 한 섬에 남긴 그랜빌 아일랜드는 이런 \"생산 공간 보존형 재생\"의 이른 사례로 읽을 수 있습니다.")
D["granville-island"]["refs"] += [
 {"t": "Regional Industrial Lands Strategy — Executive Summary (Metro Vancouver, 2020)", "u": "https://metrovancouver.org/services/regional-planning/Documents/regional-industrial-lands-strategy-executive-summary.pdf"},
 {"t": "Metro 2050 Implementation Guideline — Industrial and Employment Lands (Metro Vancouver, 2023)", "u": "https://metrovancouver.org/services/regional-planning/Documents/metro-2050-implementation-guideline-industrial-and-employment-lands.pdf"},
]
