# -*- coding: utf-8 -*-
# 도시재생 노트 — 더 자세한 본문 01 (22@ 바르셀로나 · 스트레이프-S · 카우룽 이스트 · 브루클린 해군 조선소 · 아들러스호프)
#  regen*.py 의 같은 id 를 덮어씀. 열어서 확인한 출처만 refs 에 넣었고, 확인하지 못한 것은 missing 에 적었습니다.
D = {
"22at-barcelona": {
 "spec": [
  ["위치", "스페인 바르셀로나 산 마르티 구 (Sant Martí) 포블레노우 (Poblenou) — 글로리에스 광장 (Plaça de les Glòries Catalanes) 중심"],
  ["면적", "198.26ha — 세르다 확장지구 (Eixample) 격자 블록 115개"],
  ["기간", "2000년 계획 승인 → 2017년 재검토 「22@ 다시 생각하기 (Repensem el 22@)」 → 2022년 5월 31일 개정 계획 확정 → 진행 중"],
  ["원래 용도", "19세기 \"카탈루냐의 맨체스터\" — 섬유 공장 중심의 공업지대, 1960~70년대 이후 작업장 · 창고 · 차고 · 운송업체가 들어선 노후 공업지"],
  ["변경 용도", "@활동 (지식집약 생산활동) · 7@ 지식 관련 공공시설 · 공공주택 · 녹지 혼합 — 미디어 · 정보통신 · 에너지 · 디자인 · 바이오 5대 클러스터"],
  ["원래 용도지구", "22a — 공업 전용 (1976년 메트로폴리탄 총괄계획 PGM'76)"],
  ["변경 용도지구", "22@ — 지식집약 생산활동과 주거 · 시설이 섞이는 새 용도지구 (MPGM 2000)"],
  ["계획 규모 (2000)", "총 연면적 400만㎡ (생산활동 320만㎡ · 시설 · 주거 등 80만㎡), 새 공공주택 4,000호 (25% 이상 임대), 기존 주택 4,614호 합법화, 새 녹지 11.4만㎡ · 시설 용지 14.5만㎡, 기반시설 투자 1억 8천만 유로"],
  ["개정 계획 (2022)", "새 주택 7,800호 (80% 공공 보호주택), 거리 셋 중 하나를 녹색 축으로, 보행 · 녹지 비율 40% → 70%, 남은 개발 연면적에서 일자리 약 6만 개 목표"],
 ],
 "from": "노후 공업지역 (섬유 공장 · 작업장 · 창고)",
 "to": "지식기반 혁신지구 (@활동 · 공공주택 · 7@ 시설 · 녹지 혼합)",
 "zoneFrom": "22a 공업지구 (PGM 1976)",
 "zoneTo": "22@ 지식집약 활동지구 (MPGM 2000, 2022 개정)",
 "tenants": [
  ["첨단산업 · 미디어 기업 (본사)", "메디아프로 (Mediapro)", "2008년 디아고날 177번지 메디아프로 빌딩 (설계 OAB) — 22@ 미디어 클러스터의 대표 입주사", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["첨단산업 · IT 기업 (사무)", "인드라 (Indra)", "2009년 탕헤르 거리 99번지 인드라 빌딩 (b720 Fermín Vázquez 설계)", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["첨단산업 · 글로벌 IT 기업", "야후! 연구소 (Yahoo! I+D) · 마이크로소프트 (Microsoft) · SAP · 캡제미니 (Capgemini) · NTT 데이터 (NTT Data)", "2001년 이후 입주한 대표 기업 (영문 위키, 2011년 무렵 기준 — 현재 입주 여부는 확인하지 못함)", "https://en.wikipedia.org/wiki/22@"],
  ["첨단산업 · 제약 · 에너지 기업", "사노피-아벤티스 (Sanofi-Aventis) · 슈나이더 일렉트릭 (Schneider Electric)", "2001년 이후 입주 (영문 위키, 2011년 무렵 기준)", "https://en.wikipedia.org/wiki/22@"],
  ["첨단산업 · 창업 · 공공 인큐베이터", "미디어-TIC 빌딩 (Edifici Media-TIC) · 바르셀로나 액티바 (Barcelona Activa) · 바이오메디컬 파크", "미디어-TIC 는 2009~2010 완공 (Roc Boronat 117, Enric Ruiz-Geli 설계), 2010년 22@ 광섬유망 연결 — 창업 보육 · 기술 센터", "https://ajuntament.barcelona.cat/pressupostosifinances/sites/default/files/inline-files/2010%20Informe%20anual%20GEIM.pdf"],
  ["업무 · 공공기관 본부", "통신시장위원회 (CMT, Comisión del Mercado de las Telecomunicaciones)", "2010년 볼리비아 거리 56번지 신사옥 (옛 Josep Canela 공장 터, GCA 설계)", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["업무 · 상징 업무빌딩", "글로리에스 탑 (Torre Glòries, 옛 Torre Agbar)", "2005년 완공 (장 누벨 + 페르민 바스케스) — 22@의 상징 업무 빌딩", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["업무 · 법률 · 광고", "쿠아트레카사스 (Cuatrecasas) 본사 · 바사트 오길비 (Bassat Ogilvy)", "쿠아트레카사스 본사 2017 (디아고날 191-193), 바사트 오길비 신사옥 2010년 완공 단계", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["첨단산업 · 대학", "폼페우 파브라 대학 (UPF) 포블레노우 캠퍼스 · 카탈루냐 개방대학 (UOC) · BAU 디자인 대학", "UPF 는 옛 섬유공장 Ca l'Aranyó, UOC · 바르셀로나 액티바는 Can Jaumandreu, BAU 는 Francisco Munné 공장에 입주", "https://cdn.dreso.com/fileadmin/media/10_Landingpages/Re-Building/Dossier22@English_p-komprimiert.pdf"],
  ["문화 · 박물관", "바르셀로나 디자인 박물관 (Museu del Disseny, Disseny Hub) · 자연과학 박물관 (Edifici Fòrum)", "디자인 박물관 2014 (MBM 설계), 자연과학 박물관은 2004 포럼 건물 (Herzog & de Meuron)", "https://es.wikipedia.org/wiki/Distrito_22@"],
  ["문화 · 미술관 · 예술센터", "빌라 카사스 재단 (Fundació Vila Casas, Can Framis) · 행가르 (Hangar)", "옛 공장 Can Framis 를 미술관으로, 예술 연구센터 행가르는 2010년 확장 공사 착수", "https://cdn.dreso.com/fileadmin/media/10_Landingpages/Re-Building/Dossier22@English_p-komprimiert.pdf"],
  ["업무 · 의료 공공기관", "카탈루냐 혈액 · 조직 은행 (Banc de Sang i Teixits)", "2010년 라파엘 캄팔란스 거리 2번지 신축 (SaAS 설계)", "https://es.wikipedia.org/wiki/Distrito_22@"],
 ],
 "timeline": [
  ["1953", "광역계획 (Pla Comarcal)이 도시 안 생산 용지를 공업 전용으로 묶음 — 공업지역 안 주택 수천 호가 이때부터 법적으로 불안정한 상태가 됨"],
  ["1976", "메트로폴리탄 총괄계획 (PGM)에서 포블레노우를 22a 공업지구로 지정"],
  ["2000.7.27", "「포블레노우 공업지역 재생을 위한 총괄계획 변경 — 22@BCN 활동지구 (MPGM)」 최종 승인 (10.27 기반시설 특별계획 PEI 승인), 22a → 22@ 용도지구 도입 · 같은 해 포블레노우 산업유산 특별보호계획 (PEPA, 36개 건물 목록)"],
  ["2000.11.10", "시 출자 공기업 22 ARROBA BCN, S.A.U. 설립 (2000.7.21 시의회 결정) — 사업 관리 · 홍보"],
  ["2003~2005", "옛 공장 3곳 (Passatge del Sucre · Can Gili Vell · Can Gili Nou)을 로프트 주거로 바꾸는 도시개선계획 (PMU) 승인 — 로프트 139호"],
  ["2004", "캔 리카르트 (Can Ricart) 작업장 가동 종료 · 바르셀로나 포럼 개최 — 반대 운동 (Fotut 2004 등)"],
  ["2005~2006", "캔 리카르트 철거와 아파트 건설 계획에 주민 반발 — 「캔 리카르트를 지키자 (Salvem Can Ricart)」 · 「리베라 플랫폼 (Plataforma de la Ribera)」이 공사를 멈춤"],
  ["2006.11.24", "산업유산 보호계획 개정 최종 승인 — 보호 대상 114개 요소 (기존 46 + 신규 68)로 확대"],
  ["2008.4.22", "카탈루냐 정부가 캔 리카르트 건물군 (1852~1854, 건축가 Josep Oriol i Bernadet, 직물 날염 공장)을 국가 문화재 (BCIN, 역사 단지)로 지정 — 정부 보도자료 (Diputació 자료의 2007년은 틀림)"],
  ["2012.6", "옛 공업 용지의 70%에서 재생 착수, 도시개선계획 141건 (그중 85건 민간 제안)"],
  ["2013", "22 ARROBA BCN 법인 소멸 등기"],
  ["2017", "시가 참여 과정 「22@ 다시 생각하기 (Repensem el 22@)」 시작 — 1,000명 이상 참여"],
  ["2018", "시민 · 기업 · 대학 · 행정 4자 협약 「더 포용적이고 지속가능한 22@가 있는 포블레노우를 향해」 서명"],
  ["2020.9.30", "개정 계획 (MpPGM 22@) 시의회 위원회 1차 승인 · 2022.2.25 본회의 잠정 승인"],
  ["2022.5.31", "바르셀로나 도시계획 소위원회가 개정 계획을 최종 승인 — 발효"],
  ["2023.9", "포블레노우 주민 관측소 (Observatori dels Barris del Poblenou) 보고서 — 지어진 사무실의 42%가 비어 있다고 발표, 22@ 기업 협회는 사무실 16%를 주택으로 바꾸자고 제안 (컨설팅사 Savills 는 공실률을 더 낮게 봄)"],
  ["2024.10~2025.1", "기존 공장 건물에 교육 · 문화 · 체육시설을 넣을 수 있게 하는 추가 개정 참여 과정"],
 ],
 "problem": [
  "20세기 후반 섬유 산업이 쇠퇴하고 공장이 교외로 빠져나가면서, 1980~2000년 포블레노우의 공장 건물이 대거 비거나 낮은 밀도의 작업장 · 창고로만 쓰였습니다.",
  "22a 공업 전용 지정 때문에 새 산업이나 주거가 들어올 수 없었고, 1953년 이후 공업지역 안의 주택 약 4,600호가 법적으로 인정받지 못한 상태였습니다.",
  "2000년 계획 승인 당시 지역 기반시설 (도로 · 전력 · 통신 등)이 \"분명히 부족\"하다고 진단되었습니다 (22@ 계획 자료).",
  "도시 한가운데 200ha 가까운 땅을 지식경제의 생산 거점으로 바꿔 바르셀로나 경제 활동에서 이 지역 비중을 4%에서 15% 이상으로 끌어올리겠다는 목표가 있었습니다.",
  "2010년대 후반에는 업무 · 호텔 위주 개발과 주거 부족, 남은 40%의 미개발 땅이 새 과제가 되어 2017년부터 계획을 다시 손보았습니다.",
 ],
 "overview": [
  "22@는 옛 공업지역을 주거 단지로 바꾸지 않고, \"생산하는 도시\"의 성격을 지식집약 산업으로 이어 가는 전략입니다. 공업 전용 22a 지구를 22@ 지구로 바꾸면서 기능을 나누지 않고 블록 안에 일터 · 공공주택 · 7@ 지식시설 · 녹지를 섞는 콤팩트 혼합 모델을 택했습니다.",
  "계획은 건물 모양을 미리 정하지 않고 토지 소유자의 권리와 의무만 정했습니다. 블록 전체 · 반 블록 · 2,000㎡ 이상 필지 · 보존할 공장 건물 · 주거 전면 등 여러 단위의 하위 계획 (도시개선계획 PMU · 특별계획)으로 민간이 스스로 바꾸도록 하고, 시는 6개 전략 구역을 직접 이끌었습니다. 2012년 6월까지 141건의 계획이 승인되었습니다.",
  "2022년 개정 계획은 남은 40%의 땅을 대상으로 주거와 녹지를 크게 늘렸습니다. 기존 주택과 공업 조직을 모두 보호하고, 거리 셋 중 하나를 녹색 축 (Almogàvers · Pujades · Doctor Trueta · Bolívia · Cristóbal de Moura 등)으로 바꾸며, 이미 지어진 블록은 직접 허가로, 빈 땅은 별도 계획으로 바꾸는 두 갈래로 절차를 줄였습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "베네데타 탈리아부에 (Benedetta Tagliabue) · EMBT", "캔 리카르트 「언어의 집 (Casa de les Llengües)」 설계 공모 당선 (2007, 2011년 사업 취소)"],
  ["도시계획가 · 건축가", "장 누벨 (Jean Nouvel) + 페르민 바스케스 (Fermín Vázquez)", "글로리에스 탑 (Torre Agbar, 2005) — 22@의 상징 건물"],
  ["도시계획가 · 건축가", "A+M arquitectes · MBM Arquitectes 등", "옛 공장 Can Saladrigas 개조 (2002), 바르셀로나 디자인 박물관 (2014) 등 개별 건물"],
  ["주관 기관", "바르셀로나 시의회 (Ajuntament de Barcelona)", "2000년 계획 승인 · 2022년 개정 주도, 6개 전략 구역 직접 개발, 공공주택 · 시설 공급"],
  ["주관 기관", "바르셀로나 도시계획 소위원회 (Subcomissió d'Urbanisme de Barcelona)", "2022년 5월 31일 개정 계획 최종 승인"],
  ["사업 시행", "22 ARROBA BCN, S.A.U. (시 소유 공기업, 2000~2013 소멸)", "22@ 공업 · 생산지역 도시계획 사업의 실행 · 관리, 산업유산 홍보 (2010 방문 안내서)"],
  ["관련 기관", "카탈루냐 자치정부 (Generalitat de Catalunya)", "캔 리카르트 문화재 지정, 언어의 집 공모"],
  ["민간", "토지 소유자 · 민간 개발자", "141건 계획 중 85건을 민간이 제안 (2012), 용지 기부 · 기반시설 비용 분담"],
  ["대학 · 연구", "폼페우 파브라 대학 (UPF) · 바르셀로나 대학 (UB) · 카탈루냐 공대 (UPC) · 카탈루냐 개방대학 (UOC)", "옛 공장 (Ca l'Aranyó · Can Jaumandreu 등)에 캠퍼스 · 지식 거점"],
  ["시민단체", "「캔 리카르트를 지키자 (Salvem Can Ricart)」 · 「리베라 플랫폼 (Plataforma de la Ribera)」 · 포블레노우 주민회", "2005~2006 캔 리카르트 철거 저지, 산업유산 보호 확대를 이끌어 냄"],
  ["시민 참여", "22@ 확대위원회 (Comissió Ampliada del 22@)", "주민 · 사회 · 경제 주체로 구성 — 2017년 이후 재검토 과정 감독"],
 ],
 "laws": [
  ["메트로폴리탄 총괄계획 (PGM, 1976)", "포블레노우를 22a 공업 전용지구로 지정 — 재생 이전의 규제"],
  ["포블레노우 공업지역 재생을 위한 총괄계획 변경 — 22@BCN 활동지구 (MPGM 22@, 2000)", "22a → 22@ 용도지구. 지식집약 활동 · 공공주택 · 7@ 시설 허용, 용적률 상향과 용지 기부 · 기반시설 부담을 묶음. 하위 계획 유형 (블록 · 반 블록 · 2,000㎡ 필지 · 공장 건물 · 주거 전면 · 공공시설 특별계획)을 조항으로 정함"],
  ["기반시설 특별계획 (Pla Especial d'Infraestructures, PEI)", "22@ 안 도로 37km 재정비 — 전력망 · 지역 냉난방 · 쓰레기 관로 수거 · 광통신망 · 공동구, 총 투자 1억 8천만 유로 이상"],
  ["산업유산 특별보호계획 (PEPA, 2000 · 2006 개정)", "2000년 36개 건물 → 2006년 개정으로 114개 요소 보호 (캔 리카르트만 최고 등급 A)"],
  ["도시개선계획 (PMU, Pla de Millora Urbana)", "블록 단위 세부 계획 — 대부분 민간 제안, 시 승인"],
  ["더 포용적이고 지속가능한 22@를 위한 총괄계획 변경 (MpPGM 22@, 2022.5.31 확정)", "주택 확대 (새 주택 7,800호 중 80% 보호주택), 기존 주택 · 공업 조직 보호, 녹색 축, 새 용도 (녹색 · 순환경제, 사회연대경제, 인더스트리 4.0) 허용, 직접 허가로 절차 단축", "https://ajuntament.barcelona.cat/ecologiaurbana/mpgm22@/ca/"],
  ["22@ 계획 규범 조정을 위한 부분 개정 (MpMPGM22@, 2024~2025 참여 과정)", "보호 파사드가 있는 22@ah 공장 건물에 교육 · 문화 · 체육시설 허용, PMU 수립 기준 · 권고 마련, 오류 정정, 도시계획 관리 단가 (부록 II) 갱신", "https://ajuntament.barcelona.cat/ecologiaurbana/ca/amb-qui-ho-fem/participacio-ciutadana/nu-22a"],
  ["4자 협약 「더 포용적이고 지속가능한 22@가 있는 포블레노우를 향해」 (Cap a un Poblenou amb un 22@ més inclusiu i sostenible, 2018)", "Repensem el 22@ (2017) 참여 과정의 결과 — 2019년 개정 계획의 기준 문서로 이어짐"],
 ],
 "lawsNote": ["규제완화의 핵심은 공업만 허용하던 22a를 지식집약 생산활동 · 주거 · 시설의 혼합 (22@)으로 넓히고 용적률을 올려 준 것입니다. 그 대가로 용지의 30%를 공공에 기부하고 기반시설 비용을 나눠 내게 한 \"권리-의무 교환\"이 제도의 뼈대입니다. 2022년 개정은 생산활동 위주에서 주거 · 녹지 비중을 높이는 쪽으로 방향을 바꾸었습니다."],
 "tools": [
  ["용적률 완화", "블록 순 용적률을 2.0 → 3.0㎡/㎡로 상향, 민간 몫은 2.0 → 2.7 — 공공주택 · 7@ 시설을 넣는 조건으로 단계별 (2.0 · 2.2 · 2.7 · 3.0) 인센티브"],
  ["용도변경", "22a 공업 전용 → 22@ (지식집약 @활동 의무 포함) 혼합"],
  ["공공 기여 (용지 기부)", "용지의 10% 7@ 시설 · 10% 공공주택 · 10% 녹지를 무상 기부, 별도로 도시계획 기부 10%"],
  ["기반시설 재원", "기반시설 특별계획 비용의 일부를 토지 소유자가 부담 — 총 1억 8천만 유로 이상"],
  ["기존 주택 합법화 · 공공주택", "공업지역 안 기존 주택 4,614호 합법화, 공공주택 4,000호 계획 (25% 이상 임대) — 2012년까지 민간 계획으로 보호주택 1,886호 허가"],
  ["산업유산 활용 인센티브", "보존 가치가 있는 공장 건물은 로프트 주거 등 비전통 주거로 바꿀 수 있게 허용"],
  ["클러스터 · 창업 지원", "미디어 · ICT · 에너지 · 디자인 · 바이오 클러스터, 바이오메디컬 파크 · 미디어-TIC 빌딩 · 바르셀로나 액티바 창업보육"],
 ],
 "zoning": [
  ["지정", "22@ 용도지구 — 198.26ha, 115개 블록 (2000), 2022년 개정 계획 구역"],
  ["관리 주체 · 방식", "시가 6개 전략 구역을 직접 개발하고, 나머지는 민간이 PMU · 특별계획을 제안 → 시 승인. 2022년부터는 기존 블록 (전체의 19.5%, 「존치 구역」)은 직접 허가, 빈 땅 (17.7%, 「전환 구역」)은 별도 계획"],
  ["보존 관리", "산업유산 특별보호계획 114개 요소, 캔 리카르트는 카탈루냐 국가 문화재 (Bé Cultural d'Interès Nacional, 2008.4.22 지정)", "https://govern.cat/salapremsa/notes-premsa/96095/el-govern-declara-be-cultural-d-interes-nacional-un-grup-d-edificis-de-can-ricart-a-barcelona-i-el-santuari-del-miracle-a-riner"],
  ["참여 기구", "22@ 확대위원회가 계획 재검토와 결과를 감독"],
 ],
 "zoningNote": ["2020년 시 발표에 따르면 개정 뒤 최종 비율은 경제활동 70% · 주거 30% (2000년에는 주거 10%)이며, 2000년 계획에서 남은 물량을 합쳐 앞으로 15,800호가 지어질 예정입니다 (Ara 보도)."],
 "funding": [
  ["기반시설 투자", "기반시설 특별계획 (PEI) 총 투자 1억 8천만 유로 이상 — 도로 37km 재정비, 지역 냉난방 · 쓰레기 관로 · 광통신망 · 전력망 (22@ 계획 자료)", "https://cdn.dreso.com/fileadmin/media/10_Landingpages/Re-Building/Dossier22@English_p-komprimiert.pdf"],
  ["민간 부담", "기반시설 특별계획 비용의 일부를 토지 소유자가 부담 (개발 권리의 대가)"],
  ["토지 · 용지 기부 (현물)", "용지의 30% (7@ 시설 10% · 공공주택 10% · 녹지 10%)와 도시계획 기부 10%를 무상으로 시에 기부"],
  ["민간 투자", "2012년 6월까지 계획 141건 중 85건이 민간 제안 — 생산활동 지상 연면적 69만 4,860㎡ · 보호주택 1,886호 허가"],
  ["카탈루냐 정부", "캔 리카르트 유지 · 관리 작업에 25만 유로 (Diputació de Barcelona 자료)", "https://www.diba.cat/en/web/espais-buits/detall/-/contingut/25265758/fitxa16-can-ricart"],
  ["바르셀로나 시", "캔 리카르트 대학 이용 협약 (2013) 뒤 3개월간 건물 손상 방지에 20만 8천 유로, 개조 공사비는 바르셀로나 대학 부담"],
  ["시 공기업 투자 (22 ARROBA BCN, 2007~2010)", "연간 투자 2007 2,199.8만 · 2008 1,657.4만 · 2009 1,297.8만 · 2010 2,388.8만 유로 — 거의 전부 시를 대신한 투자 (2010 2,387.5만), 재원은 시 재정 2,336.3만 · 자체 수입 51.2만 유로 (2010)", "https://ajuntament.barcelona.cat/pressupostosifinances/sites/default/files/inline-files/2010%20Informe%20anual%20GEIM.pdf"],
  ["자체 수입 변화", "22 ARROBA BCN 자체 수입 2007 1,011만 → 2008 483만 → 2009 596.3만 → 2010 51.2만 유로, 시 재정 2007 1,176.2만 → 2010 2,336.3만 유로 (2010 시 공기업 연차보고서)"],
 ],
 "operation": [
  ["운영 주체 (2000~2013)", "시 소유 공기업 22 ARROBA BCN, S.A.U. — 22@ 도시계획 사업 실행 · 관리 · 홍보, 2013년 법인 소멸 등기"],
  ["운영 주체 (현재)", "바르셀로나 시 도시계획 부서 — 「22@ 원스톱 창구 (Servei de Finestreta Única 22@)」로 기업 · 개인의 사업 · 인허가 업무 지원, 2020년 시가 22@ 기술사무소 (Oficina Tècnica del 22@) 복원 발표 (Ara)", "https://ajuntament.barcelona.cat/ecologiaurbana/mpgm22@/ca/"],
  ["기업 협회", "22@ Network Barcelona — 회원사 가입으로 운영되는 기업 협회, 네트워킹 · 위원회 · 교육 · 22@ 투어 · 사회경제 지표 (Baròmetre)", "https://www.22network.net/fes-te-soci-beneficis/?lang=ca"],
  ["재원 구조", "개발 단계에서 토지 소유자가 기반시설 비용 · 용지를 부담 (권리-의무 교환) — 지구 전체를 운영하며 임대 수입을 얻는 단일 운영사는 없음"],
  ["운영상 문제", "업무 · 호텔 위주 개발, 주거 부족, 남은 40% 미개발 — 2017년 이후 재검토 · 2022년 개정 계획"],
  ["공기업 규모 · 수지 (2007~2010)", "평균 직원 2007 28 · 2008 36 · 2009 38 · 2010 27명, 회계상 순이익 2010 36.4만 유로, 총자산 2,509.9만 유로 (2010.12.31)", "https://ajuntament.barcelona.cat/pressupostosifinances/sites/default/files/inline-files/2010%20Informe%20anual%20GEIM.pdf"],
  ["업무 이관 (2010)", "2010.3.11 시장 명령으로 경제 진흥 업무를 바르셀로나 액티바 (Barcelona Activa)로 통합 (2010.5.7 협약, 5.15 발효), 행정 · 재무 · 법무는 시 기반시설 공기업 BIMSA 로 집중 (2010.11.26 위탁)"],
  ["사업 실적 (2010 말)", "옛 공업지역의 약 69% 재생 착수, 최종 승인 계획 127건 중 80건 (62.9%) 민간 주도 — 공공 주도 6개 구역은 92만 5,482㎡ (전환 대상의 47%)"],
  ["임대 수입 사업", "22@ 광섬유망의 다크 파이버 임대 계속 — 2010년 건물 14동 신규 연결"],
  ["운영상 문제 (사무 공실, 2023)", "주민 관측소 조사로 사무실 42% 공실 (전체 빌딩이 빈 곳: Pere IV 105 · Àlaba 111 등), 22@ Network 는 노후 사무실 16% 주거 전환 제안", "https://www.vilaweb.cat/noticies/el-buidatge-de-les-oficines-del-22-empeny-el-districte-a-reconvertir-se-es-un-model-de-fracas/"],
 ],
 "operationNote": ["22@는 시가 계획 · 인허가로 지구를 관리하고 개발 비용을 토지 소유자에게 부담시키는 구조입니다. 초기에는 시 공기업 22 ARROBA BCN 이 사업을 관리 · 홍보했고, 지금은 시의 원스톱 창구와 기업 회원 협회 (22@ Network)가 지구의 일상 운영 · 네트워킹을 맡고 있습니다."],
 "famous": [
  "유럽 최대 규모의 도시재생 사업 가운데 하나로 꼽히며, 옛 \"카탈루냐의 맨체스터\" 115개 블록 · 198ha 를 혁신지구로 바꾸는 사업입니다 (영문 위키).",
  "\"혁신지구 (Districte de la Innovació)\"라는 개념의 대표 사례로, 2000~2011년 약 4,500개 기업 · 5만 6천 명 일자리가 새로 들어왔다고 알려졌습니다 (22@ 자료 · Metropolis 사례집).",
  "장 누벨의 글로리에스 탑 (Torre Agbar, 2005), 디자인 박물관 등 건축 명소가 모인 곳입니다.",
  "주민 운동으로 산업유산 보호 대상이 114개로 늘고 캔 리카르트가 국가 문화재가 된, 산업유산 보존 논쟁의 대표 사례입니다.",
  "2017년 「22@ 다시 생각하기」에 1,000명 이상이 참여해 계획을 다시 쓴, 혁신지구의 \"2세대 개정\" 사례로도 주목받습니다.",
 ],
 "result": [
  "2000~2011년 약 4,500개 기업 입주 (47.3%가 신생 창업), 약 31%가 기술 · 지식기반 기업 (영문 위키, 22@ 자료)",
  "2012년 기준 포블레노우 일대 7,000개 기업 · 9만 명 고용, 그중 4,500개 기업 · 5만 6천 명이 2000년 이후 입주 (22@ 계획 자료)",
  "2012년까지 옛 공업 용지의 70%에서 재생 착수, 계획 141건으로 지상 연면적 303만㎡ 확보",
  "거주 인구 2001년 73,464명 → 90,214명 (22.8% 증가, 영문 위키 — 출처 표시 요구 상태)",
  "2023년 9월 주민 관측소 조사: 22@ 사무실 공실 42%, 짓고 있는 건물까지 비면 53% — 주민 단체는 \"실패한 모델\"이라고 비판 (3CatInfo · VilaWeb)",
 ],
 "lesson": [
  "공업지역을 주거로 바꾸지 않고 \"도시형 지식 생산지구\"로 바꿔 일자리를 지킨 모델 — 한국 노후 산단 · 준공업지역 첨단화의 가장 직접적인 참고 사례입니다.",
  "용적률 인센티브를 공공주택 · 지식시설 · 녹지 용지 기부와 맞바꾸는 \"조건부 완화\"가 핵심입니다.",
  "건물 형태를 정하지 않고 권리 · 의무만 정한 유연한 계획으로, 블록 단위의 점진적 민간 개발을 이끌었습니다.",
  "산업유산 보호는 주민 운동이 이끌어 낸 것 — 계획 단계부터 보존 목록을 정하지 않으면 갈등과 철거가 생긴다는 점을 보여 줍니다.",
  "20년 뒤 주거 · 녹지 부족이 드러나 계획을 다시 쓴 점 — 산단 재생 계획에도 중간 점검 · 개정 절차가 필요합니다.",
  "포블레노우 · 22@ 전환은 계획 수단과 부동산 동학이 생산 공간을 밀어내는 \"산업 젠트리피케이션 (industrial gentrification)\"의 대표 연구 사례로 인용됩니다 (Charnock 등 2014 · Camerin 2019 — De Boeck · Ryckewaert 2020 재인용). 바르셀로나처럼 넓은 구역 단위로 용도를 정하는 방식과 달리 브뤼셀은 블록 단위로 생산 공간을 지정해 비교 대상이 됩니다."
 ],
 "missing": [
  "주요 입주 기업의 현재 (2026) 입주 여부와 최근 입주 기업 (2015년 이후)은 일부 확인된 자료를 찾지 못했습니다.",
  "22@ Network 의 회비 · 재정과 22 ARROBA BCN 의 2011년 이후 재무는 확인된 자료를 찾지 못했습니다.",
  "22@ 전체 총사업비와 시 · 국가 공공 재원 총액은 확인된 자료를 찾지 못했습니다.",
  "2000년 MPGM 22@ 마스터플랜 수립을 맡은 도시계획가 · 건축가는 확인된 자료를 찾지 못했습니다.",
  "22@ 사업에 대한 세제 감면 · 재정 보조는 확인된 자료를 찾지 못했습니다.",
  "22 ARROBA BCN 의 2013년 해산 결정 문서는 확인된 자료를 찾지 못했습니다 (2010년 업무 이관까지만 확인).",
 ],
 "refs": [
  {"t": "El Govern declara bé cultural d'interès nacional un grup d'edificis de Can Ricart (Govern.cat, 2008.4.22)", "u": "https://govern.cat/salapremsa/notes-premsa/96095/el-govern-declara-be-cultural-d-interes-nacional-un-grup-d-edificis-de-can-ricart-a-barcelona-i-el-santuari-del-miracle-a-riner"},
  {"t": "El 22@, en crisi? Denuncien que gairebé la meitat de les oficines estan buides (3CatInfo, 2023.9.28)", "u": "https://www.3cat.cat/3catinfo/el-22-en-crisi-denuncien-que-gairebe-la-meitat-de-les-oficines-estan-buides/noticia/3252466/"},
  {"t": "El buidatge de les oficines del 22@ empeny el districte a reconvertir-se (VilaWeb, 2023.9.27)", "u": "https://www.vilaweb.cat/noticies/el-buidatge-de-les-oficines-del-22-empeny-el-districte-a-reconvertir-se-es-un-model-de-fracas/"},
  {"t": "2010 Informe anual de les empreses i institucions municipals (Ajuntament de Barcelona) — 22 ARROBA BCN, SAU", "u": "https://ajuntament.barcelona.cat/pressupostosifinances/sites/default/files/inline-files/2010%20Informe%20anual%20GEIM.pdf"},
  {"t": "22@ Network Barcelona — Fes-te soci", "u": "https://www.22network.net/fes-te-soci-beneficis/?lang=ca"},
  {"t": "22@ Barcelona — use: urban sustainability exchange (Metropolis)", "u": "https://use.metropolis.org/case-studies/22-barcelona"},
  {"t": "Districte 22@ — Viquipèdia (카탈루냐어)", "u": "https://ca.wikipedia.org/wiki/Districte_22@"},
  {"t": "Distrito 22@ — Wikipedia (스페인어)", "u": "https://es.wikipedia.org/wiki/Distrito_22@"},
  {"t": "22@ — Wikipedia (영어)", "u": "https://en.wikipedia.org/wiki/22@"},
  {"t": "22@Barcelona Plan (영문 계획 자료, 2012)", "u": "https://cdn.dreso.com/fileadmin/media/10_Landingpages/Re-Building/Dossier22@English_p-komprimiert.pdf"},
  {"t": "MpPGM 22@: Un Poblenou més inclusiu, sostenible i productiu (Ajuntament de Barcelona)", "u": "https://ajuntament.barcelona.cat/ecologiaurbana/mpgm22@/ca/"},
  {"t": "Modificació i ajust de les Normes Urbanístiques de la MPGM per un 22@ més inclusiu i sostenible (Ajuntament de Barcelona)", "u": "https://ajuntament.barcelona.cat/ecologiaurbana/ca/amb-qui-ho-fem/participacio-ciutadana/nu-22a"},
  {"t": "Barcelona engega la transformació del 22@ amb 6.500 habitatges més (Ara, 2020)", "u": "https://www.ara.cat/societat/barcelona-habitatges-poblenou-lloguer-assequible_1_1039275.html"},
  {"t": "Dot Jutgla & Pallares-Barbera, Industrial heritage, economic revitalization and urban compactness in Poblenou-22@Barcelona (BAGE 69, 2015)", "u": "https://bage.age-geografia.es/ojs/index.php/bage/article/download/1912/1828/1896"},
  {"t": "Fitxa16 — Can Ricart (Diputació de Barcelona, Espais buits)", "u": "https://www.diba.cat/en/web/espais-buits/detall/-/contingut/25265758/fitxa16-can-ricart"},
  {"t": "22 Arroba Bcn SA (extinguida) — 기업 등기 정보 (Empresite)", "u": "https://empresite.eleconomista.es/22-ARROBA-BCN.html"},
  {"t": "De Boeck, S. & Ryckewaert, M. (2020) The Preservation of Productive Activities in Brussels: The Interplay between Zoning and Industrial Gentrification, Urban Planning 5(3)", "u": "https://doi.org/10.17645/up.v5i3.3092"}
 ],
},

"strijp-s": {
 "spec": [
  ["위치", "네덜란드 노르트브라반트주 에인트호번 (Eindhoven) 스트레이프 구 (Strijp) — 도심 북서쪽, 에인트호번-덴보스 철도변"],
  ["면적", "약 27~28ha (Sur Atlas 28만㎡ · herbestemming.nl 27만㎡), 2023년 동네 면적 0.3㎢"],
  ["기간", "2000년 첫 논의 → 2001년 필립스 매각 공모 → 2002년 매각 · 마스터플랜 → 2008년 지구 용도계획 → 진행 중 (2023년 4단계 용도계획)"],
  ["원래 용도", "필립스 (Philips)의 첫 산업단지 — 1916년 전구 유리 공장으로 시작, 자연과학연구소 (NatLab), 라디오 · TV 조립, 필라이트 (philite) 생산, 보관창고"],
  ["변경 용도", "창조산업 · 디자인 · 기술 기업, 주거 (공장 개조 로프트 포함), 문화 · 행사 (더치 디자인 위크 · GLOW · STRP), 교육 (SintLucas), 식품 시장"],
  ["원래 용도지구", "산업 (단일 기업이 소유한 폐쇄 공장단지 — \"금지된 도시 (verboden stad)\")"],
  ["변경 용도지구", "지구 용도계획 (bestemmingsplan) Strijp-S (2008) — 주거 · 업무 · 문화 · 행사 혼합 (2018 · 2023 개정)"],
  ["계획 규모", "마스터플랜 주택 약 2,500호 · 사무 9.2만㎡ · 서비스 · 상업 · 문화 6.3만㎡ (Sur Atlas), 4단계 (2023) 주택 1,480호 · 업무 4.79만㎡"],
  ["총 투자", "약 13.1억 달러 (Sur Atlas 추정)"],
  ["인구", "2023년 1월 3,010명 · 주택 2,251호 (네덜란드 통계청, nl 위키)"],
 ],
 "from": "필립스 전자 공장 (전구 · 라디오 · TV) 단지",
 "to": "창조산업 · 디자인 · 주거 · 문화 혼합지구",
 "zoneFrom": "산업 (필립스 사유 공장단지)",
 "zoneTo": "지구 용도계획 Strijp-S (bestemmingsplan, 2008) — 혼합 용도",
 "tenants": [
  ["문화 · 디자인 행사", "더치 디자인 위크 (Dutch Design Week)", "매년 10월 Strijp-S 가 중심 무대 (시계탑 건물 등)", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["문화 · 영화관", "플라자 푸투라 (Plaza Futura)", "NatLab 안 — 상영관 4개 · 강당 · 공연장 · 전시실 2개 · 스튜디오, 여름 야외 무료 상영", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["첨단산업 · 미디어랩", "VPRO 미디어랩 (VPRO Medialab)", "NatLab 안 — 공영방송 VPRO 의 새 미디어 연구 · 실험", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["문화 · 미술관", "MU (하이브리드 아트하우스)", "현대미술 전시 공간으로 Strijp-S 로 이전", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["문화 · 예술학교", "예술학교 SintLucas", "2016년 입주 (2015.3 착공)", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["상업 · 식음", "푸드홀 페르스할 헷 펨 (Vershal Het Veem)", "2015년부터 보관창고 (Veemgebouw) 1층 — 지역 상인 푸드코트", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["상업 · 식음", "레스토랑 라디오 로얄 (Radio Royaal)", "2012년 기계실 (Machinekamer) 2층 — 1층은 패션 브랜드 3곳", "https://www.herbestemming.nl/projecten/strijp-s-eindhoven"],
  ["문화 · 행사장", "시계탑 건물 (Klokgebouw) 행사장 · 공연장", "2010년 개조 — 창조산업 작업실 · 팝 공연장 · 행사장 (Flying Dutch 2015년 2만 5천 명)", "https://www.herbestemming.nl/projecten/strijp-s-eindhoven"],
  ["문화 · 스포츠", "에어리어51 (Area51) 실내 스케이트 · BMX 홀", "옛 공장 홀 SEU — 철거 대신 보존하고 그 위에 Trudo 주택 「Haasje Over」 건설 (2021)", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["주거 · 공공임대 운영", "트뤼도 (Trudo) — ANTON · GERARD", "2013년 옛 TV 공장 SAN · SBP 를 임대 로프트 240호로", "https://www.herbestemming.nl/projecten/strijp-s-eindhoven"],
  ["주거 · 공공임대 운영", "보온베드레이프 (Woonbedrijf) — SPACE-S", "2017년 7개 동 402호, 주민이 설계에 참여한 주거", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["첨단산업 · 앵커 기업", "필립스 (Philips) 일부 부서", "2016년 SFH · SEY 건물에 소규모 부서 2곳 잔류 (현재 여부는 확인하지 못함)", "https://nl.wikipedia.org/wiki/Strijp-S"],
  ["주거 · 공공임대 운영", "보온베드레이프 (Woonbedrijf) — 합계", "SPACE-S · SAS-3 등 저렴한 임대주택 약 600호 공급, 4단계에 150호 추가 (2025 발표)", "https://www.woonbedrijf.com/nieuws/strijps-viert-start-laatste-bouwfase"],
 ],
 "timeline": [
  ["1916", "안톤 필립스 (Anton Philips)가 첫 공장 (전구 유리 공장) 건설"],
  ["1923", "필립스 자연과학연구소 (NatLab) 완공"],
  ["1927~1930", "라디오 공장 동 「호허 뤼흐 (Hoge Rug)」 · 1928 시계탑 건물 (Klokgebouw) · 1929 보일러동 (Ketelhuis) · 기계실 건설"],
  ["1942", "보관창고 (Veemgebouw) 완공 · 12월 6일 영국 공군 정밀 폭격 (1944.9 독일 폭격)"],
  ["1990년대", "필립스가 에인트호번에서 단계적으로 철수"],
  ["2000~2001", "재개발 첫 논의 (2000) → 필립스가 매각 · 재개발 공모 → 폴커베셀스 (VolkerWessels) 안 선정, 시와 의향서 체결"],
  ["2002", "공공-민간 합작회사 Park Strijp Beheer B.V. 가 1억 4천만 유로에 땅 매입 (위키) · West 8 마스터플랜 (2002~2005)"],
  ["2004", "Park Strijp Beheer 가 필립스로부터 토지 인수 · 도시설계안 확정 (herbestemming.nl)"],
  ["2006", "필립스 건물 철수 본격화 (10년에 걸쳐), 에인트호번 시가 시계탑 건물 매입"],
  ["2008", "지구 용도계획 (bestemmingsplan) 확정 · 유리 건물 (Glasgebouw) 임시 임대 시작 · GLOW 빛 축제 주 무대"],
  ["2010", "시계탑 건물을 창조산업 작업실 · 공연장 · 행사장으로 개조 완료"],
  ["2012", "첫 상주 주민 입주 (신축 SAS-3) · 보일러동 · 기계실 식당 개조"],
  ["2013", "옛 TV 공장 SAN · SBP → 임대 로프트 240호 (ANTON · GERARD) · NatLab 문화시설 · 네덜란드 재생상 굴던 페닉스 (Gulden Feniks) 지역전환 부문 수상"],
  ["2015~2016", "보관창고 1층 식품 시장 (Vershal Het Veem, 2015) · 역 이름 Strijp-S 로 변경 (2015) · 예술학교 SintLucas 입주 (2016)"],
  ["2018.1.23", "지구 용도계획 「Strijp-S 2017」 개정 확정"],
  ["2023.12.19", "지구 용도계획 「Strijp-S 4단계」 확정 — 주택 1,480호 · 업무 4.79만㎡"],
  ["2025", "1분기 마지막 4단계 착공 · 9.19 「Vier Strijp-S」 기념 — 4단계 주택 1,480호 · 사무 · 메이커 공간 4.79만㎡ · 시설 7,000㎡, 유리 건물에 주택 177호 착공, Woonbedrijf 임대 로프트 150호 · 작업 로프트 11호 (2028~29 완공 예정)"],
 ],
 "problem": [
  "1990년대 필립스가 에인트호번에서 생산 · 본사 기능을 단계적으로 옮기면서, 도심 가장자리의 넓은 공장지대가 비게 되었습니다.",
  "\"모래에서 고객까지 (Van zand tot klant)\" 원칙으로 모든 생산을 한 울타리 안에서 하던 폐쇄된 땅이라, 수십 년 동안 \"금지된 도시\"로 불리며 주변 동네와 단절되어 있었습니다.",
  "기술 도시 이미지를 넘어 문화 부문을 키우고 2018 유럽 문화수도 유치를 노리는 등, 도시 정체성을 새로 세울 거점이 필요했습니다 (herbestemming.nl).",
  "2008년 이후 경제 위기로 사무 수요가 사라지면서 \"한 번에 완성\"하는 계획이 어려워졌습니다.",
 ],
 "overview": [
  "필립스가 2001년 매각 공모를 열었고, 에인트호번 시와 건설사 폴커베셀스가 지분 50 : 50의 합작회사 Park Strijp Beheer 를 세워 땅 전체를 사들였습니다. 합작회사는 West 8 에 마스터플랜을 맡기고, 땅과 건물을 나눠 민간 개발자와 주택협회 (Trudo · Woonbedrijf)에 팔아 각자 개발하게 했습니다.",
  "도시설계는 철도 쪽 업무 구역 (Spoorzone), 주거 중심의 카스타녀벨던 (Kastanjevelden), 문화재가 모인 삼각지 (Driehoek) 세 부분으로 나뉩니다. 시계탑 건물 · 호허 뤼흐 · 보관창고는 국가 문화재 (rijksmonument), NatLab 은 시 문화재 (gemeentelijk monument, 공식 사이트 기준)로 보존해 행사장 · 로프트 · 식품 시장 · 영화관으로 고쳐 썼습니다.",
  "2002년에는 2020년까지 \"한 번에\" 끝낼 계획이었지만 경제 위기 뒤 개발 단위를 잘게 나누고, 빈 건물을 싸게 임시 임대하며 더치 디자인 위크 · STRP 같은 행사로 장소를 먼저 알리는 유기적 개발로 바꿨습니다. 장기 회수가 가능한 주택협회 Trudo 가 낮은 임대료로 창조 기업을 받아들인 것이 성공 요인으로 꼽힙니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "아드리안 하우저 (Adriaan Geuze) · West 8", "도시설계안 (stedenbouwkundig plan) · 마스터플랜 (2002~2005), 계획 품질을 지키는 감독 (supervisor)"],
  ["도시계획가 · 건축가", "피트 아우돌프 (Piet Oudolf) · 하르 홀란츠 (Har Hollands) · 단 로세하르더 (Daan Roosegaarde)", "배관 거리 (Leidingstraat) 정원 설계 · 빛 작품 「횃불 (Fakkel)」 · NatLab 지하도 빛 작품 「Crystal」"],
  ["사업 시행", "Park Strijp Beheer B.V.", "에인트호번 시와 폴커베셀스의 50 : 50 공공-민간 합작회사 — 토지 일괄 매입 · 분할 매각 · 공공공간 · 기반시설 조성"],
  ["주관 기관", "에인트호번 시 (Gemeente Eindhoven)", "지구 용도계획 수립 · 확정 (2008 · 2018 · 2023), 합작회사 출자, 시계탑 건물 매입 (2006)"],
  ["관련 기관", "노르트브라반트주 (Provincie Noord-Brabant)", "용도계획 승인 절차"],
  ["관련 기업", "필립스 (Philips)", "매각 공모 (2001) · 토지 매각, 일부 건물을 다시 빌려 쓰다 단계적 철수"],
  ["민간", "폴커베셀스 (VolkerWessels) · Strijp S Ontwikkeling BV · Spoorzone BV (폴커베셀스 + ING RED)", "합작 출자 · 개발"],
  ["주택협회", "트뤼도 (Trudo) · 보온베드레이프 (Woonbedrijf)", "삼각지 문화재 구역 개발 · 낮은 임대료 공간, 첫 주택 착공 (Woonbedrijf, 2010) · SPACE-S 402호 주민 참여형 주택"],
  ["문화 · 전문가 단체", "더치 디자인 위크 (Dutch Design Week) · STRP 축제 · GLOW · MU · Plaza Futura · VPRO 미디어랩", "행사 · 전시 · 영화로 장소 브랜드를 먼저 만듦"],
  ["교육", "예술학교 SintLucas (2016)", "지구 안 교육 거점"],
 ],
 "laws": [
  ["West 8 마스터플랜 (Masterplan Strijp-S, 2002~2005) · 도시설계안 (stedenbouwkundig plan, 2004)", "옛 건물 재사용 · 주거 · 업무 · 녹지 혼합의 전략 틀, 업무 (Spoorzone) · 주거 (Kastanjevelden) · 문화재 (Driehoek) 세 구역 구성"],
  ["실행계획 「브레인포트 중심 스트레이프-S 의 예술 · 문화 강화」 (Plan van Aanpak Intensivering van kunst en cultuur op Strijp-S als centrum van Brainport, 2007)", "예술 · 문화 기능을 지구 전략의 중심에 둠"],
  ["지구 용도계획 Strijp-S (bestemmingsplan, 2008)", "산업 단지를 주거 · 업무 · 문화 · 행사 혼합 용도로 변경 — 유연한 용도계획이 성공 요인으로 평가됨"],
  ["지구 용도계획 Strijp-S 2017 (2018.1.23 확정)", "기존 기능 · 건축 가능량을 유지하면서 새 도시설계안에 맞춰 건축 범위 · 높이 조정, SX 건물 일부에 \"특징 건물\" 지정", "https://zoek.officielebekendmakingen.nl/stcrt-2018-7289.html"],
  ["지구 용도계획 Strijp-S 4단계 (2023.12.19 확정)", "주택 1,480호 · 업무 4.79만㎡ (교육시설 1만㎡를 넣으면 3.79만㎡) · 공공 기능 3,500㎡ · 행사 3,500㎡, 소매 상한 2,000㎡, 소음 기준 완화 (높은 한계값 결정)", "https://zoek.officielebekendmakingen.nl/gmb-2024-38139.html"],
  ["위기 · 회복법 (Crisis- en herstelwet)", "개조 · 철거 전의 건물을 임시로 임대할 수 있게 허용"],
  ["협력 협약 (samenwerkingsovereenkomst, SOK)", "시와 Strijp S Ontwikkeling BV 사이의 재정 관계를 정함"],
  ["문화재 지정 (rijksmonument · gemeentelijk monument)", "시계탑 건물 (518769) · 호허 뤼흐 (518718) · 보관창고 (518770)는 국가 문화재, NatLab 은 시 문화재 (Strijp-S 공식 사이트 — nl 위키는 국가 문화재로 적음)", "https://www.strijp-s.nl/historie"],
 ],
 "lawsNote": ["규제완화의 핵심은 필립스 공장 부지를 시의 지구 용도계획으로 혼합 용도로 바꾸고, 위기 · 회복법으로 개발 전 건물의 임시 사용을 허용한 것입니다. 용도계획을 여러 번 (2008 · 2018 · 2023) 고쳐 시장 수요에 맞춰 단계별로 물량을 조정했습니다."],
 "tools": [
  ["토지 일괄 매입 (PPP)", "합작회사가 필립스 땅 전체를 1억 4천만 유로에 매입 → 필지로 나눠 개발자 · 주택협회에 매각"],
  ["공공 재정", "시가 보조금으로 합작회사에 출자, 용도 변경으로 오른 땅값을 회수 (Sur Atlas)"],
  ["용도변경", "산업 → 주거 · 업무 · 문화 · 행사 혼합"],
  ["임시 사용 · 장소 만들기", "유리 건물 8개 층을 임시 임대 (2008~2009 만실), 행사 · 축제로 브랜드 형성"],
  ["문화재 재사용", "TV 공장 → 로프트 240호, 보관창고 → 식품 시장 · 주차 · 옥상 주거 3개 층, 기계실 → 식당, NatLab → 영화관 · 미디어랩"],
  ["주택협회의 장기 투자", "Trudo 가 주택 판매 수익으로 삼각지 개발 재원 마련, 낮은 임대료 유지"],
 ],
 "zoning": [
  ["지정", "지구 용도계획 Strijp-S (2008), Strijp-S 2017 (2018), Strijp-S 4단계 (2023)"],
  ["관리 주체 · 방식", "Park Strijp Beheer 가 지구 전체를 기획 · 분할 매각, 공공공간 · 기반시설 조성 — West 8 감독"],
  ["보존 관리", "시계탑 건물 · 호허 뤼흐 · 보관창고 국가 문화재 · NatLab 시 문화재, 배관 거리 · 보일러동 · 기계실 보존"],
  ["구역 구성", "업무 (Spoorzone) · 주거 (Kastanjevelden) · 문화재 (Driehoek) 세 구역"],
 ],
 "funding": [
  ["토지 매입", "필립스 땅은 재정상의 이유로 에인트호번 시가 직접 매입하고, Park Strijp Beheer 가 장부가로 넘겨받는 구조 (시 연차보고서) — 매입가는 1억 4천만 유로 (2002, 위키)", "https://eindhoven.jaarverslag-2017.nl/p2683/grondbeleid"],
  ["총사업비", "현장 총 투자 약 13.1억 달러 (Sur Atlas 추정)"],
  ["공공 재원", "에인트호번 시가 보조금 (direct grants)으로 합작회사 Park Strijp Beheer 에 출자 — 지분 시 50% · 폴커베셀스 50% (Sur Atlas)"],
  ["토지 매각 수익", "합작회사가 필지 · 건물을 민간 개발자 · 주택협회에 매각, 시는 용도 변경으로 오른 땅값을 회수 (Sur Atlas)"],
  ["주택협회 재원", "Trudo 가 할인 분양 상품 「Slimmer Kopen」으로 10년간 2억 유로를 모아 삼각지 개발 재원으로 사용 (herbestemming.nl)"],
  ["재정 협약", "시와 Strijp S Ontwikkeling BV (폴커베셀스 자회사) 사이 재정 관계를 협력 협약 (SOK)으로 정함"],
  ["시 직접 투자", "시가 시계탑 건물을 매입 (2006)하고 NatLab 을 문화시설로 개조 (2013)"],
  ["협력 구조", "시 50% · 폴커베셀스 50% 협력 협약은 2002년 2월 시의회에서 확정, 실무 조직은 BV/CV 구조의 Park Strijp Beheer (주주 이사회)", "https://eindhoven.jaarverslag-2016.nl/p69/grondbeleid"],
 ],
 "operation": [
  ["운영 주체", "Park Strijp Beheer (시 · 폴커베셀스 합작) — 지구 계획 · 공공공간 · 기반시설", "https://www.strijp-s.nl/historie"],
  ["건물별 운영", "시계탑 건물은 주택협회 Trudo 주도로, 유리 건물은 Park Strijp Beheer 가 먼저 재사용 (2005/2006~), 개발은 SDK (폴커베셀스) · Trudo · Woonbedrijf 가 구역별로 분담"],
  ["임시 임대", "유리 건물 8개 층을 기업 집합 건물로 임시 임대 — 2008 시작, 2009 만실, 사무 수요가 없는 업무 구역 기존 건물도 임시 임대 (herbestemming.nl)"],
  ["낮은 임대료 · 장기 회수", "Trudo 가 가장 낮은 임대료로 창조 기업을 받고, 주택 판매 수익 (Slimmer Kopen, 10년 2억 유로)으로 개발 재원 마련 — 긴 회수 기간을 감수"],
  ["지구 기반시설 투자", "폴커베셀스와 시가 Park Strijp Beheer 를 통해 간선 대중교통 (HOV) 차로 · 주요 도로 · 지구 전체 지열 냉난방 (WKO) 시스템 「Sanergy」에 투자"],
  ["행사 · 장소 마케팅", "더치 디자인 위크 · STRP · GLOW · FeelGood Markt (매월 셋째 일요일) 등 행사로 방문객 유치, 시계탑 건물은 행사장 · 공연장"],
  ["운영상 문제", "경제 위기로 개발 속도 저하 · 일부 사업 보류, 지하 주차 비용이 높아 주차 문제 (herbestemming.nl)"],
  ["토지 사업 수지", "Park Strijp Beheer 가 땅 · 건물을 장부가로 넘겨받아 공공 공간을 만들고 건축 필지를 개발사에 팔며, 필지를 장부가로 인수하는 약정 덕분에 토지 사업은 \"비용 충당 (kostendekkend)\" · 위험도 낮음 (2017 시 연차보고서)", "https://eindhoven.jaarverslag-2017.nl/p2683/grondbeleid"],
  ["사업 기간", "Strijp-S 토지 사업은 2027년까지로 10년 기준을 넘지만, 위험 완화 조치를 이유로 시의회가 예외 승인 (2016 시 연차보고서)"],
 ],
 "operationNote": ["Strijp-S 는 시와 민간 합작회사가 땅을 사서 기반시설 · 공공공간을 깔고 필지를 팔아 재원을 회수하고, 건물 운영은 주택협회 (Trudo · Woonbedrijf)와 개발사가 나눠 맡는 구조입니다. 개발 전 건물은 싸게 임시 임대하고 디자인 · 빛 행사로 방문객을 모아 장소 가치를 먼저 올렸으며, Trudo 는 주택 판매 수익으로 낮은 임대료를 유지했습니다."],
 "famous": [
  "필립스의 \"금지된 도시\"를 시민에게 연 산업유산 재생 사례로, 2013년 네덜란드 재생상 굴던 페닉스 (Gulden Feniks) 지역전환 부문을 받았습니다.",
  "매년 10월 더치 디자인 위크 (Dutch Design Week)의 중심 무대이며, 빛 축제 GLOW 의 주 무대 (2008)였습니다.",
  "LED 실험장으로, 조명 시스템 Light-S 가 2014년 지속가능 조명상 Auroralia Award 를 받았습니다.",
  "2015년 댄스 축제 Flying Dutch 에 약 2만 5천 명이 모이는 등 대형 행사장이 되었고, 2015년에는 옆 기차역 이름도 Strijp-S 로 바뀌었습니다.",
 ],
 "result": [
  "2023년 1월 주민 3,010명 · 주택 2,251호 (nl 위키, 통계청)",
  "2019년 주민 1,665명 중 78.2%가 20~34세, 2019년까지 기업 약 300곳 입주 (Sur Atlas)",
  "주택 약 2,000호 · 사무 · 상업 15.5만㎡ · 행사장 약 8,000㎡ 건설 (Sur Atlas)",
  "2013 굴던 페닉스 지역전환 부문 수상",
  "Woonbedrijf 저렴한 임대주택 약 600호 (2025, Woonbedrijf 발표)",
 ],
 "lesson": [
  "한 기업이 떠난 대규모 공장단지를 시와 민간 합작회사가 통째로 사서 나눠 개발한 사례 — 노후 산단의 \"일괄 매입 · 단일 관리\" 모델입니다.",
  "철거 대신 공장 건물을 문화재로 남겨 창조산업 · 주거 공간으로 고쳐 쓰고, 임시 사용과 행사로 먼저 활기를 만든 점이 핵심입니다.",
  "청사진식 일괄 개발에서 단계별 · 유기적 개발로 바꾸고 용도계획을 여러 차례 고친 유연성 — 경기 변동에 대응하는 방법을 보여 줍니다.",
  "장기 회수가 가능한 공공적 주체 (주택협회)가 낮은 임대료 공간을 지켜 창조 기업을 붙잡았습니다.",
 ],
 "missing": [
  "Strijp-S 의 주요 기술 · 디자인 기업 입주사 명단은 확인된 자료를 찾지 못했습니다.",
  "Park Strijp Beheer 의 연간 수입 · 지출 금액과 시계탑 건물 운영 수지는 확인된 자료를 찾지 못했습니다 (토지 사업이 비용 충당 구조라는 것까지만 확인).",
  "EU · 국가 보조금은 확인된 자료를 찾지 못했습니다.",
  "필립스의 토지 인수 시점은 자료에 따라 2002년 (위키)과 2004년 (herbestemming.nl)으로 달라, 정확한 소유권 이전일은 확인된 자료를 찾지 못했습니다.",
  "용적률 등 밀도 수치 (원래 · 변경)는 확인된 자료를 찾지 못했습니다.",
  "세제 지원은 확인된 자료를 찾지 못했습니다.",
  "개발에 반대하거나 참여한 주민협의회 · 보존운동 단체는 확인된 자료를 찾지 못했습니다.",
  "NatLab 의 문화재 등급은 공식 사이트 (시 문화재)와 nl 위키 (국가 문화재)가 달라, 국가 문화재 등록부 원문으로는 확인하지 못했습니다.",
 ],
 "refs": [
  {"t": "Strijp-S viert start laatste bouwfase (Woonbedrijf, 2025.9.22)", "u": "https://www.woonbedrijf.com/nieuws/strijps-viert-start-laatste-bouwfase"},
  {"t": "Fase 4 — Strijp-S (공식 사이트)", "u": "https://www.strijp-s.nl/fase4"},
  {"t": "Grondbeleid — Jaarstukken 2017 Gemeente Eindhoven", "u": "https://eindhoven.jaarverslag-2017.nl/p2683/grondbeleid"},
  {"t": "Grondbeleid — Jaarstukken 2016 Gemeente Eindhoven", "u": "https://eindhoven.jaarverslag-2016.nl/p69/grondbeleid"},
  {"t": "Historie — Strijp-S (공식 사이트)", "u": "https://www.strijp-s.nl/historie"},
  {"t": "Strijp-S — Wikipedia (네덜란드어)", "u": "https://nl.wikipedia.org/wiki/Strijp-S"},
  {"t": "Strijp-S — Wikipedia (영어)", "u": "https://en.wikipedia.org/wiki/Strijp-S"},
  {"t": "Strijp S, Eindhoven — Herbestemming.nl (Restauratiefonds)", "u": "https://www.herbestemming.nl/projecten/strijp-s-eindhoven"},
  {"t": "Strijp-S — Sur Atlas (Bocconi University)", "u": "https://suratlas.unibocconi.eu/projects/strijp-s"},
  {"t": "Gemeenteblad 2024, 38139 — Bestemmingsplan Strijp-S fase 4", "u": "https://zoek.officielebekendmakingen.nl/gmb-2024-38139.html"},
  {"t": "Staatscourant 2018, 7289 — Bestemmingsplan Strijp-S 2017", "u": "https://zoek.officielebekendmakingen.nl/stcrt-2018-7289.html"},
 ],
},

"kowloon-east": {
 "spec": [
  ["위치", "홍콩 카우룽 동부 — 관통 상업지구 (Kwun Tong Business Area) · 카우룽베이 상업지구 (Kowloon Bay Business Area) · 옛 카이탁 공항 부지, 2017년부터 산포콩 (San Po Kong) 추가"],
  ["면적", "약 488ha — 카이탁 개발구역 320ha + 관통 · 카우룽베이 기성 시가지 168ha"],
  ["기간", "2001년 업무 용도지역 도입 · 2010년 공업 빌딩 재활성화 · 2011년 「CBD2」 시정연설 · 2012년 6월 전담 사무소 설치 ~ 진행 중"],
  ["원래 용도", "1950년대부터 개발된 홍콩 최초의 대규모 공업지역 (관통 위성도시) — 고층 공업 빌딩 · 창고, 1998년까지 카이탁 공항"],
  ["변경 용도", "홍콩 제2 핵심업무지구 (CBD2) — 사무 · 상업 · 호텔 · 창조산업 · 문화, 카이탁 쪽 주거 · 스포츠 · 크루즈 터미널"],
  ["원래 용도지구", "공업 (Industrial, \"I\")"],
  ["변경 용도지구", "기타 지정 용도 — 업무 (OU(B), Other Specified Uses annotated \"Business\") · 상업 (C)"],
  ["업무 공간", "상업 · 사무 연면적 약 170만㎡ (2012) → 약 220만㎡ (2016) → 약 290만㎡ (2022, 70% 증가), 건설 · 승인 중인 사업까지 약 390만㎡, 최종 400만㎡ 이상 (센트럴 규모) 목표 — 입법회 문서 CB(1)74/2022(04)", "https://www.ekeo.gov.hk/filemanager/ekeo/common/about-us/dev20220222cb1-74-4-c.pdf"],
  ["종사자", "27만 명 이상 (2016) → 약 28만 명 (2022) · 공업 빌딩 약 260동 (대부분 민간 · 소유 분산)"],
 ],
 "from": "노후 공업지역 (공업 빌딩 · 창고) + 옛 카이탁 공항",
 "to": "제2 핵심업무지구 CBD2 (사무 · 상업 · 창조산업)",
 "zoneFrom": "공업 (Industrial, I)",
 "zoneTo": "업무 OU(B) · 상업 (C) · 카이탁 개발구역",
 "tenants": [
  ["문화 · 스포츠 · 행사장", "카이탁 스포츠 파크 (啟德體育園, Kai Tak Sports Park)", "2025.3.1 개장 — 28ha, 사업비 300억 홍콩달러, 5만 석 개폐식 지붕 경기장 (홍콩 세븐스 · 콜드플레이 공연)", "https://hongkongfp.com/2025/03/02/hong-kong-opens-kai-tak-sports-park-featuring-centrepiece-50000-seat-stadium/"],
  ["문화 · 공연장", "동카우룽 문화센터 (東九文化中心, East Kowloon Cultural Centre)", "2024.10 개관 — 우터우콕 옛 공공주택 터, 사업비 41억 홍콩달러 (건축서 설계), 예술과 기술을 결합한 공연장", "https://en.wikipedia.org/wiki/East_Kowloon_Cultural_Centre"],
  ["상업 · 크루즈 터미널", "카이탁 크루즈 터미널 (啟德郵輪碼頭)", "2013.6.12 첫 입항 — 옛 활주로 끝, 사업비 72억 홍콩달러, Foster + Partners 설계", "https://en.wikipedia.org/wiki/Kai_Tak_Cruise_Terminal"],
  ["상업 · 대형 쇼핑몰", "APM (관통)", "옛 공업 빌딩 전환의 성공 사례로 정부가 언급 (2007 입법회 발언)", "https://www.devb.gov.hk/en/publications_and_press_releases/press/index_id_2594.html"],
  ["첨단산업 · 미디어 · 음악", "관통 공업 빌딩의 영화 후반작업 회사 · 음악 스튜디오 · 라이브하우스", "재활성화 공업 빌딩의 대표 업종 (관통)", "https://en.wikipedia.org/wiki/Revitalisation_of_industrial_buildings_in_Hong_Kong"],
  ["문화 · 공공 문화공간", "Fly the Flyover 01 (反轉天橋底)", "관통 우회도로 고가 밑 비공식 공연장 — 2·3호 부지 확장 (2016)", "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"],
  ["업무 · 공공기관", "카우룽 이스트 활성화 사무소 (EKEO) 청사", "2012년 6월 초 운영 시작 — 재활용 화물 컨테이너 · 철골로 지은 저탄소 임시 청사, 정보 안내소 · 전시 겸용", "https://www.info.gov.hk/gia/general/201207/04/P201207040263.htm"],
  ["업무 · 정부 청사", "공업무역 대루 (工業貿易大樓, Trade and Industry Tower)", "카이탁 — 2012.1 재정위원회 재원 승인, 순 사무면적 3만 3천㎡, 몽콕 공업무역서 등 정부 부서 이전 (완공 연도는 확인하지 못함)", "https://www.info.gov.hk/gia/general/201207/04/P201207040263.htm"],
 ],
 "timeline": [
  ["1950년대", "관통을 위성도시 · 공업지역으로 개발 — 이후 카우룽베이 · 야우퉁으로 확장"],
  ["1980년대", "제조업이 중국 본토로 옮겨 가며 공업 빌딩이 중소기업 · 예술가 · 창조산업 공간으로 바뀌기 시작"],
  ["1998", "카이탁 공항이 첵랍콕으로 이전"],
  ["2001", "도시계획위원회 (TPB)가 업무 용도지역 OU(B) 도입 — 이후 공업 용지 약 200ha 를 업무 용도로 변경"],
  ["2009.10", "정부가 공업 빌딩 재활성화 대책 발표 → 2010.4.1 시행"],
  ["2011.9", "재활성화 대책 중간 검토 · 신청 기한을 2016년 3월까지 연장"],
  ["2011.10", "2011-12 시정연설 — 카우룽 이스트를 제2 핵심업무지구 (CBD2)로 바꾸겠다고 발표"],
  ["2012.6.7", "개발국 산하 카우룽 이스트 활성화 사무소 (EKEO) 공식 출범"],
  ["2013", "새 매각 토지에 녹화율 · BEAM Plus 골드 이상 인증 조건 부과"],
  ["2015.5", "관통 해안 산책로 (Kwun Tong Promenade) 전 구간 개방"],
  ["2016", "시정연설 — 민간이 보행 연결 통로를 지으면 임차 조건 변경 프리미엄 면제 (시범)"],
  ["2017", "EKE 범위를 산포콩까지 확대"],
  ["2018.10.10", "1987년 이전 공업 빌딩 재건축 시 비주거 용적률 최대 20% 완화 (3년 한시)"],
  ["2019 초", "15년 이상 공업 빌딩 통째 전환 시 변경료 면제 재개 (「활화공하 2.0 (活化工廈2.0)」, 2024년까지 연장) — 전환 연면적 10%를 문화 · 창조 · 사회 용도로 지정"],
  ["2020", "시정연설 — 관통 · 카우룽베이 · 카이탁이 제2 핵심업무지구로 전환되었다고 평가"],
  ["2021", "예산안에서 카이탁 상업 용지 5필지를 주거로 변경 (약 5,800호) — 계획 수정 논란"],
  ["2022.4", "EKEO 책임자 직위를 2027년 3월 31일까지 5년 연장 (입법회 제출, 2022)"],
  ["2024~2026", "동카우룽 문화센터 개관 (2024.10) · 카이탁 스포츠 파크 개장 (2025.3.1) · 카이탁 개발구역 주요 공공 기반시설 2026년 대체로 완공 예정 (EKEO)"],
 ],
 "problem": [
  "1980년대 이후 제조업이 중국 본토로 옮겨 가고 카이탁 공항이 이전하면서, 관통 · 카우룽베이 공업 빌딩의 원래 기능이 사라졌습니다 (2007년 12월 공업 빌딩 공실률 6.7%).",
  "금융 · 서비스업 성장과 다국적 기업 지역 본부 증가로 우량 사무 공간 수요가 늘었지만, 센트럴 등 전통 도심만으로는 공급을 감당하지 못했습니다.",
  "차량 위주로 만들어진 옛 공업지역이라 녹지 · 공공 공간 · 보행 환경이 나빴습니다.",
  "1987년 이전 공업 빌딩은 현대 소방 안전 기준에 맞지 않고, 공업 용도로만 묶인 토지 임차 조건 때문에 다른 용도로 바꾸기 어려웠습니다.",
 ],
 "overview": [
  "카우룽 이스트는 정부가 땅을 사서 한꺼번에 재개발하는 방식이 아니라, 용도지역 (OU(B))을 바꾸고 공업 빌딩의 통째 전환 · 재건축에 인센티브를 주어 민간 소유자가 건물 단위로 사무 · 상업 빌딩으로 바꾸게 하는 \"시장 주도 · 점진적\" 전환입니다. 이미 27만 명 이상이 일하는 지역이라 전면 재개발 대신 유기적 성장을 택했다고 정부는 설명합니다.",
  "2012년 개발국 산하에 도시계획가 · 건축가가 이끄는 전담 사무소 (EKEO)를 세워, 「걸을 수 있는 카우룽 이스트」 보행 개선 (2016년 10월까지 보행 개선 25건 · 교통 개선 23건), 해안 산책로 · 고가도로 밑 문화 공간 (Fly the Flyover), 명거 (King Yip Street nullah)를 하천 「Tsui Ping River」로 바꾸는 사업, 정부 용지 매각 · 재배치를 조정했습니다.",
  "카이탁 (320ha)은 계획적 신개발 구역이고, 관통 · 카우룽베이 (168ha)는 기존 공업 빌딩의 전환 구역입니다. 정부는 공업 역사를 \"창조의 정신 (Spirit of Creation)\"으로 도시설계에 담는 장소 만들기 전략도 썼습니다.",
 ],
 "actors": [
  ["주관 기관", "홍콩 특별행정구 정부 개발국 (Development Bureau, 發展局)", "CBD2 정책 · 공업 빌딩 재활성화 정책 수립"],
  ["전담 조직", "카우룽 이스트 활성화 사무소 (Energizing Kowloon East Office, EKEO, 起動九龍東辦事處, 2012.6.7)", "개념 마스터플랜 수립 · 갱신, 부서 간 사업 조정, 민간 개발 원스톱 지원 — 수석 도시계획관 · 정부 건축가 직위로 출범"],
  ["관련 기관", "도시계획위원회 (Town Planning Board)", "OU(B) 도입 (2001) · 용도지역 변경 · 용적률 완화 승인"],
  ["관련 기관", "지정청 (Lands Department, 地政總署)", "토지 임차 조건 변경 · 변경료 면제 · 프리미엄 산정"],
  ["관련 기관", "토목공정확장서 (CEDD) 카이탁 사무소 · 배수서 (DSD) · 운수서 · 도로서", "카이탁 개발, 친환경 교통 연결 검토, 하천 복원, 보행 · 교통 개선"],
  ["관련 기관", "관통구 의회 · 하버프런트 위원회 (Harbourfront Commission)", "해안 녹화 사업 지지 · 협의"],
  ["민간", "공업 빌딩 소유자 · 개발자", "건물 단위의 통째 전환 · 재건축"],
  ["대학 · 연구", "홍콩 이공대학 학생 등", "뒷골목 벽화 사업 (後巷計劃) 참여"],
  ["시민 · 문화", "관통 공업 빌딩의 예술 · 음악 단체", "임대료 상승으로 작업실이 밀려난다는 비판, 일부가 EKEO 행사 보이콧 (2013 고가도로 밑 행사 개막식에 밴드 20팀 불참)"],
 ],
 "laws": [
  ["도시계획조례 (Town Planning Ordinance, Cap. 131) — OU(B) 업무 용도지역 (2001)", "공업 · 공업-사무 빌딩에서 사무 · IT · 통신 · 창조산업 등 상업 · 비오염 산업을 계획 허가 없이 허용, 호텔은 신청으로 허용", "https://www.devb.gov.hk/en/publications_and_press_releases/press/index_id_2594.html"],
  ["공업 빌딩 재활성화 대책 (2010.4 ~ 2016.3)", "① 30년 이상 공업 빌딩의 강제매각 신청 기준 소유 90% → 80% ② 최적 용도 기준 \"지은 만큼 내는\" 프리미엄 ③ 2천만 홍콩달러 초과 프리미엄의 80%를 5년 분할 ④ 15년 이상 공업 빌딩 (I · C · OU(B) 지역)의 통째 전환 시 변경료 면제", "https://www.legco.gov.hk/yr12-13/english/panels/hg/hg_lths/papers/hg_lths0716cb1-1529-1-e.pdf"],
  ["2011 중간 검토 보완책", "옥상 설비 (아래층 면적 50% 이하) · 외벽 커튼월은 높이 · 규모 증가로 보지 않음, 연면적 10% 이내 외부 구조 철거 허용"],
  ["2018 시정연설 재활성화 대책", "1987년 이전 공업 빌딩 (주거지역 밖) 재건축 시 비주거 용적률 최대 20% 상향 (도시계획위원회 승인, 프리미엄 전액), 통째 전환 변경료 면제 재개 (전환 연면적 10%를 예술 · 창조 · 혁신 · 사회 용도로 지정), 예술 작업실 · 연구개발 등 용도는 별도 신청 · 변경료 없이 허용", "https://www.legco.gov.hk/yr18-19/english/panels/dev/papers/dev20181219cb1-379-1-e.pdf"],
  ["보행 연결 시범 정책 (2016)", "카우룽베이 · 관통 상업지구에서 계획된 보행 통로를 민간이 지으면 임차 조건 변경 프리미엄 면제", "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"],
  ["2011-12 시정연설 (Policy Address 2011-12) — 「카우룽 이스트 활성화 (Energizing Kowloon East)」", "카우룽베이 · 관통 상업지구 · 옛 카이탁 공항을 제2 핵심업무지구 (CBD2)로 — 토지 용도 검토 · 도시설계 · 연결성 · 기반시설 개선, 2017 산포콩 확대", "https://www.ekeo.gov.hk/en/about-ekeo/background/index.html"],
  ["카우룽 이스트 개념 마스터플랜 (Conceptual Master Plan 5.0, 2016) · EKEO 소책자 (2012-2016+)", "「걸을 수 있는 카우룽 이스트」, 환경 개선, 개발 잠재력 (행동구역), 스마트시티 시범지구 전략", "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"],
  ["카이탁 개발계획 (Kai Tak Development, 옛 동남 카우룽 개발계획 South East Kowloon Development, 2004 재검토)", "옛 공항 부지 320ha — 스포츠 단지 · 크루즈 터미널 · 주거 · 상업"],
  ["카우룽 이스트 개념 마스터플랜 6.0 (起動九龍東概念總綱計劃6.0)", "연결 · 보행성 · 이동성 강화, 스마트 · 녹색 · 회복력 있는 CBD, 지속가능한 성장, 「창조 정신」 — 홍콩계획사학회 (HKIP) 2025 연례상 동상", "https://www.ekeo.gov.hk/tc/about-ekeo/conceptual-master-plan/index.html"],
 ],
 "lawsNote": ["규제완화의 핵심은 세 겹입니다 — 용도지역을 공업에서 업무 (OU(B))로 바꿔 계획 허가 없이 사무 · 상업을 허용하고, 토지 임차 조건 변경료 (프리미엄)를 면제하며, 재건축 시 용적률을 최대 20% 올려 준 것입니다. 정부는 땅을 사지 않고 민간 소유자가 스스로 전환하게 했습니다."],
 "tools": [
  ["용도변경 (공업 → 업무)", "OU(B) 지정 — 2007년까지 공업 용지 약 200ha 를 업무 용도로, 약 50ha 를 주거 (E) · 종합개발구역 · 상업으로 변경 (홍콩 전역)"],
  ["변경료 · 프리미엄 면제", "15년 이상 공업 빌딩 통째 전환 시 변경료 면제 (2010~2016, 2019 재개), 보행 통로 제공 시 프리미엄 면제 (2016)"],
  ["용적률 완화", "1987년 이전 공업 빌딩 재건축 시 비주거 용적률 최대 +20% (2018)"],
  ["강제매각 기준 완화 · 분할 납부", "공업 빌딩 강제매각 신청 기준 80%, 프리미엄 5년 분할 납부"],
  ["정부 용지 매각 · 재배치", "2016년까지 정부 용지 5필지 매각 (상업 · 사무 약 27만㎡), 카우룽베이 · 관통 행동구역의 정부 시설을 옮겨 상업 · 사무 약 56만㎡ 확보 추진"],
  ["공공 환경 선투자", "해안 산책로 · 공원 · 뒷골목 개선 · 보행 · 교통 개선, 하천 복원 (Tsui Ping River)"],
  ["녹색 · 스마트 조건", "새 매각 토지에 BEAM Plus 골드 이상 · 녹화율 · 스마트 수도 계량기 · 전기차 충전 의무 (2013~)"],
 ],
 "toolsNote": ["2010년 대책으로 2013년 6월까지 71건 (전환 · 신규 연면적 약 72만㎡), 2014년 9월까지 100건이 승인되었습니다 (홍콩 전역 기준)."],
 "zoning": [
  ["지정", "OU(B) 업무 · 상업 용도지역 (관통 · 카우룽베이 상업지구), 카이탁 개발구역 (320ha)"],
  ["관리 주체 · 방식", "EKEO 가 개념 마스터플랜 (Conceptual Master Plan, 2016년 5.0판)을 수시로 갱신하며 부서 · 민간을 조정 — 2012년 이후 연장 운영"],
  ["보존 관리", "공업 빌딩을 문화재로 지정하지 않고, 「카우룽 이스트 공업 전통 · 공공미술 · 도시설계 연구」로 공업 역사를 공원 · 광장 설계에 반영 (Tsun Yip Street 놀이터 등)"],
 ],
 "funding": [
  ["공공 재원 (조직)", "입법회 재정위원회가 EKEO 의 수석 도시계획관 (D3) · 정부 건축가 (D2) 직위 재원 승인 (2012.4 · 2013.5, 2017년 6월까지)", "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"],
  ["공공 재원 (사업)", "재정위원회가 2016년 6월 「Tsui Ping River Garden」 이전 조성 재원 승인, 차량검사센터 이전은 공공사업 계획으로 재원 신청 추진"],
  ["토지 매각 수익", "2016년까지 정부 용지 5필지 (NKIL 6311 · 6312 · 6512 · 6313, KTIL 761) 매각 — 상업 · 사무 약 27만㎡"],
  ["세외 지원 (변경료 면제)", "15년 이상 공업 빌딩 통째 전환 시 토지 변경료 면제 (2010~2016, 2019 재개), 보행 통로 제공 시 프리미엄 면제 (2016)", "https://www.legco.gov.hk/yr12-13/english/panels/hg/hg_lths/papers/hg_lths0716cb1-1529-1-e.pdf"],
  ["분할 납부", "재건축 프리미엄이 2천만 홍콩달러를 넘으면 80%를 5년간 고정 금리로 분할 납부"],
  ["소규모 사업", "뒷골목 벽화 사업 (後巷計劃@九龍東)에 약 70만 홍콩달러 (중문 위키)"],
  ["공공 사업비 (공원)", "하이분로드 공원 · 주변 개선 (466RO) 추정 1억 8,670만 홍콩달러, 카이탁 애비뉴 파크 (436RO) 3억 2,190만 홍콩달러 — 명목 가격, 재정위원회 공공사업 소위 상정 (2018.2.6)", "https://www.legco.gov.hk/yr17-18/english/fc/pwsc/papers/p17-32e.pdf"],
  ["카이탁 개발 총사업비", "옛 공항 부지 카이탁 개발 전체 약 1,000억 홍콩달러 (영문 위키, 카이탁 개발계획 기준)"],
 ],
 "operation": [
  ["운영 주체", "개발국 산하 정부 조직 EKEO — 별도 수익사업 없이 정부 예산으로 운영, 2017.7~2022.3 운영 연장 제안 (2016)", "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"],
  ["운영 인건비 (2016 제안)", "책임자 2명 (수석 도시계획관 D3 · 정부 건축가 D2) 명목 연봉 444만 3천 홍콩달러 (부대비용 포함 약 615만 9천), 비지휘직 공무원 · 계약직 22명 — 공무원 연 1,411만 1천 · 계약직 484만 6천 홍콩달러 이내"],
  ["민간 운영 · 수입", "공업 빌딩은 개별 소유자가 전환 · 임대 운영 — 정부는 변경료 면제 · 용적률 인센티브로 유도"],
  ["토지 매각 수익", "2016년까지 정부 용지 5필지 매각 (상업 · 사무 약 27만㎡)"],
  ["공공 공간 운영", "고가도로 밑 「Fly the Flyover 01」 공연장 등 정부 부지를 예술 · 문화 · 창조 용도로 운영"],
  ["운영상 문제", "임대료 상승으로 소규모 작업실 · 예술 공간이 밀려남, 근로 인구 급증에 따른 교통 혼잡 (중문 위키)"],
  ["운영 연장 (2022)", "책임자 2명 직위를 2022.4.1~2027.3.31 5년 연장, 「개발국 공무과 (發展局工務科)」 산하 전담 기구", "https://www.ekeo.gov.hk/filemanager/ekeo/common/about-us/dev20220222cb1-74-4-c.pdf"],
 ],
 "operationNote": ["카우룽 이스트는 단지 운영회사가 임대료로 운영하는 구조가 아니라, 정부 조직 (EKEO)이 예산으로 인력을 두고 계획 · 조정을 맡고, 공업 빌딩의 운영 · 수익은 각 민간 소유자에게 맡기는 구조입니다. 정부 쪽 수입은 토지 매각이며, 지출은 공공 공간 · 보행 개선 투자입니다."],
 "famous": [
  "홍콩 정부가 공식적으로 내건 \"제2 핵심업무지구 (CBD2)\"로, 2020년 시정연설에서 전환에 성공했다고 평가했습니다.",
  "2012년 「카우룽 이스트 활성화」를 주제로 한 홍콩관 전시가 제13회 베네치아 건축 비엔날레에서 상위 5위 안에 들었습니다 (중문 위키).",
  "카우룽 이스트는 홍콩의 스마트시티 시범지구로 지정되어, 새 매각 토지에 스마트 수도 계량기 · 전기차 충전 등을 의무화했습니다.",
  "고가도로 밑 공간을 공연장으로 바꾼 「Fly the Flyover」 등 장소 만들기 사업으로 알려졌지만, 임대료 상승으로 예술 공간이 밀려난다는 비판도 함께 받았습니다.",
  "카우룽 이스트 개념 마스터플랜이 홍콩계획사학회 (Hong Kong Institute of Planners) 2025 연례상 동상을 받았습니다 (EKEO).",
 ],
 "result": [
  "상업 · 사무 연면적 약 170만㎡ (2012) → 약 220만㎡ (2016) — 사무 140만 → 180만㎡",
  "카우룽 이스트에 BEAM Plus 골드 · 플래티넘 건물 23동 (2016)",
  "관통구 근로 인구 252,724명 (2006) → 289,093명 (2011) — 교통 혼잡 심화 비판 (중문 위키)",
  "정부는 2020년 시정연설에서 제2 핵심업무지구 전환에 성공했다고 평가",
  "2012~2020년 홍콩 전체 신규 상업 · 사무 공급의 평균 약 40%가 카우룽 이스트 (2022년 55% 예상) — 입법회 문서 (2022)",
  "공업 빌딩 재활성화 승인 건수 중 카우룽 이스트 비중: 1.0 (2010~2016) 45% → 2.0 (2018~) 64%",
  "새로 만들거나 고친 공공 공간 17ha 이상 (InPARK · 취핑강 정원 · 하이분로드 공원), 개발사업 130건 이상 원스톱 지원, 행사 참여 약 112만 명 (2022까지)",
 ],
 "lesson": [
  "산업단지를 공공 재개발이 아니라 \"용도지역 완화 + 변경료 면제 + 용적률 인센티브\"로 민간이 빌딩 단위로 전환하게 한 모델 — 한국 노후 산단 · 준공업지역의 지식산업센터 전환과 직접 비교할 수 있습니다.",
  "용도만 풀면 끝이 아니라, 전담 조직이 보행 · 녹지 · 교통 같은 도시 환경을 함께 고쳐야 업무지구로 완성된다는 점을 보여 줍니다.",
  "전환이 진행될수록 임대료가 올라 공업 빌딩의 예술 · 소규모 작업 공간이 밀려나는 문제가 생겼습니다 — 2018년 대책에서 전환 연면적 10%를 문화 · 창조 · 사회 용도로 지정한 것은 이에 대한 보완입니다.",
  "근로 인구 증가에 맞춘 교통 기반시설 계획이 함께 가지 않으면 혼잡이 심해집니다.",
 ],
 "missing": [
  "관통 · 카우룽베이 업무지구에 입주한 주요 기업 (본사 · 지역 본부) 명단은 확인된 자료를 찾지 못했습니다.",
  "EKEO 의 연간 사업 예산 총액 (인건비 외)은 확인된 자료를 찾지 못했습니다.",
  "관통 · 카우룽베이 (기성 시가지)를 포함한 카우룽 이스트 전체의 공공 투자 총액은 확인된 자료를 찾지 못했습니다 (카이탁 개발 · 개별 공원 사업비까지만 확인).",
  "마스터플랜 · 설계를 맡은 도시계획가 · 건축가는 확인된 자료를 찾지 못했습니다.",
  "관통 · 카우룽베이에서 실제로 전환 · 재건축된 공업 빌딩 수 (지역별 통계)는 확인된 자료를 찾지 못했습니다.",
  "OU(B) 지역의 구체적인 용적률 수치 (공업 지역 대비)는 확인된 자료를 찾지 못했습니다.",
  "세제 지원은 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "立法會CB(1)74/2022(04)號文件 — 延續起動九龍東辦事處運作 (2022)", "u": "https://www.ekeo.gov.hk/filemanager/ekeo/common/about-us/dev20220222cb1-74-4-c.pdf"},
  {"t": "起動九龍東 — 概念總綱計劃 (EKEO, 번체 중문)", "u": "https://www.ekeo.gov.hk/tc/about-ekeo/conceptual-master-plan/index.html"},
  {"t": "起動九龍東 — 常見問題 (EKEO, 번체 중문)", "u": "https://www.ekeo.gov.hk/tc/about-ekeo/faqs/index.html"},
  {"t": "起動九龍東 — 背景 (EKEO, 번체 중문)", "u": "https://www.ekeo.gov.hk/tc/about-ekeo/background/index.html"},
  {"t": "Kai Tak Cruise Terminal — Wikipedia", "u": "https://en.wikipedia.org/wiki/Kai_Tak_Cruise_Terminal"},
  {"t": "LCQ14: Energizing Kowloon East Office (2012.7.4)", "u": "https://www.info.gov.hk/gia/general/201207/04/P201207040263.htm"},
  {"t": "East Kowloon Cultural Centre — Wikipedia", "u": "https://en.wikipedia.org/wiki/East_Kowloon_Cultural_Centre"},
  {"t": "Hong Kong opens Kai Tak Sports Park featuring centrepiece 50,000-seat stadium (HKFP/AFP, 2025.3.2)", "u": "https://hongkongfp.com/2025/03/02/hong-kong-opens-kai-tak-sports-park-featuring-centrepiece-50000-seat-stadium/"},
  {"t": "PWSC(2017-18)32 — Avenue Park at Kai Tak, Improvement of Hoi Bun Road Park (LegCo, 2018)", "u": "https://www.legco.gov.hk/yr17-18/english/fc/pwsc/papers/p17-32e.pdf"},
  {"t": "Energizing Kowloon East — Background (EKEO)", "u": "https://www.ekeo.gov.hk/en/about-ekeo/background/index.html"},
  {"t": "起動九龍東辦事處 — 維基百科 (중문)", "u": "https://zh.wikipedia.org/zh-hk/%E8%B5%B7%E5%8B%95%E4%B9%9D%E9%BE%8D%E6%9D%B1"},
  {"t": "LC Paper CB(1)133/16-17(04) Extending the Operation of Energizing Kowloon East Office (2016)", "u": "https://www.legco.gov.hk/yr16-17/english/panels/dev/papers/dev20161122cb1-133-4-e.pdf"},
  {"t": "LC Paper CB(1)1529/12-13(01) Revitalisation of Industrial Buildings (2013)", "u": "https://www.legco.gov.hk/yr12-13/english/panels/hg/hg_lths/papers/hg_lths0716cb1-1529-1-e.pdf"},
  {"t": "LC Paper CB(1)379/18-19(01) Measures to revitalise industrial buildings (2018)", "u": "https://www.legco.gov.hk/yr18-19/english/panels/dev/papers/dev20181219cb1-379-1-e.pdf"},
  {"t": "Speech by SHPL on Legco motion on Assisting in the transformation of factory buildings (DEVB)", "u": "https://www.devb.gov.hk/en/publications_and_press_releases/press/index_id_2594.html"},
  {"t": "Revitalisation of industrial buildings in Hong Kong — Wikipedia", "u": "https://en.wikipedia.org/wiki/Revitalisation_of_industrial_buildings_in_Hong_Kong"},
  {"t": "Kai Tak Development — Wikipedia", "u": "https://en.wikipedia.org/wiki/Kai_Tak_Development"},
  {"t": "Kwun Tong — Wikipedia", "u": "https://en.wikipedia.org/wiki/Kwun_Tong"},
 ],
},

"brooklyn-navy-yard": {
 "spec": [
  ["위치", "미국 뉴욕시 브루클린 북서부 월러바웃 만 (Wallabout Bay) — 네이비 가 · 플러싱 애비뉴 · 켄트 애비뉴 · 이스트 강 사이"],
  ["면적", "약 300에이커 (약 121ha, 사업 구역) — 국가 사적 역사지구는 225.15에이커 (91.11ha)"],
  ["기간", "1966년 해군 폐쇄 → 1969년 시 소유 → 1981년 개발공사 → 2018년 마스터플랜 → 2021년 특별지구 지정 ~ 진행 중"],
  ["원래 용도", "1801년 설립된 미 해군 조선소 (뉴욕 해군 조선소) — 군함 230척 이상 건조, 2차 대전 최대 7만 5천 명 고용 (\"Can-Do Shipyard\"), 전함 미주리 · 애리조나 · 메인 등 건조"],
  ["변경 용도", "도시형 현대 제조업 산업단지 — 하드웨어 · 기후기술 창업 (Newlab), 영화 · TV 스튜디오 (Steiner Studios), 식품 · 디자인 · 가구 제조, 사무 (Dock 72), 교육 (STEAM 센터 · 대학원)"],
  ["원래 용도지구", "연방 해군 시설"],
  ["변경 용도지구", "주로 중공업지구 M3-1 (용적률 2.0) → 2021년 브루클린 해군 조선소 특별지구 (Special Brooklyn Navy Yard District, BNY) — 외곽 M2-1 로 변경 · 용도 확대 (주거 불허 유지)"],
  ["기존 시설", "연면적 약 636.5만 ft² (약 59만㎡, 실사용 용적률 0.52) — 제조 555만 ft²"],
  ["마스터플랜 (2018)", "신축 약 461만 ft² (약 43만㎡) → 총 약 1,097.5만 ft² (용적률 0.91), 공공 개방 공간 18.9만 ft², 2030년 고용 3만 명 목표, 사업비 약 25억 달러"],
 ],
 "from": "해군 조선소 (군함 건조 · 수리)",
 "to": "시 소유 현대 제조업 산업단지 (주거 없음)",
 "zoneFrom": "연방 해군 시설",
 "zoneTo": "M3-1 공업지구 → 브루클린 해군 조선소 특별지구 (BNY, 2021)",
 "tenants": [
  ["첨단산업 · 영화 스튜디오", "스타이너 스튜디오 (Steiner Studios)", "2004년 개장 (1억 1,800만 달러, 70년 임대) — 할리우드 밖 미국 최대급 제작 스튜디오", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["첨단산업 · 창업 · 공유오피스", "뉴랩 (Newlab)", "2016년 128동 (그린 제조 센터) — 로봇 · 엔지니어링 · 나노기술 · 하드웨어 기업 허브, 금속 · 목공소 · 3D 프린팅", "https://nmtccoalition.org/project/brooklyn-navy-yard-building-128/"],
  ["업무 · 공유오피스", "도크 72 (Dock 72) — 위워크 (WeWork)", "2017년 상량, 67만 5천 ft² 사무 빌딩, 위워크 사무실 (위키 기준 — 현재 운영 여부는 확인하지 못함)", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["첨단산업 · 대학", "브루클린 칼리지 파이어스틴 영화 대학원 (Feirstein Graduate School of Cinema)", "스타이너 스튜디오 캠퍼스 안 약 7만 ft² (2013 시장 특례로 허용)", "https://zap-api-production.herokuapp.com/document/projectaction/sites/nycdcppfs/dcp_projectaction/ZM%20-%20Zoning%20Map%20Amendment%20_03D01E0C3964E811812E1458D04D2538/210462.pdf"],
  ["첨단산업 · 교육", "브루클린 STEAM 센터 (직업기술 고교)", "77동 약 6만 2천 ft² (2018 시장 특례로 허용)", "https://zap-api-production.herokuapp.com/document/projectaction/sites/nycdcppfs/dcp_projectaction/ZM%20-%20Zoning%20Map%20Amendment%20_03D01E0C3964E811812E1458D04D2538/210462.pdf"],
  ["첨단산업 · 대학 연구소", "프랫 인스티튜트 리서치 야드 (Pratt Research Yard)", "2023년 3동에 1단계, 2025년 2단계 제안 공모", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["상업 · 식음", "마켓 @77 푸드홀 (Market @77) · 웨그먼스 (Wegmans)", "77동 식품 홀 (2017 재개장), 웨그먼스 슈퍼마켓 2019년 개장 (제독 관사 터)", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["문화 · 박물관", "BLDG 92 (브루클린 해군 조선소 센터)", "2011.11 개관 — 조선소 역사 박물관 · 방문자센터", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["상업 · 도시농업", "브루클린 그레인지 (Brooklyn Grange)", "3동 옥상 6만 5천 ft² 상업 농장 (2015 무렵)", "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"],
  ["업무 · 제조 (정밀가공 · 식품)", "사이어 프리시전 (Cyre Precision) · 마스트 브라더스 초콜릿 (Mast Brothers)", "128동 입주 기업으로 소개 (2012 신시장 세액공제 사례) — 현재 여부는 확인하지 못함", "https://nmtccoalition.org/project/brooklyn-navy-yard-building-128/"],
 ],
 "timeline": [
  ["1801", "연방정부가 존 잭슨에게서 부두와 땅 40에이커를 사들여 해군 조선소 설립"],
  ["1941~1945", "2차 대전 — 최대 7만 5천 명 고용 (시 자료는 약 7만 명), 16층 77동 (본부 · 창고) 건설"],
  ["1964~1966", "국방장관 맥나마라가 폐쇄 발표 (1964.11) → 1966.6.25 폐쇄식, 6.30 해군 철수 — 민간인 1만 600명 실직 · 시를 대신해 운영할 비영리 법인 CLICK 설립"],
  ["1967~1969", "1967.5 매입가 2,400만 달러 합의 → 1969년 소유권 시로 이전 (최종 계약 2,250만 달러)"],
  ["1978", "고용 정점 — 입주 38곳 · 5,500명"],
  ["1979.1", "최대 입주사 시트레인 조선 (Seatrain) 폐업 — 1,300명 이상 해고"],
  ["1981", "코크 시장이 비영리 브루클린 해군 조선소 개발공사 (BNYDC) 선정 — CLICK 대체"],
  ["1984~1996", "쓰레기 소각장 계획 — 1984 시 승인 → 윌리엄스버그 주민 반대 · 주 허가 거부 (1989) → 1990년대 중반 계획 폐기"],
  ["1999.10", "더글러스 스타이너가 70년 임대 계약 → 2004년 스타이너 스튜디오 개장 (1억 1,800만 달러)"],
  ["2011", "BNYDC 장기 개발 계획 착수 · 11월 역사 박물관 BLDG 92 개관"],
  ["2014", "조선소 전체가 국가 사적 (NRHP) 역사지구로 등재"],
  ["2016", "128동 (옛 기계 · 조립 공장) 그린 제조 센터 · Newlab 개장 · 제독 관사 (Admiral's Row) 10동 중 9동 철거"],
  ["2017.11", "77동 (100만 ft²) 1억 4,300만 달러 개조 후 재개장 · Dock 72 (사무, 위워크) 상량"],
  ["2018", "BNYDC 마스터플랜 발표 (WXY) — 수직형 제조 건물 · 고용 3만 명 목표"],
  ["2021.10~12", "도시계획위원회 승인 (10.20) → 시의회 승인 · 특별지구 발효 (12.15)"],
  ["2026.1", "첫 FY25 성과 보고서 — 550개 이상 기업 · 1만 3천 명 이상 고용"],
 ],
 "problem": [
  "1966년 해군이 조선소를 닫으며 민간인 1만 600명의 일자리가 한꺼번에 사라졌습니다.",
  "시가 사들인 뒤에도 운영 법인 CLICK 의 부실 경영 · 부패 의혹, 대형 컨테이너선이 들어오지 못하는 입지 탓에 약속한 3~4만 개 일자리는 생기지 않았고, 1979년 최대 입주사 폐업으로 고용이 급감했습니다.",
  "1980~90년대에는 조선소 안에 쓰레기 소각장을 지으려는 시 계획이 주민 건강 문제로 큰 갈등을 낳았습니다.",
  "대도시 공업 용지가 주거 · 상업으로 바뀌어 사라지는 가운데, 중산층 일자리인 도시형 제조업을 어떻게 지킬지가 과제였습니다.",
  "2010년대 후반에는 남은 낡은 건물이 거의 개조되어 (임대율 95%) 성장하려면 신축이 필요했지만, 기존 공업지구 규제는 현대 제조업 건물의 형태 · 층고와 맞지 않았습니다.",
 ],
 "overview": [
  "브루클린 해군 조선소는 주거 · 상업으로 바꾸지 않고 \"현대 도시형 산업단지\"로 재생한 드문 사례입니다. 땅은 뉴욕시가 계속 소유하고 (시 중소기업청 SBS 관할), 비영리 개발공사 BNYDC 가 99년 장기 임차로 넘겨받아 개발자 · 관리자로서 제조업체에 안정적이고 저렴한 장기 임대를 제공합니다.",
  "1990년대 이후 옛 조선소 건물을 하나씩 고쳐 소규모 제조 · 예술 · 영화 기업을 들였고, 2004년 스타이너 스튜디오, 2016년 128동 그린 제조 센터 · Newlab, 2017년 77동 (식품 홀 · 제조 · 사무)이 앵커가 되었습니다. 2011년부터 시가 대규모 투자를 했습니다.",
  "2018년 마스터플랜은 아래층에 층고 40ft 의 대형 제조 공간, 중간층에 시제품 · 소규모 제조, 위층에 기술 · 연구 사무를 쌓는 \"수직형 제조 건물\"을 외곽 3곳 (Navy Street · Flushing · Barge Basin)에 짓는 계획입니다. 2021년 특별지구로 소매 · 교육 · 보육 · 박물관 등 지원 용도와 건물 높이 · 형태 규제를 풀어 주었지만, 주거는 여전히 허용하지 않습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "WXY (건축 · 도시설계 사무소)", "2018년 브루클린 해군 조선소 마스터플랜 세부 설계 — 수직형 제조 건물 · 외곽 개발지 3곳"],
  ["사업 시행", "브루클린 해군 조선소 개발공사 (Brooklyn Navy Yard Development Corporation, BNYDC, 1981)", "비영리 부동산 개발자 · 관리자 — 99년 장기 임차, 임대 · 신축 · 고용 센터 운영"],
  ["토지 소유", "뉴욕시 (City of New York) — 중소기업청 (NYC Small Business Services) 관할", "1969년 연방정부로부터 매입, 땅 소유 · 2021년 특별지구 공동 신청"],
  ["관련 기관", "뉴욕시 도시계획위원회 (City Planning Commission) · 시의회 (City Council)", "2021년 특별지구 · 용도지역 변경 승인"],
  ["관련 기관", "브루클린 제2 커뮤니티 보드 · 브루클린 구청장", "2021년 특별지구 심의 · 찬성 권고"],
  ["옛 운영 법인", "CLICK (Commerce Labor Industry Corporation of Kings, 1966~1981)", "초기 임대 운영 — 부실 경영으로 교체"],
  ["앵커 · 민간", "스타이너 스튜디오 (Steiner Studios) · Newlab · Dock 72 (위워크) · Wegmans · 399 Sands Street", "영화 · 하드웨어 창업 · 사무 · 상업 앵커"],
  ["대학 · 교육", "브루클린 칼리지 파이어스틴 영화 대학원 · 브루클린 STEAM 센터 (직업기술 고교) · 프랫 인스티튜트 (Research Yard, 2023)", "교육 · 연구 · 인력 양성"],
  ["시민단체", "윌리엄스버그 주민 (하시디 유대인 공동체 등)", "1980~90년대 조선소 소각장 계획 반대 — 계획 폐기에 영향"],
  ["보존 단체", "보존 운동가 · 연구자", "제독 관사 (Admiral's Row) 보존 논쟁 — 결국 대부분 철거 (2016)"],
 ],
 "laws": [
  ["뉴욕시 용도지역 결의 (Zoning Resolution) — M3-1 · M1-2 · M1-4 공업지구", "대부분 중공업지구 M3-1 (제조 · 일부 상업, 용적률 2.0), 서쪽 일부 경공업지구 M1-2"],
  ["시장 특례 (Mayoral Override) 4건 (2013~2018)", "M3-1 지구 안 대학원 (2013) · Dock 72 주차 기준 완화 1,849 → 379면 (2015) · 77동 대형 간판 (2017) · STEAM 고교 (2018) 허용"],
  ["브루클린 해군 조선소 특별지구 (Special Brooklyn Navy Yard District, ZR 제14편 제4장, 2021.12.15)", "외곽 일부를 M3-1 · M1-2 · R6B → M2-1 로 변경, 1만 ft² 넘는 소매 · 보육 · 체육 · 학교 · 박물관 등 추가 허용 (외곽 지구별 30만 ft², 상업 10만 ft² 상한), 용적률은 2.0 유지, 높이 · 후퇴 · 탑 형태 규제 완화 (최고 375~395ft 탑 가능), 주차 · 하역 기준 조정, 수변 공공 개방 공간 의무", "https://zr.planning.nyc.gov/recently-adopted/special-brooklyn-navy-yard-district-n-210463a-zrk"],
  ["브루클린 해군 조선소 마스터플랜 (Brooklyn Navy Yard Master Plan, BNYDC, 2018)", "신축 461만 ft² · 공공 개방 공간 18.9만 ft² · 2030년 고용 3만 명 — 수직형 제조 건물, 외곽 3개 개발지 (도시계획위원회 보고서에 요약)", "https://zap-api-production.herokuapp.com/document/projectaction/sites/nycdcppfs/dcp_projectaction/ZM%20-%20Zoning%20Map%20Amendment%20_03D01E0C3964E811812E1458D04D2538/210462.pdf"],
  ["산업사업지구 (Industrial Business Zone) · 중요 해양 · 산업 지역 (SMIA)", "조선소 대부분이 브루클린 해군 조선소 IBZ 와 SMIA 안에 있음"],
  ["국가 사적 역사지구 (NRHP, 2014)", "조선소 전체 등재, 사령관 관사 (Quarters A)는 국가 역사 기념물, 1호 건선거 · 해군 병원 등은 뉴욕시 랜드마크"],
 ],
 "lawsNote": ["규제완화의 핵심은 \"용도는 산업으로 지키되 형태와 지원 용도를 푸는 것\"입니다. 2021년 특별지구는 최대 용적률 2.0을 그대로 두면서 (실제 사용은 0.52 → 0.91) 높이 · 형태 · 주차 규제를 풀어 수직형 제조 건물을 가능하게 했고, 주거는 끝까지 허용하지 않았습니다."],
 "tools": [
  ["공공 소유 · 장기 임차", "땅을 팔지 않고 시가 소유 — BNYDC 에 99년 장기 임차, 입주 기업에는 안정적 · 저렴한 장기 임대"],
  ["주거 전환 금지 (산업 용도 유지)", "공업지구 · 특별지구로 제조업 일자리 보호"],
  ["건물 재사용", "128동 (기계 공장, 25만 ft²) → 그린 제조 센터 · Newlab, 77동 (100만 ft², 1억 4,300만 달러) → 제조 · 사무 · 식품 홀, 92동 → 박물관"],
  ["공공 투자", "2007년까지 블룸버그 시정부 3,000만 달러 투입 · 1억 8,000만 달러 추가 계획, 마스터플랜 25억 달러 (지분 · 부채 · 공공 재원 혼합으로 BNYDC 자체 개발)"],
  ["민간 장기 임대 · 앵커", "스타이너 스튜디오 70년 임대 (1999), Dock 72 · 399 Sands Street 등"],
  ["고용 연계", "앨버트 C. 윌트셔 고용 센터 — 입주 기업 구인의 약 70%를 지역 주민 등 신규 인력으로 채움 (FY25)"],
  ["용도 · 형태 특례", "2021 특별지구로 대형 층고 (40ft) 제조층 · 탑 형태 · 지원 용도 허용"],
 ],
 "zoning": [
  ["지정", "브루클린 해군 조선소 특별지구 (BNY, 2021) — 핵심 지구 (Core, M3-1) + 외곽 지구 3곳 (Navy Street · Flushing · Barge Basin, M2-1)"],
  ["관리 주체 · 방식", "BNYDC 가 시를 대신해 입주 심사 · 임대 · 신축 · 운영, 고용 센터 · STEAM 센터 운영"],
  ["보존 관리", "국가 사적 역사지구 (2014), 사령관 관사 국가 역사 기념물, 1호 건선거 등 시 랜드마크 — 제독 관사는 대부분 철거 (2016)"],
  ["관련 지정", "브루클린 해군 조선소 산업사업지구 (IBZ) · 중요 해양 · 산업 지역 (SMIA) · 100년 홍수 구역"],
 ],
 "funding": [
  ["토지 매입 (시비)", "뉴욕시가 연방정부로부터 2,250만 달러에 매입 계약 (1969, 1967년 합의가는 2,400만 달러)"],
  ["시비 투자", "블룸버그 시정부가 2007년까지 개조에 3,000만 달러 투입, 1억 8,000만 달러 추가 계획 (위키)"],
  ["연방 세제 혜택 (NMTC)", "128동 개조 (총 8,280만 달러)에 신시장 세액공제 (New Markets Tax Credit) 2,500만 달러 — Empire State Development · GS New Markets Fund · TruFund, 투자자 골드만삭스 (2012)", "https://nmtccoalition.org/project/brooklyn-navy-yard-building-128/"],
  ["민간 투자", "스타이너 스튜디오 1억 1,800만 달러 (2004 개장, 70년 임대)"],
  ["건물 개조", "77동 개조 1억 4,300만 달러 (2017)"],
  ["연방 재난 기금", "연방재난관리청 (FEMA)이 허리케인 샌디 피해 복구에 2,870만 달러 (2025)"],
  ["마스터플랜 재원", "2018 마스터플랜 약 25억 달러 — BNYDC 가 지분 · 부채 · 공공 재원을 섞어 자체 개발 (도시계획위원회 보고서)", "https://zap-api-production.herokuapp.com/document/projectaction/sites/nycdcppfs/dcp_projectaction/ZM%20-%20Zoning%20Map%20Amendment%20_03D01E0C3964E811812E1458D04D2538/210462.pdf"],
  ["연구 지원", "1996년 BNYDC 가 조선소 활용 방안 연구비 73만 9천 달러를 받음"],
  ["운영 보조금 (FY2024~25)", "운영 수입 가운데 보조금 79만 1,447달러 (FY2025, FY2024 106만 7,156달러) — 운영 수입의 약 0.8%", "https://comptroller.nyc.gov/wp-content/uploads/documents/BNYDC-Audited-Financial-Statements-6-30-25-Govt.pdf"],
  ["시 자본 기여 (FY2023~25)", "시 자본 기여 2,548만 (FY2023) · 4,504만 (FY2024) · 6,634만 달러 (FY2025) — 기반시설 · 건물 투자"],
  ["개발 대출 · 지역개발 채권 (FY2025 말)", "개발 대출 잔액 약 1억 5,658만 달러 (유동 3,663만 + 비유동 1억 1,996만), 지역개발 어음 약 3,533만 달러"],
 ],
 "operation": [
  ["운영 주체", "BNYDC — 뉴욕시의 구성 단위 (component unit)인 비영리 법인, 시와의 임대차 (갱신 포함 2111년까지) · 연간 관리 계약으로 조선소를 임대 · 관리 · 개발", "https://comptroller.nyc.gov/wp-content/uploads/documents/BNYDC-Audited-Financial-Statements-6-30-25-Govt.pdf"],
  ["자립 원칙", "운영 수입으로 모든 운영비를 충당하면서 고용을 늘리는 \"이중 책임\" — 도로 · 상하수도 · 소화전 · 청소 · 제설 · 경비까지 직접 관리"],
  ["수입 구성 (FY2025)", "운영 수입 9,505만 8천 달러 — 임대료 5,214만 · 리스 이자 2,392만 · 공공요금 1,189만 · 보험 291만 · 보조금 79만 · 기타 341만 달러"],
  ["수지 (FY2025)", "운영 지출 1억 93만 달러 → 운영 손실 약 587만 달러, 비운영 순지출 1,555만 달러 → 자본 기여 전 손실 2,142만 달러"],
  ["공공 자본 지원", "시 자본 기여 6,634만 달러 (FY2025, FY2024 4,504만) — 순자산 5억 1,149만 달러로 증가, 시가 기반시설 개선 재원을 대고 BNYDC 가 먼저 집행한 뒤 청구"],
  ["시에 내는 임대료", "1996년 개정 임대차로 기본 임대료는 순영업이익의 100% 또는 합의액 — 준비금 조건 충족 시 연 기본 임대료 0 (준비금 기준을 50만 달러로 낮춤)"],
  ["건물별 투자 구조", "128동은 55년 · 39년 전대차 구조와 역사 건물 세액공제 투자자 (BNY HTC, 2013~2022)를 활용, 77동은 전용 비영리 법인 (Building 77 QALICB)이 개조 · 운영"],
  ["운영 성과", "임대율 95% (2021, 도시계획위원회 보고서), 고용 센터가 입주 기업 구인 약 70% 충원 (FY25)"],
  ["운영상 문제", "FY2024 예상치 못한 공실로 임대 수입 감소, FY2024~25 운영 손실"],
 ],
 "operationNote": ["BNYDC 는 시 소유 땅을 장기 임차해 제조업체에 임대하고, 임대료 · 리스 이자 · 공공요금 등 연 약 9,500만 달러의 자체 수입으로 단지 관리비를 대는 구조입니다. 시에 내는 기본 임대료는 사실상 0이고, 큰 건물 개조 · 기반시설 투자는 시의 자본 기여와 세액공제 · 개발 대출로 채웁니다. 최근 운영 수지는 소폭 적자이지만 시 자본 투자로 순자산은 늘고 있습니다."],
 "famous": [
  "1801년 세워진 미 해군 조선소로, 전함 미주리 · 애리조나 · 메인 등을 지었고 2차 대전 때 7만 명 넘게 일한 \"Can-Do Shipyard\"였습니다.",
  "조선소 전체가 2014년 국가 사적 (NRHP) 역사지구로 등재되었습니다.",
  "도시 제조업을 주거로 바꾸지 않고 지켜 낸 \"현대 도시형 산업단지\"의 전국적 모델로 소개되며, 550개 넘는 기업에서 1만 3천 명 이상이 일합니다 (BNYDC).",
  "스타이너 스튜디오는 할리우드 밖 미국 최대급 제작 스튜디오이고, Newlab 은 로봇 · 하드웨어 · 기후기술 창업의 거점입니다.",
 ],
 "result": [
  "고용 2,700명 (1989) → 1만 1천 명 · 입주 450곳 (2021) → 1만 3천 명 이상 · 550곳 이상 (2025), 연 경제효과 25억 달러 이상 (BNYDC)",
  "입주 기업 17개 산업, 약 45%가 여성 · 소수인종 기업 (FY25)",
  "임대율 95% · 신축 150만 ft² 이상 (2021, 도시계획위원회 보고서)",
  "스타이너 스튜디오 — 할리우드 밖 미국 최대급 제작 스튜디오",
 ],
 "lesson": [
  "노후 산단을 주거로 바꾸지 않고 \"도시형 현대 제조업 단지\"로 유지한 모델 — 공공 소유 · 장기 임대로 산업 용지와 임대료를 지켰습니다.",
  "운영 주체의 역량이 성패를 가른다는 점 — 부실한 CLICK 에서 전문 비영리 공사 BNYDC 로 바꾼 뒤 회복했습니다.",
  "용적률을 올리지 않고도 높이 · 형태 · 지원 용도 규제만 풀어 \"수직형 공장\"을 가능하게 한 특별지구 방식은, 한국 산단의 고밀 복합화 규제 설계에 참고할 만합니다.",
  "고용 센터 · 직업고교를 단지 안에 두어 지역 주민을 일자리와 직접 연결했습니다.",
  "개발과 보존의 충돌 (제독 관사 철거)은 보존 대상을 미리 정해 두어야 함을 보여 줍니다.",
  "산업용지 보전 정책 연구에서 브루클린 해군 조선소는 공공이 산업 용지를 사들여 자격 있는 산업 용도에만 임대하는 \"산업 토지 신탁 · 은행 (industrial land trust or bank)\"의 대표 예로 꼽힙니다 (보스턴 해양산업단지 · 클리블랜드 토지은행과 함께, Chapple 2014)."
 ],
 "missing": [
  "브루클린 해군 조선소 산업사업지구 (IBZ)의 지정 연도는 확인된 자료를 찾지 못했습니다 (기존 내용의 2006년은 확인하지 못해 뺐습니다).",
  "입주 기업에 대한 세제 감면 내용은 확인된 자료를 찾지 못했습니다.",
  "1990년대 이후 시 · 주의 누적 공공 투자 총액은 확인된 자료를 찾지 못했습니다 (FY2023~25 시 자본 기여까지만 확인).",
 ],
 "refs": [
  {"t": "Brooklyn Navy Yard Development Corporation — Audited Financial Statements FY2025 (NYC Comptroller)", "u": "https://comptroller.nyc.gov/wp-content/uploads/documents/BNYDC-Audited-Financial-Statements-6-30-25-Govt.pdf"},
  {"t": "Brooklyn Navy Yard, Building 128 — New Markets Tax Credit Coalition", "u": "https://nmtccoalition.org/project/brooklyn-navy-yard-building-128/"},
  {"t": "Brooklyn Navy Yard — Wikipedia", "u": "https://en.wikipedia.org/wiki/Brooklyn_Navy_Yard"},
  {"t": "City Planning Commission, C 210462 ZMK — Special Brooklyn Navy Yard District (2021.10.20)", "u": "https://zap-api-production.herokuapp.com/document/projectaction/sites/nycdcppfs/dcp_projectaction/ZM%20-%20Zoning%20Map%20Amendment%20_03D01E0C3964E811812E1458D04D2538/210462.pdf"},
  {"t": "Special Brooklyn Navy Yard District (N 210463(A) ZRK) — NYC Zoning Resolution", "u": "https://zr.planning.nyc.gov/recently-adopted/special-brooklyn-navy-yard-district-n-210463a-zrk"},
  {"t": "Zoning Resolution 144-00 Special Brooklyn Navy Yard District", "u": "https://zr.planning.nyc.gov/index.php/article-xiv/chapter-4/144-00"},
  {"t": "Who we are — Brooklyn Navy Yard (BNYDC)", "u": "https://www.brooklynnavyyard.org/mission/"},
  {"t": "Brooklyn Navy Yard Releases FY25 Impact Report (BNYDC, 2026.1.8)", "u": "https://www.brooklynnavyyard.org/brooklyn-navy-yard-fy25-impact-report/"},
  {"t": "Chapple, K. (2014) The Highest and Best Use? Urban Industrial Land and Job Creation, Economic Development Quarterly", "u": "https://doi.org/10.1177/0891242413517134"}
 ],
},

"adlershof": {
 "spec": [
  ["위치", "독일 베를린 남동부 트렙토-쾨페니크 구 (Treptow-Köpenick) — 아들러스호프 · 요한니스탈 (Johannisthal)"],
  ["면적", "도시개발조치 구역 420ha (보완 구역 40ha 별도), 그중 상업 · 업무 용지 260ha · 경관공원 65~66ha (자연보호구역 26ha) — WISTA 과학기술단지 전체 4.6㎢ (2025)"],
  ["기간", "1991년 원칙 결정 → 1994.12.7 개발구역 지정 → 2003 계획 전환 → 진행 중"],
  ["원래 용도", "요한니스탈 비행장 (1909, 독일 최초의 동력 비행장) · 독일 항공연구소 (DVL) 시험시설 → 동독 과학아카데미 연구소 · 동독 TV 방송 (DFF, 1952~1991) · 국가보위부 경비연대 · 국가인민군 — 출입이 막힌 보안 구역"],
  ["변경 용도", "과학 · 경제 · 미디어 도시 (WISTA) — 훔볼트 대학 자연과학 캠퍼스 · 연구소 18곳 · 기업 약 1,300곳 · 미디어 시티 · 주거 · 경관공원"],
  ["원래 용도지구", "동독 국가 소유 연구 · 방송 · 군사 시설 (출입 제한 구역)"],
  ["변경 용도지구", "도시개발조치 구역 (städtebaulicher Entwicklungsbereich Johannisthal/Adlershof, 건설법전 제165조) — 지구상세계획 50건 중 43건 확정"],
  ["계획 규모 (1994)", "주택 5,500호 · 업무 · 미디어 · 연구 연면적 168.7만㎡ → 2003년 축소 조정"],
  ["현재 (2025)", "기업 약 1,300곳 · 과학기관 18곳 · 종사자 약 29,600명 · 학생 약 6,200명, 매출 · 예산 42억 유로 이상 (WISTA)"],
 ],
 "from": "옛 비행장 · 동독 과학아카데미 연구소 · 국가보위부 부대 · TV 방송국",
 "to": "과학 · 기술 · 미디어 도시 (대학 · 연구소 · 기업 · 주거 · 공원)",
 "zoneFrom": "동독 국가 소유 연구 · 방송 · 군사 시설",
 "zoneTo": "도시개발조치 구역 Johannisthal/Adlershof (BauGB §165, 1994)",
 "tenants": [
  ["첨단산업 · 대학", "훔볼트 대학 (Humboldt-Universität zu Berlin) 자연과학 캠퍼스", "1997~2003 이전 — 수학 · 정보 · 화학 · 물리 등 6개 연구소, 학생 약 6,000명 (2007 무렵)", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["첨단산업 · 연구시설", "BESSY II 전자 저장링 (현 헬름홀츠 센터 베를린, HZB)", "1994.7 착공 · 1997.4 가동 · 1998.10 첫 실험 (Brenner & Partner 설계), HZB 는 약 7,000㎡ 실험 · 사무동 증축 중 (2025)", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["첨단산업 · 연구기관", "막스 보른 연구소 (Max-Born-Institut, 비선형 광학 · 단펄스 분광)", "1991년 말 옛 아카데미 연구소 가운데 처음 설립된 연구기관", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["첨단산업 · 연방 연구기관", "연방 재료연구 · 시험원 (BAM)", "2025년 새 실험 · 연구동 착공", "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"],
  ["첨단산업 · 기술센터", "광자학 · 광학기술 센터 (Zentrum für Photonik und Optische Technologien, WISTA)", "1998.9 개관, 6개 동 7,000㎡ 이상, 6,300만 유로 — 신축 Sauerbruch Hutton · Ortner & Ortner", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["첨단산업 · 창업센터", "혁신 · 창업센터 IGZ · 태양광 · 재생에너지 센터 (WISTA)", "IGZ 1991 개설, 태양광 센터는 2025년 임대 공간 확장", "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"],
  ["첨단산업 · 앵커 기업", "예놉틱 다이오드 랩 (JENOPTIK Diode Lab) · 로데 슈바르츠 SIT (Rohde & Schwarz SIT) · 이글야드 포토닉스 (Eagleyard Photonics)", "2007년 무렵 결산 자료에 소개된 입주 기업 (신축 공장 · 사옥)", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["업무 · 공유오피스", "ST3AM 아르바이츠벨텐 (ST3AM-Arbeitswelten) · 메이커 스페이스", "2025.1 개관 (WISTA) — 코워킹 · 시제품 제작 공간", "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"],
  ["첨단산업 · 미디어", "미디어 시티 아들러스호프 (Medienstadt)", "기업 약 230곳 · 종사자 약 3,600명 (2025) — 옛 동독 TV 센터 자리", "https://www.wista.de/aktuelles/news/berlin-adlershof-daten-und-fakten-2026"],
  ["주거 · 신규 주거지", "세겔플리거 지구 (Segelflieger Quartier)", "2025.9 착공 — 약 21ha, 주택 약 1,800호 (4분의 1 공공 지원), 업무 공간 약 15만 3천㎡", "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"],
 ],
 "timeline": [
  ["1909", "요한니스탈 비행장 개장 — 독일 최초의 동력 비행장, 이후 독일 항공연구소 (DVL)"],
  ["1932~1940", "DVL 항공 시험시설 건설 — 대형 풍동 (1932~1934) · 회전 탑 (Trudelturm, 1934~1936) · 방음 엔진 시험대, 건축가 헤르만 브레너 (Hermann Brenner) · 베르너 도이치만 (Werner Deutschmann)"],
  ["1950~1952", "동독 TV 센터 건설 → 1952.12.21 동독 TV (DFF) 방송 시작, 동독 과학아카데미 연구소 · 국가보위부 경비연대 입주"],
  ["1990", "국가보위부와 경비연대 해체"],
  ["1991", "학술위원회 (Wissenschaftsrat)가 아카데미 연구소를 평가 · 일부를 새 기관으로 이전 권고, 말 막스 보른 연구소 설립 · 혁신창업센터 (IGZ) 개설, 주 대학구조위원회가 훔볼트 대학 자연과학부 이전 권고"],
  ["1991", "주 정부가 개발회사 EGA 에 옛 아카데미 땅 (약 76ha) 개발 위탁 (1994년 WISTA Management GmbH 로 이름 변경), 기본계획 (Rahmenplan) 발주"],
  ["1991.12.31", "동독 TV 방송 종료 · 아카데미 연구소 해산"],
  ["1992.9", "베를린 주 정부가 「아들러스호프/요한니스탈 경제 · 과학 개발사업」 기본 구상 결정 · 도시개발조치 예비조사 지시"],
  ["1993", "2단계 협력 설계 공모 (7개 팀) → 10월 합의안, 8월 수탁 개발회사 JAAG (뒤에 BAAG) 선정"],
  ["1994.7~1997", "전자 저장링 BESSY II 건설 (1997.4 가동)"],
  ["1994.12.7", "주 정부가 420ha 를 건설법전 제165조 도시개발조치 구역으로 정식 지정"],
  ["1996.6", "주 정부 10개항 프로그램 — 개발을 3단계로 나누고 밀도 축소"],
  ["1997~2003", "훔볼트 대학 자연과학 캠퍼스 건설 (1997.2 투자 규모 약 28% 삭감)"],
  ["2003.7", "주 정부 \"과감한 방향 전환\" — 구역 축소 · 조기 종료 · 신규 대출 금지 · 주 예산으로 재정 전환, 미실현 주거 용지를 업무 용지로"],
  ["2004.1.1", "WISTA 자회사 Adlershof Projekt GmbH 가 새 수탁 개발회사로 (현 WISTA.Plan GmbH)"],
  ["2005~2021", "고속도로 A113 연결 개통 (2005 · 2008) · 트램 아들러스호프 II 구간 개통 (2021)"],
  ["2025.9", "베를린 남동부 전력 시설 방화로 3일간 정전 — 단지 기업 · 연구소가 운영 차질, 그래도 2025년 매출 · 예산 약 5% 늘어 42억 유로 이상 (주 경제부 2026.3.23 발표)"],
 ],
 "problem": [
  "통일 뒤 동독 과학아카데미 연구소와 동독 TV 가 1991년 말 문을 닫고 국가보위부 부대가 해체되면서, 수십 년 동안 울타리로 막혀 있던 넓은 땅이 서로 연결되지 않은 채 버려졌습니다.",
  "작은 기업들이 일부 건물에 들어왔지만 기반이 약해 지역을 살릴 힘이 없었습니다.",
  "1990년대 초 베를린은 주택 35~40만 호와 업무 공간 300만㎡ 가 더 필요하다는 전망 아래, 큰 개발 용지를 빠르게 공급해야 했습니다.",
  "연구 인력과 장비를 살려 동베를린에 새로운 첨단 산업 거점을 만들 필요가 있었습니다.",
  "1990년대 중반 기대한 성장이 오지 않고 주 재정이 나빠지면서, 계획을 축소 · 조정해야 하는 문제가 생겼습니다.",
 ],
 "overview": [
  "아들러스호프는 학술위원회 평가로 살아남은 연구소, 옮겨 온 훔볼트 대학 자연과학부, 기업을 한곳에 모은 \"과학 도시\"입니다. 옛 아카데미 땅은 주 정부가 세운 WISTA Management 가 기술센터 · 창업센터를 지어 운영하고, 그 둘레 420ha 는 건설법전의 도시개발조치로 공공이 땅을 사서 기반을 닦은 뒤 되파는 방식으로 개발했습니다.",
  "1993년 설계 공모 합의안은 넓은 경관공원에서 녹지 쐐기가 풍차 날개처럼 새 구역 사이로 뻗고, 루도버 쇼세 (Rudower Chaussee)와 그로스-베를리너 담을 두 축으로 하는 \"지어진 공원\" 구상이었습니다. 옛 비행장은 경관공원 · 주거 지구로 바뀌었고, 풍동 · 회전 탑 · 엔진 시험대는 훔볼트 대학 캠퍼스의 「항공역학 공원」에 조형물처럼 남았습니다.",
  "1990년대 후반 경기 침체와 재정난으로 2003년 계획을 크게 줄였습니다. 주거 목표를 대폭 낮추고, 수탁 개발회사를 WISTA 자회사로 바꿔 기업 유치 중심으로 돌렸습니다. 그 뒤 광학 · 광자학, 태양광 · 재생에너지, 마이크로시스템 · 소재, IT · 미디어, 바이오 · 환경 클러스터가 자리 잡았습니다.",
 ],
 "actors": [
  ["도시계획가 · 건축가", "헤르만 브레너 (Hermann Brenner) · 베르너 도이치만 (Werner Deutschmann)", "1930년대 DVL 풍동 · 회전 탑 등 항공 시험시설 설계 (현 항공역학 공원의 문화재)"],
  ["도시계획가 · 건축가", "UrbanPlan (계획 그룹) + Becker Giseke Mohren Richard (조경)", "기본계획 (Rahmenplan) 수립 (1991년 발주)"],
  ["도시계획가 · 건축가", "Jourdan/Müller + Projektbüro Stadtlandschaft + BGS (교통) · Machleidt + Partner", "1993 설계 공모 1등안 → 합의안 / WISTA 부지 기반시설 · 도시설계 구상"],
  ["도시계획가 · 건축가", "Thomanek + Duquesnoy (조경) · Sauerbruch Hutton · Ortner & Ortner · Brenner & Partner · Benedikt Tonon", "항공역학 공원 설계 / 광자학 센터 신축 1 (1998) · 신축 2+3 / BESSY II / 화학 · 물리 연구소 건물"],
  ["주관 기관", "베를린 주 정부 (Senat von Berlin) — 도시개발부", "1991 원칙 결정, 1994 개발구역 지정 (법규명령), 2003 방향 전환, 재원 부담"],
  ["운영 관리", "WISTA Management GmbH (주 소유, 1991 EGA → 1994 개명)", "과학기술단지 개발 · 운영, 기술 · 창업센터, 기업 유치"],
  ["사업 시행 (수탁)", "JAAG → BAAG (Berlin Adlershof Aufbaugesellschaft, 1993~2003) → Adlershof Projekt GmbH (2004~, 현 WISTA.Plan)", "도시개발조치 수탁 시행 — 토지 매입 · 정비 · 기반시설 · 필지 매각"],
  ["전문가 기구", "학술위원회 (Wissenschaftsrat) · 베를린 주 대학구조위원회 (LHSK)", "아카데미 연구소 평가 · 재편 (1991), 훔볼트 대학 자연과학부 이전 권고"],
  ["감사 기구", "베를린 주 감사원 (Landesrechnungshof)", "1998~2000 개발조치 중단 여부 검토 — 중단 대신 축소 · 조기 종료 권고"],
  ["대학 · 연구", "훔볼트 대학 (6개 연구소) · 막스 보른 연구소 · BESSY · 아들러스호프 비대학 연구기관 협의회 (IGAFA)", "지식 거점 · 앵커"],
 ],
 "laws": [
  ["연방 건설법전 (Baugesetzbuch, BauGB) 제165조 — 도시개발조치 (städtebauliche Entwicklungsmaßnahme)", "공공이 구역 안 땅을 사서 개발한 뒤 계획 권리가 붙은 땅으로 되팔 수 있음, 필요하면 지구상세계획 없이도 수용 가능. 스스로 개발하는 소유자는 개발로 오른 땅값만큼 정산금 (Ausgleichsbetrag) 납부, 개발 중 매매 · 분할에 허가 필요, 되판 땅엔 건축 의무"],
  ["Johannisthal/Adlershof 개발구역 지정 법규명령 (1994.12.7)", "420ha 를 도시개발조치 구역으로 정식 지정, WISTA 부지는 \"적응 구역 (Anpassungsgebiet)\"으로 특별 취급", "https://www.berlin.de/sen/stadtentwicklung/neue-stadtquartiere/johannisthal-adlershof/planungsprozess/"],
  ["기본계획 (Rahmenplan Johannisthal/Adlershof, 1991 발주) · 기본 구상 「아들러스호프/요한니스탈 경제 · 과학 개발사업」 (Rahmenkonzept, 1992.9 주 정부 결정)", "과학 · 경제 · 미디어 도시의 용도 구상, 도시개발조치 예비조사 지시"],
  ["도시설계 합의안 (Konsensplan, 1993.10) · 도시계획 종합안 (Städtebaulicher Gesamtplan 1993)", "경관공원과 녹지 쐐기, 두 개의 주축, 캠퍼스 블록 격자의 \"지어진 공원\" 구상"],
  ["주택 건설 행동 프로그램 「Wohnungsbaustrategien '95」 (1992.4)", "베를린 주택 공급 27개 후보지에 아들러스호프 포함 — 특별 도시계획법 수단을 쓰기로 함"],
  ["지구상세계획 (Bebauungsplan)", "50건 작성 · 43건 확정 — 용도 · 밀도 결정"],
  ["주 정부 방향 전환 결정 (2003.7)", "개발 목표 축소, 구역 축소, 종료 시점 2006년 (정산 2007), 미실현 주거 용지를 업무 용지 · 혼합 지역으로 변경", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["주 정부 10개항 프로그램 (Zehnpunkteprogramm, 1996.6)", "개발조치를 3단계 (1996~2000 · 2001~2005 · 2006~2010)로 나누고 수요 맞춤 · 밀도 축소"],
 ],
 "lawsNote": ["규제완화라기보다 \"강한 공공 개입\" 제도입니다. 도시개발조치는 공공이 개발 전 땅을 확보하고 개발이익 (땅값 상승분)으로 정비 · 기반시설 비용을 충당하는 방식으로, 원래 국가 소유 땅이 많던 이곳에 대규모 일괄 개발을 가능하게 했습니다. 다만 개발이익만으로는 비용을 감당하지 못해 주 예산이 크게 들어갔습니다."],
 "tools": [
  ["개발이익 환수", "수탁 재산 (Treuhandvermögen)의 주 수입원은 개발 전후 땅값 차이 — 주가 산 땅은 되팔 때, 나머지는 소유자 정산금으로 회수"],
  ["토지 매입 · 정비", "공공이 땅을 사서 오염 정화 · 부지 정리 (4,700만 유로 투입) 후 필지 매각"],
  ["주 예산 직접 투자", "공공 기반시설 · 외부 연결 · 공공시설은 처음부터 주 예산, 2003년 이후 전부 주 예산 — 주가 아들러스호프에 쓴 순비용 약 3억 6천만 유로 이상 (지출 약 4억 6천만 유로 − 토지 매각 수입)"],
  ["기술 · 창업센터", "WISTA 가 혁신창업센터 (1991) · 광자학 센터 (1998, 6,300만 유로) 등을 지어 임대"],
  ["대학 이전 (앵커)", "훔볼트 대학 자연과학부 6개 연구소 이전 (1997~2003)"],
  ["클러스터 특화", "광학 · 광자학, 태양광 · 재생에너지, 마이크로시스템 · 소재, IT · 미디어, 바이오 · 환경"],
 ],
 "zoning": [
  ["지정", "도시개발조치 구역 Johannisthal/Adlershof — 420ha, 1994.12.7 (법규명령)"],
  ["관리 주체 · 방식", "베를린 주가 수탁 개발회사 (BAAG → Adlershof Projekt GmbH / WISTA.Plan)를 통해 시행, 과학기술단지는 WISTA Management 가 운영 — 단지를 핵심 지구 · 성장 지구 · 미디어 시티로 나눠 관리"],
  ["보존 관리", "DVL 풍동 (1932~34) · 회전 탑 · 엔진 시험대 · 구형 항온 실험실 (1959~61) 등 기존 건물을 계획에서 \"확정 존치 건물 (문화재 등)\"로 남겨 캠퍼스 공원에 보존, 포럼 광장의 실험실 작은 건물들은 문화재 보호"],
  ["녹지 관리", "경관공원 (경관보호구역) · 자연보호구역 26ha"],
 ],
 "funding": [
  ["개발이익 (수탁 재산)", "수탁 재산의 주 수입원은 개발 전후 땅값 차이 — 토지 재매각 · 소유자 정산금, 그 사이 수탁회사가 지방채 수준 조건으로 대출 (2003년 이후 금지 · 주 예산으로 인수)", "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"],
  ["주 예산 (순비용)", "베를린 주가 Johannisthal/Adlershof 에 들인 순비용 약 3억 6천만 유로 이상 — 지출 약 4억 6천만 유로에서 토지 매각 수입을 뺀 값 (결산 자료)"],
  ["주 예산 (직접)", "공공 기반시설 용지 매입 · 외부 연결 · 공공시설은 처음부터 주 예산으로 직접 부담"],
  ["정화 비용", "오염 정화 · 부지 정리에 4,700만 유로"],
  ["시설 투자", "광자학 · 광학기술 센터 6,300만 유로 (1998 개장)"],
  ["보조금 의존도", "WISTA 기업 매출 중 보조금 비율 23.8% (1996) → 4.5% (2006)"],
 ],
 "operation": [
  ["운영 주체", "WISTA Management GmbH — 베를린 주 100% 소유 (자본금 1,177.6만 유로, 직원 80명, 2025 매출 3,190만 유로)", "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"],
  ["수입 구성", "기술센터를 직접 짓고 운영 · 임대, 지상권 (Erbbaurecht) 설정으로도 토지 공급 (2025 연차보고서) — 창업 · 네트워킹 · 교육 (WISTA Academy) 서비스"],
  ["자회사", "WISTA.Plan GmbH (주의 도시개발 수탁 시행자, 직원 50명, 매출 420만 유로) · WISTA.Service GmbH (시설관리, 직원 113명, 매출 2,100만 유로)"],
  ["공모 보조금", "연방경제부가 기후 회복력 연구 2건 (TransformResQ · ResQEnergy)에 280만 유로 (2025)"],
  ["주 정부 위탁 업무", "주 경제부 위탁으로 「베를린 미래 장소 (Zukunftsorte)」 사무국 운영, 다른 혁신 단지 (CHIC · FUBIC · Marzahn) 운영 · 마케팅"],
  ["단지 성과", "2025년 기업 약 1,300곳 · 종사자 29,600명 · 매출 · 예산 42억 유로 이상"],
  ["보조금 의존도 변화", "WISTA 기업 매출 중 보조금 비율 23.8% (1996) → 4.5% (2006)"],
  ["수입 구성 (2017)", "WISTA 매출 2,395.9만 유로 (총성과의 95.3%) — 그중 임대 · 임차 수입 2,052.4만 유로, 행사 서비스 (Adlershof con.vent.) 97.2만, 프로젝트 수입 122.6만 유로 / 보조금 (Zuwendungen) 101.7만 유로 (4.0%)", "https://www.wista.de/fileadmin/user_upload/downloads/wista/2017_WISTA_Lagebericht.pdf"],
  ["수지 (2017)", "연간 순이익 190.1만 유로 (2016 293.5만), 부동산 비용 1,655.8만 · 감가상각 1,193.9만 · 인건비 371.8만 유로"],
  ["기술센터 입주율 (2017)", "기술센터 입주율 93% — 보조금을 받은 센터는 입주 기간이 보통 최대 8년으로 제한되어, 졸업 기업을 민간 건물로 옮기는 것이 과제"],
  ["토지 매각 (2017)", "판매 가능한 토지 약 3.5ha (공시지가 기준 약 1,300만 유로) — 직접 투자하는 입주 기업에 토지를 파는 것을 매출 개선의 주 수단으로 제시"],
 ],
 "operationNote": ["아들러스호프는 주 소유 회사 WISTA 가 기술센터 임대와 지상권 설정으로 수입을 얻고, 시설관리 자회사 · 개발 수탁 자회사를 함께 거느려 단지를 운영합니다. 개발 단계의 기반시설 · 토지 비용은 주 예산과 개발이익 (도시개발조치)으로 충당했고, 운영 단계에서는 임대 · 서비스 수입과 주 · 연방의 사업 위탁 · 연구 보조금이 섞여 있습니다."],
 "famous": [
  "독일에서 가장 큰 과학 · 기술 단지로 평가되며 (주 정부 결산 자료), 2025년 기업 약 1,300곳 · 종사자 약 29,600명이 모였습니다 (WISTA).",
  "2002년 유럽연합으로부터 「우수 지역 (Region of Excellence)」으로 선정되었습니다.",
  "1909년 문을 연 독일 최초의 동력 비행장 자리이고, 풍동 · 회전 탑 같은 1930년대 항공 시험시설이 캠퍼스 공원에 남아 있습니다.",
  "동독 과학아카데미 · 동독 TV · 국가보위부 시설을 통일 뒤 과학 도시로 바꾼, 통일 독일의 대표적 전환 사례입니다.",
 ],
 "result": [
  "WISTA 입주 기업 200곳 (1997) → 757곳 (2006), 매출 중 보조금 비율 23.8% (1996) → 4.5% (2006) (주 정부 결산 자료)",
  "2025년 기업 약 1,300곳 · 과학기관 18곳 · 종사자 약 29,600명 · 학생 약 6,200명, 매출 · 예산 42억 유로 이상 (WISTA)",
  "2002년 유럽연합 「우수 지역 (Region of Excellence)」 선정",
  "주택 약 2,900호 완공, 약 2,400호 건설 · 계획 중 (베를린 도시개발부)",
  "2025년 과학기관 종사자 4,200명, 훔볼트 대학 입주 기관 외부 연구비 3,800만 · 기본 재원 8,600만 유로, 비대학 연구소 예산 3억 5,600만 유로 · 외부 연구비 1억 300만 유로 (+27%) — 주 경제부 보도자료 (2026)",
 ],
 "lesson": [
  "공공 (주)이 운영회사를 세워 연구소 · 대학 · 기업을 한곳에 모은 \"과학 도시\"형 재생 — 대학 이전이 강력한 앵커가 되었습니다.",
  "개발이익 환수형 제도 (도시개발조치)로 공공이 땅을 먼저 확보한 점은 한국 산단 재생의 토지 · 재원 구조와 비교할 만하지만, 개발이익만으로는 비용을 다 감당하지 못했다는 점도 함께 보아야 합니다.",
  "수요 예측이 빗나가자 2003년 계획을 과감히 줄이고 시행 주체를 단지 운영회사로 일원화한 \"중간 수정\"이 이후 성장의 계기가 되었습니다.",
  "항공 시험시설 같은 산업유산을 캠퍼스 공원의 상징으로 살려 장소의 정체성을 만들었습니다.",
 ],
 "missing": [
  "2007년 결산 자료에 나온 입주 기업 (예놉틱 · 로데 슈바르츠 등)의 현재 입주 여부는 확인된 자료를 찾지 못했습니다.",
  "2025년 WISTA 매출의 세부 구성 (임대 · 지상권료 · 보조금 비율)은 확인된 자료를 찾지 못했습니다 (2017년 구성만 확인).",
  "EU 구조기금 등 외부 보조금 액수는 확인된 자료를 찾지 못했습니다.",
  "통일 뒤 재배치된 연구 인력 수 · 옛 아카데미 연구자 창업 기업 수는 확인된 자료를 찾지 못했습니다 (기존 내용의 1,500명 · 250곳 중 100곳 · 5,600명은 확인하지 못해 뺐습니다).",
  "지구상세계획의 용적률 (GFZ) 수치는 확인된 자료를 찾지 못했습니다.",
  "개발에 참여 · 반대한 주민 · 시민단체는 확인된 자료를 찾지 못했습니다.",
  "개발조치 구역의 공식 해제 (Aufhebung) 시점은 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Trotz Anschlag in 2025: Technologiepark Adlershof wächst weiter (Senatsverwaltung für Wirtschaft, 2026.3.23)", "u": "https://www.berlin.de/sen/web/presse/pressemitteilungen/2026/pressemitteilung.1655130.php"},
  {"t": "Der Aerodynamische Park in Adlershof — Berliner Zentrum Industriekultur", "u": "https://industriekultur.berlin/ort/aerodynamischer-park-adlershof/"},
  {"t": "WISTA-Management GmbH Lagebericht 2017", "u": "https://www.wista.de/fileadmin/user_upload/downloads/wista/2017_WISTA_Lagebericht.pdf"},
  {"t": "WISTA Jahresbericht 2025 (WISTA Management GmbH)", "u": "https://www.wista.de/fileadmin/user_upload/downloads/jahresberichte/WISTA_Jahresbericht_2025.pdf"},
  {"t": "Unternehmensprofil — WISTA Management GmbH", "u": "https://www.wista.de/unternehmensprofil"},
  {"t": "Berlin-Adlershof — Wikipedia (독일어)", "u": "https://de.wikipedia.org/wiki/Berlin-Adlershof"},
  {"t": "Städtebaulicher Entwicklungsbereich Johannisthal/Adlershof — Bilanz der Entwicklung (베를린 주 정부 결산 자료)", "u": "https://www.adlershof.de/fileadmin/user_upload/downloads/JohannisthalAdlershofBilanz.pdf"},
  {"t": "Johannisthal/Adlershof — Planungsprozess (Senatsverwaltung für Stadtentwicklung, Berlin.de)", "u": "https://www.berlin.de/sen/stadtentwicklung/neue-stadtquartiere/johannisthal-adlershof/planungsprozess/"},
  {"t": "Johannisthal/Adlershof — Lage und Geschichte (Berlin.de)", "u": "https://www.berlin.de/sen/stadtentwicklung/neue-stadtquartiere/johannisthal-adlershof/lage-und-geschichte/"},
  {"t": "Berlin Adlershof: Daten und Fakten 2026 (WISTA Management GmbH)", "u": "https://www.wista.de/aktuelles/news/berlin-adlershof-daten-und-fakten-2026"},
 ],
},
}
