# -*- coding: utf-8 -*-
# 리노베이션 노트 — 더 자세한 본문 (reno*.py 의 같은 id 를 덮어씀) — 배정 08
#  sesc-pompeia, lx-factory, ghirardelli-square, seoullo-7017, culture-station-seoul-284, mmca-seoul
D = {
"sesc-pompeia": {
 "from": "강철 드럼통 공장 → 냉장고 공장", "to": "SESC 문화 · 여가 · 스포츠 센터", "y0": "1938 공장 개업 · 1970년대 SESC 가 인수",
 "archAbout": [
  "리나 보 바르디 (Lina Bo Bardi, 1914~1992)는 이탈리아에서 태어나 1946년 브라질로 이주한 건축가입니다. 상파울루 미술관 (MASP)도 그의 작품이며, MASP 와 세스크 폼페이아 모두 브라질 국가 문화유산 기관 이파운 (IPHAN)의 보호를 받습니다.",
  "1976년 SESC 의 초청으로 옛 폼페이아 드럼통 공장 창고들을 여가 센터로 바꾸는 설계를 맡았습니다. 설계에 앞서 이미 공장 터를 쓰고 있던 동네 사람들(5인제 축구 팀, 아마추어 연극 모임, 노인 댄스 모임, 어린이 보이스카우트 등)을 관찰한 것이 출발점이었습니다.",
  "협력 건축가는 앙드레 바이네르 (André Vainer) · 마르셀루 페하스 (Marcelo Ferraz), 구조 기술자는 조제 카를루스 지 피게이레두 페하스 (José Carlos de Figueiredo Ferraz)입니다. 마르셀루 페하스는 훗날 이 작업의 과정을 기록한 글 「세스크 폼페이아 만들기 (The Making of SESC Pompéia)」를 남겼습니다.",
 ],
 "spec": [
  ["원 건축물", "폼페이아 공장 (Fábrica da Pompeia) — 독일계 마우제르 (Mauser & Cia Ltda.)의 강철 드럼통 공장, 1938년 개업 (영문 위키백과). 페하스의 글은 1920년대 설립으로 적음"],
  ["원 구조", "프랑수아 엔비크 (François Hennebique) 방식의 철근콘크리트 골조 + 벽돌 창고 (아르키텍투라 비바)"],
  ["원래 용도 변천", "드럼통 공장 → 1945년 브라질 회사에 넘어감 → 이베자-젤로마치크 (Ibesa-Gelomatic) 냉장고 공장"],
  ["변경 용도", "SESC 폼페이아 — 극장 (774석) · 도서실 · 전시장 · 식당 (코메도리아) · 작업실 · 수영장 · 체육관 · 일광욕 데크"],
  ["건축주 · 운영", "상업사회서비스 (SESC, Serviço Social do Comércio) 상파울루"],
  ["개조 설계", "리나 보 바르디 (Lina Bo Bardi) — 협력 앙드레 바이네르 (André Vainer) · 마르셀루 페하스 (Marcelo Ferraz)"],
  ["구조", "조제 카를루스 지 피게이레두 페하스 (José Carlos de Figueiredo Ferraz)"],
  ["설계 · 공사", "1976년 초청 · 1977년 설계 → 1977~1986년 (2단계)"],
  ["개관", "1982년 1단계 (옛 공장 창고) · 1986년 2단계 (스포츠 블록)"],
  ["대지 · 연면적", "대지 16,573㎡ · 연면적 23,571㎡ (arquivo.arq.br)"],
  ["새 탑", "콘크리트 스포츠 탑 2동 + 높이 70m 원통형 물탱크 탑 · 두 탑 사이 프리스트레스트 콘크리트 공중 다리 8개 (최대 경간 25m)"],
  ["위치", "브라질 상파울루 폼페이아 — 클렐리아 거리 (Rua Clélia) 93"],
 ],
 "tenants": [
  ["문화 · 공연장", "극장 (Teatro)", "옛 공장에서 가장 높은 창고 · 774석, 양쪽에서 무대를 보는 객석 · 1982년 1단계 개관 때부터", "https://pt.wikipedia.org/wiki/Sesc_Pompeia"],
  ["문화 · 도서관", "도서실 · 독서 공간 (Biblioteca / Espaço de Leitura)", "옛 공장 창고 안 · 6세 이하 어린이 놀이 공간 (Espaço de Brincar)과 함께", "https://portal.sescsp.org.br/online/artigo/compartilhar/9780_OCUPE+O+SESC+POMPEIA"],
  ["문화 · 전시장", "전시 공간 (Área de Exposições)", "옛 공장 창고 · 기획 전시", "https://portal.sescsp.org.br/online/artigo/compartilhar/9780_OCUPE+O+SESC+POMPEIA"],
  ["문화 · 휴게 공간", "함께 지내는 곳 (Área de Convivência)", "옛 공장 창고 · 실내 물길과 벽난로", "https://portal.sescsp.org.br/online/artigo/compartilhar/9780_OCUPE+O+SESC+POMPEIA"],
  ["문화 · 작업실", "작업실 (Oficinas)", "콘크리트 블록으로 새로 지은 작업실 — 공예 · 미술 강좌", "https://portal.sescsp.org.br/online/artigo/compartilhar/9780_OCUPE+O+SESC+POMPEIA"],
  ["상업 · 식음", "코메도리아 (Comedoria) · 쇼페리아 (Choperia, 맥주홀)", "옛 공장 창고 · 유럽 선술집에서 따온 긴 공동 식탁", "https://agenciabrasil.ebc.com.br/cultura/noticia/2015-03/iphan-tomba-complexo-cultural-projetado-por-lina-bo-bardi-na-capital"],
  ["문화 · 스포츠", "스포츠 블록 (Bloco Esportivo) · 수영장 · 일광욕 데크 (Solarium)", "1986년 · 콘크리트 탑 2동에 체육관 · 탈의실을 층층이, 데크가 옛 공장과 연결", "https://arquitecturaviva.com/works/sesc-fabrica-pompeia-9"],
 ],
 "timeline": [
  ["1938", "독일계 마우제르 (Mauser & Cia Ltda.)의 폼페이아 공장 개업 (영문 위키백과 기준)"],
  ["1945", "공장이 브라질 회사에 넘어감 — 이후 이베자-젤로마치크 냉장고 공장"],
  ["1946", "SESC 설립 (법령 9.853호, 9월 13일)"],
  ["1976", "SESC 가 리나 보 바르디를 초청해 옛 드럼통 공장 창고의 여가 센터 설계를 맡김"],
  ["1977", "설계 시작 — 옛 공장 창고부터 개조 착수"],
  ["1982", "1단계 개관 (옛 공장 창고: 극장 · 전시 · 도서 · 식당 · 작업실). 개관 행사에 펑크 밴드들이 공연"],
  ["1986", "2단계 스포츠 블록 (콘크리트 탑 2동 · 물탱크 탑 · 공중 다리) 개관"],
  ["1992", "리나 보 바르디 별세"],
  ["2009", "상파울루시 보존위원회 (CONPRESP) 결의 05/09 — 라파 지역 산업 유산 (ZEPEC)으로 보호"],
  ["2015.3", "IPHAN 문화유산 자문회의 (제78차)가 국가 지정 (tombamento)을 만장일치로 승인"],
  ["2015.12", "IPHAN 미술 대장 (Livro do Tombo das Belas Artes)에 등재 (절차 번호 1726-T-2014)"],
 ],
 "heritage": [
  ["국가 지정 (Tombamento federal, IPHAN, 2015)", "문화유산 자문회의 만장일치 승인 (2015.3), 미술 대장 (Livro do Tombo das Belas Artes) 등재 (2015.12), 절차 1726-T-2014. 지정 이유 — 브라질 건축의 이정표이며, 특히 보 바르디의 구조적 개입이 지닌 기술적 · 미적 가치"],
  ["시 지정 (CONPRESP 결의 05/09, 2009)", "상파울루시 라파 (Lapa) 지역 산업 유산 보존 구역 (ZEPEC) 가운데 하나로 보호"],
 ],
 "concept": [
  "보 바르디는 공장 창고들을 허물지 않고, 이미 그곳을 쓰고 있던 사람들의 모습(공놀이 · 연극 · 춤)을 그대로 이어 갈 \"시민의 집\"을 구상했습니다. 옛 공장에서 트럭이 드나들던 길은 보행자 전용 거리가 되었습니다.",
  "옛 공장을 남기기로 하면서 스포츠 시설을 놓을 땅은 대지 한쪽 귀퉁이만 남았고, 그 가운데로 지하수가 흐르는 땅(아과스 프레타스 개천, Córrego das Águas Pretas)에는 건물을 지을 수 없었습니다. 그래서 체육관 · 수영장을 두 개의 콘크리트 탑에 층층이 쌓고, 건축할 수 없는 띠 위로 프리스트레스트 콘크리트 공중 다리 8개를 걸었습니다.",
  "높이 70m 의 원통형 물탱크 탑은 멀리서도 보이는 표지이며, 보 바르디는 그 \"레이스\" 같은 표면을 멕시코 건축가 루이스 바라간 (Luis Barragán)에게 바치는 오마주라고 했습니다.",
 ],
 "strategy": {
  "keep": ["옛 공장 창고들 — 벽돌 벽 · 철근콘크리트 골조 · 지붕", "트럭이 다니던 공장 안 길 (보행 거리로)"],
  "change": ["창고 → 극장 (가장 높은 창고, 양쪽 객석) · 전시장 · 도서실 · 식당 (긴 공동 식탁) · 작업실", "\"함께 지내는 곳 (Convivência)\" — 실내에 물길과 벽난로를 둔 휴게 공간"],
  "add": ["콘크리트 스포츠 탑 2동 (체육관 · 탈의실을 층층이)", "높이 70m 원통형 물탱크 탑", "공중 다리 8개 (최대 25m)", "콘크리트 블록 작업실 · 동굴을 떠올리게 하는 불규칙한 창", "옛 공장과 스포츠 블록을 잇는 데크 (일광욕장)"],
 },
 "why": [
  "철거 대신, 사람들이 이미 쓰고 있던 방식을 관찰해 공간 계획의 근거로 삼았습니다. 공장 길은 거리로, 창고는 극장 · 식당 · 작업실로 바뀌어 일상의 쓰임이 이어졌습니다.",
  "땅의 제약(좁은 귀퉁이 · 지하수 띠)을 수직으로 쌓은 탑과 공중 다리로 풀어, 보존과 신축 프로그램을 함께 이뤘습니다.",
  "새 콘크리트 탑과 옛 벽돌 창고가 뚜렷이 대비되면서도 한 단지로 묶여, 브라질 국가 문화유산 (IPHAN) 지정 사유로 \"구조적 개입의 기술적 · 미적 가치\"가 꼽혔습니다.",
 ],
 "space": [
  "옛 공장 쪽: 가운데 보행 거리를 따라 창고들이 늘어서고, 그 안에 극장 (가장 높은 창고, 양쪽 객석) · 전시장 · 도서실 · 독서 공간 · 6세 이하 어린이 놀이 공간 · 식당 · 맥주홀이 들어 있습니다.",
  "스포츠 블록: 두 콘크리트 탑에 운동 공간과 탈의실을 층층이 쌓고, 두 탑을 공중 다리 8개가 잇습니다. 다리 아래로는 아과스 프레타스 개천 띠가 지나갑니다.",
  "데크 (일광욕장)가 옛 공장과 스포츠 블록을 이어 줍니다. 어린아이를 위해 \"해변처럼\" 만든 수영장이 있습니다.",
 ],
 "material": [
  "옛 것: 엔비크 방식의 철근콘크리트 골조와 붉은 벽돌 창고를 그대로 드러냈습니다.",
  "새 것: 거친 노출 콘크리트 탑 · 프리스트레스트 콘크리트 다리 · 콘크리트 블록 작업실.",
  "세부: 기능별로 색을 칠한 배관, 화장실의 색 타일, 화가 후벵스 게르시만 (Rubens Gerchman)이 그린 바나나잎 무늬 타일(주방 · 수영장), 나무 의자의 극장.",
 ],
 "funding": [
  ["운영 재원 (공공 성격 의무 분담금)", "SESC 는 1946년 법령 9.853호로 세워졌고, 상업 · 서비스 · 관광 기업이 급여 총액의 1.5% 를 의무 분담금으로 내어 운영됩니다.", "https://transparencia-dn.sesc.com.br/transparencia/pagina/ler/7"],
  ["의무 분담금 규모 (SESC 상파울루 전체, 2024)", "분담금 (Contribuições) 수납액 약 29억 9,593만 헤알 (R$ 2.995.934.016,53) — 상파울루 지부 47개 시설 전체 기준이며, 폼페이아 한 곳의 몫은 공개되지 않음", "https://transparencia-sp.sesc.com.br/uploads/documento/avaliacao_arquivos/27/relatorio-de-gestao/relatorio-de-gestao-pdf-2024.pdf"],
  ["무상 제공 의무 (PCG)", "법령 6.632/2008 에 따라 순 의무 분담금의 1/3 (33.33%) 을 교육 등에 쓰고 그 절반 (16.67%) 을 무상 제공 — 2024년 상파울루 지부 실적: 배정 9억 4,839만 헤알, 그중 무상 4억 7,434만 헤알", "https://transparencia-sp.sesc.com.br/uploads/documento/avaliacao_arquivos/27/relatorio-de-gestao/relatorio-de-gestao-pdf-2024.pdf"],
 ],
 "famous": [
  "뉴욕 타임스 (The New York Times)가 제2차 세계대전 뒤 지어진 가장 중요한 건축 25선의 하나로 꼽았습니다 (포르투갈어 위키백과).",
  "2015년 브라질 국가 문화유산 (IPHAN)으로 지정되었습니다.",
  "하루 약 5,000명이 이용하는 살아 있는 시설입니다 (영문 위키백과).",
  "영국 가디언 (The Guardian)의 \"가장 아름다운 콘크리트 건물\" 목록에서 6위로 꼽혔습니다 (SESC 상파울루 소개 글).",
 ],
 "lesson": [
  "설계 전에 그 장소를 이미 쓰고 있는 사람들의 활동을 관찰하면, 무엇을 남길지(길 · 창고)가 분명해집니다.",
  "옛 건물을 지키느라 생긴 땅의 제약은 수직 증축과 다리 같은 과감한 신축으로 풀 수 있습니다.",
  "새 구조물을 옛 것과 분명히 다른 재료(노출 콘크리트)로 지으면, 둘 다 읽히는 단지가 됩니다.",
 ],
 "operation": [
  ["운영 주체", "상업사회서비스 (SESC) 상파울루 지부 — 1946년 법령 9.853호로 세운 민간 비영리 기관 (\"S 시스템\")"],
  ["수입 구성", "상업 · 서비스 · 관광 기업이 급여 총액의 1.5% 를 의무 분담금으로 내며, SESC 는 이 분담금으로 \"상당 부분\" 유지됩니다", "https://transparencia-dn.sesc.com.br/transparencia/pagina/ler/7"],
  ["수입 구성 (SESC 상파울루 전체, 2024 결산)", "총수입 약 37억 8,422만 헤알 — 의무 분담금 29억 9,593만 (약 79%) · 재산 수입 (receita patrimonial) 5억 1,194만 (약 14%) · 서비스 수입 (receita de serviços) 2억 4,030만 (약 6%) · 기타 약 3,600만. 총지출 약 37억 헤알", "https://transparencia-sp.sesc.com.br/uploads/documento/avaliacao_arquivos/27/relatorio-de-gestao/relatorio-de-gestao-pdf-2024.pdf"],
  ["시설 자산 (폼페이아)", "SESC 상파울루 부동산 목록의 폼페이아 가액 약 3억 3,539만 헤알 (2024, 장부 기준)", "https://transparencia-sp.sesc.com.br/uploads/documento/avaliacao_arquivos/27/relatorio-de-gestao/relatorio-de-gestao-pdf-2024.pdf"],
  ["이용 체계", "상업 노동자용 회원증 (Credencial Plena) 제도가 있음 — 요금 체계 · 비율은 확인 못 함"],
  ["운영 성과", "하루 약 5,000명 이용 (영문 위키백과)"],
 ],
 "operationNote": ["세스크 폼페이아는 정부 보조금이나 임대 수익이 아니라, 기업들이 급여의 1.5% 를 내는 의무 분담금으로 주로 운영되는 SESC 상파울루의 47개 시설 가운데 하나입니다. 2024년 SESC 상파울루 전체 수입 약 37억 8천만 헤알 가운데 약 79% 가 의무 분담금이고, 이용료 등 서비스 수입은 약 6% 입니다. 법령에 따라 순 분담금의 1/6 을 무상 제공에 써야 하므로 이용자 부담이 낮게 유지됩니다. 폼페이아 한 곳의 수입 · 지출은 공개 보고서에서 따로 확인하지 못했습니다."],
 "missing": [
  "주요 입주 시설 — SESC 가 직접 운영하는 시설로 외부 입주 기업은 없으며, 식당 등의 현재 운영 방식은 확인된 자료를 찾지 못했습니다.",
  "수익사업 · 운영 재원 — 세스크 폼페이아 한 곳의 연간 예산 · 수입 구성과 최근 이용자 수는 확인된 자료를 찾지 못했습니다 (SESC 상파울루 전체 수치만 확인).",
  "SESC 가 공장 터를 사들인 정확한 연도와 금액은 확인된 자료를 찾지 못했습니다.",
  "공장 설립 연도는 자료마다 다릅니다(영문 위키백과 1938년, 마르셀루 페하스의 글 1920년대). 포르투갈어 위키백과와 SESC 상파울루 글은 \"옛 드럼통 공장 (antiga fábrica de tambores)\"이라고만 적습니다.",
  "1단계 개관 날짜는 영문 위키백과의 1982년 1월 22일과 SESC 글의 1982년 5월이 엇갈립니다.",
  "CONPRESP 보호 연도는 arquivo.arq.br 에 1982년으로 적혀 있으나 결의 번호(05/09)와 맞지 않아 확인하지 못했습니다. 주(州) 기관 CONDEPHAAT 지정은 확인된 자료를 찾지 못했습니다.",
  "공사비와 탑의 층수 · 높이(물탱크 탑 70m 외)는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "SESC Pompeia — 영문 위키백과", "u": "https://en.wikipedia.org/wiki/SESC_Pompeia"},
  {"t": "Sesc Pompeia — 포르투갈어 위키백과", "u": "https://pt.wikipedia.org/wiki/Sesc_Pompeia"},
  {"t": "ArchDaily Brasil — Sesc Pompéia de Lina Bo Bardi é tombado pelo IPHAN (2015)", "u": "https://www.archdaily.com/pt/763334/sesc-pompeia-de-lina-bo-bardi-e-tombado-pelo-iphan"},
  {"t": "Agência Brasil — Iphan torna Sesc Pompeia patrimônio cultural do país (2015)", "u": "https://agenciabrasil.ebc.com.br/cultura/noticia/2015-03/iphan-tomba-complexo-cultural-projetado-por-lina-bo-bardi-na-capital"},
  {"t": "ipatrimônio — São Paulo, Sesc Pompeia (IPHAN 1726-T-2014, CONPRESP 05/09)", "u": "https://www.ipatrimonio.org/sao-paulo-sesc-pompeia/"},
  {"t": "arquivo.arq.br — SESC Pompéia (면적 · 협력자 · 구조)", "u": "https://arquivo.arq.br/projetos/sesc-pompeia"},
  {"t": "Marcelo Ferraz — The Making of SESC Pompéia (Lina Bo Bardi Together)", "u": "https://linaboba.dns-systems.net/2012/08/03/the-making-of-sesc-pompeia-by-marcelo-ferraz/"},
  {"t": "Arquitectura Viva — SESC Pompéia Factory", "u": "https://arquitecturaviva.com/works/sesc-fabrica-pompeia-9"},
  {"t": "Sesc SP — Ocupe o Sesc Pompeia", "u": "https://portal.sescsp.org.br/online/artigo/compartilhar/9780_OCUPE+O+SESC+POMPEIA"},
  {"t": "Sesc São Paulo — Relatório Anual de Gestão 2024 (PDF)", "u": "https://transparencia-sp.sesc.com.br/uploads/documento/avaliacao_arquivos/27/relatorio-de-gestao/relatorio-de-gestao-pdf-2024.pdf"},
  {"t": "Sesc 국가본부 투명성 포털 — 재원", "u": "https://transparencia-dn.sesc.com.br/transparencia/pagina/ler/7"},
 ],
},

"lx-factory": {
 "from": "방직 공장 → 인쇄소 등 산업 단지", "to": "창조 산업 단지 (사무 · 상점 · 식당 · 서점)", "y0": "1846 알칸타라 이전 · 1849 본관 준공",
 "archAbout": [
  "LX 팩토리는 한 명의 건축가가 설계한 작품이 아니라, 부동산 회사 메인사이드 (Mainside)가 2008년부터 옛 공장 단지를 크게 고치지 않고 작은 단위로 임대해 운영하며 만든 \"운영형 리노베이션\"입니다.",
  "단지 안의 개별 공간은 입주자가 따로 고쳤습니다. 대표적인 예가 옛 그라피카 미란델라 (Gráfica Mirandela) 인쇄소 자리에 들어선 서점 레르 데바가르 (Ler Devagar)로, 리스본의 오로라 아르키텍투스 (Aurora Arquitectos)가 2009년 약 1,000㎡ 를 설계했습니다.",
 ],
 "spec": [
  ["원 건축물", "리스본 방적 · 방직 회사 (Companhia de Fiação e Tecidos Lisbonense) 공장 — 1838년 회사 설립, 1846년 알칸타라 산투 아마루로 이전, 1849년 4월 4일 4층 본관 준공 (90마력 증기기관)"],
  ["원래 용도 변천", "면 방적 · 방직 공장 → 포르투갈 식민지 산업회사 (Companhia Industrial de Portugal e Colónias) → 인쇄소 아누아리우 코메르시알 (Tipografia Anuário Comercial de Portugal) → 그라피카 미란델라 (Mirandela Artes Gráficas)"],
  ["변경 용도", "창조 기업 사무실 · 디자인 상점 · 식당 · 서점 (레르 데바가르) · 행사장 — 약 200개 업체 (2017)"],
  ["부지 면적", "약 23,000㎡"],
  ["개조 · 운영", "메인사이드 (Mainside) — 2005년 부지 매입, 2008년 LX 팩토리로 개장"],
  ["소유 변경", "2017년 프랑스 키스 (Keys Asset Management) 매입 → 2022년 그루포 아리에 (Grupo Arié) · 유로피 (Europi Property Group) · 베드록 캐피털 (Bedrock Capital) 합작사 매입"],
  ["대표 내부 개조", "서점 레르 데바가르 — 오로라 아르키텍투스, 2009년, 약 1,000㎡, 2009년 4월 23일 (세계 책의 날) 개점"],
  ["위치", "포르투갈 리스본 알칸타라 — 4월 25일 다리 아래"],
 ],
 "tenants": [
  ["문화 · 서점", "레르 데바가르 (Ler Devagar)", "2009년 4월 23일 입주 · 옛 그라피카 미란델라 인쇄소 약 1,000㎡ · 3층 높이 윤전기를 남긴 서점 겸 카페", "https://aurora.com.pt/en/project/livraria-ler-devagar/"],
  ["상업 · 식음", "칸치나 (Cantina)", "옛 미란델라 공장 시설 · 가구 · 설비를 고쳐 쓴 식당 — 1846년부터 노동자들을 먹인 옛 구내식당의 기억을 잇는다고 소개", "http://web.archive.org/web/2025/https://lxfactory.com/category/restaurantes-pt/page/2/"],
  ["상업 · 식음", "란도 쇼콜라트 (Landeau Chocolate) · 타베르나 1300 (Taberna 1300) · 말라카 투 (Malaca Too) 등", "단지 안 식당 · 카페 (공식 사이트 식당 목록, 2025년 보관본)", "http://web.archive.org/web/2025/https://lxfactory.com/category/restaurantes-pt/page/2/"],
  ["상업 · 소매", "디자인 · 공예 상점 — LBP 콘셉트 스토어 (LBP Concept Store) · 오리가미 팩토리 (Origami Factory) · QIM 등", "공식 사이트 상점 목록 (2025년 보관본)", "http://web.archive.org/web/2025/https://lxfactory.com/category/lojas-pt/"],
  ["첨단산업 · 테크 기업 사무실", "리차지닷컴 (Recharge.com) · 굿해비츠 포르투갈 (GoodHabitz Portugal) · 베스포크 디지털 (Bespoke Digital)", "디지털 결제 · 온라인 교육 · 디지털 서비스 기업 사무실 (공식 사이트 사무실 목록, 2025년 보관본)", "http://web.archive.org/web/2025/https://lxfactory.com/category/escritorios-pt/"],
  ["업무 · 사무실", "건축 · 디자인 · 컨설팅 사무소 — 에스페호/단타스 (Espejo/Dantas) · 스튜디오 JV · 캡베스트 (Capvest) 등", "사무실 약 200개 업체 가운데 일부 (공식 사이트 사무실 목록)", "http://web.archive.org/web/2025/https://lxfactory.com/category/escritorios-pt/"],
  ["상업 · 숙박", "LX 호스텔 (LX Hostel)", "단지 안 호스텔 (공식 사이트 기타 목록)", "http://web.archive.org/web/2025/https://lxfactory.com/category/outros-pt/"],
  ["문화 · 행사장", "아이리스 이벤트 룸 (IRIS Event Room) 등 행사 공간 · 리스본 커피 페스트 (Lisbon Coffee Fest)", "대관 · 축제 — 2017년 키스는 행사 부문 강화를 밝힘", "http://web.archive.org/web/2025/https://lxfactory.com/category/outros-pt/"],
 ],
 "timeline": [
  ["1838", "리스본 상인들이 리스본 방적 · 방직 회사 설립 — 처음엔 시내 여러 곳에 흩어져 작업"],
  ["1846", "회사가 알칸타라 산투 아마루의 땅을 사들여 이전 결정"],
  ["1849.4.4", "4층 직사각형 본관 공장 준공 — 90마력 증기기관 (당시 전국 증기 동력의 10%)"],
  ["1851~1855", "본관 옆에 건물 5동 추가 (\"작은 공장, Fábrica Pequena\")"],
  ["1881", "노동자 850명 · 방추 15,700개 · 기계 직기 387대"],
  ["1910~1917", "공화정 수립 뒤 경영난, 1917년 위기로 해산 가속"],
  ["이후", "건물이 포르투갈 식민지 산업회사 → 인쇄소 아누아리우 코메르시알 → 그라피카 미란델라로 넘어감"],
  ["2005", "부동산 회사 메인사이드가 약 23,000㎡ 매입"],
  ["2008", "메인사이드가 옛 산업 단지를 창조 산업 단지 LX 팩토리로 개장"],
  ["2009.4.23", "서점 레르 데바가르가 옛 그라피카 미란델라 인쇄소 자리로 옮겨 개점 (윤전기 보존)"],
  ["2017", "프랑스 키스 (Keys)가 메인사이드 자회사 카툼벨 (Catumbel)로부터 매입 — 당시 약 200개 업체 입주"],
  ["2022.8", "그루포 아리에 등 합작사가 매입 — 산업적 정체성 유지와 단계적 개보수 계획 발표"],
 ],
 "concept": [
  "공장 건물과 낡은 표면 · 기계를 그대로 둔 채, 공간을 작게 나눠 창조 기업 · 상점 · 식당에 빌려주는 최소 개입 방식입니다. 큰 건축 설계 대신 임대 구성과 운영이 재생의 주된 수단이었습니다.",
  "서점 레르 데바가르에서는 옛 인쇄소의 대형 윤전기를 \"잠든 거인\"으로 남겨 두고, 그 주변을 청소 · 덜어 내기 · 구역 나누기의 단순한 원칙으로 정리했습니다. 윤전기 위에 얹은 새 구조물에 입구 · 회의실 · 사무실을 두었습니다.",
 ],
 "strategy": {
  "keep": ["19세기 공장 건물과 이후 인쇄소 건물들 · 낡은 벽 · 간판", "옛 그라피카 미란델라의 대형 윤전기 (서점 안)"],
  "change": ["공장 · 인쇄소 층 → 사무실 · 상점 · 식당 · 서점 · 행사장", "단지 안 길 → 보행 거리"],
  "add": ["입주자별 내부 개조", "레르 데바가르의 강철 · OSB 합판 새 구조물 (밖은 보라색, 안은 노란색)"],
 },
 "why": [
  "철거 · 대규모 재개발 없이, 임대와 운영만으로 버려진 산업 단지를 약 200개 업체가 입주한 창조 산업 거점으로 바꿨습니다.",
  "산업 유산의 흔적(기계 · 표면)이 그대로 장소의 개성이 되어, 소유주가 두 번 바뀐 뒤에도 새 소유주들이 \"산업적 정체성\"을 유지하겠다고 밝혔습니다.",
 ],
 "space": [
  "여러 공장 · 인쇄소 건물 사이의 골목과 마당이 보행 거리가 되고, 1층에는 상점 · 식당, 위층에는 사무실 · 작업실이 들어 있습니다.",
  "서점 레르 데바가르 (약 1,000㎡)는 높은 공장 공간 한가운데 3층 높이의 윤전기를 두고, 기능을 \"오아시스\" 같은 구역으로 나눴습니다.",
 ],
 "material": [
  "기존 벽돌 · 철 · 콘크리트 공장 구조를 그대로 드러냅니다.",
  "새로 넣은 것은 가볍고 되돌릴 수 있는 재료입니다 — 레르 데바가르의 강철 · OSB 합판 구조물.",
 ],
 "funding": [
  ["민간 투자 (매입)", "메인사이드 (Mainside)가 2005년 약 23,000㎡ 부지를 매입 (금액 미공개)"],
  ["민간 투자 (재매입)", "2017년 프랑스 키스 (Keys Asset Management)가 메인사이드로부터 매입 (2017년 6월 30일 종결) — 금액 미공개", "https://eco.sapo.pt/2017/09/13/franceses-do-grupo-keys-compram-lx-factory/"],
  ["채권 발행", "2017년 6월 30일 소유 법인 카툼벨이 1,200만 유로 사모 채권 발행", "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/novo-donos-destacam-forte-potencial-de-desenvolvimento-da-lx-factory"],
  ["민간 투자 (재매입)", "2022년 그루포 아리에 · 유로피 · 베드록 캐피털 합작사가 매입 — 금액 미공개", "https://eco.sapo.pt/2022/08/09/francesa-keys-vende-lx-factory-a-joint-venture-do-grupo-arie/"],
 ],
 "famous": [
  "19세기 리스본 최대 공장 가운데 하나(1849년 본관, 1881년 노동자 850명)였던 단지를 그대로 쓰는 창조 산업 단지입니다.",
  "2017년 기준 약 200개 업체가 입주해 있었습니다 (ECO).",
  "서점 레르 데바가르는 옛 인쇄소 윤전기를 품은 공간으로 \"세계에서 가장 아름다운 서점 겸 카페\"의 하나로 꼽혔습니다 (타임아웃 리스본).",
 ],
 "lesson": [
  "큰 공사 없이도 작게 나눈 임대와 운영만으로 산업 단지를 살릴 수 있습니다.",
  "남겨 둔 기계 · 표면이 새 입주자의 개성이 되므로, 무엇을 \"치우지 않을지\"가 설계만큼 중요합니다.",
  "소유주가 바뀌어도 이어질 수 있도록 장소의 정체성을 분명히 해 두는 것이 중요합니다.",
 ],
 "operation": [
  ["운영 주체", "민간 소유 · 운영 — 메인사이드 (2008~2017) → 키스 (Keys Asset Management, 2017~2022) → 그루포 아리에 · 유로피 · 베드록 캐피털 합작사 (2022~)"],
  ["수입 구성", "사무실 · 소매 · 식당 공간의 임대 — 2022년 새 소유주는 \"사무실 · 소매 · 식당 용도를 유지\"하겠다고 밝힘", "https://eco.sapo.pt/2022/08/09/francesa-keys-vende-lx-factory-a-joint-venture-do-grupo-arie/"],
  ["운영 성과 (입주)", "2017년 약 200개 업체 입주 — 키스는 건물을 고쳐 더 많은 업체를 받겠다고 밝힘", "https://eco.sapo.pt/2017/09/13/franceses-do-grupo-keys-compram-lx-factory/"],
  ["입주율", "2017년 매각 당시 임대 가능한 공간이 모두 임대된 상태 (totalmente arrendados) — 쓰임은 사무실 · 상점 · 작업실 · 행사 (키스는 행사 부문 강화 계획)", "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/novo-donos-destacam-forte-potencial-de-desenvolvimento-da-lx-factory"],
  ["고용", "약 200개 업체 · 1,000명 이상 근무 (조르나우 지 네고시우스, 개장 약 10년 기사)", "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/lx-factory-uma-decada-a-fundir-o-classico-com-o-cosmopolita"],
  ["자금 조달", "2017년 6월 30일 소유 법인 카툼벨 (Catumbel)이 1,200만 유로 사모 채권 발행 — 같은 날 키스로 매각 종결", "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/novo-donos-destacam-forte-potencial-de-desenvolvimento-da-lx-factory"],
  ["재투자 계획", "2022년 새 소유주: 공간의 단계적 개보수, 외부 공간 · 차량 동선 개선, \"산업적 분위기 (look & feel) 유지\""],
 ],
 "operationNote": ["LX 팩토리는 공공 보조금 없이 민간 소유주가 옛 공장 공간을 사무실 · 상점 · 식당에 빌려주는 임대 수익으로 운영됩니다. 소유주가 두 번 바뀌었지만 모두 산업적 정체성과 임대 용도를 유지하겠다고 밝혔습니다."],
 "missing": [
  "주요 입주 시설 — 공식 사이트가 2026년 현재 열리지 않아 2025년 웹 보관본 목록으로 확인했습니다. 현재 입주 여부는 확인하지 못했습니다.",
  "수익사업 · 운영 재원 — 임대료 수준, 연간 임대 수입, 최근 입주율, 방문객 수는 확인된 자료를 찾지 못했습니다.",
  "LX 팩토리 건물의 국가 · 시 보호 지정 여부는 확인된 자료를 찾지 못했습니다 (포르투갈 국가유산 목록 SIPA 에 「Edifício da Companhia de Fiação e Tecidos Lisbonense」 항목이 있으나 접속이 막혀 내용을 확인하지 못했습니다).",
  "재원 · 보조금(공공 지원)은 확인된 자료를 찾지 못했습니다. 매입 금액도 모두 공개되지 않았습니다.",
  "단지 전체의 개조 설계자 · 공사비 · 연면적은 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "LX Factory — 포르투갈어 위키백과", "u": "https://pt.wikipedia.org/wiki/LX_Factory"},
  {"t": "Restos de Colecção — Companhia de Fiação e Tecidos Lisbonense", "u": "https://restosdecoleccao.blogspot.com/2021/05/companhia-de-fiacao-e-tecidos-lisbonense.html"},
  {"t": "ECO — Franceses do Grupo Keys compram Lx Factory (2017)", "u": "https://eco.sapo.pt/2017/09/13/franceses-do-grupo-keys-compram-lx-factory/"},
  {"t": "ECO — Francesa Keys vende Lx Factory a joint-venture do Grupo Arié (2022)", "u": "https://eco.sapo.pt/2022/08/09/francesa-keys-vende-lx-factory-a-joint-venture-do-grupo-arie/"},
  {"t": "Aurora Arquitectos — Ler Devagar Bookshop at LX Factory", "u": "https://aurora.com.pt/en/project/livraria-ler-devagar/"},
  {"t": "Jornal de Negócios — Novo donos destacam forte potencial de desenvolvimento da LX Factory (2017)", "u": "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/novo-donos-destacam-forte-potencial-de-desenvolvimento-da-lx-factory"},
  {"t": "Jornal de Negócios — LX Factory, uma década a fundir o clássico com o cosmopolita", "u": "https://www.jornaldenegocios.pt/empresas/imobiliario/detalhe/lx-factory-uma-decada-a-fundir-o-classico-com-o-cosmopolita"},
  {"t": "Time Out Lisboa — A Ler Devagar é um dos cafés-livraria mais bonitos do mundo", "u": "https://www.timeout.pt/lisboa/pt/noticias/a-ler-devagar-e-um-dos-cafes-livraria-mais-bonitos-do-mundo-092425"},
  {"t": "LX Factory 공식 사이트 — 식당 · 상점 · 사무실 · 기타 목록 (웹 보관본, 2025)", "u": "http://web.archive.org/web/2025/https://lxfactory.com/category/escritorios-pt/"},
 ],
},

"ghirardelli-square": {
 "from": "모직 공장 · 초콜릿 공장 · 본사", "to": "상점 · 식당 · 광장 (이후 호텔 일부)", "y0": "1858 모직 공장 · 1893 기라델리 매입 · 1960년대 초 이전",
 "archAbout": [
  "조경가 로런스 핼프린 (Lawrence Halprin, Lawrence Halprin & Associates)과 건축 사무소 워스터 베르나르디 앤 에먼스 (Wurster, Bernardi & Emmons, 윌리엄 워스터 William Wurster)가 개조를 맡았습니다. 핼프린 사무소에서는 진 월턴 (Jean Walton) · 돈 카터 (Don Carter) · 니컬러스 퀘넬 (Nicholas Quennell)이 참여했습니다.",
  "원 건물은 스위스 출신 건축가 윌리엄 무저 (William S. Mooser)가 1861년 불탄 파이어니어 모직 공장을 다시 지었고, 그의 아들 윌리엄 무저 2세 (William S. Mooser Jr.)가 기라델리 가문의 의뢰로 단지를 고쳐 지었습니다.",
  "1962년 윌리엄 M. 로스 (William M. Roth)와 어머니 러라인 맷슨 로스 (Lurline Matson Roth)가 철거를 막으려고 단지를 사들여 개조를 발주했습니다.",
 ],
 "spec": [
  ["원 건축물", "파이어니어 모직 공장 (Pioneer Woolen Mills, 1858 · 1861 화재 뒤 재건) + 기라델리 초콜릿 회사 (D. Ghirardelli Company) 공장 · 본사 건물들 (1890년대 말~) · 시계탑 (1915~1916)"],
  ["원 설계", "윌리엄 S. 무저 (William S. Mooser, 모직 공장 재건) · 윌리엄 S. 무저 2세 (William S. Mooser Jr., 기라델리 단지)"],
  ["원래 용도", "모직 공장 (1889 폐쇄) → 초콜릿 공장 · 본사 (1960년대 초 골든 그레인 마카로니에 인수된 뒤 이전)"],
  ["변경 용도", "상점 · 식당 · 야외 광장 (+ 2008년 페어몬트 헤리티지 플레이스 53실)"],
  ["건축주", "윌리엄 M. 로스 · 러라인 맷슨 로스 (1962 매입)"],
  ["개조 설계", "워스터 베르나르디 앤 에먼스 (Wurster, Bernardi & Emmons) · 로런스 핼프린 앤 어소시에이츠 (Lawrence Halprin & Associates)"],
  ["개장", "1964년 (11월)"],
  ["이후 개조", "1965 벤저민 톰프슨 앤 어소시에이츠 (Benjamin Thompson and Associates) 시계탑 1층 개조 · 1968 루스 아사와 (Ruth Asawa) 인어 분수 · 1982 새 포장 · 계단"],
  ["규모", "한 블록 — 노스 포인트 · 라킨 · 비치 · 폴크 거리로 둘러싸임"],
  ["위치", "미국 샌프란시스코 피셔맨스 워프 서쪽"],
 ],
 "tenants": [
  ["상업 · 식음 (앵커)", "기라델리 초콜릿 (Ghirardelli Chocolate)", "시계탑 건물 아래층의 기라델리 스퀘어 대표 초콜릿 가게 — 옛 공장 주인의 브랜드가 매장으로 남아 앵커 역할 (영문 위키백과 · 공식 사이트 목록)", "https://en.wikipedia.org/wiki/Ghirardelli_Square"],
  ["상업 · 숙박", "페어몬트 헤리티지 플레이스 (Fairmont Heritage Place, Ghirardelli Square)", "2008년 · 옛 시계탑 건물 일부 · 4개 층 53실, 객실 지분 분할 소유", "https://www.historichotels.org/us/hotels-resorts/fairmont-heritage-place-ghirardelli-square/history.php"],
  ["상업 · 식음", "매코믹 앤 쿨레토스 시푸드 앤 스테이크 (McCormick & Kuleto's) · 샌프란시스코 브루 컴퍼니 (San Francisco Brew Co.) · 스퀘어 파이 가이스 (Square Pie Guys) · 바리오 (Barrio) 등", "공식 사이트 식음 목록 (2026년 확인)", "https://www.ghirardellisq.com/explore"],
  ["상업 · 식음", "브로드 스트리트 오이스터 (Broad Street Oyster Co.)", "공식 사이트에 \"곧 개점 (Coming Soon)\"으로 표시", "https://www.ghirardellisq.com/explore"],
  ["상업 · 소매", "보M 파스 (vom Fass) · 로라 샌프란시스코 (LOLA San Francisco) · 포토마티카 (Photomatica) · COL 갤러리 등", "공식 사이트 상점 목록", "https://www.ghirardellisq.com/explore"],
  ["문화 · 놀이", "서브파 미니어처 골프 (Subpar Miniature Golf)", "실내 미니 골프장 (공식 사이트 목록)", "https://www.ghirardellisq.com/explore"],
  ["상업 · 소매 (과거)", "디자인 리서치 (Design Research)", "1965년 · 벤저민 톰프슨이 시계탑 1층을 고쳐 연 디자인 상점 — 지금은 그 자리에 기라델리 초콜릿 가게", "https://en.wikipedia.org/wiki/Ghirardelli_Square"],
 ],
 "timeline": [
  ["1858", "파이어니어 모직 공장 (Pioneer Woolen Mills) 가동"],
  ["1861", "화재로 소실 → 윌리엄 S. 무저가 4층, 길이 약 150피트의 새 공장으로 재건"],
  ["1889", "모직 공장 폐쇄 (1880년대 초 직기 약 130대)"],
  ["1893", "도메니코 기라델리 (Domenico Ghirardelli)가 블록 전체를 사들여 초콜릿 회사 본사로"],
  ["1915~1916", "프랑스 고딕풍 시계탑 건립 (자료마다 1915 · 1916)"],
  ["1960년대 초", "골든 그레인 마카로니 (Golden Grain Macaroni)가 기라델리 회사 인수 — 공장 이전"],
  ["1962", "윌리엄 M. 로스와 러라인 맷슨 로스가 철거를 막기 위해 부지 매입"],
  ["1964.11", "기라델리 스퀘어 개장 — 미국 최초의 성공한 적응적 재사용 사업으로 평가"],
  ["1965", "벤저민 톰프슨 앤 어소시에이츠가 시계탑 1층 개조"],
  ["1968", "루스 아사와의 청동 인어 분수 설치"],
  ["1970.5.3", "샌프란시스코시 지정 랜드마크 제30호"],
  ["1982.4.29", "미국 국가사적지 (NRHP) 등재 「Pioneer Woolen Mills and D. Ghirardelli Company」 · 새 포장 · 계단 공사"],
  ["2008", "페어몬트 헤리티지 플레이스 (Fairmont Heritage Place) 개장 — 4개 층 53실"],
  ["2013", "제임스타운 (Jamestown L.P.)이 매입 — 이후 시계탑 · 지붕 간판 복원"],
  ["2026.4", "제임스타운이 엠브레이스 리얼 에스테이트 (Embrace Real Estate) · 1823 파트너스 (1823 Partners)에 매각 — 컨티뉴엄 파트너스 (Continuum Partners)가 임대 · 운영 담당"],
 ],
 "heritage": [
  ["샌프란시스코시 지정 랜드마크 제30호 (San Francisco Designated Landmark No. 30, 1970)", "1970년 5월 3일 지정 — 노스 포인트 · 라킨 · 비치 · 폴크 거리로 둘러싸인 블록"],
  ["미국 국가사적지 (National Register of Historic Places, 1982)", "1982년 4월 29일 「Pioneer Woolen Mills and D. Ghirardelli Company」로 등재 (참조번호 82002249)"],
 ],
 "concept": [
  "경사진 한 블록 위의 붉은 벽돌 공장들을 남기고, 그 사이에 계단 · 경사로 · 테라스로 이어지는 광장을 만들어 바다 쪽 전망을 열었습니다. 공장 건물은 상점 · 식당이 되었습니다.",
  "핼프린은 계단과 경사로로 \"언덕 위의 움직임을 연출\"하고, 나무 그늘의 테라스와 현장에 맞춘 조명 · 가구 · 분수를 설계했습니다. 지하 주차장도 핼프린이 설계해, 광장을 사람에게 돌려주었습니다.",
 ],
 "strategy": {
  "keep": ["붉은 벽돌 공장 건물들 · 시계탑 · 지붕 위 \"GHIRARDELLI\" 간판"],
  "change": ["초콜릿 · 모직 공장 → 상점 · 식당", "공장 마당 → 계단식 광장 · 테라스"],
  "add": ["지하 주차장", "워스터 건물 (신축)", "분수 (1968 루스 아사와 인어 분수) · 조명 · 가구 · 수목"],
 },
 "why": [
  "1964년 개장해 \"미국 최초의 성공한 적응적 재사용 사업\"으로 평가됩니다. 1966년 미국 국가역사보존법 (National Historic Preservation Act)보다 먼저였습니다 (TCLF).",
  "건물보다 \"건물 사이\" — 광장 · 계단 · 테라스 — 를 설계해, 공장 단지를 사람들이 머무는 도시 공간으로 바꿨습니다.",
  "민간 건축주가 철거를 막으려고 직접 사들여 보존과 개발을 함께 이룬 사례입니다.",
 ],
 "space": [
  "한 블록의 가장자리를 벽돌 공장들이 두르고, 가운데 경사를 따라 여러 높이의 광장 · 테라스가 층층이 놓여 계단과 경사로로 이어집니다.",
  "자동차는 지하 주차장으로 넣고, 지상은 보행 광장과 \"야외 방\"들로 비웠습니다.",
 ],
 "material": [
  "옛 것: 붉은 벽돌 공장 건물들과 프랑스 고딕풍 시계탑을 보존했습니다.",
  "새 것: 광장 포장 · 계단 · 나무 · 분수 · 조명 등 조경 요소와 신축 워스터 건물.",
 ],
 "funding": [
  ["민간 투자", "1962년 윌리엄 M. 로스와 러라인 맷슨 로스가 개인적으로 부지를 매입하고 개조를 발주했습니다 (금액은 확인 못 함)."],
 ],
 "famous": [
  "1964년 개장 — 미국 최초의 성공한 적응적 재사용 사업으로 평가됩니다.",
  "조경가 로런스 핼프린의 대표작으로, 미국 문화경관재단 (TCLF)이 기록한 경관입니다.",
  "1970년 샌프란시스코시 랜드마크 제30호, 1982년 국가사적지로 지정되었습니다.",
  "건물 12동에 연간 약 900만 명이 찾는 피셔맨스 워프의 대표 명소입니다 (2026년 매각 발표).",
 ],
 "lesson": [
  "공장 건물을 바꾸는 것만큼, 건물 사이의 외부 공간(광장 · 계단)을 설계하는 일이 장소의 성패를 좌우합니다.",
  "보존 제도가 갖춰지기 전에도 민간의 결단으로 보존형 개발이 가능하며, 그 성공이 이후 제도 지정(1970 · 1982)으로 이어졌습니다.",
 ],
 "operation": [
  ["운영 주체", "민간 소유 — 로스 가문 (1962~) → 캐피털 앤 카운티스 USA · 노스웨스턴 뮤추얼 생명 (1981~) → 제임스타운 (Jamestown L.P., 2013~2026) → 엠브레이스 리얼 에스테이트 · 1823 파트너스 (2026.4~), 임대 · 일상 운영은 컨티뉴엄 파트너스", "https://pulse2.com/embrace-real-estate-and-1823-partners-acquire-ghirardelli-square-in-san-francisco-with-continuum-partners/"],
  ["매각 · 규모", "2013년 제임스타운이 약 100,394제곱피트 규모의 소매 · 오락 단지를 매입 — 가격은 약 5,400만 달러 (더 레지스트리, 거래 관계자 전언) 또는 5,600만 달러 (SF 스탠더드 2026)로 자료마다 다름. 2026년 매각가는 공개 원문에서 확인 못 함", "https://news.theregistrysf.com/jamestown-properties-buys-ghirardelli-square-in-san-francisco/"],
  ["방문객", "연간 약 900만 명 · 건물 12동 (2026년 매각 발표)", "https://pulse2.com/embrace-real-estate-and-1823-partners-acquire-ghirardelli-square-in-san-francisco-with-continuum-partners/"],
  ["수입 구성", "상점 · 식당 임대 + 2008년 옛 시계탑 건물 일부의 호텔 페어몬트 헤리티지 플레이스 (53실, 객실 지분 분할 소유 판매)"],
 ],
 "operationNote": ["기라델리 스퀘어는 처음부터 공공 보조금 없이 민간이 사들여 상점 · 식당 임대로 운영한 사업이며, 여러 차례 매각되었습니다. 2008년에는 건물 일부를 객실 지분을 나눠 파는 호텔로 바꿔 수입원을 넓혔습니다."],
 "missing": [
  "수익사업 · 운영 재원 — 임대 수입과 입주율은 확인된 자료를 찾지 못했습니다 (\"현재 소매 공간이 모두 찼다\"는 내용은 검색 요약에만 있어 넣지 않았습니다).",
  "로스 가문의 매입가와 개조 공사비, 공공 재원 · 보조금 · 세제 혜택은 확인된 자료를 찾지 못했습니다.",
  "상점 수 · 연면적은 확인된 자료를 찾지 못했습니다 (기존의 \"40여 개 상점\"은 출처를 찾지 못해 뺐습니다).",
  "시계탑 건립 연도는 자료마다 1915년 · 1916년으로 다릅니다.",
 ],
 "refs": [
  {"t": "Ghirardelli Square — 영문 위키백과", "u": "https://en.wikipedia.org/wiki/Ghirardelli_Square"},
  {"t": "The Cultural Landscape Foundation — Ghirardelli Square", "u": "https://www.tclf.org/landscapes/ghirardelli-square"},
  {"t": "Historic Hotels of America — Fairmont Heritage Place, Ghirardelli Square: History", "u": "https://www.historichotels.org/us/hotels-resorts/fairmont-heritage-place-ghirardelli-square/history.php"},
  {"t": "List of San Francisco Designated Landmarks — 영문 위키백과", "u": "https://en.wikipedia.org/wiki/List_of_San_Francisco_Designated_Landmarks"},
  {"t": "u-s-history.com — Ghirardelli Square", "u": "https://www.u-s-history.com/pages/h2852.html"},
  {"t": "The Registry — Jamestown Properties Buys Ghirardelli Square in San Francisco (2013)", "u": "https://news.theregistrysf.com/jamestown-properties-buys-ghirardelli-square-in-san-francisco/"},
  {"t": "The San Francisco Standard — Ghirardelli Square sold to new company with ties to Miami investment firm (2026.4)", "u": "https://sfstandard.com/2026/04/24/ghiradelli-square-miami-investment-firm/"},
  {"t": "Pulse 2.0 — Embrace Real Estate And 1823 Partners Acquire Ghirardelli Square (2026.4)", "u": "https://pulse2.com/embrace-real-estate-and-1823-partners-acquire-ghirardelli-square-in-san-francisco-with-continuum-partners/"},
  {"t": "Ghirardelli Square 공식 사이트 — Explore (입주 업체)", "u": "https://www.ghirardellisq.com/explore"},
 ],
},

"seoullo-7017": {
 "from": "자동차 고가도로 (서울역 고가)", "to": "보행 고가 공원", "y0": "1970 개통 · 2015.12.13 차량 통행 중단",
 "archAbout": [
  "네덜란드 로테르담의 MVRDV (위니 마스 Winy Maas · 야코프 판 레이스 Jacob van Rijs · 나탈리 더프리스 Nathalie de Vries)가 2015년 5월 국제 설계공모에서 당선되었습니다. 조경가 벤 카위퍼르스 (Ben Kuipers)가 함께했습니다.",
  "한국 쪽 협력은 건축 디엠피 (DMP), 조경 KECC, 구조 삼안 (Saman Engineering) 등입니다. MVRDV 는 한국 식물 50과 · 약 228종을 한글 가나다순으로 배열한 \"살아 있는 식물 사전\"을 제안했습니다.",
 ],
 "spec": [
  ["원 건축물", "서울역 고가도로 — 1970년 8월 15일 개통 (서울시), 퇴계로 ~ 만리동 방향 · 차도 길이 938m"],
  ["원래 용도", "자동차 고가도로 (2015년 12월 13일까지 16,556일 운영)"],
  ["변경 용도", "보행 고가 공원 — 원형 화분 정원 · 카페 · 전시 · 공연 · 어린이 시설 · 족욕탕 등"],
  ["건축주 · 운영", "서울특별시"],
  ["개조 설계", "MVRDV (위니 마스) · 조경 벤 카위퍼르스 (Ben Kuipers)"],
  ["현지 협력", "디엠피 (DMP, 건축) · KECC (조경) · 삼안 (Saman Engineering, 구조)"],
  ["공모", "2015년 5월 국제 설계공모 당선"],
  ["공사 · 개장", "2015.12.13 고가 폐쇄 후 착공 → 2017년 5월 20일 개장 (공사 525일)"],
  ["규모", "총길이 1,024m (고가 810m + 지상 214m, 서울시) · 폭 10.3m · 최고 높이 17m — MVRDV 는 983m · 16m 로 표기"],
  ["식재", "50과 228종 · 24,085주 · 원형 화분 645개 (66가지 모양)"],
  ["연결", "주변을 잇는 보행로 17개 (승강기 · 에스컬레이터 · 보행 다리 · 횡단보도)"],
  ["안전", "내진 1등급 (규모 6.3~6.5 견딤) · 5만 명 하중 설계 · 난간 높이 1.4m"],
  ["총사업비", "597억 원 (그중 40% 이상 안전 보강)"],
 ],
 "tenants": [
  ["문화 · 공연장", "담쟁이극장", "만리동광장 근처 인형극장 — 자원봉사 인형극단 정례 공연 · 구연동화 (2017 개장 당시)", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["문화 · 전시장", "서울로전시관", "서울역 철로 위 약 16㎡ 소규모 전시관 — 네이버문화재단 주도로 분기별 전시 (2017 개장 당시)", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["문화 · 교육", "정원교실", "작은 도서관처럼 꾸민 공간 · 가족 정원 만들기 프로그램", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["문화 · 공연장", "장미무대 · 목련무대", "거리 무대 — 목련무대는 퇴계로 쪽, 대우재단빌딩 · 호텔 마누 연결 통로 옆", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["문화 · 놀이", "방방놀이터 · 공중자연쉼터", "트램펄린 2대의 어린이 놀이터 · 계절별 족욕탕 · 낙엽 밟기 등", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["상업 · 관광 편의", "서울로여행자카페 · 서울로가게", "퇴계로 교통섬의 종합 관광 안내소 · 공식 기념품 20여 종 판매점 (퇴계로 초입)", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["상업 · 식음", "식당 · 카페", "고가 위와 만리동 쪽 — 비빔밥 · 꼬마김밥 · 토스트 · 디저트 (2017 개장 당시)", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["문화 · 공공미술", "윤슬 (만리동광장)", "노천극장 형태의 공공미술 작품 — 댄스 공연 · 미디어 아트", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
 ],
 "timeline": [
  ["1970.8.15", "서울역 고가도로 개통 (서울시 \"숫자로 보는 서울로7017\")"],
  ["2000년대", "서울시 안전진단에서 바닥판이 시급한 보수가 필요한 D등급 판정"],
  ["2015.5", "MVRDV 안이 국제 설계공모 당선"],
  ["2015.12.13", "고가도로 차량 통행 중단 · 공사 시작 (45년, 16,556일 운영 마감)"],
  ["2015.12~2017.4", "공사 525일 — 연인원 28,362명, 철근 419t, 콘크리트 3,476㎥"],
  ["2017.5.20", "서울로7017 개장 — 국내 첫 고가 보행길"],
  ["2017.5~7", "개장 직후 투신 시도 · 안전유리 파손 · 바닥 균열 약 80곳 등 문제 제기"],
  ["2023.8", "서울역 국가상징공간 추진에 따른 철거설 보도에 서울시가 해명자료로 \"서울로7017 관련 별도 계획 없음\"이라고 밝힘"],
  ["2023.10", "국회 국정감사에서 오세훈 시장 \"계량화하면 좋은 평가가 아닌 것은 분명\", 존폐는 객관적 평가 뒤 결정하겠다고 답변 · 철거 관련 용역 진행 중"],
  ["2025.8", "방문객 감소 · 유지비 부담으로 서울역 일대 계획에서 철거안을 검토 중이라는 보도 (한국일보 · 문화일보)"],
 ],
 "concept": [
  "낡은 고가를 허무는 대신 보강해 보행 공원으로 바꾸고, 한국 식물을 가나다순으로 심은 원형 화분 645개를 늘어놓아 \"서울의 식물 사전\"을 만들었습니다. 이름의 「70」은 1970년, 「17」은 2017년 · 17개의 보행로 · 고가 높이 17m 를 함께 뜻합니다.",
  "고가 위에 섬처럼 놓인 화분과 작은 건물(카페 · 상점 · 전시 · 정원 교실 · 트램펄린 · 족욕탕 · 무대 · 어린이 극장 · 안내소)이 걷는 길을 머무는 길로 바꾸도록 했습니다. 밤에는 나무들을 \"파란 하늘의 별\"처럼 비추는 조명을 계획했습니다.",
  "고가가 이어 주지 못하던 서울역 동서 지역(만리동 · 중림동 · 남대문시장 · 회현 등)을 17개 보행로로 연결해, 끝에서 끝까지 걷는 시간을 최대 14분 줄이는 것이 목표였습니다.",
 ],
 "strategy": {
  "keep": ["1970년 고가 구조 (철골 · 콘크리트, 교각 · 교대 36개)를 보강해 재사용"],
  "change": ["차도 → 폭 10.3m 보행로 · 정원", "통과 교통 시설 → 주변 6개 지역을 잇는 보행망의 축"],
  "add": ["원형 화분 645개 · 식물 24,085주", "문화시설 8개소 · 작은 건물들 · 화장실 8곳", "승강기 · 에스컬레이터 · 보행 다리 등 연결로 17개", "조명 555개 (111개 기둥) · 안개 분수 노즐 360개 · 높이 1.4m 안전 난간", "만리동광장 (10,480㎡)"],
 },
 "why": [
  "안전 문제로 철거 대상이던 기반시설을 보강해 보행 공원으로 바꾼, 국내 첫 고가 보행길입니다.",
  "공원 하나가 아니라, 서울역으로 끊겼던 주변 지역을 17개 보행로로 잇는 도시 보행망으로 계획되었습니다.",
  "한편 구조가 무거운 흙과 큰 나무를 감당하지 못해 화분 정원에 머물렀고, 그늘 부족 · 유지비 · 방문객 감소 등의 비판도 꾸준히 제기되었습니다.",
 ],
 "space": [
  "본선은 서울역 위를 가로지르는 고가 810m 와 지상 214m 로 이뤄지고, 그 위에 원형 화분과 작은 건물이 불규칙하게 흩어져 걷는 동선을 굽이치게 만듭니다.",
  "양 끝과 중간에서 승강기 · 에스컬레이터 · 보행 다리 · 횡단보도 등 17개 연결로가 주변 건물과 거리로 이어집니다. 만리동 쪽 끝에는 길이 200m, 폭 40~50m 의 만리동광장이 있습니다.",
 ],
 "material": [
  "옛 철골 · 콘크리트 고가를 보강했습니다 — 사업비 597억 원의 40% 이상을 안전 보강에 썼고, 내진 1등급과 5만 명 하중을 확보했습니다.",
  "새 것: 원형 콘크리트 화분 (66가지 모양) · 높이 1.4m 안전 난간 · 조명 기둥 111개 (조명 555개) · 안개 분수 노즐 360개.",
 ],
 "funding": [
  ["총사업비 (공공 재원)", "597억 원 — 서울특별시, 그중 40% 이상을 안전 보강에 투입", "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"],
  ["운영비 (서울시 예산)", "유지 · 운영 예산 2017년 14억 3천만 원 → 2018년 43억 3천만 원 → 2019년 47억 7천만 원 → 2020 · 2021년 각 약 37억 원 → 2022년 직영 전환 뒤 20억 원대 초반 → 최근 연 16억 원 안팎. 2017~2025년 누적 250억 원 이상 (조선비즈 2026)", "https://news.nate.com/view/20260619n15045"],
 ],
 "famous": [
  "국내 첫 고가 보행길로, 철거 대신 재활용을 택한 서울의 대표적 기반시설 재생 사례입니다.",
  "네덜란드 MVRDV 의 국제 공모 당선작으로, 한국 식물 228종 · 24,085주를 가나다순으로 배열한 \"식물 사전\" 개념이 널리 소개되었습니다.",
  "개장 뒤에도 해마다 600만~750만 명이 찾는 보행로입니다 (2022년 754만 명, 2025년 603만 명 — 네이트 뉴스 2026).",
  "뉴욕 하이라인 (High Line)을 본뜬 사업으로 알려졌지만, 그늘 · 유지비 · 존폐 문제로 꾸준한 논쟁의 대상이기도 합니다.",
 ],
 "lesson": [
  "낡은 구조를 재사용할 때는 보강 비용(이 사례는 40% 이상)과 구조가 견딜 수 있는 하중이 공원의 모습(화분 정원)을 결정합니다.",
  "고가 하나보다 주변을 잇는 연결로 · 주변 재생이 함께 가야 이용이 지속됩니다.",
  "개장 뒤 유지비와 이용 변화까지 계획에 넣어야 \"철거 논쟁\"을 피할 수 있습니다.",
 ],
 "operation": [
  ["운영 주체", "서울특별시 — 박원순 시장 때는 민간위탁으로 프로그램 · 운영관리, 이후 유지관리 중심으로 전환"],
  ["입장료", "무료 공공 보행로"],
  ["운영 예산", "2017년 14억 3천만 원 → 2019년 47억 7천만 원 (최고) → 2020 · 2021년 약 37억 원 → 2022년 직영 전환 뒤 20억 원대 초반 → 최근 연 약 16억 원 (조선비즈 2026 · 문화일보 2025)", "https://news.nate.com/view/20260619n15045"],
  ["운영 방식 변화", "2017년 개장 때 서울시가 직접 관리 → 2019년 하반기 민간위탁 → 2022년 시 직영 전환"],
  ["누적 비용", "개장 뒤 누적 유지 · 운영비 250억 원 이상, 최초 사업비를 더하면 약 850억 원"],
  ["방문객", "2022년 754만 명 → 2023년 651만 명 → 2024년 641만 명 → 2025년 603만 명 (2025년 6월 말까지 317만 명 — 문화일보)"],
  ["운영상 문제", "방문객 감소 · 유지비 부담 · 치안 문제로 서울역 일대 계획에서 철거안이 검토되었다는 보도 (한국일보 2025)"],
 ],
 "operationNote": ["서울로 7017은 입장료 · 임대 수익이 없는 무료 공공 시설로, 서울시 예산만으로 운영됩니다. 초기에는 민간위탁으로 행사 · 콘텐츠를 운영했으나, 이후 유지관리 중심으로 바꾸며 연간 집행 예산을 약 37억 원에서 15억 원 수준으로 줄였습니다 (2019년 47억 7천만 원 → 최근 약 16억 원). 방문객이 해마다 줄면서 비용 대비 효과가 논란이 되고 있습니다."],
 "missing": [
  "주요 입주 시설 — 2017년 개장 당시 서울시 발표 기준이며, 2022년 직영 전환 뒤 현재 운영 여부는 확인된 자료를 찾지 못했습니다.",
  "한국일보 칼럼(2025)의 \"연간 유지비 45억 원\"은 2018~2019년 예산(43억~48억 원) 수준이며 최근 연도(약 16억 원)와 다릅니다. 서울시 예산서 원문은 직접 열어 확인하지 못했습니다.",
  "D등급 판정 연도는 자료마다(2000년 · 2006년) 다릅니다.",
  "고가도로 준공 시점은 한국어 위키백과 1970년 3월, 서울시 「숫자로 보는 서울로7017」 1970년 8월 15일(운영 시작일)로 다릅니다.",
  "총길이는 서울시 1,024m, MVRDV 983m 로, 높이는 서울시 17m, MVRDV 16m 로 표기가 다릅니다 (기존의 \"높이 17m · 약 1km\"는 이를 함께 적었습니다).",
  "수상 경력은 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "서울시 내 손안에 서울 — 숫자로 보는 '서울로7017'", "u": "https://mediahub.seoul.go.kr/archives/1078264"},
  {"t": "서울시 내 손안에 서울 — [서울역 7017] '고'부가 '가'치가 있는 '고가'로 변신", "u": "https://mediahub.seoul.go.kr/archives/863544"},
  {"t": "서울정책아카이브 — 국내 첫 고가보행길 '서울로7017' 5월20일 개장", "u": "https://seoulsolution.kr/ko/content/%EA%B5%AD%EB%82%B4-%EC%B2%AB-%EA%B3%A0%EA%B0%80%EB%B3%B4%ED%96%89%EA%B8%B8-%E2%80%98%EC%84%9C%EC%9A%B8%EB%A1%9C7017%E2%80%99-5%EC%9B%9420%EC%9D%BC-%EA%B0%9C%EC%9E%A5"},
  {"t": "서울시 정보소통광장 — 서울로 7017 미리보기", "u": "https://opengov.seoul.go.kr/seoullove/11932536"},
  {"t": "서울로 7017 — 한국어 위키백과", "u": "https://ko.wikipedia.org/wiki/%EC%84%9C%EC%9A%B8%EB%A1%9C_7017"},
  {"t": "Landezine International Landscape Award — Seoullo 7017 Skygarden (MVRDV)", "u": "https://landezine-award.com/seoullo-7017-skygarden/"},
  {"t": "조선비즈 (네이트) — 바퀴벌레 논란 서울로7017, 유지·운영비만 250억 넘었다 (2026)", "u": "https://news.nate.com/view/20260619n15045"},
  {"t": "문화일보 — 年16억 쏟는데 발길 뜸해… 서울로7017 존폐기로 (2025)", "u": "https://www.munhwa.com/article/11524088"},
  {"t": "한국일보 — 서울로 7017 하반기부터 민간이 운영한다 (2019)", "u": "https://www.hankookilbo.com/news/article/201903101540362537"},
  {"t": "이데일리 — 오세훈 시장 \"서울로7017 철거, 객관적 평가로 결정할 것\" (2023 국감)", "u": "https://m.edaily.co.kr/News/Read?newsId=03473526635775872&mediaCodeNo=257"},
  {"t": "환경과조경 (라펜트) — 서울로7017 철거 가능성…서울시, 해명자료 통해 부인 (2023)", "u": "https://www.latimes.kr/news/articleView.html?idxno=50799"},
  {"t": "한국일보 — 존폐 기로 '서울로 7017' (2025)", "u": "https://www.hankookilbo.com/news/article/A2025080711080005689"},
  {"t": "네이트 뉴스 — 박원순 때 600억 들인 서울로7017…15억 유지비 돈값할까? (2026)", "u": "https://news.nate.com/view/20260625n03699"},
 ],
},

"culture-station-seoul-284": {
 "from": "철도역 (경성역 → 서울역)", "to": "복합문화공간 (전시 · 공연 · 행사)", "y0": "1925 준공 · 2003~2004 역 기능 이전",
 "archAbout": [
  "원 건축물 경성역은 도쿄제국대학 건축학과 교수 쓰카모토 야스시 (塚本靖)가 설계에 참여한 것으로 알려져 있고, 조선호텔을 지은 시미즈구미 (清水組)가 시공했습니다. 국가유산청 설명은 \"일본인이 설계\"했다고만 적고 있습니다.",
  "외관이 스위스 루체른역 (1896)과 닮았다는 연구가 있습니다 (서울역사박물관 도면 공개 때 안창모 경기대 교수의 설명).",
  "복원 · 재활용은 문화체육관광부가 발주했고, 2011년부터 한국공예디자인문화진흥원이 운영합니다. 복원 자문에는 안창모 교수 등이 참여했습니다.",
 ],
 "spec": [
  ["원 건축물", "경성역 (京城驛) — 1922년 착공, 1925년 9월 30일 준공, 10월 15일 영업 개시"],
  ["원 설계 · 시공", "쓰카모토 야스시 (塚本靖) 설계 참여로 알려짐 · 시미즈구미 (清水組) 시공"],
  ["원 구조 · 양식", "지하 1층 · 지상 2층 석재 혼합 벽돌조 — 1층은 르네상스 궁전 건축 기법, 1층 윗부분과 2층은 붉은 벽돌 + 화강석 장식 (국가유산청)"],
  ["원 공사비", "당초 예산 약 420만 원 → 1923년 간토 대지진으로 줄어 약 195만 원 (서울시)"],
  ["원래 용도", "철도역 — 1947년 서울역으로 개칭, 2003~2004년 민자역사로 역무 이전"],
  ["변경 용도", "복합문화공간 「문화역서울 284」 — 전시 · 공연 · 영화 · 세미나"],
  ["건축주 · 운영", "문화체육관광부 (복원) · 한국공예디자인문화진흥원 (운영)"],
  ["복원 공사", "2009년 7월 ~ 2011년 (약 2년) — 1925년 준공 당시 자료를 근거로 원형 복원"],
  ["복원 사업비", "약 200억 원"],
  ["개관", "2011년 8월 9일"],
  ["지정 면적", "2,964㎡ (사적)"],
  ["보호", "사적 「구 서울역사」 (1981년 9월 25일 지정, 옛 사적 제284호)"],
  ["위치", "서울특별시 중구 통일로 1 (봉래동2가)"],
 ],
 "tenants": [
  ["문화 · 전시장", "중앙홀", "1층 · 524㎡ · 화강암 기둥 12개와 돔, 스테인드글라스 — 전시 · 공연 · 카페 다목적", "http://www.seoul284.org/space/menu/256"],
  ["문화 · 전시장", "1 · 2등 대합실 · 부인대합실 · 3등 대합실", "1층 · 각 172㎡ · 63㎡ · 366㎡ — 전시실로 사용", "http://www.seoul284.org/space/menu/256"],
  ["문화 · 전시장", "귀빈실 · 귀빈예비실 · 역장실", "1층 · 93㎡ · 62㎡ · 45㎡ — 조선총독 · 역대 대통령 대기실이던 방을 전시에 사용", "http://www.seoul284.org/space/menu/256"],
  ["문화 · 공연장", "RTO 공연장", "건물 오른편 · 323㎡ · 옛 미군 수송사무소 (Railroad Transportation Office) — 음악 · 공연 · 강연", "http://www.seoul284.org/space/menu/256"],
  ["문화 · 공연장", "그릴", "2층 · 254㎡ · 1925년 문을 연 한국 첫 양식당 자리 — 공연 · 전시 · 세미나", "http://www.seoul284.org/space/menu/256"],
  ["문화 · 전시장", "복원전시실", "옛 이발소 · 화장실 자리 · 2011년 복원 과정과 도면 · 자재 상설 전시", "http://www.seoul284.org/space/menu/256"],
  ["업무 · 운영 기관", "한국공예디자인문화진흥원 (KCDF)", "2011년부터 문화역서울 284 운영 — 전시 · 공연 기획, 대관 · 협력전시 공모", "http://www.seoul284.org/cms/content/view/287"],
 ],
 "timeline": [
  ["1900.7", "남대문정거장 영업 개시"],
  ["1905.3.24", "남대문역으로 개칭"],
  ["1915.10.15", "목조 정차장을 헐고 새 남대문역사 준공"],
  ["1922", "새 역사 착공"],
  ["1923.1.1", "경성역으로 개칭 · 같은 해 간토 대지진으로 공사비 축소"],
  ["1925.9.30", "경성역 준공 (10.15 영업 개시, 10.25 2층 양식당 개업)"],
  ["1947.11.1", "서울역으로 개칭"],
  ["1981.9.25", "사적 제284호 「구 서울역사」로 지정"],
  ["1988~1997", "민자역사 · 문화관 · 철도박물관 개관"],
  ["2003~2004", "통합 민자역사로 역무 이전 (2004년 KTX 개통과 함께 옛 역사 폐쇄)"],
  ["2004 · 2007.8.30", "2004년 철도공사에서 문화재청으로 소유권 이전 → 2007년 8월 30일 문화체육관광부로 관리 위임 (한국어 위키백과)"],
  ["2009.7", "문화체육관광부, 원형 복원 공사 착수"],
  ["2011.4~7", "4월 15일 한국공예디자인문화진흥원 위탁 운영 시작 · 4~5월 명칭 공모 · 7월 14일 복원 공사 준공 (한국어 위키백과)"],
  ["2011.8.9", "「문화역서울 284」 개관 — 첫 6개월간 약 60개 문화 행사 계획"],
  ["2016.7.7", "서울역사박물관, 기증받은 경성역 준공 도면 공개"],
  ["2025.9.30~11.30", "옛 역사 지하 통로를 일시 개방 (한국어 위키백과)"],
 ],
 "heritage": [
  ["사적 (구 서울역사 · 舊 서울驛舍, 1981)", "1981년 9월 25일 지정 (옛 사적 제284호). 지정 면적 2,964㎡, 소유 · 관리 국가유산청. 가장 오래된 철도 건물이라는 건축사적 가치와 일제의 대륙 침탈 수송 거점이라는 역사의 증언 (사이토 마코토 글씨의 정초석)", "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1331102840000"],
 ],
 "concept": [
  "원형 복원이 원칙입니다. 1925년 준공 당시 사진 · 자료를 근거로 내부 공간을 역사적 중요도에 따라 상 · 중 · 하 3등급으로 나누어 방마다 복원 수준을 달리했고, 문화재 자문회의를 거쳤습니다.",
  "복원한 공간을 그대로 문화 공간으로 씁니다 — 1층 중앙홀은 공연 · 전시 · 카페 등 다목적 공간, 2층 옛 양식당 「그릴」은 공연 · 전시 · 세미나 공간이 되었습니다.",
  "이름 「문화역서울 284」는 옛 사적 번호 284에 \"서울\"이라는 지명의 역사적 · 도시적 상징성을 결합한 것입니다.",
 ],
 "strategy": {
  "keep": ["1925년 외관 — 붉은 벽돌 · 화강석 · 중앙 돔", "중앙홀 — 바닥에서 16m 높이의 가로세로 8m 스테인드글라스 천창", "대합실 · 2층 그릴 등 원형 공간 (상 · 중 · 하 등급별 복원)"],
  "change": ["역 대합실 · 홀 → 전시 · 공연 · 카페 다목적 공간", "2층 양식당 그릴 → 공연 · 전시 · 세미나 공간"],
  "add": ["전시 · 공연용 설비 (원형 복원을 해치지 않는 범위)"],
 },
 "why": [
  "근대 교통 유산을 철거나 상업 개발 대신 원형 복원해 공공 문화공간으로 바꾼 국가 사업입니다.",
  "공간마다 역사적 중요도를 매겨 복원 수준을 달리한 방식이, 보존과 새 쓰임을 함께 이룬 방법이었습니다.",
 ],
 "space": [
  "지하 1층 · 지상 2층. 1층은 중앙홀(돔 아래, 16m 높이 스테인드글라스 천창)을 중심으로 좌우의 옛 역 공간들이 이어져 전시장으로 쓰입니다.",
  "2층에는 1925년 문을 연 양식당 「그릴」 자리가 공연 · 전시 · 세미나 공간으로 쓰입니다.",
 ],
 "material": [
  "석재 혼합 벽돌조 — 1층은 르네상스 궁전 건축 기법의 석재, 위는 붉은 벽돌에 화강석 장식 (국가유산청). 중앙홀은 벽돌과 철근콘크리트를 함께 썼습니다 (이데일리).",
  "복원: 준공 당시 자료에 따라 스테인드글라스 · 실내 마감을 되살렸습니다.",
 ],
 "funding": [
  ["공공 재원 (국비)", "복원 · 활용 사업비 약 200억 원 — 문화체육관광부, 2009~2011년", "https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01161126596315176"],
 ],
 "famous": [
  "국가유산청은 \"우리나라에서 가장 오래된 철도 건물\"로서 건축사적 가치가 크다고 설명합니다.",
  "1925년부터 약 80년 동안 서울의 관문 역이었던 건물입니다.",
  "이름의 「284」가 옛 사적 번호에서 왔을 만큼, 문화재를 문화공간으로 쓰는 대표 사례로 알려져 있습니다.",
 ],
 "lesson": [
  "공간마다 보존 등급을 정하면, 원형 복원과 새 쓰임을 한 건물 안에서 조율할 수 있습니다.",
  "기능을 잃은 교통 유산도 원래 공간(홀 · 대합실 · 식당)의 성격을 살린 프로그램으로 다시 쓰일 수 있습니다.",
 ],
 "operation": [
  ["운영 주체", "문화체육관광부 (소유 · 국가유산청 관리 사적) · 한국공예디자인문화진흥원 (운영)"],
  ["입장료", "관람료 무료 (공식 사이트 방문안내)", "http://www.seoul284.org/cms/content/view/250"],
  ["수입 구성", "공연 예매 · 대관 신청 서비스를 운영 (공식 사이트 이용약관) — 대관료 금액은 확인 못 함", "http://www.seoul284.org/cms/content/view/287"],
 ],
 "operationNote": ["문화역서울 284는 국비로 복원한 뒤 문화체육관광부 산하 한국공예디자인문화진흥원이 맡아 무료 전시 · 공연을 여는 공공 운영 방식입니다. 대관 · 공연 예매 제도가 있으나, 연간 운영 예산과 자체 수입 비율은 확인하지 못했습니다."],
 "missing": [
  "수익사업 · 운영 재원 — 연간 운영 예산, 대관료 수입 · 비율, 방문객 수는 확인된 자료를 찾지 못했습니다.",
  "복원 설계 · 시공 회사와 연면적은 확인된 자료를 찾지 못했습니다.",
  "원 설계자는 쓰카모토 야스시의 참여만 확인되며, 전체 설계 책임자는 분명하지 않다는 자료가 있습니다.",
  "역무 이전 연도는 국가유산청 2003년, 운영 기관 연혁 2004년(KTX 개통)으로 다릅니다.",
 ],
 "refs": [
  {"t": "국가유산청 국가유산포털 — 사적 구 서울역사", "u": "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1331102840000"},
  {"t": "문화역서울284 — 한국어 위키백과 (연혁 · 시설)", "u": "https://ko.wikipedia.org/wiki/%EB%AC%B8%ED%99%94%EC%97%AD%EC%84%9C%EC%9A%B8284"},
  {"t": "문화역서울284 — 지나온 이야기 (연혁)", "u": "https://www.seoul284.org/cms/content/view/253"},
  {"t": "문화체육관광부 보도자료 — 구 서울역사, 복원 마치고 '문화역 서울 284'로 재탄생", "u": "https://www.mcst.go.kr/site/s_notice/press/pressView.jsp?pSeq=11498"},
  {"t": "이데일리 — 사적 284호 옛 서울역사 복원완료", "u": "https://edaily.co.kr/News/Read?mediaCodeNo=257&newsId=01161126596315176"},
  {"t": "서울사랑 — 서울의 관문, 서울역의 117년을 돌아보다", "u": "https://love.seoul.go.kr/articles/4397"},
  {"t": "천지일보 — 1925년 서울역 모습은… 경성역 준공도면 공개 (2016)", "u": "https://www.newscj.com/news/articleView.html?idxno=360826"},
  {"t": "문화역서울284 — 방문안내", "u": "http://www.seoul284.org/cms/content/view/250"},
  {"t": "문화역서울284 — 이용약관 (공연예매 · 대관신청)", "u": "http://www.seoul284.org/cms/content/view/287"},
  {"t": "문화역서울284 — 공간안내", "u": "http://www.seoul284.org/space/menu/256"},
 ],
},

"mmca-seoul": {
 "from": "병원 외래진찰소 → 보안사 · 기무사 (군 정보기관)", "to": "국립 현대미술관", "y0": "1933 완공 (병원) · 2008 기무사 이전",
 "archAbout": [
  "민현준 (홍익대 건축학과 교수, 엠피아트 건축사사무소 mp_art 대표)이 이끈 엠피아트 · 시에이플랜 (C.A. Plan) 컨소시엄의 「무형의 미술관 (Shapeless Museum)」 안이 2010년 8월 6일 당선되었습니다. 2010년 2월 아이디어 공모에 국내외 113개 팀이 참가했고, 그중 5개 팀이 본공모에 올랐습니다.",
  "민현준은 빌바오 구겐하임 같은 \"오브제\" 미술관 대신, 건물 사이 마당을 중심으로 한 \"군도형 (archipelago)\" 미술관을 제안했습니다. 이 작품으로 2014년 한국건축가협회상과 한국건축문화대상 (준공건축물 부문 대상)을 받았습니다.",
 ],
 "spec": [
  ["원 건축물", "경성의학전문학교 부속의원 외래진찰소 — 1928년 병원 개원, 1932년 일부 준공, 1933년 증축 완성 (철근콘크리트 지하 1층 · 지상 3층)"],
  ["원래 용도 변천", "병원 → 국군보안사령부 · 국군기무사령부 (1971~2008, 국군서울지구병원 등 11개 동)"],
  ["함께 있는 유산", "종친부 경근당 · 옥첩당 (조선 왕실 종친 관청, 1866 중건) — 1981년 다른 곳으로 옮겼다가 2013년 원래 자리로 이전"],
  ["변경 용도", "국립현대미술관 서울관 — 전시실 8개 (10,450㎡) · 미디어랩 · 영화관 · 다목적홀 · 디지털 도서관 · 식당"],
  ["건축주 · 운영", "문화체육관광부 · 국립현대미술관"],
  ["개조 설계", "민현준 — 엠피아트 · 시에이플랜 (C.A. Plan) 컨소시엄"],
  ["공모", "2009.12 시작 → 2010.2 아이디어 공모 (113팀) → 2010.8.6 당선"],
  ["공사", "2011년 6월 15일 기공 → 2013년 완공"],
  ["개관", "2013년 11월 13일"],
  ["대지 · 연면적", "대지 27,264㎡ · 건축면적 11,196㎡ · 연면적 52,125㎡"],
  ["층수 · 높이", "지하 3층 · 지상 3층, 높이 12m · 전시실 천장 4~17m"],
  ["총사업비", "2,460억 원"],
  ["시공 · 건설관리", "지에스건설 컨소시엄 (GS건설 · 계룡건설 · 태영건설) · 건설사업관리 한미글로벌 외 2개사"],
  ["수상", "2014 한국건축가협회상 · 2014 한국건축문화대상 (준공건축물 공공 부문 대상)"],
 ],
 "tenants": [
  ["문화 · 기업 후원 전시", "현대자동차 — MMCA 현대차 시리즈 (MMCA Hyundai Motor Series)", "2014~2023년 10회 — 해마다 한국 중진 작가 1명의 대규모 신작 개인전을 서울관에서 후원 (2014 이불 ~ 2023 정연두, 2023년이 열 번째)", "https://www.hyundaimotorgroup.com/ko/news/CONT0000000000109233"],
  ["문화 · 영화관", "MMCA 영화관", "지하 · 122석 · 예술 · 실험 영화 상영과 국제영화제", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["문화 · 공연장", "멀티프로젝트홀", "지하 · 253석 · 가변 객석 — 다원예술 · 퍼포먼스", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["문화 · 도서관", "디지털정보실 — 디지털 도서관 (2층) · 디지털 아카이브 (3층)", "한국 근현대 미술 도서 · 도록 · 작가 자료 열람", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["상업 · 소매", "MMCA 아트존 (뮤지엄숍)", "사무동 1층 · 438㎡ · 국립현대미술관진흥재단 직접 운영 (개관 당시)", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["상업 · 식음", "레스토랑 · 카페테리아 · 푸드코트 · 디지털 북카페 4곳", "레스토랑 사무동 2층 514㎡ (경복궁 조망) · 카페테리아 1층 267㎡ — 위탁 운영 (개관 당시 계획)", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["문화 · 전시장", "서울박스 · 미디어랩", "서울박스는 8개 전시실 동선의 중심 공간, 미디어랩은 신매체 융복합 전시 공간", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
 ],
 "timeline": [
  ["1866", "흥선대원군 집권기 종친부 중건 (경근당 · 옥첩당)"],
  ["1928", "경성의학전문학교 부속의원 개원"],
  ["1932~1933", "외래진찰소 건물 일부 준공 후 증축 완성 — 지금의 옛 기무사 본관"],
  ["1946", "서울대학교 의과대학 제2부속병원으로 사용 (미술관 개관 자료)"],
  ["1971", "육군 특수부대에서 비롯된 보안사가 소격동 터 사용 시작"],
  ["1978 · 1991", "일부가 국군서울지구병원으로 개편 · 1991년 국군기무사령부로 개칭 (미술관 개관 자료)"],
  ["1981", "종친부 경근당 · 옥첩당을 다른 곳으로 옮김"],
  ["2008.7.3", "옛 기무사 본관, 등록문화재 제375호 지정"],
  ["2008.11.18", "국군기무사령부, 37년 만에 과천으로 이전"],
  ["2009.1", "옛 기무사 터에 국립현대미술관 서울관 건립 확정"],
  ["2010.8.6", "엠피아트 · 시에이플랜 「무형의 미술관」 당선 (113팀 아이디어 공모 → 5팀 본공모)"],
  ["2011.6.15", "기공식"],
  ["2012.8.13", "공사 중 화재 — 4명 사망 · 25명 부상"],
  ["2013", "종친부 경근당 · 옥첩당을 원래 자리로 이전"],
  ["2013.11.13", "국립현대미술관 서울관 개관"],
  ["2021.12.27", "종친부 경근당과 옥첩당, 보물 지정 (서울시 유형문화재 제9호는 해제)"],
 ],
 "heritage": [
  ["국가등록문화유산 (서울 구 국군기무사령부 본관, 2008)", "2008년 7월 3일 등록 (옛 등록문화재 제375호). 1928년 개원한 경성의학전문학교 부속의원 외래진찰소, 1932년 일부 준공 · 1933년 증축 완성의 철근콘크리트 3층 건물. 소유 · 관리 국립현대미술관", "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=4411103750000"],
  ["보물 (종친부 경근당과 옥첩당, 2021)", "2021년 12월 27일 지정. 조선 정1품 관청 종친부의 중심 건물 (1866 중건). 1981년 이전했다가 2013년 원위치로 옮기며 많은 부재를 재사용해 진정성을 인정받음. 관리 국가유산청 경복궁관리소", "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1121121510000"],
  ["서울시 유형문화재 제9호 (종친부 경근당과 옥첩당, 1972 → 2021 해제)", "1972년 5월 25일 지정, 보물 승격으로 2021년 12월 27일 해제"],
 ],
 "concept": [
  "\"무형의 미술관 (Shapeless Museum)\" — 눈에 띄는 한 덩어리 대신 크기 · 높이가 다른 건물을 마당 사이에 섬처럼 흩어 놓은 \"군도형\" 배치입니다. 담장을 없애 둘레의 네 길 어디서나 들어올 수 있게 했습니다.",
  "경복궁 · 종친부 · 북촌 경관을 해치지 않도록 제1전시실을 뺀 2~7전시실을 땅속에 두고, 지상 높이를 12m 로 낮췄습니다.",
  "정해진 순서 대신 관람객이 스스로 길을 고르는 \"네트워크형 동선\"을 계획했습니다. 설계는 문화재 · 도시계획 위원회 심의를 34차례 거쳤습니다.",
 ],
 "strategy": {
  "keep": ["옛 기무사 본관 (1933, 철근콘크리트 지하 1층 · 지상 3층, 등록문화유산)", "종친부 경근당 · 옥첩당 (원래 자리로 옮겨 복원, 보물)"],
  "change": ["군 정보기관 · 병원 터 (11개 동, 연병장 · 테니스장) → 담장 없는 미술관과 마당"],
  "add": ["새 전시동 · 지하 전시실 (전시실 8개, 10,450㎡, 천장 4~17m)", "마당 6곳", "미디어랩 · 영화관 · 다목적홀 · 디지털 도서관 · 식당"],
 },
 "why": [
  "권력의 상징이던 군 정보기관 터를 담장 없는 시민의 미술관으로 바꾼 장소의 전환입니다. 당시 한국은 OECD 가운데 수도에 국립미술관이 없는 유일한 나라였습니다 (정책브리핑).",
  "조선 관청 (종친부) · 근대 병원 건물 (기무사 본관) · 새 건물이 한 대지에 공존하며, 큰 전시실을 땅속에 묻어 역사 경관을 지켰습니다.",
  "2014년 한국건축가협회상 · 한국건축문화대상을 받았습니다.",
 ],
 "space": [
  "지상: 옛 기무사 본관 · 종친부 · 새 전시동이 마당 6곳을 사이에 두고 흩어져 있고, 담장 없이 사방의 길에서 들어옵니다.",
  "지하: 2~7전시실 등 큰 전시실을 지하에 모아, 천장 높이 4~17m 의 다양한 전시 공간(화이트큐브 · 설치 · 블랙박스)을 만들었습니다.",
  "동선: 한 줄 관람 대신 여러 길이 그물처럼 이어져 관람객이 고를 수 있습니다.",
 ],
 "material": [
  "보존: 옛 기무사 본관 — 1933년 철근콘크리트 3층 건물 · 종친부 — 조선 목조 관아 건축 (원부재 상당수 재사용).",
  "새 것: 따뜻한 색의 테라코타 타일이 새 전시동의 주 외장재로, 주변 경복궁 · 북촌 경관과 어울리도록 분절한 외관을 덮습니다.",
 ],
 "funding": [
  ["총사업비 (국비)", "2,460억 원 (서울관 건립 사업 전체) — 공사비 1,276억 · 부지매입비 1,038억 · 설계비 90억 · 감리비 53억 · 부대비 3억 원 (국립현대미술관 개관 D-20 기자간담회 자료, 2013.10.22)", "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"],
  ["전시 사업비 · 관람료 수입", "2025년 「론 뮤익」전: 예산 30억 원, 관람객 약 53만 명, 관람료 수입 약 25억 원 — 손익분기 못 넘김 (아시아경제 2026.1)", "https://view.asiae.co.kr/article/2026010711201971024"],
 ],
 "famous": [
  "옛 국군기무사령부 터라는 장소의 역사 때문에, 권력 공간을 시민 문화공간으로 바꾼 상징적 사례로 알려져 있습니다.",
  "2010년 공모에 아이디어 단계에서만 113개 팀이 참가했습니다.",
  "2014년 한국건축가협회상과 한국건축문화대상 대상을 받았습니다.",
  "조선 종친부 (보물) · 근대 병원 건물 (등록문화유산) · 현대 미술관이 한 대지에 함께 있습니다.",
 ],
 "lesson": [
  "역사 경관 옆에 큰 시설을 넣을 때는 큰 부피를 땅속에 넣고 지상을 낮고 잘게 나누는 방법이 있습니다.",
  "담장을 없애고 마당을 동네와 잇는 것만으로도, 닫힌 권력 공간을 열린 공공 공간으로 바꿀 수 있습니다.",
  "여러 시대의 건물을 각자의 자리에서 보존하면 대지 자체가 역사의 층을 보여 줍니다.",
 ],
 "operation": [
  ["운영 주체", "국립현대미술관 — 문화체육관광부 소속기관, 2006년 1월 1일 책임운영기관 지정 (한국어 위키백과)"],
  ["입장료", "기획전 통합관람권 10,000원 (기획전 3개 이상일 때) · 수 · 토 야간 (18~21시) 무료 · 매월 마지막 수요일 무료", "https://www.mmca.go.kr/visitingInfo/seoulInfo.do"],
  ["관람료 수준", "일반 전시 2,000원, 대형 기획전은 차등 — 2025년 론 뮤익전 5,000원, 2026년 데이미언 허스트전 8,000원 (작품 운송비가 전시 예산 30억 원의 약 70%) · 개관 특별전 통합권 7,000원 (2013)", "https://view.asiae.co.kr/article/2026010711201971024"],
  ["방문객", "2025년 서울관 206만 명 — 개관 이래 최다 (미술관 4관 전체 337만 명, 12월 20일 기준) · 회원 약 40만 명", "https://www.mmca.go.kr/pr/pressDetail.do?bdCId=202512240010140"],
  ["수지", "대형 국제전도 관람료로 비용을 다 채우지 못함 — 론 뮤익전 예산 30억 원 대비 관람료 수입 약 25억 원"],
  ["기타 수입", "유료 회원제 · 후원사 (패트론 / 파트너) 제도 · 주차 요금 (최초 1시간 4,200원) · 아트숍 · 편의시설"],
 ],
 "operationNote": ["국립현대미술관 서울관은 국비로 지은 국립 시설로, 문화체육관광부 소속 책임운영기관이 운영합니다. 관람료는 일반 전시 2,000원으로 낮게 두고 대형 국제전에만 5,000~8,000원을 받는데, 2025년 론 뮤익전도 예산 30억 원에 관람료 수입 약 25억 원으로 비용을 다 채우지 못했습니다. 2025년 서울관 방문객은 206만 명으로 개관 이래 최다였습니다. 기관 전체 예산과 자체 수입 비율은 확인하지 못했습니다."],
 "missing": [
  "주요 입주 시설 — 레스토랑 · 카페 등 위탁 식음 시설의 현재 업체명과 현대차 시리즈가 10회(2023) 이후 이어지는지는 확인된 자료를 찾지 못했습니다.",
  "수익사업 · 운영 재원 — 국립현대미술관(책임운영기관)의 연간 예산 · 세입 구성과 서울관 몫, 자체 수입 비율은 확인된 자료를 찾지 못했습니다.",
  "구조 · 조경 협력사는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "국가유산포털 — 서울 구 국군기무사령부 본관 (국가등록문화유산)", "u": "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=4411103750000"},
  {"t": "국가유산포털 — 종친부 경근당과 옥첩당 (보물)", "u": "https://www.heritage.go.kr/heri/cul/culSelectDetail.do?ccbaCpno=1121121510000"},
  {"t": "건축도시공간연구소 건축자료 — 국립현대미술관 서울관", "u": "http://www.aurum.re.kr/Bits/BuildingDoc.aspx?mm=4&ss=1&num=5116"},
  {"t": "한국일보 — 국립현대미술관 서울관 설계 공모에 'Shapeless Museum' 선정 (2010)", "u": "https://www.hankookilbo.com/news/article/201008060765476328"},
  {"t": "아시아경제 — 초현대, 전통, 근대가 어우러진 열린 공간 (2013.10)", "u": "https://www.asiae.co.kr/article/2013102213443155916"},
  {"t": "아시아경제 — 국립현대 서울관 13일 개관 (2013.11)", "u": "https://www.asiae.co.kr/article/2013111207362586361"},
  {"t": "정책브리핑 — '도심 속 미술관' 생겼다…옛 기무사터에 국립현대미술관 개관", "u": "https://m.korea.kr/news/reporterView.do?newsId=148769812&pWise=sub&pWiseSub=J1"},
  {"t": "서울신문 — 공간과 공간 잇는 미술관 마당 [건축 오디세이] (2023)", "u": "https://www.seoul.co.kr/news/newsView.php?id=20230612021001"},
  {"t": "시선뉴스 — 국군기무사령부, 37년 만에 서울서 과천으로 이전", "u": "http://www.sisunnews.co.kr/news/articleView.html?idxno=93153"},
  {"t": "국립현대미술관 — 서울관 개관 D-20 기자간담회 자료 (2013.10.22, PDF)", "u": "https://www.mmca.go.kr/upload/m/data/board/2013/10/23/20131023141426.pdf"},
  {"t": "국립현대미술관 보도자료 — 2025 방문객 337만 명 돌파", "u": "https://www.mmca.go.kr/pr/pressDetail.do?bdCId=202512240010140"},
  {"t": "아시아경제 — 국립현대미술관, 국제 거장전 관람료 8000원으로 인상 (2026.1)", "u": "https://view.asiae.co.kr/article/2026010711201971024"},
  {"t": "국립현대미술관 서울관 — 한국어 위키백과", "u": "https://ko.wikipedia.org/wiki/%EA%B5%AD%EB%A6%BD%ED%98%84%EB%8C%80%EB%AF%B8%EC%88%A0%EA%B4%80_%EC%84%9C%EC%9A%B8%EA%B4%80"},
  {"t": "국립현대미술관 — 서울관 관람 안내", "u": "https://www.mmca.go.kr/visitingInfo/seoulInfo.do"},
  {"t": "국립현대미술관 — 한국어 위키백과", "u": "https://ko.wikipedia.org/wiki/%EA%B5%AD%EB%A6%BD%ED%98%84%EB%8C%80%EB%AF%B8%EC%88%A0%EA%B4%80"},
  {"t": "현대자동차그룹 — 《MMCA 현대차 시리즈 2023: 정연두》展 개막", "u": "https://www.hyundaimotorgroup.com/ko/news/CONT0000000000109233"},
  {"t": "디지털타임스 — MMCA 현대차 시리즈 10년", "u": "https://www.dt.co.kr/article/11491843"},
 ],
},
}
