# -*- coding: utf-8 -*-
# 리노베이션 노트 — 더 자세한 본문 (배정 05: 폰세 시티 마켓 · 디아 비컨 · 매스모카 · 뒤스부르크 경관공원 · 요코하마 아카렌가 · 콜 드롭스 야드)
#  reno*.py 의 같은 id 를 덮어씀. 출처에서 직접 확인한 사실만 씀.
D = {
"ponce-city-market": {
 "from": "시어스 통신판매 물류센터 · 백화점 → 애틀랜타 시청 별관",
 "to": "복합 (푸드홀 · 상점 · 사무 · 아파트 · 옥상 놀이 공간)",
 "y0": "1926 건설 · 1989 물류센터 폐쇄 · 2010 시청 별관 이전",
 "archAbout": [
  "원 건축물은 시카고의 니먼스 앤드 컴퍼니 (Nimmons & Company)가 설계했습니다. 국가사적 등재 기록에 따르면 시어스 로벅 (Sears, Roebuck and Co.)은 20세기 첫 10년에 시카고 본사 단지를 설계한 니먼스 앤드 펠로스 (Nimmons and Fellows)의 \"정식\"을 전국의 물류센터 · 매장에 되풀이했고, 애틀랜타 건물도 \"긴 다층 건물 한가운데 탑을 세우고 탑에만 장식을 두는\" 같은 방식입니다. 시공은 시카고의 B-W 건설 (B-W Construction Company)이 맡았습니다.",
  "개조는 부동산 투자사 제임스타운 (Jamestown L.P.)이 2011년 건물을 사들여 추진했고, 설계 건축가는 뉴욕의 S9 아키텍처 (S9Architecture)입니다. 제임스타운은 맨해튼 첼시 마켓을 운영했던 회사입니다.",
 ],
 "spec": [
  ["원 건축물", "시어스 로벅 통신판매 창고 · 소매점 (Sears, Roebuck and Co. Mail-Order Warehouse and Retail Store) — 1926년 개장, 지상 9층 + 지하, 철근 콘크리트 골조에 벽돌 외장"],
  ["원 설계 · 시공", "니먼스 앤드 컴퍼니 (Nimmons & Company) 설계 · B-W 건설 (1926) · 비어스 건설 (Beers Construction, 1948 증축)"],
  ["증축", "1932년 서쪽 증축 · 1948년 남서쪽 증축 · 1966~1971년 동쪽 창고동 (유진 보스웰 (Eugene Bothwell) 설계, 약 621,700 제곱피트) — 주차장 등 포함 전체 200만 제곱피트 이상"],
  ["원래 용도", "통신판매 카탈로그 물류 · 매장 · 지역 사무소 (1926~1989) → 애틀랜타 시청 별관 「시티 홀 이스트 (City Hall East)」 — 경찰 · 소방 · 911 상황실"],
  ["폐쇄", "시어스는 1987년 물류센터를 1989년까지 닫기로 결정 · 1989년까지 가동 / 시 기관은 2010년 이전"],
  ["변경 용도", "1~2층 상점 · 푸드홀, 지하 · 3층 주차, 4~9층 사무실, 1948년 증축동 위층 아파트, 10층 (탑 안) 식당 · 옥상 놀이 공간"],
  ["개조 설계", "S9 아키텍처 (S9Architecture) — 설계 건축가"],
  ["건축주 · 개발", "제임스타운 (Jamestown L.P.) — 2011년 7월 애틀랜타시로부터 2,700만 달러에 매입"],
  ["공사 기간", "2011~2014년 (1단계)"],
  ["개관", "2014년 8월 25일 (위키백과) — 국가사적 등재 기록은 \"2015년 개장\"으로 적음"],
  ["연면적", "약 210만 제곱피트 (약 20만㎡), 대지 16에이커 (약 6.5ha) — 한 블록 전체"],
  ["높이", "중앙 탑 227피트 (약 69m) — Traditional Building 기준"],
  ["프로그램", "사무 약 50만 제곱피트 · 상업 약 30만 제곱피트 · 주거 수백 세대 (Traditional Building)"],
  ["인증", "LEED 골드 (2016년)"],
  ["위치", "미국 조지아주 애틀랜타 폰세 드 레온 거리 675 (675 Ponce de Leon Ave. NE) — 동쪽 면이 애틀랜타 벨트라인 (Atlanta BeltLine) 산책로"],
 ],
 "timeline": [
  ["1905~1910", "부지에 있던 폰세 드 레온 온천 위 놀이공원이 전성기를 맞음"],
  ["1925", "12월 시어스 로벅이 R.J. 스필러 사로부터 부지를 매입"],
  ["1926", "9층 물류센터 · 매장과 부속 선적동 완공 · 개장"],
  ["1932", "서쪽 (글렌 아이리스 거리 쪽) 첫 증축"],
  ["1948", "남서쪽 두 번째 증축 완공 (1945 · 1946년 두 차례 허가로 4층 + 5층)"],
  ["1966~1971", "동쪽 창고동 증축 (9층) · 주차 건물 · 자동차 정비동 신축"],
  ["1987", "시어스가 물류센터를 1989년까지 닫기로 결정"],
  ["1989", "카탈로그 물류센터 운영 종료"],
  ["1990", "10월 애틀랜타시가 1,200만 달러에 매입 발표 → 시청 별관 「시티 홀 이스트」"],
  ["2005", "시가 개발업자에게 매각 추진 시작"],
  ["2010", "1966년 주차 건물 철거 · 12월 미국 국립공원청이 역사건물 세제 혜택 인증 신청 (Part 1)을 검토해 \"국가사적 요건 충족\" 판단 · 시 기관 이전 (3월)"],
  ["2011", "7월 제임스타운이 2,700만 달러에 매입 · 개조 착공"],
  ["2014", "8월 25일 폰세 시티 마켓 개장"],
  ["2016", "11월 15일 미국 국가사적 (NRHP) 등재 · LEED 골드 인증"],
 ],
 "heritage": [
  ["미국 국가사적 (National Register of Historic Places, 2016)", "2016년 11월 15일 등재, 참조번호 16000769 — 등재명 「Sears, Roebuck and Company Mail-Order Warehouse and Retail Store」. 기준 A (상업)과 C (건축), 중요 시기 1926~1948년. 1966~1971년 증축동 · 정비동 · 주차 건물은 비기여 요소", "https://npgallery.nps.gov/AssetDetail/NRIS/16000769"],
  ["연방 역사건물 개조 세제 혜택 인증 절차 (Historic Preservation Certification, 2010~)", "2010년 12월 22일 미국 국립공원청이 제임스타운의 인증 신청 Part 1 (사업번호 25400)을 검토해 1926년 건물과 1932 · 1948년 증축동을 \"기여 건물\"로 판단 — 등재 뒤 \"인증 역사 구조물\"이 되는 조건", "https://npgallery.nps.gov/AssetDetail/NRIS/16000769"],
 ],
 "concept": [
  "한 블록을 통째로 차지한 210만 제곱피트의 물류 건물을 \"거리처럼\" 쪼개는 것이 핵심입니다. 1~2층은 상점과 푸드홀, 지하와 3층은 주차, 4~9층은 사무실, 1948년 증축동 위층은 아파트로 층별로 용도를 나눴습니다.",
  "두 개의 큰 구멍을 냈습니다. 1926년 건물의 1~2층 사이 콘크리트 바닥을 크게 걷어 내 푸드홀 아트리움을 만들었고, 남쪽 선적동은 지붕과 기둥 일부를 걷어 내 중정으로 바꾼 뒤 남은 가운데 부분만 상점으로 남겼습니다.",
  "건물 뒤쪽을 땅높이로 맞췄습니다. 노스 애비뉴에서 지하 하역장으로 내려가던 경사로를 없애고 뒤쪽 주차장 전체를 도로 높이로 올려, 사방에서 걸어 들어올 수 있게 했습니다. 동쪽의 벨트라인 산책로에서는 다리로 2층에 바로 들어옵니다.",
 ],
 "strategy": {
  "keep": ["철근 콘크리트 버섯 기둥 (mushroom columns) · 콘크리트 바닥 · 나무 바닥 · 계단 네 곳", "다창 철제 피벗 창 — 정비해 재사용", "이탈리아 르네상스 리바이벌 양식 중앙 탑과 탑 안의 물탱크 (지금도 급수)", "선적동 지붕 위 철도 가대의 철골 구조 · 뒤쪽 가대 위 선로 일부", "1948년 증축동의 엘리베이터 세 대 · 계단 두 곳"],
  "change": ["물류 · 매장층 → 상점 · 푸드홀 · 사무실 · 아파트", "시청 별관 때 넣은 칸막이 · 내린 천장 · 바닥재 철거", "북쪽 보행 출입구 세 곳은 원래 배치 그대로 두고 문만 같은 형태로 교체", "하역장 진입 경사로 철거 · 뒤쪽 주차장을 도로 높이로"],
  "add": ["1~2층 사이 아트리움과 나선 계단 (푸드홀)", "선적동 지붕을 걷어 낸 중정 · 물 시설 · 작은 야외 공연장", "벨트라인에서 2층으로 들어오는 보행 · 자전거 다리", "남동쪽 5층 주차 건물 (1층 상점)", "탑의 「Ponce」 네온 간판과 시계 · 옥상 놀이 공간"],
 },
 "why": [
  "죽은 \"슈퍼블록\"을 벨트라인 산책로와 이어, 철도 순환선 재생 사업의 대표 거점으로 만들었습니다 — 건물 동쪽 면이 바로 산책로이고, 다리로 2층에 들어갑니다.",
  "공공이 20년 가까이 쓰지 못하던 건물을 민간 개발로 되살린 사례입니다. 애틀랜타시는 1990년 1,200만 달러에 사들였지만 \"건물 면적의 일부밖에 쓰지 못했고\" (국가사적 등재 기록), 2011년 2,700만 달러에 제임스타운에 팔았습니다.",
  "연방 역사건물 세제 혜택 절차를 밟아 버섯 기둥 · 나무 바닥 · 철제 창 같은 \"특징 요소\"를 지키면서 용도를 바꿨고, 개조가 끝난 뒤 2016년 국가사적에 올랐습니다.",
 ],
 "space": [
  "1926년 본관과 1932년 증축동은 예나 지금이나 한 건물처럼 쓰입니다. 1~2층은 상점과 푸드홀, 지하와 3층은 주차장, 4~9층은 사무실, 탑 안의 10층은 식당과 옥상으로 오르는 통로입니다.",
  "1948년 증축동은 1~2층이 상점 · 사무실, 위층이 아파트이며 중정으로 들어가는 길목이 됩니다. 아파트 안에도 옛 기둥 · 바닥 · 천장을 남기고 새 벽은 석고보드로 세웠습니다.",
  "출입은 사방에서 합니다 — 북쪽 폰세 드 레온 거리의 원래 보행 출입구 세 곳, 남쪽 중정 (옛 하역 문 두 개를 열어 고정), 서쪽 글렌 아이리스 거리 쪽 새 상점 입면, 동쪽 벨트라인에서 2층으로 이어지는 다리.",
 ],
 "material": [
  "구조는 1920년대 기술인 현장 타설 철근 콘크리트 버섯 기둥과 바닥판, 벽돌 커튼월입니다. 국가사적 등재 기록은 철근 콘크리트 구조를 \"이 건물의 가장 중요한 특징의 하나\"로 꼽습니다.",
  "선적동은 콘크리트 · 철골에 벽돌 외장이며, 본관과 달리 기둥이 네모납니다. 지붕 위 철도 가대의 선로는 대부분 걷어 냈지만 철골 받침은 실내에 드러나 있습니다.",
  "새 칸막이는 주로 석고보드와 유리로 하고, 입주자는 옛 바닥 · 천장 · 기둥을 보호하는 지침을 따라야 합니다. Traditional Building 은 공사 폐기물의 98% (5만 톤 이상)를 재활용했다고 전합니다.",
 ],
 "funding": [
  ["공공 매입 (1990)", "애틀랜타시가 1,200만 달러에 매입해 시청 별관으로 사용", "https://npgallery.nps.gov/AssetDetail/NRIS/16000769"],
  ["민간 매입 (2011)", "제임스타운이 2011년 7월 11일 애틀랜타시로부터 2,700만 달러에 매입 (위키백과)", "https://en.wikipedia.org/wiki/Ponce_City_Market"],
  ["총사업비", "자료마다 다름 — Bisnow (2011)는 개조 투자 계획 1억 8천만 달러, Traditional Building 은 3억 달러로 적음. 1억 8천만 달러는 2014년 공사 대출액과도 같아 혼동 가능성이 있음", "https://www.bisnow.com/atlanta/news/commercial-real-estate/PONCE-MARKETS-TAX-CREDITS-5028"],
  ["세제 혜택 절차", "연방 역사건물 개조 세제 혜택 인증 — 2010년 12월 국립공원청이 Part 1 신청 (사업번호 25400)을 검토", "https://npgallery.nps.gov/AssetDetail/NRIS/16000769"],
  ["세제 혜택 (2011)", "연방 역사건물 세제 혜택 1,500만 달러 이상이 제임스타운의 2,700만 달러 매입 자금에 쓰임 — 매입은 제임스타운 「Coinvest V」 펀드 (4억 3천만 달러 규모 기회 펀드)로 2011년 7월 11일 완료 (Bisnow)", "https://www.bisnow.com/atlanta/news/commercial-real-estate/PONCE-MARKETS-TAX-CREDITS-5028"],
  ["세제 혜택 (사업 전체)", "사업 전체로 5천만 달러 이상의 세제 혜택을 활용해 자기자본을 마련 — 역사보존 자문사 레이 엘리스 앤드 라브리 (Ray, Ellis & LaBrie, 국가사적 등재 · 세제 혜택 서류 담당)", "https://www.rayandellis.com/hello-world-2/"],
  ["민간 대출 (2014)", "2014년 4월 29일 공사 대출 1억 8천만 달러 — PNC 은행이 선트러스트 · JP모건과 함께 제공. 그 전까지는 제임스타운 자기자본 100%로 공사 (REBusinessOnline)", "https://rebusinessonline.com/jamestown-secures-180-million-loan-for-atlantas-ponce-city-market/"],
 ],
 "famous": [
  "2016년 미국 국가사적에 오른 1926년 시어스 물류센터 · 매장 건물로, 주차장 등을 합쳐 200만 제곱피트가 넘는 애틀랜타 최대급 건물입니다 (등재 기록).",
  "애틀랜타 벨트라인 산책로와 직접 이어진 첫 대형 복합 재생 건물로, 동쪽 면이 산책로에 붙어 있습니다.",
  "메일침프 (Mailchimp) 모회사 · 핀터레스트 · 팬듀얼 등이 사무실로 입주했고, 앤 쿼트라노 · 린턴 홉킨스 · 션 브록 등 이름난 요리사들이 푸드홀에 들어왔습니다 (위키백과).",
  "2016년 LEED 골드 인증을 받았습니다 (Traditional Building).",
 ],
 "lesson": [
  "거대한 바닥판은 층별로 다른 용도를 쌓고, 바닥 · 지붕 일부를 걷어 아트리움과 중정을 내면 \"한 블록짜리 건물\"도 거리처럼 걸을 수 있습니다.",
  "공공이 쓰지 못한 큰 산업 건물은 역사건물 세제 혜택과 녹지 · 교통 사업 (벨트라인)을 함께 묶을 때 민간 개발의 사업성이 생깁니다.",
 ],
 "operation": [
  ["운영 주체", "민간 부동산 투자 · 운영사 제임스타운 (Jamestown) — 2011년 매입 뒤 직접 소유 · 운영하며, 본사도 건물 안에 둠 (CBRE)", "https://www.cbre.com/services/manage-properties-and-portfolios/landlord-leasing/calibre-creative-group/ponce-city-market"],
  ["수입 구성", "공공 운영 보조 없는 민간 임대 사업 — 사무실 (약 50만 제곱피트) · 상업 (약 30만 제곱피트) · 주거 임대료가 중심 (면적은 Traditional Building 기준)"],
  ["임대 운영", "CBRE 가 제임스타운과 함께 사무 임대 전략을 다시 짬 — 초기 입주사가 주로 기술 스타트업이었던 데서 금융 · 전문 서비스 기업까지 넓히는 \"성숙한 캠퍼스\"로 재포지셔닝", "https://www.cbre.com/services/manage-properties-and-portfolios/landlord-leasing/calibre-creative-group/ponce-city-market"],
  ["운영 성과", "2024년 CONA 서비스가 4만 9천 제곱피트 사무 임대 계약 — 그해 미드타운 사무 임대 상위 5건, 4분기 미드타운 2위 규모 (CBRE)", "https://www.cbre.com/services/manage-properties-and-portfolios/landlord-leasing/calibre-creative-group/ponce-city-market"],
  ["운영상 과제", "CBRE 는 \"새 건물 효과\"가 사라지고 미드타운 사무 임대 시장이 성숙하면서 브랜드와 임대 전략을 바꿔야 했다고 적음", "https://www.cbre.com/services/manage-properties-and-portfolios/landlord-leasing/calibre-creative-group/ponce-city-market"],
  ["임대 면적 구성 (2014 대출 시점)", "1단계 복원 110만 제곱피트 — 상업 · 식당 33만 제곱피트, A급 로프트 사무실 51만 7천 제곱피트, 주거 259세대 (REBusinessOnline)", "https://rebusinessonline.com/jamestown-secures-180-million-loan-for-atlantas-ponce-city-market/"],
 ],
 "operationNote": [
  "폰세 시티 마켓은 공공 운영 보조금 없이 민간 소유주 제임스타운이 임대 수입으로 운영합니다. 개조 단계에서는 연방 역사건물 세제 혜택 인증 절차를 밟았고, 개장 뒤에는 사무 · 상업 · 주거 임대가 수입원입니다. 푸드홀과 벨트라인 연결은 사무 임차인을 끄는 편의 시설로 마케팅됩니다.",
  "CBRE 에 따르면 개장 초 기술 스타트업 위주였던 임차 구성이 시장 변화로 한계에 부딪히자, 2024년 무렵 브랜드와 임대 전략을 바꿔 전문 서비스 기업까지 끌어들였습니다.",
 ],
 "missing": [
  "사무 · 상업 · 주거별 임대 수입과 입주율 수치는 확인된 자료를 찾지 못했습니다.",
  "총사업비는 자료마다 달라 (1억 8천만 달러 / 3억 달러) 확정하지 못했습니다.",
  "S9 아키텍처 외 현지 기록 건축가 · 구조 설계자는 열어 본 원문으로 확인하지 못했습니다.",
  "옥상 놀이 공간의 개장 연도는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Bisnow — Ponce Market's Tax Credits (2011)", "u": "https://www.bisnow.com/atlanta/news/commercial-real-estate/PONCE-MARKETS-TAX-CREDITS-5028"},
  {"t": "REBusinessOnline — Jamestown Secures $180 Million Loan for Atlanta's Ponce City Market (2014)", "u": "https://rebusinessonline.com/jamestown-secures-180-million-loan-for-atlantas-ponce-city-market/"},
  {"t": "Ray, Ellis & LaBrie — Ponce City Market", "u": "https://www.rayandellis.com/hello-world-2/"},
  {"t": "CBRE — Ponce City Market (Calibre Creative Group 사례)", "u": "https://www.cbre.com/services/manage-properties-and-portfolios/landlord-leasing/calibre-creative-group/ponce-city-market"},
  {"t": "NPGallery — Sears, Roebuck and Company Mail-Order Warehouse and Retail Store (NRIS 16000769)", "u": "https://npgallery.nps.gov/AssetDetail/NRIS/16000769"},
  {"t": "NRHP 등재 신청서 PDF (2016, NPS Form 10-900)", "u": "https://npgallery.nps.gov/GetAsset/e6ea8468-be89-4793-905c-317118b0e59e"},
  {"t": "Wikipedia — Ponce City Market", "u": "https://en.wikipedia.org/wiki/Ponce_City_Market"},
  {"t": "Traditional Building — S9Architecture's Sustainable Ponce City Market", "u": "https://www.traditionalbuilding.com/projects/ponce-city-market"},
 ],
},

"dia-beacon": {
 "from": "나비스코 과자 상자 제작 · 인쇄 공장",
 "to": "현대미술관 (1960년대 이후 미술 상설 전시)",
 "y0": "1929 건설 · 1999 디아 재단에 기증",
 "archAbout": [
  "원 건축물은 루이스 N. 위르싱 주니어 (Louis N. Wirsching, Jr.)와 존 W. 카우퍼스 사 (John W. Cowpers Co.)가 1929년 나비스코 (National Biscuit Company)의 상자 제작 · 인쇄 공장으로 지었습니다 (미국 국가사적 기록).",
  "개조는 미술가 로버트 어윈 (Robert Irwin)과 건축 사무소 오픈오피스 (OpenOffice — 앨런 코크 · 린 라이스 · 갈리아 솔로모노프 · 린다 탈만)가 디아 미술재단 (Dia Art Foundation) 관장 마이클 고반 (Michael Govan)과 함께 했습니다. 어윈은 주변 경관을 포함한 마스터플랜을 짜고, 건물에는 진입 광장과 전시실 사이의 작은 전이 공간 (파빌리온)을 더하는 등 \"미묘한 손질\"만 했습니다.",
  "디아 미술재단은 1974년 세워진 비영리 기관으로, 미술가의 대형 · 장소 특정 작업을 지원하고 오래 전시해 온 곳입니다.",
 ],
 "spec": [
  ["원 건축물", "나비스코 상자 제작 · 인쇄 공장 (National Biscuit Company Carton Making and Printing Plant) — 1929년, 건물 세 동과 열차 창고 (train shed)가 한 덩어리로 붙은 구조"],
  ["원 설계", "루이스 N. 위르싱 주니어 (Louis N. Wirsching, Jr.) · 존 W. 카우퍼스 사 (John W. Cowpers Co.)"],
  ["원래 용도", "과자 상자 인쇄 → 마지막 소유주 인터내셔널 페이퍼 (International Paper)"],
  ["변경 용도", "디아 비컨, 리지오 갤러리 (Dia:Beacon, Riggio Galleries) — 1960년대 초부터 현재까지의 미술, 한 전시실에 한 작가"],
  ["개조 설계", "로버트 어윈 (미술가, 마스터플랜 · 경관) · 오픈오피스 (OpenOffice, 건축)"],
  ["건축주 · 운영", "디아 미술재단 (Dia Art Foundation)"],
  ["공사 기간", "약 2년 (2003년 봄 완공)"],
  ["개관", "2003년 5월 18일"],
  ["전시 면적", "24만 제곱피트 (약 22,000㎡) — 디아 공식 발표 기준 (위키백과 디아 재단 항목은 개관 당시 전시 공간 16만 제곱피트로 적음)"],
  ["천창", "3만 4천 제곱피트 (약 3,200㎡) 이상"],
  ["대지", "국가사적 기록상 26.6에이커 (약 10.8ha)"],
  ["공사비", "5천만 달러 (뉴욕타임스 인용, 위키백과)"],
  ["위치", "미국 뉴욕주 비컨 비크먼 거리 3 (3 Beekman Street) — 허드슨강 동쪽 기슭, 메트로노스 역에서 걸어서 5분"],
 ],
 "timeline": [
  ["1929", "나비스코 상자 제작 · 인쇄 공장 준공"],
  ["1974", "디아 미술재단 설립"],
  ["1999", "마지막 소유주 인터내셔널 페이퍼가 공장을 디아에 기증"],
  ["1999~2003", "기증 뒤 약 2년간의 개조 공사 — 로버트 어윈 · 오픈오피스"],
  ["2003", "봄 공사 완료 · 작품 설치 · 뉴욕주 공원 · 여가 · 역사보존청이 국가사적 등재 추천"],
  ["2003", "4월 18일 미국 국가사적 등재"],
  ["2003", "5월 18일 「디아:비컨, 리지오 갤러리」 개관"],
 ],
 "heritage": [
  ["미국 국가사적 (National Register of Historic Places, 2003)", "2003년 4월 18일 등재, 참조번호 03000253 — 등재명 「National Biscuit Company Carton Making and Printing Plant」. 기준: 사건 · 건축/공학, 분야: 건축 · 산업, 중요 연도 1929년", "https://npgallery.nps.gov/AssetDetail/NRIS/03000253"],
 ],
 "concept": [
  "디아는 \"원 구조의 성격을 그대로 지킨다\"는 원칙을 세웠습니다 — 높은 천장, 기둥 사이의 넓은 경간, 3만 4천 제곱피트가 넘는 천창이 그대로 전시 조건이 됩니다. 전시실 대부분은 천창 빛만으로 밝히고, 조명 · 난방 · 공조 · 경보 설비는 눈에 띄지 않게 숨겼습니다.",
  "한 전시실에는 한 작가만 둡니다. 여러 설치는 작가와 함께 만들었습니다 (도널드 저드 작품을 위해서는 전시실 지붕 높이를 올렸습니다).",
  "어윈의 마스터플랜은 건물과 경관을 한 덩어리로 다룹니다 — 사계절 모습이 다른 꽃나무 숲과 정형 정원, 진입 광장, 그리고 광장에서 전시실로 넘어가는 작은 파빌리온.",
 ],
 "strategy": {
  "keep": ["톱날 지붕의 북향 천창 (3만 4천 제곱피트 이상)과 높은 천장", "기둥 사이의 넓은 경간 · 철 · 콘크리트 · 유리의 공장 구조", "앞쪽 전시실의 나무 바닥과 뒤쪽의 콘크리트 바닥", "옛 열차 창고 (train shed) — 리처드 세라 대형 조각 전시실로"],
  "change": ["인쇄 공장 → 한 작가씩의 전시실", "옛 관리동 → 카페 · 서점 · 사무실", "도널드 저드 전시실의 지붕 높이를 올림"],
  "add": ["진입 광장과 전시실 사이의 작은 파빌리온 (어윈)", "꽃나무 숲 · 정형 정원 · 진입 마당 (어윈)", "보이지 않게 숨긴 조명 · 공조 · 경보 설비"],
 },
 "why": [
  "공장의 크기와 빛이 그대로 미술 체험이 된 사례입니다. 북향 천창은 앞쪽 전시실에 고른 빛을, 뒤쪽 고측창은 변하는 빛을 주어 회화와 조각에 맞는 두 가지 빛 환경이 생겼습니다.",
  "미술가가 건축가와 함께 마스터플랜을 짠 드문 미술관입니다 — 로버트 어윈이 경관 · 진입 동선 · 파빌리온을 맡았습니다.",
  "디아는 개관 당시 이 미술관을 \"뉴욕 현대미술관 (MoMA)이 1930년대 말 문을 연 뒤 미국에서 문을 연 가장 큰 미술관의 하나\"로 소개했습니다.",
 ],
 "space": [
  "앞쪽 구역 — 북향 천창이 고른 빛을 주어 회화 · 종이 작품에 맞습니다. 들어서면 월터 드 마리아 (Walter De Maria)의 「같은 면적 연작」이 좌우 대칭 두 전시실 한가운데 놓이고, 가장자리 전시실은 큰 공장 창의 직사광 아래 댄 플래빈 (Dan Flavin)의 형광등 작품 등을 둡니다. 앤디 워홀 「그림자」, 애그니스 마틴 「순수한 사랑」 연작도 이 구역에 있습니다.",
  "뒤쪽 구역 — 고측창의 변하는 빛과 콘크리트 바닥으로 조각에 맞습니다. 도널드 저드 (Donald Judd)의 합판 상자 15개, 바닥 속으로 약 20피트 파고든 마이클 하이저 (Michael Heizer)의 「북, 동, 남, 서」가 있습니다.",
  "옛 열차 창고에는 리처드 세라 (Richard Serra)의 「비틀린 타원」 세 점과 나선 한 점이 놓이고, 아래층에는 브루스 나우먼 (Bruce Nauman)의 영상 설치가 있습니다.",
 ],
 "material": [
  "디아는 원 건물을 \"철 · 콘크리트 · 유리로 지은 20세기 초 산업 건축의 모범\"으로 소개합니다. 톱날 지붕의 북향 천창과 고측창이 자연광을 끌어들입니다.",
  "개조는 새 재료를 더하기보다 숨기는 쪽이었습니다 — 조명 · 공조 · 경보 설비를 시야에서 감추고, 앞쪽은 나무 바닥, 뒤쪽은 콘크리트 바닥을 그대로 썼습니다.",
 ],
 "funding": [
  ["건물 기증 (1999)", "인터내셔널 페이퍼가 공장 건물을 디아에 기증 — 건축 자금도 일부 지원", "https://web.archive.org/web/2020/https://www.diaart.org/about/press/dia-completes-construction-of-new-museum-in-beacon-new-york/type/text"],
  ["총사업비", "5천만 달러 (뉴욕타임스 인용, 위키백과 디아 재단 항목)", "https://en.wikipedia.org/wiki/Dia_Art_Foundation"],
  ["후원 · 기부", "레너드 리지오 (Leonard Riggio, 디아 이사장) 최소 3,500만 달러 · 래넌 재단 (Lannan Foundation) 1,000만 달러 · 앤 테넌바움과 토머스 H. 리 250만 달러 — 미술관 이름 「리지오 갤러리」는 리지오 부부를 기림", "https://en.wikipedia.org/wiki/Dia_Art_Foundation"],
  ["공공 재원", "조지 파타키 주지사실 (엠파이어 스테이트 개발공사) · 더치스 카운티 산업개발청 · 비컨시 · 뉴욕주 공원 · 여가 · 역사보존청 · 뉴욕주 예술위원회가 기여 (금액은 공개되지 않음)", "https://web.archive.org/web/2020/https://www.diaart.org/about/press/dia-completes-construction-of-new-museum-in-beacon-new-york/type/text"],
 ],
 "famous": [
  "개관 당시 전시 면적 24만 제곱피트로, 디아는 \"MoMA 이후 미국에서 문을 연 가장 큰 미술관의 하나\"라고 소개했습니다.",
  "리처드 세라 · 도널드 저드 · 댄 플래빈 · 앤디 워홀 · 애그니스 마틴 등 1960년대 이후 미술을 작가마다 한 전시실에 상설로 두는 방식으로 이름났습니다.",
  "미술가 로버트 어윈이 건축가와 함께 공장 미술관의 마스터플랜을 짠 사례입니다.",
  "2003년 개관과 같은 해 공장 건물이 미국 국가사적에 올랐습니다.",
 ],
 "lesson": [
  "작품에 필요한 조건 (빛 · 크기 · 바닥)을 먼저 정하고, 공장 건물이 이미 가진 것 (천창 · 넓은 경간)을 고르면 개입을 최소로 줄일 수 있습니다.",
  "설비를 숨기고 원래 빛을 살리는 \"덜 하는 설계\"가 오히려 건물의 성격을 가장 강하게 드러냅니다.",
  "기부된 산업 건물 + 큰 개인 후원 + 주 · 지방 정부 지원의 조합이 소도시 대형 미술관을 가능하게 했습니다.",
 ],
 "operation": [
  ["운영 주체", "비영리 디아 미술재단 (법인명 Dia Center for the Arts, Inc.) — 비컨 외에 첼시 등 여러 장소를 함께 운영하므로 아래 재무는 재단 전체 수치", "https://projects.propublica.org/nonprofits/organizations/237397946"],
  ["수입 구성 (2022.7~2023.6 회계연도)", "총수입 약 3,721만 달러 중 기부 · 보조금 약 3,008만 달러 (약 81%), 사업 수입 (입장료 등) 약 207만 달러, 투자 수입 약 423만 달러, 부동산 임대 총수입 약 187만 달러, 물품 판매 약 47만 달러 — 미국 국세청 990 신고서", "https://projects.propublica.org/nonprofits/organizations/237397946"],
  ["지출 · 자산", "같은 해 총지출 약 2,019만 달러, 연말 순자산 약 2억 2,543만 달러 (990 신고서)", "https://projects.propublica.org/nonprofits/organizations/237397946"],
  ["공공 운영 보조금", "990 신고서의 정부 보조금 항목은 비어 있음 (별도 공개 수치 없음)", "https://projects.propublica.org/nonprofits/organizations/237397946"],
  ["입장료", "성인 25달러 · 65세 이상 18달러 · 학생 · 장애인 12달러 · 5~11세 5달러 · 5세 미만 무료, 비컨 · 뉴버그 주민과 회원 무료, 허드슨 밸리 주민은 매달 마지막 일요일 무료 (디아 공식 안내)", "https://welcome.diaart.org/"],
  ["비컨 운영 규모", "디아 비컨 운영과 급여에 연간 약 600만 달러 투자, 직원 약 100명 · 교육 작가 25명 — 2024년 1월 26일 디아 관장 제시카 모건의 뉴욕주 의회 예산 청문 서면 증언", "https://nyassembly.gov/write/upload/publichearing/001402/004999.pdf"],
  ["공공 운영 보조금", "뉴욕주 예술위원회 (NYSCA)가 해마다 일반 운영비를 지원 (금액 미공개) · 개관 때는 엠파이어 스테이트 개발공사가 개조를 도움 · 최근 주 재원으로 조경 사업 (같은 증언)", "https://nyassembly.gov/write/upload/publichearing/001402/004999.pdf"],
  ["시설 유지", "옥상 공조 설비 교체에 600만 달러 모금 · 외관 복원 · 화장실 개조 · 무료 입장 확대는 최근 기부로 진행 (같은 증언)", "https://nyassembly.gov/write/upload/publichearing/001402/004999.pdf"],
  ["지역 효과", "디아 비컨이 지역 관광으로 연간 약 800만 달러를 끌어들인다고 추정, 방문객의 75%가 45세 미만 (같은 증언)", "https://nyassembly.gov/write/upload/publichearing/001402/004999.pdf"],
 ],
 "operationNote": [
  "디아 비컨은 입장료보다 기부에 기대어 운영됩니다. 재단 전체 기준으로 2023 회계연도 수입의 약 81%가 기부 · 보조금이고, 입장료 등 사업 수입은 약 6%에 그칩니다. 큰 순자산 (약 2억 2,500만 달러)에서 나오는 투자 수입과 부동산 임대 수입이 이를 보탭니다.",
  "건물 자체가 1999년 인터내셔널 페이퍼의 기증이었고, 개조비 5천만 달러도 리지오 부부 · 래넌 재단 등 개인 · 재단 기부가 대부분이었습니다 — 건립과 운영 모두 기부 모델입니다.",
  "비컨 한 곳만 보면, 디아는 2024년 주의회 증언에서 운영과 급여에 연간 약 600만 달러를 쓰고 직원 약 100명을 둔다고 밝혔습니다. 주 예술위원회가 일반 운영비를 해마다 보태지만, 공조 설비 교체 (600만 달러) 같은 큰 유지 공사는 따로 모금해야 했습니다. 비컨 · 뉴버그 주민에게는 무료 입장을 넓혀 지역과의 관계를 유지합니다.",
 ],
 "missing": [
  "디아 비컨 한 곳만의 입장료 수입과 뉴욕주 예술위원회 운영 보조금 액수, 연간 방문객 수 (공식 수치)는 확인된 자료를 찾지 못했습니다.",
  "원 공장의 폐쇄 연도는 확인된 자료를 찾지 못했습니다.",
  "국가사적 등재 신청서 본문은 아직 디지털화되지 않아 (NPGallery) 원 건물의 층수 · 구조 상세는 확인하지 못했습니다.",
  "공사 시공사 · 구조 설계자는 확인된 자료를 찾지 못했습니다.",
 ],
 "refs": [
  {"t": "Dia Art Foundation — 2024 New York State Executive Budget 증언 (2024.1.26, 뉴욕주 의회)", "u": "https://nyassembly.gov/write/upload/publichearing/001402/004999.pdf"},
  {"t": "Dia Art Foundation — Visit (입장료)", "u": "https://welcome.diaart.org/"},
  {"t": "ProPublica Nonprofit Explorer — Dia Center for the Arts Inc (IRS 990)", "u": "https://projects.propublica.org/nonprofits/organizations/237397946"},
  {"t": "Dia Art Foundation 보도자료 — Dia Completes Construction of New Museum in Beacon, New York (웹 아카이브 사본)", "u": "https://web.archive.org/web/2020/https://www.diaart.org/about/press/dia-completes-construction-of-new-museum-in-beacon-new-york/type/text"},
  {"t": "NPGallery — National Biscuit Company Carton Making and Printing Plant (NRIS 03000253)", "u": "https://npgallery.nps.gov/AssetDetail/NRIS/03000253"},
  {"t": "Wikipedia — Dia Beacon", "u": "https://en.wikipedia.org/wiki/Dia_Beacon"},
  {"t": "Wikipedia — Dia Art Foundation", "u": "https://en.wikipedia.org/wiki/Dia_Art_Foundation"},
  {"t": "Roll Magazine — Sky light on modern art: Dia Beacon, Riggio Galleries", "u": "http://www.rollmagazine.com/archive/nov09/articles/art.php"},
  {"t": "Eat Drink See Architecture — Dia Beacon (OpenOffice and Robert Irwin)", "u": "https://www.eatdrinkseearchitecture.com/dia-beacon/"},
 ],
},

"mass-moca": {
 "from": "직물 날염 공장 (아널드 프린트 웍스) → 전자 부품 공장 (스프레이그 전기)",
 "to": "현대미술 · 공연 센터 (+ 임대 공간)",
 "y0": "1872 착공 · 1942 날염 종료 · 1985 스프레이그 철수",
 "archAbout": [
  "보스턴의 브루너/콧 (Bruner/Cott & Associates, 현 Bruner/Cott Architects)이 1992년 주 설계자로 선정되어, 1990년대 초 \"아직 상상되지 않은 미술관\"을 위한 마스터플랜에서 시작해 1999년 1단계, 2017년 6동 (3단계)까지 약 25년 넘게 단계적으로 고쳤습니다. 공동 설립자 시미언 브루너 (Simeon Bruner)가 이끌었습니다.",
  "원 공장은 매사추세츠 역사위원회 기록상 \"설계자 미상\"의 이탈리아풍 산업 건축입니다. 1871년 12월 27일 화재로 첫 공장 8동이 타 버린 뒤 1872년 지금의 본관 (4동)을 짓기 시작했고, 1900년까지 현존 건물의 약 90%가 세워졌습니다.",
 ],
 "spec": [
  ["원 건축물", "아널드 프린트 웍스 (Arnold Print Works) — 1872년 본관 착공, 1881~1903년 증축, 26동 (1985년 조사 당시 그중 2동만 근래 건물)"],
  ["원래 용도", "면직물 날염 (1860년대~1942) → 스프레이그 전기 (Sprague Electric) 전자 부품 공장 (1942~1985)"],
  ["고용", "아널드 1905년 약 3,200명 · 스프레이그 1966년 4,137명 (매스모카 공식 연혁)"],
  ["변경 용도", "현대미술 전시 · 공연 · 음악 축제 + 상업 임대 공간"],
  ["개조 설계", "브루너/콧 (Bruner/Cott & Associates) — 1992년 주 설계자 선정"],
  ["6동 협력 설계", "구조 아럽 (Arup) · 기계설비 피터슨 엔지니어링 · 시공관리 길베인 (Gilbane) · 조명 루멘 스튜디오 · 음향 어센테크"],
  ["운영", "매사추세츠 현대미술관 (MASS MoCA) — 초대 관장 조지프 C. 톰프슨 (1999~2021)"],
  ["개관", "1999년 (1단계, 전시실 19개 · 약 10만 제곱피트) → 2008년 7동 (솔 르윗 회고전 공간 2만 7천 제곱피트) → 2017년 5월 6동 (약 13만 제곱피트)"],
  ["대지", "후식강 (Hoosic River) 남 · 북 지류 사이 16에이커 (공식 연혁, 1985년 조사 기록은 약 24에이커)"],
  ["6동 공사비", "2,650만 달러 (2015년 가치, 제곱피트당 200달러 — 미국건축가협회 COTE 기록)"],
  ["수상", "6동 — 미국건축가협회 COTE 톱 10 (2024)"],
  ["위치", "미국 매사추세츠주 노스애덤스 마셜 거리 87 — 옛 도심 상업지구의 약 3분의 1을 차지"],
 ],
 "timeline": [
  ["1861", "하비 아널드 형제가 「하비 아널드 사」 설립 (남북전쟁 군복용 면직 수요)"],
  ["1871", "12월 27일 화재로 첫 공장 8동 전소"],
  ["1872", "지금의 본관 (4동) 착공 — 이후 1881~1903년 동 · 서로 증축"],
  ["1905", "직원 약 3,200명, 노스애덤스 최대 고용주"],
  ["1942", "날염 공장 폐쇄 (비컨 리얼티에 190만 달러에 매각) → 스프레이그 전기가 인수해 전자 부품 공장으로"],
  ["1966", "스프레이그 직원 4,137명"],
  ["1985", "스프레이그가 마셜 거리 공장 가동 중단 · 10월 25일 「아널드 프린트 웍스」 국가사적 등재"],
  ["1986", "윌리엄스 대학 미술관장 토머스 크렌스 (Thomas Krens) 등이 미술관 구상"],
  ["1988", "매사추세츠 주의회가 지원 의결 (WBUR — 주 채권 3,500만 달러)"],
  ["1992", "브루너/콧을 주 설계자로 선정"],
  ["1999", "매스모카 개관 (주 재원 3,500만 달러 + 민간 1,500만 달러)"],
  ["2008", "7동 확장 · 11월 솔 르윗 (Sol LeWitt) 벽화 회고전 공간 개관"],
  ["2014", "3월 주의회가 6동 공사비 2,540만 달러 승인"],
  ["2017", "5월 6동 (로버트 W. 윌슨 빌딩) 개관 — 전시 공간이 약 두 배로"],
 ],
 "heritage": [
  ["미국 국가사적 (National Register of Historic Places, 1985)", "1985년 10월 25일 「아널드 프린트 웍스 (Arnold Print Works)」로 등재, 참조번호 85003379 — 노스애덤스 다중 자원 지정 (North Adams MRA)의 하나, 분야: 산업, 중요 연도 1872년. 공식 연혁은 \"26동이 국가사적 목록에 올라 있다\"고 적습니다.", "https://npgallery.nps.gov/AssetDetail/NRIS/85003379"],
 ],
 "concept": [
  "\"미술관 안의 미술관\" — 26동의 공장 단지를 한꺼번에 고치지 않고, 마당 · 다리 · 시계탑이 있는 단지 구조를 그대로 둔 채 동마다 단계적으로 전시 · 공연 · 임대 공간을 채워 넣었습니다 (1999 · 2008 · 2017).",
  "6동에서 브루너/콧은 세 가지 방법을 썼습니다 — \"편집\" (기존 바닥 · 벽을 조각하듯 걷어 내고 그 재료를 다시 씀), \"엮기\" (1,000개가 넘는 기둥과 옛 요소 사이에 새 개입을 엮음), \"삽입\" (작품에 맞춘 전시 장치). 가장 중요한 방향 잡기 · 전이 공간을 새 재료를 더하지 않고 \"조각하듯 걷어 내어\" 만들었습니다.",
  "미술관이 대형 신작을 만들고 오래 전시하는 \"작업장\" 역할을 하고, 일부 건물은 상업 임대로 운영합니다.",
 ],
 "strategy": {
  "keep": ["26동의 벽돌 공장 · 덮개 있는 보행 다리 세 개 · 차량 다리 세 개 · 마당 · 시계탑", "벽돌 내력벽 · 아치 창 · 내쌓기 벽돌 처마", "6동의 드러난 벽돌 벽 · 큰 창 · 가는 주철 기둥 (1,000개 이상)", "6동 바닥 면적 100%를 재사용 · 1,200만 kg 이상의 재료를 제자리에"],
  "change": ["날염 · 전자 부품 공장 → 대형 전시실 · 공연장 · 임대 공간", "6동 — 바닥 일부를 걷어 내 층을 잇는 큰 전이 공간으로"],
  "add": ["작품별 맞춤 전시 장치", "걷어 낸 벽돌 · 구조 목재 · 마감 목재 (약 10만 kg)를 다시 짜 맞춘 계단 · 벽 · 마감", "에너지 성능 개선 (6동 실측 에너지 사용 강도 19.2 kBtu/sf/yr — 기준 대비 80% 낮음)"],
 },
 "why": [
  "1985년 최대 고용주가 떠난 소도시가 주 정부 재원과 민간 기부로 공장 단지를 문화 시설로 바꾼 \"산업도시 재생\"의 대표 사례입니다. WBUR 은 매스모카가 지역 경제에 \"연간 2천만 달러 이상\"을 가져온다고 전했습니다.",
  "한 건축가가 25년 넘게 같은 마스터플랜으로 단지를 단계적으로 채운 장기 리노베이션입니다 (1992 선정 → 1999 · 2008 · 2017).",
  "6동은 바닥 100% 재사용 · 걷어 낸 재료 재활용 · 기준 대비 80% 낮은 에너지 사용으로 2024년 미국건축가협회 COTE 톱 10 에 올랐습니다.",
 ],
 "space": [
  "단지는 후식강 남 · 북 지류 사이의 좁은 반도 위에 길게 늘어선 건물 줄과, 남쪽 지류 건너편의 작은 독립 건물들로 나뉘고, 덮개 있는 보행 다리 세 개와 차량 다리 세 개가 둘을 잇습니다. 마셜 거리 입구 쪽에 중심 마당이 있습니다.",
  "1999년 1단계는 전시실 19개 (약 10만 제곱피트)로 시작했고, 2008년 7동에 솔 르윗 벽화 회고전 공간 (2만 7천 제곱피트), 2017년 6동에 3개 층 약 13만 제곱피트의 전시 · 행사 공간이 더해졌습니다.",
  "6동은 강 두 지류가 만나는 곳에 \"뱃머리처럼\" 놓인 건물로, 영상 · 멀티미디어 전시 · 행사 · 작업장 · 수장 공간이 들어갔습니다 (로버트 라우션버그 · 루이즈 부르주아 · 제임스 터렐 · 제니 홀저 · 로리 앤더슨 등).",
 ],
 "material": [
  "원 건물은 19세기 후반의 전형적인 산업 건축 — 벽돌 내력벽, 아치형 창 머리, 내쌓기 벽돌 처마입니다. 본관 (4동, 1872)은 4층에 완만한 지붕, 1882년 염색동 (5동)은 1층이 돌입니다 (매사추세츠 역사위원회 기록).",
  "6동은 주철 기둥 · 목조 바닥 · 벽돌 벽의 구조를 그대로 쓰고, 새로 쓴 벽돌 · 구조 목재 · 마감 목재는 모두 같은 건물에서 걷어 낸 것입니다. 구조 설계는 아럽 (Arup)이 맡았습니다.",
 ],
 "funding": [
  ["공공 재원 (1988~1999)", "주의회가 1988년 지원 의결, 1999년 개관까지 주 재원 3,500만 달러 (WBUR)", "https://www.wbur.org/news/2014/03/06/mass-moca-double"],
  ["민간 기부 (1999)", "민간 1,500만 달러 (WBUR) — 공식 연혁은 민간이 800만 달러 이상의 대응 기금을 약속했다고 적음", "https://massmoca.org/about/history/"],
  ["보조금 (2014)", "6동 공사에 주 정부 2,540만 달러 승인 (2014년 3월) + 민간 모금 필요", "https://www.wbur.org/news/2014/03/06/mass-moca-double"],
  ["6동 공사비", "2,650만 달러 (2015년 가치, 제곱피트당 200달러) — 미국건축가협회 COTE 기록", "https://www.aia.org/design-excellence/award-winners/mass-moca-building-6"],
 ],
 "famous": [
  "2017년 6동 개관으로 전시 공간이 약 두 배가 되어, 미국에서 가장 큰 현대미술 · 공연 센터의 하나가 되었습니다 (WBUR · 공식 자료).",
  "1985년 스프레이그 전기 폐쇄로 일자리를 잃은 노스애덤스를 문화로 되살린 대표 사례로 꼽힙니다.",
  "솔 르윗 벽화 회고전 (2008)과 솔리드 사운드 음악 축제 (2010~) 같은 장기 프로그램으로 이름났습니다 (위키백과).",
  "6동이 2024년 미국건축가협회 COTE 톱 10 지속가능 설계상을 받았습니다.",
 ],
 "lesson": [
  "큰 공장 단지는 한 번에 고치지 말고 마스터플랜을 세워 재원이 생길 때마다 동별로 채워 가면, 30년에 걸쳐서도 일관된 결과를 얻을 수 있습니다.",
  "걷어 내는 것 자체가 설계가 될 수 있습니다 — 6동은 새 재료 대신 기존 재료를 \"편집\"해 공간을 만들었고, 그 결과 에너지 · 탄소 성능도 좋아졌습니다.",
  "주 정부의 초기 재원이 민간 기부를 끌어내는 마중물이 되었습니다.",
 ],
 "operation": [
  ["운영 주체", "비영리 매사추세츠 현대미술관 재단 (Massachusetts Museum of Contemporary Art Foundation, Inc.)", "https://projects.propublica.org/nonprofits/organizations/43113688"],
  ["수입 구성 (2022.10~2023.9 회계연도)", "총수입 약 2,181만 달러 중 기부 · 보조금 약 1,505만 달러 (약 69%), 사업 수입 (입장료 · 공연 등) 약 359만 달러, 부동산 임대 약 196만 달러, 투자 수입 약 113만 달러, 물품 판매 순수입 약 45만 달러 — 미국 국세청 990 신고서", "https://projects.propublica.org/nonprofits/organizations/43113688"],
  ["지출 · 자산", "같은 해 총지출 약 2,043만 달러, 연말 순자산 약 7,839만 달러", "https://projects.propublica.org/nonprofits/organizations/43113688"],
  ["임대 사업", "공장 단지 일부 건물을 상업 임대 — 990 신고서상 부동산 임대 수입 2021년 약 188만 · 2022년 약 200만 · 2023년 약 196만 달러", "https://projects.propublica.org/nonprofits/organizations/43113688"],
  ["입장료", "성인 25달러 · 65세 이상 · 참전 군인 22달러 · 학생 15달러 · 6~16세 10달러, 매사추세츠 저소득 지원 카드 소지자 2달러, 회원 · 5세 이하 무료 (공식 안내)", "https://massmoca.org/visit/"],
  ["공공 재원", "건립 · 확장은 주 정부 재원 (1999년까지 3,500만 달러, 2014년 6동 2,540만 달러)에 크게 기댔으나, 990 신고서의 정부 보조금 항목은 비어 있음"],
  ["운영 성과 (2023 · 2024 회계연도 평균)", "연간 방문객 약 17만 7천 명 · 연 수입 약 1,820만 달러 · 직원 약 170명 · 연간 시설 투자 약 67만 달러 — 케임브리지 이코노메트릭스 경제효과 보고서 (2025년 9월 15일 공개)", "https://massmoca.org/about/economic-impact/"],
  ["지역 경제 효과", "방문객이 버크셔 지역 업소에서 연간 약 3,340만 달러를 쓰고, 총 경제효과는 연간 약 8,350만 달러로 추정 (같은 보고서)", "https://massmoca.org/about/economic-impact/"],
 ],
 "operationNote": [
  "매스모카는 건물 공사는 주 정부 재원으로, 운영은 기부 (수입의 약 70%)와 입장료 · 공연 수입으로 이어 갑니다. 공장 단지라는 큰 부동산을 가진 덕에 일부 건물을 상업 임대로 내주어 해마다 약 200만 달러의 임대 수입을 얻는 점이 다른 미술관과 다릅니다.",
 ],
 "missing": [
  "임대 입주사 · 임대 면적은 확인된 자료를 찾지 못했습니다.",
  "1999년 1단계 · 2008년 확장의 공사비와 연면적 전체는 확인된 자료를 찾지 못했습니다.",
  "주민 수 등 노스애덤스 인구 통계는 열어 본 원문에서 확인하지 못해 뺐습니다.",
 ],
 "refs": [
  {"t": "MASS MoCA — Economic Impact (Cambridge Econometrics, 2025)", "u": "https://massmoca.org/about/economic-impact/"},
  {"t": "ProPublica Nonprofit Explorer — Massachusetts Museum of Contemporary Art Foundation (IRS 990)", "u": "https://projects.propublica.org/nonprofits/organizations/43113688"},
  {"t": "MASS MoCA — Visit (입장료)", "u": "https://massmoca.org/visit/"},
  {"t": "MASS MoCA — History (공식 연혁)", "u": "https://massmoca.org/about/history/"},
  {"t": "NPGallery — Arnold Print Works (NRIS 85003379)", "u": "https://npgallery.nps.gov/AssetDetail/NRIS/85003379"},
  {"t": "매사추세츠 역사위원회 조사표 — Arnold Print Works (NRHP 첨부 PDF, 1985)", "u": "https://npgallery.nps.gov/GetAsset/ea52b7db-2cde-410c-89a5-09d9e6474423"},
  {"t": "Wikipedia — Massachusetts Museum of Contemporary Art", "u": "https://en.wikipedia.org/wiki/Massachusetts_Museum_of_Contemporary_Art"},
  {"t": "WBUR — MASS MoCA Plans To Double Its Size With $25.4 Million From State (2014)", "u": "https://www.wbur.org/news/2014/03/06/mass-moca-double"},
  {"t": "AIA — COTE Top Ten: MASS MoCA Building 6", "u": "https://www.aia.org/design-excellence/award-winners/mass-moca-building-6"},
  {"t": "ArchDaily — MASS MoCA Building 6 / Bruner/Cott & Associates", "u": "https://www.archdaily.com/883699/mass-moca-building-6-bruner-cott-and-associates"},
  {"t": "Bruner/Cott — MASS MoCA Building 6 Opens", "u": "https://brunercott.com/mass-moca-building-6-opens/"},
 ],
},

"landschaftspark-duisburg": {
 "from": "제철소 (티센 마이데리히 제철소, 용광로)",
 "to": "산업유산 경관공원 (공원 · 다이빙 · 암벽 등반 · 공연 · 조명 예술)",
 "y0": "1901 착공 · 1903 첫 용광로 · 1985 폐쇄",
 "archAbout": [
  "독일 조경가 페터 라츠 (Peter Latz, 크란츠베르크)가 1989년 공고된 국제 공모 (유럽 여러 나라의 다섯 팀 참가)에서 1991년 5월 당선되어 계획과 실현을 맡았습니다. 라츠 + 파트너 (Latz + Partner)의 기록상 설계 · 실현 기간은 1990~2002년입니다.",
  "라츠는 산업 이용이 남긴 패턴과 조각들을 지우지 않고 다시 읽어 새로운 \"경관\"으로 엮는 방식을 썼습니다. 이 공원으로 2000년 제1회 유럽 조경상 로사 바르바상 (Rosa Barba)을 받았습니다.",
  "사업은 노르트라인베스트팔렌 주의 국제건축전시회 엠셔 파크 (IBA Emscher Park, 1989/1990~1999)의 대표 사업이었습니다.",
 ],
 "spec": [
  ["원 건축물", "마이데리히 제철소 — 1902년 아우구스트 티센 (August Thyssen)이 「제철 주식회사 (Aktiengesellschaft für Hüttenbetrieb)」로 설립, 1901년 착공"],
  ["원래 용도", "특수 선철 생산 — 84년간 3,700만 톤 (1903년 5월 16일 1호 용광로 화입 ~ 1985년)"],
  ["폐쇄", "3 · 4호 용광로 1968/1970년, 1 · 2호 1982년, 5호 1985년 정지"],
  ["변경 용도", "경관공원 — 5호 용광로 전망대, 가스탱크 다이빙장, 광석 벙커 정원 · 암벽 등반장 (약 400개 루트), 주조장 · 송풍기동 · 발전동 공연 · 행사장, 조명 예술"],
  ["개조 설계", "라츠 + 파트너 (Latz + Partner) — 1991년 국제 공모 당선"],
  ["협력", "조명 예술 — 조너선 파크 (Jonathan Park), 1996년 12월 점등"],
  ["건축주", "노르트라인베스트팔렌 주 개발공사 (LEG NRW) · 뒤스부르크시 · 엠셔 조합 (Emschergenossenschaft) · 루르 지역 연합 (KVR) — 라츠 + 파트너 기록"],
  ["운영", "1997년 시 소유 「경관공원 뒤스부르크-노르트 유한회사」 설립 → 2003년 뒤스부르크 마케팅 편입 → 현재 뒤스부르크 콘토어 홀 관리 유한회사의 사업 부문"],
  ["공모 · 공사", "1989년 공모 공고 · 1991년 5월 당선 · 1990~1999년 홀 · 건물 · 외부 공간 개조 (독일어 위키백과)"],
  ["개장", "1994년 6월 17일 첫 구역 개방"],
  ["면적", "약 180ha (독일어 위키백과) — 라츠 + 파트너는 200ha, 일부 매체는 230ha 로 적음"],
  ["사업비", "1,550만 유로 (Landezine 기준)"],
  ["방문객", "연평균 약 100만 명 · 2016년 1,019,391명 · 연간 약 250개 행사"],
  ["수상", "로사 바르바 유럽 조경상 (2000) · 그랑 메다유 뒤르바니슴 (2001) · EDRA 장소상 (2005) · 그린 굿 디자인상 (2009)"],
 ],
 "timeline": [
  ["1901", "제철소 착공 (1902년 아우구스트 티센이 회사 설립)"],
  ["1903", "5월 16일 1호 용광로 화입"],
  ["1968~1982", "3 · 4호 (1968/1970), 1 · 2호 (1982) 용광로 정지"],
  ["1985", "마지막 5호 용광로 정지 · 제철소 폐쇄"],
  ["1988", "국제건축전시회 엠셔 파크 (IBA) 출범 — 노르트라인베스트팔렌 주가 부지를 매입해 IBA 사업으로"],
  ["1989", "조경가 국제 공모 공고 (다섯 팀 참가)"],
  ["1991", "5월 페터 라츠 당선"],
  ["1992", "4월 뒤스부르크 시의회가 제철소 보존 결정 — 전문가 위원회는 철거 안 대부분이 보존보다 \"훨씬 비싸다\"고 판단"],
  ["1994", "6월 17일 첫 구역 개장"],
  ["1996", "12월 조너선 파크의 조명 설치 점등 · 1호 주조장 야외 극장 · 1996~1998년 가스탱크를 다이빙 센터로"],
  ["1997", "발전동을 행사장으로 개조 · 운영 회사 설립"],
  ["1999", "IBA 엠셔 파크 종료"],
  ["2002~2003", "송풍기동 · 주조장을 다목적 공연장으로 개조 · 1호 주조장에 투명 막 지붕"],
  ["2024", "2월 노르트라인베스트팔렌 「정원 기념물 (Gartendenkmal)」로 보호 지정 발표"],
 ],
 "heritage": [
  ["정원 기념물 (Gartendenkmal, 2024 발표)", "2022년 시행된 노르트라인베스트팔렌 새 기념물보호법이 만든 「정원 기념물」 범주로, 뒤셀도르프 지방정부가 기념물보호청의 평가를 거쳐 공원 전체와 그 안의 기반시설 · 산업 유구를 보호 대상으로 올렸습니다 (2024년 2월 7일 공원 보도자료). 피아차 메탈리카와 조너선 파크의 조명 설치도 평가 요소였습니다.", "https://www.landschaftspark.de/site/assets/files/31438/lp_pm_der_landschaftspark_ist_jetzt_gartendenkmal.pdf"],
 ],
 "concept": [
  "IBA 전문가 위원회는 제철소 설비를 살펴보고 \"철거 안 대부분이 보존보다 훨씬 비싸다\"고 결론 내렸고, 뒤스부르크 시의회는 1992년 4월 폐 제철소를 보존하기로 했습니다. 라츠의 안은 이 결정을 공원 설계로 옮긴 것입니다.",
  "공원은 서로 독립된 여러 \"층\"으로 짜였습니다 — 낮은 곳의 수로 공원, 높은 산책로가 된 철도 공원, 갈라졌던 동네를 다시 잇는 거리 높이의 산책로, 개별 정원 · 식생 덩어리. 철로 위에는 엔지니어들이 만든 대지 예술 \"레일 하프\"가 있습니다.",
  "하수로였던 옛 엠셔강 (Alte Emscher)을 빗물만으로 채우는 맑은 물길로 바꿨습니다. 빗물 · 배수 · 포장면 유출수를 저류조에 모아 여름 물 부족을 보충하고, 식물 여과를 거쳐 물길로 흘려보냅니다.",
 ],
 "strategy": {
  "keep": ["용광로 (5호는 오를 수 있는 전망대) · 가스탱크 · 광석 저장 벙커 · 발전동 · 송풍기동 · 주조장 · 냉각 설비", "철로 · 고가 철도 · 다리", "공정수 정화 설비 (다시 사용)", "제철소의 저절로 자란 식생"],
  "change": ["가스탱크 → 2만㎥ 물을 채운 다이빙장", "광석 벙커 → 벙커 정원 · 암벽 등반장", "주조장 · 송풍기동 · 발전동 → 공연 · 행사장", "하수로 옛 엠셔강 → 빗물로 채운 맑은 물길", "주물 틀을 덮던 철판 → 「피아차 메탈리카」 광장 바닥"],
  "add": ["조너선 파크의 야간 조명 설치 (1996, 2009년부터 LED 로 교체)", "빗물 저류 · 식물 여과 물 순환 체계", "고가 산책로 · 자전거 · 도보 네트워크", "공원 기차역 (2005)"],
 },
 "why": [
  "산업 폐허를 \"지우지 않고 다시 읽는\" 포스트 인더스트리얼 조경의 원형으로, 2000년 제1회 로사 바르바 유럽 조경상을 받았습니다.",
  "보존이 철거보다 싸다는 경제적 판단 (1992년 시의회 결정)에서 출발해, 오염 물질은 벙커 벽 안에 봉해 가두고 그 위를 정원으로 쓰는 등 설비 자체를 정화 · 놀이 시설로 바꿨습니다.",
  "개장 30년 만인 2024년 「정원 기념물」로 지정되어, 조경 작품 자체가 문화재가 된 드문 사례입니다.",
 ],
 "space": [
  "공원은 위아래로 겹친 층으로 읽힙니다 — 맨 아래 옛 엠셔강 수로 공원, 그 위 벙커 정원 (옛 소결 공장 · 광석 벙커 안에 높이와 깊이를 달리한 정원), 다시 그 위 고가 철도 산책로와 레일 하프, 가장 높은 곳 5호 용광로 전망대.",
  "가운데에 주철 판을 깐 피아차 메탈리카가 있고, 주변 주조장 · 송풍기동 · 발전동이 행사 공간으로 쓰입니다. 거리 높이의 산책로가 제철소로 갈라졌던 주변 동네를 다시 잇습니다.",
 ],
 "material": [
  "피아차 메탈리카는 선철 주조장에서 주물 틀을 덮던 철판을 깔아 만든 광장으로, 철판은 계속 녹슬고 닳아 갑니다.",
  "벙커 벽은 밀봉한 용기 속 옛 오염 물질, 굴토 흙, 물 또는 정원을 담습니다. 녹슨 철 · 콘크리트 · 제철 부산물을 그대로 재료로 씁니다.",
  "1호 주조장에는 2003년 투명 막 (공기 쿠션) 지붕을 씌워 공연장으로 쓰고, 조명 설치는 2009년부터 절전형 LED 로 바꿨습니다.",
 ],
 "funding": [
  ["부지 매입", "노르트라인베스트팔렌 주가 1988년 부지를 매입해 IBA 사업으로 지정 (금액 미확인)", "https://www.landschaftspark.de/en/background-knowledge/international-building-exhibition/"],
  ["공공 재원", "IBA 엠셔 파크는 노르트라인베스트팔렌 주 · 연방 정부 · 지방자치단체가 함께 추진 (공원별 분담액 미확인)", "https://www.landschaftspark.de/en/background-knowledge/international-building-exhibition/"],
  ["총사업비", "1,550만 유로 (Landezine 기록)", "https://landezine.com/post-industrial-landscape-architecture-latz-partner/"],
  ["공원 조성비 (다른 집계)", "15,338,800 유로, 공사 1992~2000년, 발주 뒤스부르크시 · IBA 엠셔 파크 (유럽 도시 공공공간상 기록)", "https://www.publicspace.org/works/-/project/a008-landschaftspark-duisburg-nord"],
 ],
 "famous": [
  "2000년 제1회 로사 바르바 유럽 조경상 등 국제 조경상을 여러 차례 받았습니다 (라츠 + 파트너).",
  "2015년 영국 「가디언」이 세계에서 가장 아름다운 공원 10곳의 하나로 꼽았습니다 (공원 연혁).",
  "연평균 약 100만 명이 찾고 (2016년 1,019,391명), 해마다 약 250개 행사가 열립니다.",
  "가스탱크 다이빙장 · 벙커 암벽 등반장 · 오를 수 있는 용광로처럼 설비를 그대로 놀이 시설로 바꾼 방식으로 이름났습니다.",
  "2024년 노르트라인베스트팔렌의 새 범주 「정원 기념물」로 지정되었습니다.",
 ],
 "lesson": [
  "철거 비용과 보존 비용을 먼저 비교하라 — 뒤스부르크는 \"철거가 더 비싸다\"는 판단에서 보존형 공원이 시작되었습니다.",
  "설비를 구경거리로만 두지 말고 오르고 · 잠수하고 · 등반하는 실제 쓰임을 주면 시민이 산업유산을 자기 것으로 받아들입니다.",
  "오염 물질을 모두 반출하지 않고 현장 구조물 안에 가두는 것도 하나의 설계 수단이 됩니다.",
 ],
 "operation": [
  ["운영 주체", "「뒤스부르크 콘토어 홀 관리 유한회사 (Duisburg Kontor Hallenmanagement GmbH)」의 한 사업 부문 — 1997년 시 소유 운영 회사로 출발", "https://www.landschaftspark.de/site/assets/files/37544/lp_pm_neues_besucherzentrum_im_landschaftspark_duisburg-nord.pdf"],
  ["입장료 · 주차", "공원은 연중 시간 제한 없이 무료 입장 · 정문 앞 무료 주차 1,500면 (공식 사이트)", "https://www.landschaftspark.de/"],
  ["수입 구성", "유료 안내 투어 (제철소 투어 · 횃불 투어 등)와 행사 입장권 판매 (공식 사이트 일정), 연간 약 250개 행사 — 금액은 미확인", "https://www.landschaftspark.de/"],
  ["공공 보조 (시설 투자)", "새 방문자 센터 (옛 중앙 계측실) 사업비 390만 유로 중 310만 유로 (80%)를 EU 지역개발기금 · 공정전환기금 (EFRE/JTF) 노르트라인베스트팔렌 2021~2027 프로그램이 부담, 20%는 운영사 자부담 — 2028년까지 개조 (2025.10.20 보도자료)", "https://www.landschaftspark.de/site/assets/files/37544/lp_pm_neues_besucherzentrum_im_landschaftspark_duisburg-nord.pdf"],
  ["운영 성과", "연평균 약 120만 명 방문 · 연간 약 250개 행사 (2025년 보도자료)", "https://www.landschaftspark.de/site/assets/files/37544/lp_pm_neues_besucherzentrum_im_landschaftspark_duisburg-nord.pdf"],
  ["토지 · 건물", "공원 부지는 노르트라인베스트팔렌 「루르 토지기금 (Grundstücksfonds Ruhr/NW)」과 맺는 점유 이전 계약에 따라 운영사가 관리 — 운영사의 공원 업무: 공원 조성 계속 · 부동산 관리 · 행사 유치로 \"비용 충당 개선\" · 공공 보조금의 신탁 관리 (뒤스부르크시 2018 지분 보고서)", "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/85935/Beteiligungsbericht-2018.pdf"],
  ["운영사 재무 (2018, 회사 전체)", "뒤스부르크 콘토어 홀 관리 (자본금 68만 유로, 시 100%): 매출 541.5만 유로 + 기타 영업수익 379.8만 유로 = 영업수익 921.3만 유로, 영업비용 1,411.1만 유로 → 시 보조금 477.5만 유로로 결손 전액 보전 (2016년 452.8만 · 2017년 625.8만 유로). 머카토르할레 등 다른 홀 포함 수치", "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/85935/Beteiligungsbericht-2018.pdf"],
  ["자립도 (2018, 회사 전체)", "영업수익 ÷ 영업비용 = 약 65% (921.3만 ÷ 1,411.1만 유로, 위 보고서로 계산) — \"결손은 시 재정이 허락하는 한 시가 보전\"", "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/85935/Beteiligungsbericht-2018.pdf"],
  ["시 보조금 (2024, 회사 전체)", "뒤스부르크시 보조금 811.9만 유로 · 평균 직원 48.5명 (2024년 지분 연차 개요)", "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/109221/Jahresuebersicht-2024Gesamtdokument.pdf"],
  ["대관 실적 (사용일)", "2024년 공원 시설별 사용일 — 발전동 (Kraftzentrale) 153일 · 송풍기동 59일 · 주조장 20일 · 야외 120일 · 옛 제철 창고 (Hüttenmagazin) 89일 · 기타 64일 (2023년 각 117 · 171 · 48 · 220 · 125 · 99일)", "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/109221/Jahresuebersicht-2024Gesamtdokument.pdf"],
 ],
 "operationNote": [
  "공원 자체는 입장료도 주차료도 받지 않습니다. 운영은 뒤스부르크 콘토어 홀 관리 회사가 맡고, 유료 투어와 행사가 자체 수입원입니다. 큰 시설 투자는 EU · 주 정부 보조금에 기댑니다 — 예컨대 2025년 확정된 방문자 센터 사업비 390만 유로의 80%가 EU 기금입니다.",
  "운영사 (뒤스부르크 콘토어 홀 관리)는 공원과 머카토르할레 등 시 행사장을 함께 운영하며, 해마다 결손을 시가 보조금으로 메웁니다 — 2018년 477.5만 유로 (영업수익으로 비용의 약 65% 충당), 2024년 811.9만 유로. 부지는 주의 루르 토지기금 소유로, 운영사가 계약에 따라 관리합니다.",
 ],
 "missing": [
  "시 보조금 · 수입 가운데 경관공원 부문만의 금액은 공개 자료에서 따로 나뉘지 않아 확인하지 못했습니다 (운영사 전체 수치만 확인).",
  "부지 매입가와 주 · 연방 재원 분담액은 확인된 자료를 찾지 못했습니다.",
  "1994년 이전 제철소 건물의 개별 문화재 (건축 기념물) 지정 여부 · 연도는 확인된 자료를 찾지 못했습니다.",
  "공모에 참가한 다른 네 팀의 이름은 확인된 자료를 찾지 못했습니다.",
  "식물을 이용한 토양 정화 (식물 정화)는 열어 본 원문에서 확인하지 못해 뺐습니다.",
 ],
 "refs": [
  {"t": "Stadt Duisburg — Beteiligungsbericht 2018 (뒤스부르크 콘토어 홀 관리)", "u": "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/85935/Beteiligungsbericht-2018.pdf"},
  {"t": "Stadt Duisburg — Jahresübersicht Beteiligungsunternehmen, Berichtsjahr 2024", "u": "https://www.duisburg.de/vv/produkte/pro_du/dez_i/20/jahresuebersicht.php.media/109221/Jahresuebersicht-2024Gesamtdokument.pdf"},
  {"t": "Public Space — Landschaftspark Duisburg-Nord", "u": "https://www.publicspace.org/works/-/project/a008-landschaftspark-duisburg-nord"},
  {"t": "Landschaftspark Duisburg-Nord — Neues Besucherzentrum (2025.10.20 보도자료 PDF)", "u": "https://www.landschaftspark.de/site/assets/files/37544/lp_pm_neues_besucherzentrum_im_landschaftspark_duisburg-nord.pdf"},
  {"t": "Landschaftspark Duisburg-Nord — 공식 사이트 (입장 · 주차 안내)", "u": "https://www.landschaftspark.de/"},
  {"t": "Wikipedia (독일어) — Landschaftspark Duisburg-Nord", "u": "https://de.wikipedia.org/wiki/Landschaftspark_Duisburg-Nord"},
  {"t": "Landschaftspark Duisburg-Nord — Chronik (공원 연혁 보도자료 PDF)", "u": "https://www.landschaftspark.de/site/assets/files/6892/0000_chronologie.pdf"},
  {"t": "Landschaftspark Duisburg-Nord — Der Landschaftspark ist jetzt Gartendenkmal! (2024.2.7 보도자료 PDF)", "u": "https://www.landschaftspark.de/site/assets/files/31438/lp_pm_der_landschaftspark_ist_jetzt_gartendenkmal.pdf"},
  {"t": "Landschaftspark Duisburg-Nord — International Building Exhibition (배경 지식)", "u": "https://www.landschaftspark.de/en/background-knowledge/international-building-exhibition/"},
  {"t": "Latz + Partner — Duisburg Nord Landscape Park", "u": "https://www.latzundpartner.de/en/projekte/postindustrielle-landschaften/landschaftspark-duisburg-nord-de/"},
  {"t": "Landezine — Landschaftspark Duisburg Nord by Latz + Partner", "u": "https://landezine.com/post-industrial-landscape-architecture-latz-partner/"},
  {"t": "Urban Green-Blue Grids — Landscape park Duisburg-Nord", "u": "https://urbangreenbluegrids.com/projects/landscape-park-duisburg-nord/"},
 ],
},

"yokohama-red-brick": {
 "from": "세관 보세 창고 (신코 부두 보세 창고)",
 "to": "문화 시설 (1호관) · 상업 시설 (2호관)",
 "y0": "1911 · 1913 준공 · 1989 창고 용도 폐지",
 "archAbout": [
  "원 건축물은 대장성 임시건축부 (大蔵省臨時建築部, 부장 쓰마키 요리나카 (妻木頼黄))가 설계했습니다. 쓰마키는 메이지 건축계의 \"3대 거장\"으로 꼽히는 관청 건축가입니다. 2호관은 직영, 1호관은 하라키 센노스케 (原木仙之助)가 시공했습니다.",
  "보존 · 활용 개수는 신이 지아키 도시건축설계 (新居千秋都市建築設計)가 설계하고, 구조 설계는 TIS & PARTNERS 가 맡았습니다. 시공은 1호관이 다케나카 공무점 · 고마쓰 공무점 공동기업체, 2호관이 다케나카 공무점입니다.",
 ],
 "spec": [
  ["원 건축물", "신코 부두 보세 창고 (新港埠頭保税倉庫) — 2호관 1907년 착공 · 1911년 준공, 1호관 1908년 착공 · 1913년 준공"],
  ["원 설계", "대장성 임시건축부 (부장 쓰마키 요리나카 (妻木頼黄))"],
  ["구조", "벽돌 조적조 일부 철골조 — 일본어 위키백과 · 건설신문은 지상 3층, 요코하마시 인정 기록은 \"벽돌조 2층\"으로 적음. 벽돌 사이에 철재를 넣은 보강"],
  ["규모", "전체 길이 약 150m · 연면적 17,163㎡ (1호관 5,575㎡ · 2호관 10,755㎡) · 국산 벽돌 636만 개"],
  ["원래 용도", "세관 보세 창고 (1945~1956년경 연합군 접수 · 1989년 창고 용도 폐지)"],
  ["변경 용도", "1호관 — 홀 · 전시 등 문화 시설, 2호관 — 상점 · 레스토랑"],
  ["개조 설계", "신이 지아키 도시건축설계 (新居千秋都市建築設計) · 구조 TIS & PARTNERS"],
  ["시공", "1호관 다케나카 공무점 · 고마쓰 공무점 JV, 2호관 다케나카 공무점"],
  ["건축주", "요코하마시 (1992년 국가로부터 취득)"],
  ["운영", "1호관 — 요코하마시 예술문화진흥재단, 2호관 — (주)요코하마 아카렌가 (横浜赤レンガ)"],
  ["공사 기간", "1994~1999년 보존 공사 → 2000년 활용을 위한 내부 개수 착수 → 2002년 3월 준공"],
  ["개장", "2002년 4월 12일"],
  ["수상", "2010년 유네스코 아시아 · 태평양 문화유산 보전상 우수상"],
  ["위치", "일본 요코하마시 나카구 신코 1-1 (新港1-1) — 미나토미라이 21 신코 지구"],
 ],
 "timeline": [
  ["1899", "요코하마항 2기 축항 공사 시작 — 신코 부두 조성"],
  ["1911", "2호관 준공 (메이지 44)"],
  ["1913", "1호관 준공 (다이쇼 2)"],
  ["1923", "9월 1일 간토 대지진 — 1호관 가운데 부분이 무너짐 (약 30% 손괴)"],
  ["1930년경", "복구 공사 완료 · 1호관은 절반 길이로 줄어듦"],
  ["1945", "종전 뒤 연합군 (GHQ)이 접수해 미군 항만사령부로 사용"],
  ["1956년경", "접수 해제 · 항만 창고로 재가동"],
  ["1989", "창고 용도 폐지"],
  ["1992", "요코하마시가 국가로부터 토지 · 건물 취득"],
  ["1994~1999", "보존 공사 — 기와 14만 장 전면 교체 · 창 · 차양 복원 · 낙서 제거 · 철골 보강"],
  ["2000~2002", "활용을 위한 내부 개수 · 2002년 3월 요코하마시 인정 역사적 건조물"],
  ["2002", "4월 12일 「요코하마 아카렌가 창고」 개장 (그해 방문객 569만 명)"],
  ["2010", "유네스코 아시아 · 태평양 문화유산 보전상 우수상"],
  ["2019", "누적 방문객 1억 명 돌파"],
 ],
 "heritage": [
  ["요코하마시 인정 역사적 건조물 (横浜市認定歴史的建造物, 2002)", "2002년 3월 인정 — 요코하마시 역사를 살린 마을 만들기 제도에 따른 시 인정. 국가 지정 문화재 (중요문화재 등)는 아닙니다.", "https://www.city.yokohama.lg.jp/naka/kurashi/machizukuri_kankyo/machizukuri/rekiken/n01.html"],
  ["근대화 산업유산 (近代化産業遺産, 2007)", "경제산업성 인정 (법적 규제가 아닌 인정 제도)", "https://www.yokohama-akarenga.jp/about/history/"],
 ],
 "concept": [
  "\"보존을 넘어 적극적으로 활용하며 지킨다\" — 시가 먼저 1994~1999년에 보존 공사 (지붕 · 창 · 구조 보강)를 끝내고, 그 뒤 2000년부터 쓰임에 맞춘 내부 개수를 따로 해 두 단계로 나눴습니다.",
  "두 동의 성격을 나눴습니다. 작은 1호관 (5,575㎡)은 시 예술문화진흥재단이 홀 · 전시 등 문화 사업을, 큰 2호관 (10,755㎡)은 민간이 상업 시설을 운영합니다. 두 동 사이와 앞의 광장이 연중 행사 무대가 됩니다.",
 ],
 "strategy": {
  "keep": ["붉은 벽돌 외벽 (장소마다 다른 네 종류의 벽돌 — 지하 과소성 벽돌, 바깥 면 연마 벽돌, 실내 보통 벽돌, 창대 검은 벽돌)", "뒷면의 철골 발코니 · 벽돌 사이 철재 보강 구조", "지진 뒤 반으로 줄어든 1호관의 모습"],
  "change": ["보세 창고 → 1호관 문화 시설 · 2호관 상업 시설", "기와 14만 장 전면 교체 · 부식된 창과 차양 복원"],
  "add": ["벽돌 벽에 에폭시 수지 주입 (1호관 5만 개소 · 2호관 7만 5천 개소)으로 벽 전체 강도를 높이는 보강", "철골 보강", "문화 · 상업 시설을 위한 내부 설비 · 동선"],
 },
 "why": [
  "간토 대지진 · 전쟁 · 미군 접수 · 방치를 거친 메이지 말 벽돌 창고를 시가 사들여 보존 공사와 활용 개수를 단계적으로 마친 사례로, 2010년 유네스코 아시아 · 태평양 문화유산 보전상 우수상을 받았습니다.",
  "벽돌 벽에 에폭시 수지를 주입해 \"벽 전체의 강도를 높이는 새로운 방법\"으로 겉모습을 바꾸지 않고 보강했습니다 (건설신문).",
  "개장 첫해 569만 명, 2019년 누적 1억 명이 찾은 요코하마의 대표 장소가 되었습니다.",
 ],
 "space": [
  "길이 약 150m 의 두 동이 광장을 사이에 두고 나란히 섭니다. 1호관은 지진 피해 복구 때 절반으로 줄어 2호관보다 짧습니다.",
  "1호관은 공연 · 전시 홀 등 문화 시설, 2호관은 층마다 상점 · 레스토랑이 들어선 상업 시설입니다.",
 ],
 "material": [
  "벽돌 조적조 일부 철골조로, 국산 벽돌 636만 개가 쓰였습니다. 벽돌 사이에 철재를 넣는 보강 덕분에 간토 대지진 때 2호관은 피해가 적었습니다.",
  "보존 공사에서는 기와 14만 장을 모두 다시 이고, 부식된 창 · 차양을 복원하고, 철골로 보강했습니다. 활용 개수에서는 1호관 5만 개소, 2호관 7만 5천 개소에 에폭시 수지를 주사하듯 주입해 벽돌 벽 전체를 굳혔습니다.",
 ],
 "funding": [
  ["공공 매입 · 보존", "요코하마시가 1992년 국가로부터 토지 · 건물 취득, 1994~1999년 시 보존 공사 (금액 미확인)", "https://www.city.yokohama.lg.jp/kanko-bunka/minato/taikan/asobu/spot/red-renga/hozon/preservation.html"],
  ["운영 구조", "(주)요코하마 미나토미라이 21 이 1 · 2호관을 임대받아, 1호관은 시 예술문화진흥재단, 2호관은 민간 사업자가 운영 (건설신문)", "https://www.kensetsunews.com/web-kan/765116"],
  ["보존 사업비 (개략)", "\"약 10년의 시간과 수십억 엔\"이 들었다고 현지 매체가 전함 — 정확한 금액은 미공개", "https://shin-yoko.net/2022/12/05/mm21-6/"],
  ["토지 취득 방식", "요코하마시가 국가 (대장성)와의 토지 교환으로 취득 — 당시 시 담당자 엔도 가네쓰구의 2019년 강연 기록", "https://s36213fcafaae67fb.jimcontent.com/download/version/1584692280/module/10749720379/name/%EF%BC%92%EF%BC%90%EF%BC%91%EF%BC%99%EF%BC%8E%EF%BC%94%EF%BC%8E%EF%BC%91%EF%BC%90%EF%BC%8E%E9%81%A0%E8%97%A4%E5%8C%85%E5%97%A3%E8%AC%9B%E6%BC%94%E8%A8%98%E9%8C%B2%E3%83%BB%E5%85%AC%E9%96%8B%E8%B3%87%E6%96%99.pdf"],
 ],
 "famous": [
  "2010년 유네스코 아시아 · 태평양 문화유산 보전상 우수상을 받았습니다.",
  "개장 첫해 569만 명, 2011년 5천만 명, 2019년 누적 1억 명 방문 (공식 연혁).",
  "메이지 건축의 거장 쓰마키 요리나카가 설계한 메이지 말 · 다이쇼 초의 벽돌 창고로, 간토 대지진을 견딘 보강 구조로 알려졌습니다.",
  "2007년 경제산업성 근대화 산업유산으로 인정되었습니다.",
 ],
 "lesson": [
  "\"보존 공사\"와 \"활용 개수\"를 나눠, 먼저 지붕 · 창 · 구조를 지키고 쓰임은 나중에 정하는 단계적 방식이 공공 소유 유산에 맞습니다.",
  "겉모습을 바꾸지 않는 보강법 (에폭시 주입 · 숨은 철골)이 벽돌 조적 유산의 내진 문제를 푸는 열쇠입니다.",
  "공공 문화동과 민간 상업동을 나눠 운영하면 공공성과 사업성을 함께 지킬 수 있습니다.",
 ],
 "operation": [
  ["토지 · 건물 임대 구조", "소유자 요코하마시 → (주)요코하마 미나토미라이 21 이 1 · 2호관을 임차 → 1호관은 요코하마시 예술문화진흥재단, 2호관은 민간 사업자가 운영 (건설신문)", "https://www.kensetsunews.com/web-kan/765116"],
  ["2호관 운영사", "(주)요코하마 아카렌가 — 2000년 7월 설립, 자본금 20억 9천만 엔, 사업: 상업시설 운영 · 행사 기획 · 주차장 경영, 주요 주주 미쓰비시상사 도시개발 (공식 회사 개요)", "https://www.yokohama-akarenga.jp/company/"],
  ["수입 · 이익 (2023.4~2024.3)", "(주)요코하마 아카렌가 매출 25억 6,800만 엔 · 영업이익 7억 1,100만 엔 · 당기순이익 5억 8,300만 엔, 순자산 30억 7,600만 엔 — 제24기 결산공고 (gBizINFO)", "https://info.gbiz.go.jp/hojin/financialstatement?kessanJohoId=5453b76b-a6c4-48b9-96ac-d1afb88c515c"],
  ["1호관 운영", "공익재단법인 요코하마시 예술문화진흥재단이 문화 사업 (홀 · 전시) 운영 (일본어 위키백과 · 건설신문)"],
  ["운영 성과", "개장 첫해 569만 명 · 2019년 누적 1억 명 방문 (공식 연혁)", "https://www.yokohama-akarenga.jp/about/history/"],
  ["사업자 공모", "2호관 운영자 공모에 3개 그룹이 응모, 기린 중심으로 기린 · 삿포로 등 4개사가 연합한 그룹이 선정 → 이 그룹의 운영 회사 ((주)요코하마 아카렌가)가 요코하마 미나토미라이 21 로부터 2호관을 임차해 점포 임대 운영 (엔도 강연 기록)", "https://s36213fcafaae67fb.jimcontent.com/download/version/1584692280/module/10749720379/name/%EF%BC%92%EF%BC%90%EF%BC%91%EF%BC%99%EF%BC%8E%EF%BC%94%EF%BC%8E%EF%BC%91%EF%BC%90%EF%BC%8E%E9%81%A0%E8%97%A4%E5%8C%85%E5%97%A3%E8%AC%9B%E6%BC%94%E8%A8%98%E9%8C%B2%E3%83%BB%E5%85%AC%E9%96%8B%E8%B3%87%E6%96%99.pdf"],
  ["1호관 · 광장", "1호관 1층에 요코하마 연고 점포 5곳을 미나토미라이 21 이 관리 · 운영, 두 동 사이 광장은 시로부터 관리 위탁 (엔도 강연 기록)", "https://s36213fcafaae67fb.jimcontent.com/download/version/1584692280/module/10749720379/name/%EF%BC%92%EF%BC%90%EF%BC%91%EF%BC%99%EF%BC%8E%EF%BC%94%EF%BC%8E%EF%BC%91%EF%BC%90%EF%BC%8E%E9%81%A0%E8%97%A4%E5%8C%85%E5%97%A3%E8%AC%9B%E6%BC%94%E8%A8%98%E9%8C%B2%E3%83%BB%E5%85%AC%E9%96%8B%E8%B3%87%E6%96%99.pdf"],
  ["2022년 재단장", "개업 20년 만의 첫 대규모 개수 뒤 2022년 12월 재개장 — 점포 66곳 (2호관 55 · 1호관 11), 그중 25곳 교체. 코로나 이전 연간 방문객 약 500만 명 (신요코하마 지역 매체)", "https://shin-yoko.net/2022/12/05/mm21-6/"],
 ],
 "operationNote": [
  "시가 소유한 건물을 요코하마 미나토미라이 21 이 빌리고, 상업동 (2호관)은 미쓰비시상사 도시개발이 주요 주주인 민간 회사가 점포 임대 · 행사 · 주차장으로 운영합니다. 이 회사는 2023 회계연도에 매출 약 25.7억 엔, 순이익 약 5.8억 엔을 냈습니다. 문화동 (1호관)은 시 예술문화진흥재단이 맡아, 수익동과 공공 문화동을 나눈 구조입니다.",
 ],
 "missing": [
  "시에 내는 임대료 액수와 1호관 문화 사업의 보조금 · 수지는 확인된 자료를 찾지 못했습니다.",
  "보존 공사비 · 개수 공사비의 정확한 금액은 확인된 자료를 찾지 못했습니다 (\"수십억 엔\"이라는 매체 표현만 확인).",
  "국가 지정 문화재 (중요문화재 · 등록유형문화재) 지정은 확인된 자료를 찾지 못했습니다 — 시 인정 역사적 건조물입니다.",
  "층수는 자료마다 2층 / 3층으로 달라 확정하지 못했습니다.",
 ],
 "refs": [
  {"t": "新横浜新聞 — 商業施設化から20年の「横浜赤レンガ倉庫」、初の大改修を終えリニューアル (2022.12.5)", "u": "https://shin-yoko.net/2022/12/05/mm21-6/"},
  {"t": "遠藤包嗣 — 赤レンガ倉庫・保存活用事業について (2019 강연 기록, NPO 田村明記念・まちづくり研究会)", "u": "https://s36213fcafaae67fb.jimcontent.com/download/version/1584692280/module/10749720379/name/%EF%BC%92%EF%BC%90%EF%BC%91%EF%BC%99%EF%BC%8E%EF%BC%94%EF%BC%8E%EF%BC%91%EF%BC%90%EF%BC%8E%E9%81%A0%E8%97%A4%E5%8C%85%E5%97%A3%E8%AC%9B%E6%BC%94%E8%A8%98%E9%8C%B2%E3%83%BB%E5%85%AC%E9%96%8B%E8%B3%87%E6%96%99.pdf"},
  {"t": "横浜赤レンガ倉庫 — 会社概要 (株式会社横浜赤レンガ)", "u": "https://www.yokohama-akarenga.jp/company/"},
  {"t": "gBizINFO — 株式会社横浜赤レンガ 第24期決算公告 (2024.6.27)", "u": "https://info.gbiz.go.jp/hojin/financialstatement?kessanJohoId=5453b76b-a6c4-48b9-96ac-d1afb88c515c"},
  {"t": "Wikipedia (일본어) — 横浜赤レンガ倉庫", "u": "https://ja.wikipedia.org/wiki/横浜赤レンガ倉庫"},
  {"t": "横浜市 — 赤レンガ倉庫 (認定歴史的建造物)", "u": "https://www.city.yokohama.lg.jp/naka/kurashi/machizukuri_kankyo/machizukuri/rekiken/n01.html"},
  {"t": "横浜市 — 赤レンガ倉庫の保存", "u": "https://www.city.yokohama.lg.jp/kanko-bunka/minato/taikan/asobu/spot/red-renga/hozon/preservation.html"},
  {"t": "横浜赤レンガ倉庫 — 歴史 (공식)", "u": "https://www.yokohama-akarenga.jp/about/history/"},
  {"t": "建設通信新聞 — 【記念シリーズ・横浜市公共建築】第50回 横浜赤レンガ倉庫", "u": "https://www.kensetsunews.com/web-kan/765116"},
 ],
},

"coal-drops-yard": {
 "from": "철도 석탄 하역장 (이후 창고 · 유리병 공장 · 나이트클럽)",
 "to": "쇼핑 · 레스토랑 · 행사 거리",
 "y0": "동 1851~52 · 서 1859~60 건설",
 "archAbout": [
  "헤더윅 스튜디오 (Heatherwick Studio, 토머스 헤더윅)가 2014년 아전트 (Argent)에게 설계를 의뢰받아 킹스크로스 센트럴 재개발의 일부로 설계했습니다. 실시 설계 · 설비는 BAM 디자인이 맡았습니다.",
  "원 건축물 중 동쪽 하역장은 Historic England 등재 기록상 \"아마도 루이스 큐빗 (Lewis Cubitt)\"의 설계입니다. 큐빗은 1850년대 킹스크로스역과 화물 야적장 (Goods Yard)을 함께 지은 건축가로, 그레너리 (Granary) 건물을 중심으로 한 이탈리아풍 실용 건축 언어를 썼습니다.",
 ],
 "spec": [
  ["원 건축물", "동쪽 석탄 하역장 (Eastern Coal Drops) — 1851~52년 · 서쪽 석탄 하역장 (Western Coal Drops) — 1859~60년"],
  ["원 설계", "루이스 큐빗 (Lewis Cubitt, 동쪽 하역장 — \"아마도\")"],
  ["원래 용도", "북동부 · 요크셔 석탄을 높은 철로 위 화차에서 아래 저장고로 쏟아 마차에 싣던 하역 시설"],
  ["이후 용도", "1876년 동쪽 하역장을 유리병 회사 배글리 와일드 사가 사들임 · 19세기 말 남쪽을 창고로 개조 · 서쪽은 1897~99년 일반 화물 창고로 · 1985년 화재 · 나이트클럽 「배글리스 (Bagley's)」 2008년 폐업"],
  ["변경 용도", "상점 · 레스토랑 · 바 · 카페 · 행사 공간 — 약 60개 점포 (약 17㎡ ~ 1,800㎡ 이상)"],
  ["개조 설계", "헤더윅 스튜디오 (Heatherwick Studio) — 2014년 위촉"],
  ["협력", "구조 아럽 (Arup) · 시공 · 실시 설계 BAM · 문화유산 자문 자일스 쿼미 어소시에이츠 (Giles Quarme & Associates) · 설비 호어 리 (Hoare Lea) · 조명 스피어스 앤드 메이저 · 사인 홈스 우드 · 비용 G+T"],
  ["건축주", "아전트 (Argent) — 킹스크로스 센트럴 개발"],
  ["공사 기간", "2015년 12월 계획 허가 · 2016년 2월 착공 · 2018년 여름 준공"],
  ["개관", "2018년 10월 26일"],
  ["면적", "상업 면적 약 9,290㎡ (10만 제곱피트) · 헤더윅 기록상 연면적 13,500㎡"],
  ["공사비", "약 1억 파운드"],
  ["수상", "RIBA 런던상 · RIBA 국가상 · 영국 구조공학회 구조 변형상 · 영국 토목학회 배절젯 지속가능상 (2019)"],
  ["위치", "영국 런던 캠던구 킹스크로스 — 리전트 운하 북쪽, 그레너리 광장 옆"],
 ],
 "timeline": [
  ["1851~52", "동쪽 석탄 하역장 건설 — 높은 철로 네 줄 아래 저장고 · 마차 하역칸"],
  ["1859~60", "서쪽 석탄 하역장 건설 — 큰 주철 보로 높은 철로를 받치는 단순화된 방식"],
  ["1865", "두 하역장 사이로 플림솔 고가 (Plimsoll Viaduct)와 운하 다리 건설 (1920년대 벽돌 · 콘크리트로 재건)"],
  ["1876", "동쪽 하역장을 유리병 회사 배글리 와일드 사에 매각"],
  ["1897~99", "서쪽 하역장을 일반 화물 창고로 전환"],
  ["1983", "7월 27일 동쪽 하역장 2등급 (Grade II) 등재"],
  ["1985", "동쪽 하역장 북쪽 부분 화재"],
  ["2008", "나이트클럽 배글리스 폐업"],
  ["2012", "킹스크로스 마스터플랜 (앨리스 앤드 모리슨)에 따라 플림솔 고가 철거 — 서쪽 하역장의 옛 주철 고가가 드러남"],
  ["2014", "헤더윅 스튜디오 위촉"],
  ["2015", "12월 계획 허가"],
  ["2016", "2월 착공"],
  ["2018", "10월 26일 콜 드롭스 야드 개장"],
  ["2019", "RIBA 국가상 등 수상"],
 ],
 "heritage": [
  ["2등급 등재 건축물 (Listed Building Grade II, 1983)", "동쪽 석탄 하역장 (Eastern Coal Drops at Kings Cross Goods Yard) — 1983년 7월 27일 첫 등재, 등재번호 1379214. 「계획 (등재 건축물 · 보존지구) 법 1990」에 따른 보호", "https://historicengland.org.uk/listing/the-list/list-entry/1379214"],
  ["리전트 운하 보존지구 (Regent's Canal Conservation Area)", "서쪽 석탄 하역장은 개별 등재되지 않았고, 보존지구에 \"긍정적으로 기여하는 건물\"로 분류됩니다 (2024년 문화유산 보고서)"],
 ],
 "concept": [
  "나란히 비스듬히 선 두 하역장의 안쪽 박공지붕을 늘여 올려 서로를 향해 뻗게 하고, 가운데에서 맞닿게 해 새 위층을 만들었습니다 (\"키스하는 지붕\"). 그 아래에는 지붕 덮인 2층 높이의 야외 공간이, 위에는 런던을 내려다보는 유리 공간이 생겼습니다.",
  "새 지붕은 옛 건물에 하중을 얹지 않는 완전히 독립된 새 구조가 받칩니다 — 옛 건물 안에 박아 넣은 50여 개의 강철 기둥 (BAM 52개 · 위키백과 54개)과 강관 말뚝.",
  "1920년대 플림솔 고가를 걷어 내고 동쪽 하역장 고가의 폭을 일부 줄여, 마당 높이에서 남북으로 곧게 걷는 길과 남쪽으로 넓어지는 광장을 만들었습니다. 이 땅은 역사상 처음으로 일반에게 열렸습니다.",
 ],
 "strategy": {
  "keep": ["두 동의 빅토리아 시대 벽돌 하역장과 붙은 철도 고가 · 워프 로드 고가 일부", "동쪽 하역장의 주철 기둥 · 보 골조, 벽돌 아케이드, 목조 지붕 트러스", "서쪽 하역장의 주철 고가", "화강석 포석 마당 · 계류 기둥 · 철도 흔적"],
  "change": ["석탄 하역 · 창고 · 클럽 → 상점 · 레스토랑 · 행사 공간", "벽돌 아치 아래 → 매장 · 오락 공간", "가운데 공공 공간의 바닥을 약 1m 낮춤"],
  "add": ["가운데에서 맞닿는 새 지붕과 그 아래 떠 있는 새 위층 (약 1,900㎡)", "독립 강철 기둥 · 강관 말뚝 · 폭 35m 지붕 구조", "위층의 높이 8m 맞춤 유리", "두 건물 1,000m 길이의 기초 보강 (언더피닝)"],
 },
 "why": [
  "등재 건축물 두 동을 손대지 않고 그 사이에 \"한 동작\"의 새 지붕을 올려 하나의 장소로 묶은 대담한 개입입니다 — 새 구조가 옛 건물과 독립되어 옛 골조에 무게를 얹지 않습니다.",
  "2019년 RIBA 국가상, 영국 구조공학회 구조 변형상, 영국 토목학회 배절젯 지속가능상을 받아 건축 · 구조 · 지속가능성 세 분야에서 인정받았습니다.",
  "철거 현장에서 나온 벽돌을 되살려 쓰고 (BAM: 30만 개 중 75% 이상 회수), 지붕은 옛 지붕과 같은 웨일스산 슬레이트로 이었습니다.",
 ],
 "space": [
  "마당 (야드) 높이와 고가 높이의 두 층으로 읽힙니다. 마당 높이에서는 두 하역장 사이 길이 남북으로 곧게 이어지고 남쪽으로 넓은 광장이 열리며, 고가 높이에서는 옛 철로 자리를 따라 상점이 이어집니다.",
  "맞닿은 지붕 아래 가장 높은 층에 큰 매장 하나가 들어가고, 그 아래는 비를 피하는 2층 높이의 열린 행사 공간이 됩니다. 매장 크기는 약 17㎡ (180 제곱피트)부터 1,800㎡ 이상까지 다양합니다.",
  "북쪽 워프 로드 고가 (지금의 배글리 워크)에서 두 하역장과 새 지붕을 내려다보는 시선이 주요 조망입니다.",
 ],
 "material": [
  "동쪽 하역장은 여러 색의 런던 스톡 벽돌을 안팎의 주철 기둥 · 보 골조가 받치고, 슬레이트 모임지붕 아래 목조 트러스 (목재 보 · 서까래 · 버팀대에 철봉 · 연철 판 · 주철 까치발)가 있습니다. 실내에는 위층 철로와 저장고를 받치던 굵은 목조 골조가 남아 있습니다 (Historic England 등재 기록).",
  "서쪽 하역장은 큰 주철 보로 높은 철로를 받치는 더 단순한 방식입니다.",
  "새 지붕은 강철 구조에 웨일스 북부산 슬레이트 8만 장 이상을 이었습니다 (170년 전과 같은 광맥). 켄트 · 서식스에서 회수한 벽돌 30만 개를 보수에 썼습니다 (Building).",
 ],
 "funding": [
  ["총사업비", "약 1억 파운드 (Building 지, 위키백과)", "https://www.building.co.uk/news/in-pictures-heatherwicks-100m-coal-drops-yard-opens-its-doors/5096191.article"],
  ["민간 투자", "아전트 (Argent)가 킹스크로스 센트럴 개발의 일부로 발주"],
 ],
 "famous": [
  "토머스 헤더윅의 \"키스하는 지붕\" — 두 빅토리아 시대 건물의 지붕이 늘어나 맞닿는 형태로 널리 알려졌습니다.",
  "2019년 RIBA 런던상 · 국가상, 구조공학회 · 토목학회 상을 받았습니다 (위키백과).",
  "킹스크로스 재개발 (그레너리 광장 · 가스홀더 등)의 마지막 큰 퍼즐로, 화물 야적장 땅을 역사상 처음 공공에 열었습니다.",
  "개장 때 연간 1,200만 명 방문이 예상되었습니다 (Building).",
 ],
 "lesson": [
  "옛 건물이 약할 때는 새 구조를 독립시켜 \"옛 건물 위에 얹지 않고 옆에서 받치는\" 방식으로 큰 개입도 가능합니다.",
  "등재 건물과 비등재 기여 건물을 함께 다루면서, 나중 시대의 덧붙임 (1920년대 플림솔 고가)을 걷어 내 더 오래된 층을 드러내는 선택이 공간과 유산 가치를 함께 높였습니다.",
  "같은 산지의 재료 (웨일스 슬레이트 · 런던 벽돌)를 쓰면 대담한 새 형태도 옛 건물과 이어져 보입니다.",
 ],
 "operation": [
  ["소유 · 운영", "킹스크로스 단지는 킹스크로스 센트럴 유한 파트너십 (KCCLP — 연금기금 오스트레일리안 슈퍼와 페더레이티드 허미스 고객사로 구성)이 소유, 개발 · 운영은 릴레이티드 아전트 (Related Argent) (공식 사이트)", "https://relatedargent.co.uk/places/kings-cross/"],
  ["수입 구성", "공공 운영 보조 없는 민간 상업 임대 — 약 60개 점포 (상점 · 식당 · 바 · 카페)의 임대료가 중심 (점포 수는 2024 문화유산 보고서)"],
  ["단지 규모", "킹스크로스 전체 67에이커 · 새로 짓거나 고친 건물 50동 · 새 주택 1,750호 · 상점 · 식당 100곳 · 열린 공간 26에이커 (릴레이티드 아전트)", "https://relatedargent.co.uk/places/kings-cross/"],
  ["운영 성과", "개장 때 연간 1,200만 명 방문 예상 (Building)"],
  ["개장 초 문제 (2019)", "개장 6개월 뒤 일부 입점 업체가 \"10시간 동안 손님 8명\" 등 낮은 방문객 수를 호소 (Drapers, 2019년 4월 10일) — 브랜드 구성이 너무 고급이고 위치가 고립되었다는 지적", "https://www.drapersonline.com/news/coal-drops-yard-retailers-horrified-at-footfall"],
  ["회복 성과", "매출 2022년 전년 대비 48% · 2023년 20% 증가, 방문객 수 (footfall) 2022년 34% · 2023년 21% 증가 (킹스크로스 공식 보도자료, 2024년 5월 31일)", "https://www.kingscross.co.uk/press/2024/05/31/uniqlo-joins-coal-drops-yard"],
  ["임대 성과", "2024년 유니클로가 3개 층 약 1만 2천 제곱피트 임차 — 2018년 개장 뒤 가장 큰 임대 계약. 이후 18~24개월에 걸쳐 1층 공간 약 17곳을 새로 임대 예정 (같은 보도자료)", "https://www.kingscross.co.uk/press/2024/05/31/uniqlo-joins-coal-drops-yard"],
 ],
 "operationNote": [
  "콜 드롭스 야드는 공공 보조금이 아닌 연금기금 자본으로 운영되는 민간 상업 시설입니다. 킹스크로스 단지 소유 파트너십이 점포 임대료로 수입을 얻고, 상업 시설은 사무 · 주거 · 대학이 모인 단지 전체의 매력을 높이는 공공 공간 역할도 합니다.",
  "개장 초에는 방문객이 적어 입점 업체의 불만이 컸지만 (2019), 2021~2023년 매출과 방문객이 해마다 크게 늘었고 2024년 유니클로 대형 임대로 상업 구성을 넓혔습니다. 고급 브랜드 위주에서 대중 브랜드 · 식음료로 구성을 바꾸며 임대 사업을 안정시킨 사례입니다.",
 ],
 "missing": [
  "콜 드롭스 야드 단독의 임대 수입 · 입점률 · 연간 방문객 절대 수는 확인된 자료를 찾지 못했습니다 (증가율만 확인).",
  "공공 재원 · 보조금은 확인된 자료를 찾지 못했습니다 (민간 개발).",
  "서쪽 석탄 하역장의 원 설계자는 확인된 자료를 찾지 못했습니다.",
  "강철 기둥 수는 자료마다 52개 (BAM) / 54개 (위키백과)로 달라 \"50여 개\"로 적었습니다.",
 ],
 "refs": [
  {"t": "King's Cross — UNIQLO to join Coal Drops Yard (2024.5.31 보도자료)", "u": "https://www.kingscross.co.uk/press/2024/05/31/uniqlo-joins-coal-drops-yard"},
  {"t": "Drapers — Coal Drops Yard retailers 'horrified' at footfall (2019)", "u": "https://www.drapersonline.com/news/coal-drops-yard-retailers-horrified-at-footfall"},
  {"t": "Related Argent — King's Cross redevelopment", "u": "https://relatedargent.co.uk/places/kings-cross/"},
  {"t": "Historic England — Eastern Coal Drops at Kings Cross Goods Yard (List Entry 1379214)", "u": "https://historicengland.org.uk/listing/the-list/list-entry/1379214"},
  {"t": "King's Cross Central — Coal Drops Yard, Pavilion to Southern Yard: Heritage Statement (2024.7)", "u": "https://friendsofregentscanal.org/features/property-devt/Kings-Cross/Coal-Drops/docs/Heritage-Statement.pdf"},
  {"t": "Heatherwick Studio — Coal Drops Yard", "u": "https://heatherwick.com/projects/buildings/coal-drops-yard/"},
  {"t": "BAM — Coal Drops Yard, King's Cross", "u": "https://www.bam.co.uk/case-studies/coal-drops-yard-kings-cross"},
  {"t": "Building — In pictures: Heatherwick's £100m Coal Drops Yard opens its doors", "u": "https://www.building.co.uk/news/in-pictures-heatherwicks-100m-coal-drops-yard-opens-its-doors/5096191.article"},
  {"t": "Wikipedia — Coal Drops Yard", "u": "https://en.wikipedia.org/wiki/Coal_Drops_Yard"},
 ],
},
}
