# -*- coding: utf-8 -*-
# 건축가 노트 1/3 — ArchDaily 에 자주 나오는 건축가·사무소
# 각 항목: id · name(원어) · ko · kind(인물/사무소) · who(대표 인물) · country · years · pritzker
#          wiki(영문 위키백과 제목 — 사진용) · life[] · theory[{h,p}] · works[{t,ko,y,at,p,wiki}]
A = [
{
 "id": "snohetta", "name": "Snøhetta", "ko": "스뇌헤타", "kind": "사무소",
 "who": "Kjetil Trædal Thorsen · Craig Dykers", "country": "노르웨이 · 미국", "years": "1989 설립 (오슬로)",
 "pritzker": None, "wiki": "Snøhetta (company)",
 "life": [
  "1989년 오슬로에서 노르웨이 건축가 셰틸 트레달 토르센과 미국 건축가 크레이그 다이커스 등이 모여 만든 설계 집단입니다. 이름은 노르웨이 중부의 산(Snøhetta)에서 따왔습니다 — 특정 개인이 아니라 \"산처럼 함께 짓는 공동체\"라는 뜻을 담았습니다.",
  "첫 작품이 국제 공모로 따낸 이집트 알렉산드리아 도서관(2002)이었고, 오슬로 오페라하우스(2008)로 세계적 이름을 얻었습니다. 지금은 오슬로·뉴욕·파리·홍콩 등에 사무소를 두고 건축·조경·인테리어·그래픽을 한 팀이 함께 하는 \"전 분야 통합\" 방식으로 일합니다.",
 ],
 "why": "무명 신생 팀이 첫 작품으로 알렉산드리아 도서관 국제 공모(523개 팀)를 따낸 \"신데렐라 스토리\"로 등장했고, 지붕 위를 시민이 걸어 다니는 오슬로 오페라하우스가 \"건축이 곧 공공 광장\"이라는 새 모델을 보여 주며 세계적 사무소가 되었습니다.",
 "nat": "노르웨이", "person": "스뇌헤타", "firm": "Snøhetta",
 "theory": [
  {"h": "건축과 조경의 경계 지우기", "p": "건물을 땅의 연장으로 봅니다. 오슬로 오페라하우스의 지붕은 사람이 걸어 올라가는 광장이 되고, 건물은 풍경 속에 \"누워\" 있습니다."},
  {"h": "공공성 — 모두가 올라설 수 있는 건축", "p": "문턱을 낮추고 누구나 쓸 수 있는 공공 공간을 우선합니다. 비싼 문화시설도 시민이 그냥 걸어 들어오는 장소가 되게 합니다."},
  {"h": "초학제(trans-disciplinary) 협업", "p": "건축가·조경가·디자이너가 직급과 분야를 섞어 한 테이블에서 설계합니다. 역할을 바꿔 보는 \"트랜스포지셔닝\" 워크숍으로 유명합니다."},
  {"h": "에너지 플러스와 지역성", "p": "Powerhouse 프로젝트처럼 쓰는 것보다 많은 에너지를 만드는 건물, 북유럽 자연과 재료(돌·나무)에 뿌리를 둔 디자인을 추구합니다."},
 ],
 "works": [
  {"t": "Bibliotheca Alexandrina", "ko": "알렉산드리아 도서관", "y": 2002, "at": "이집트 알렉산드리아", "p": "지중해를 향해 기울어진 거대한 원반 지붕 — 고대 도서관의 부활", "wiki": "Bibliotheca Alexandrina"},
  {"t": "Oslo Opera House", "ko": "오슬로 오페라하우스", "y": 2008, "at": "노르웨이 오슬로", "p": "바다에서 솟은 빙하처럼 지붕 위를 걸어 오르는 공공 광장", "wiki": "Oslo Opera House"},
  {"t": "National September 11 Memorial Museum Pavilion", "ko": "9·11 메모리얼 박물관 파빌리온", "y": 2014, "at": "미국 뉴욕", "p": "그라운드 제로의 입구, 기울어진 유리와 줄무늬 외피", "wiki": "National September 11 Memorial & Museum"},
  {"t": "Under", "ko": "언더 (해저 레스토랑)", "y": 2019, "at": "노르웨이 린데스네스", "p": "바닷속으로 기울어 잠긴 유럽 최초의 해저 레스토랑", "wiki": "Under (restaurant)"},
  {"t": "Norwegian Wild Reindeer Centre Pavilion", "ko": "노르웨이 야생순록센터 파빌리온", "y": 2011, "at": "노르웨이 도브레", "p": "바위를 깎은 듯한 나무 덩어리 안쪽, 바깥은 강철 상자", "wiki": "Snøhetta (company)"},
 ],
},
{
 "id": "oma", "name": "OMA · Rem Koolhaas", "ko": "OMA · 렘 콜하스", "kind": "사무소",
 "who": "Rem Koolhaas (1944~)", "country": "네덜란드", "years": "1975 설립 (런던 → 로테르담)",
 "pritzker": 2000, "wiki": "Rem Koolhaas",
 "life": [
  "렘 콜하스는 1944년 로테르담에서 태어나 기자와 시나리오 작가로 먼저 일했습니다. 런던 AA 스쿨에서 건축을 배운 뒤 1975년 엘리아 젠겔리스 등과 OMA(Office for Metropolitan Architecture)를 세웠습니다.",
  "1978년 책 『광기의 뉴욕(Delirious New York)』으로 맨해튼의 과밀을 찬양하는 \"회고적 선언\"을 내놓아 이론가로 먼저 이름을 알렸습니다. 2000년 프리츠커상을 받았고, 연구 조직 AMO를 따로 두어 건축 밖의 도시·미디어·정치 연구를 함께 합니다. 하버드 GSD 교수로 도시 연구를 이끌었습니다.",
 ],
 "why": "건물보다 책과 이론으로 먼저 유명해진 드문 건축가 — 『광기의 뉴욕』 『S,M,L,XL』이 한 세대 건축가들의 생각을 바꿨고, 시애틀 도서관·CCTV 같은 \"기존 유형을 뒤집는\" 작품으로 현대 건축 담론의 중심이 되었습니다. 그의 사무소 출신(BIG·MVRDV·자하 하디드 등)이 세계 건축계를 이끌고 있다는 점도 큽니다.",
 "nat": "네덜란드", "person": "렘 콜하스", "firm": "OMA",
 "theory": [
  {"h": "과밀의 문화 (Culture of Congestion)", "p": "도시의 밀도와 뒤섞임을 문제가 아니라 창조의 조건으로 봅니다. 한 건물 안에 서로 다른 프로그램을 쌓아 \"수직 도시\"를 만듭니다."},
  {"h": "빅니스 (Bigness)", "p": "일정 규모를 넘은 건물은 건축의 규칙이 아니라 도시의 규칙을 따른다는 주장 — 『S,M,L,XL』(1995)에서 펼쳤습니다."},
  {"h": "프로그램이 형태를 만든다", "p": "기능의 배치와 동선(다이어그램)에서 출발해 형태를 끌어냅니다. 시애틀 도서관은 기능 덩어리를 쌓고 어긋나게 한 결과입니다."},
  {"h": "정크스페이스 (Junkspace)", "p": "공항·쇼핑몰처럼 끝없이 이어지는 현대의 무정형 공간을 비판적으로 분석했습니다."},
 ],
 "works": [
  {"t": "Kunsthal", "ko": "쿤스트할", "y": 1992, "at": "네덜란드 로테르담", "p": "경사로가 관통하는 전시장 — 동선이 곧 건축", "wiki": "Kunsthal"},
  {"t": "Seattle Central Library", "ko": "시애틀 중앙도서관", "y": 2004, "at": "미국 시애틀", "p": "기능 덩어리를 어긋나게 쌓고 유리 그물로 감싼 도서관", "wiki": "Seattle Central Library"},
  {"t": "CCTV Headquarters", "ko": "CCTV 본사", "y": 2012, "at": "중국 베이징", "p": "두 탑이 공중에서 꺾여 만나는 고리 모양의 초고층", "wiki": "CCTV Headquarters"},
  {"t": "Casa da Música", "ko": "카사 다 무지카", "y": 2005, "at": "포르투갈 포르투", "p": "다면체 콘크리트 덩어리 속 공연장", "wiki": "Casa da Música"},
  {"t": "Leeum, Samsung Museum of Art (Child Education Center)", "ko": "리움 미술관 (어린이교육문화센터)", "y": 2004, "at": "한국 서울", "p": "마리오 보타 · 장 누벨과 함께 지은 리움의 블랙 콘크리트 동", "wiki": "Leeum, Samsung Museum of Art"},
 ],
},
{
 "id": "mvrdv", "name": "MVRDV", "ko": "MVRDV", "kind": "사무소",
 "who": "Winy Maas · Jacob van Rijs · Nathalie de Vries", "country": "네덜란드", "years": "1993 설립 (로테르담)",
 "pritzker": None, "wiki": "MVRDV",
 "life": [
  "OMA 출신의 비니 마스, 야코프 반 레이스, 나탈리 드 브리스가 1993년 로테르담에서 세 사람의 이름 머리글자로 만든 사무소입니다.",
  "노인 주택 WoZoCo(1997)의 공중에 매달린 세대들, 하노버 엑스포 네덜란드관(2000)의 \"쌓아 올린 풍경\"으로 단숨에 주목받았습니다. 연구 조직 The Why Factory(델프트 공대)를 통해 미래 도시의 밀도·데이터를 연구하며, 서울로 7017(2017)로 한국과도 인연이 깊습니다.",
 ],
 "why": "법규·수치 같은 \"재미없는 조건\"을 끝까지 밀어붙여 놀라운 형태를 만드는 방법론(데이터스케이프)과, 공중에 매달린 세대 같은 파격적 첫 작품으로 1990년대 \"슈퍼 더치\" 붐의 주역이 되었습니다.",
 "nat": "네덜란드", "person": "MVRDV", "firm": "MVRDV",
 "theory": [
  {"h": "데이터스케이프 (Datascape)", "p": "법규·일조·밀도 같은 수치 조건을 끝까지 밀어붙여 그 자체로 형태를 만듭니다 — 책 『FARMAX』."},
  {"h": "쌓기와 밀도", "p": "도시의 땅이 부족하면 풍경·공원·주거를 수직으로 쌓습니다. 하노버 엑스포관은 숲·밭·바람을 층층이 쌓은 건물입니다."},
  {"h": "유쾌함과 색", "p": "강렬한 색과 장난스러운 형태로 사람들의 참여와 소셜미디어 속 \"화제성\"을 만드는 데 능합니다."},
  {"h": "재생과 재사용", "p": "서울로 7017처럼 낡은 기반시설을 공원으로 바꾸는 작업, 데포 보이만스처럼 공개 수장고를 만드는 실험."},
 ],
 "works": [
  {"t": "WoZoCo", "ko": "보조코 노인주택", "y": 1997, "at": "네덜란드 암스테르담", "p": "일조 규정 때문에 공중으로 튀어나온 세대들", "wiki": "WoZoCo"},
  {"t": "Expo 2000 Netherlands Pavilion", "ko": "하노버 엑스포 네덜란드관", "y": 2000, "at": "독일 하노버", "p": "숲·밭·물을 층층이 쌓은 풍경 건축", "wiki": "Netherlands Pavilion, Expo 2000"},
  {"t": "Markthal", "ko": "마크트할", "y": 2014, "at": "네덜란드 로테르담", "p": "아치형 주거동이 감싼 거대한 실내 시장", "wiki": "Markthal Rotterdam"},
  {"t": "Seoullo 7017", "ko": "서울로 7017", "y": 2017, "at": "한국 서울", "p": "서울역 고가도로를 보행 정원으로 바꾼 재생 사업", "wiki": "Seoullo 7017"},
  {"t": "Depot Boijmans Van Beuningen", "ko": "데포 보이만스 반 뵈닝언", "y": 2021, "at": "네덜란드 로테르담", "p": "도시가 비치는 거울 그릇 — 세계 최초의 공개 수장고", "wiki": "Depot Boijmans Van Beuningen"},
 ],
},
{
 "id": "big", "name": "BIG · Bjarke Ingels", "ko": "BIG · 비아케 잉엘스", "kind": "사무소",
 "who": "Bjarke Ingels (1974~)", "country": "덴마크", "years": "2005 설립 (코펜하겐)",
 "pritzker": None, "wiki": "Bjarke Ingels",
 "life": [
  "1974년 코펜하겐에서 태어나 만화가를 꿈꾸다 건축으로 진로를 바꿨습니다. OMA에서 일한 뒤 PLOT을 거쳐 2005년 BIG(Bjarke Ingels Group)을 세웠습니다.",
  "산처럼 쌓은 주거 「마운틴 드웰링스」(2008), 8자 모양 주거 「8 하우스」(2010)로 주목받았고, 뉴욕 VIA 57 West, 구글 사옥, 쓰레기 소각장 위 스키장 「코펜힐」 등으로 세계적 스타 건축가가 되었습니다. 책·만화 형식의 『Yes is More』로 생각을 대중적으로 풀어냅니다.",
 ],
 "why": "어려운 건축을 만화·다이어그램·짧은 영상으로 쉽게 설명하는 소통 능력, 스키장을 얹은 발전소처럼 \"말이 되는 엉뚱함\"으로 대중과 기업 모두에게 사랑받는 스타 건축가가 되었습니다. 30대에 뉴욕·런던에 진출한 속도도 화제였습니다.",
 "nat": "덴마크", "person": "비아케 잉엘스", "firm": "BIG",
 "theory": [
  {"h": "실용적 유토피아 (Pragmatic Utopia)", "p": "현실의 제약(예산·법규·기능)을 받아들이되 그것을 비틀어 이상적인 결과를 만든다는 태도."},
  {"h": "Hedonistic Sustainability", "p": "지속가능성은 희생이 아니라 즐거움이어야 한다 — 발전소 지붕에서 스키를 타는 코펜힐이 대표 사례."},
  {"h": "Yes is More", "p": "반대보다 \"예\"에서 출발해 상충하는 요구를 모두 끌어안는 진화적 설계."},
  {"h": "다이어그램 건축", "p": "쉽게 설명되는 한 장의 다이어그램에서 형태를 끌어내 대중과 소통합니다."},
 ],
 "works": [
  {"t": "8 House", "ko": "8 하우스", "y": 2010, "at": "덴마크 코펜하겐", "p": "자전거로 꼭대기까지 오르는 8자형 복합 주거", "wiki": "8 House"},
  {"t": "VIA 57 West", "ko": "비아 57 웨스트", "y": 2016, "at": "미국 뉴욕", "p": "유럽식 중정 주거와 뉴욕 고층의 혼합 — \"코트스크레이퍼\"", "wiki": "Via 57 West"},
  {"t": "CopenHill (Amager Bakke)", "ko": "코펜힐", "y": 2019, "at": "덴마크 코펜하겐", "p": "폐기물 발전소 지붕 위의 스키장과 암벽", "wiki": "Amager Bakke"},
  {"t": "LEGO House", "ko": "레고 하우스", "y": 2017, "at": "덴마크 빌룬", "p": "레고 블록을 쌓은 듯한 체험관", "wiki": "Lego House (Billund)"},
  {"t": "Google Bay View", "ko": "구글 베이뷰 캠퍼스", "y": 2022, "at": "미국 마운틴뷰", "p": "용 비늘 같은 태양광 지붕의 사옥 (헤더윅과 협업)", "wiki": "Google Bay View"},
 ],
},
{
 "id": "adjaye", "name": "Adjaye Associates · David Adjaye", "ko": "데이비드 아자예", "kind": "인물",
 "who": "David Adjaye (1966~)", "country": "가나 · 영국", "years": "1966 탄자니아 다르에스살람 출생",
 "pritzker": None, "wiki": "David Adjaye",
 "life": [
  "가나 외교관 가정에서 태어나 아프리카·중동 여러 나라에서 자랐고, 런던 사우스뱅크 대학과 왕립예술대학(RCA)에서 건축을 공부했습니다.",
  "2000년 런던에 사무소를 열어 예술가들의 집과 작업실로 시작했고, 워싱턴 D.C.의 국립 아프리카계 미국인 역사문화박물관(2016)으로 세계적 명성을 얻었습니다. 2017년 영국 기사 작위를 받고 2021년 RIBA 로열 골드 메달 수상자로 선정되었으나, 2023년 직장 내 문제 의혹이 제기되어 여러 직위에서 물러났습니다.",
 ],
 "why": "아프리카 출신 건축가로서 흑인 역사·정체성을 다루는 국가적 박물관(NMAAHC)을 맡아, 서구 중심 건축계에서 새로운 목소리와 상징을 만든 점으로 주목받았습니다.",
 "nat": "영국 · 가나", "person": "데이비드 아자예", "firm": "Adjaye Associates",
 "theory": [
  {"h": "아프리카 건축의 재발견", "p": "아프리카 53개국 도시를 10년간 사진으로 기록한 연구(『African Metropolitan Architecture』)를 바탕으로, 지역의 기후·재료·형태 언어를 현대 건축으로 옮깁니다."},
  {"h": "재료의 물성과 빛", "p": "어두운 목재·청동·콘크리트 같은 무게감 있는 재료와 섬세한 빛의 조절로 감정적 깊이를 만듭니다."},
  {"h": "기억과 정체성", "p": "박물관·기념관에서 공동체의 역사와 정체성을 형태(왕관 · 코로나)로 상징화합니다."},
 ],
 "works": [
  {"t": "Idea Store Whitechapel", "ko": "아이디어 스토어 화이트채플", "y": 2005, "at": "영국 런던", "p": "도서관을 시장처럼 열어 놓은 지역 학습센터", "wiki": "Idea Store"},
  {"t": "National Museum of African American History and Culture", "ko": "국립 아프리카계 미국인 역사문화박물관", "y": 2016, "at": "미국 워싱턴 D.C.", "p": "요루바 왕관에서 온 3단 청동빛 외피", "wiki": "National Museum of African American History and Culture"},
  {"t": "Sugar Hill", "ko": "슈가 힐 복합주거", "y": 2014, "at": "미국 뉴욕 할렘", "p": "어린이 박물관과 저렴 주택을 함께 품은 건물", "wiki": "Sugar Hill Development"},
  {"t": "Moscow School of Management Skolkovo", "ko": "스콜코보 경영대학원", "y": 2010, "at": "러시아 모스크바", "p": "원반 위에 막대 건물들을 얹은 캠퍼스", "wiki": "Moscow School of Management SKOLKOVO"},
 ],
},
{
 "id": "zaha", "name": "Zaha Hadid · Zaha Hadid Architects", "ko": "자하 하디드", "kind": "인물",
 "who": "Zaha Hadid (1950~2016) · 대표 Patrik Schumacher", "country": "이라크 · 영국", "years": "1950 바그다드 출생 – 2016 사망",
 "pritzker": 2004, "wiki": "Zaha Hadid",
 "life": [
  "1950년 바그다드에서 태어나 베이루트 아메리칸 대학에서 수학을 공부한 뒤 런던 AA 스쿨에서 렘 콜하스에게 배웠습니다. 1980년 런던에 사무소를 열었으나 오랫동안 \"짓지 못하는 건축가(paper architect)\"로 불렸습니다 — 홍콩 피크 공모 당선안(1983)도 지어지지 못했습니다.",
  "1993년 비트라 소방서를 시작으로 실현이 이어졌고, 2004년 여성 최초로 프리츠커상을 받았습니다. 2016년 갑작스레 세상을 떠난 뒤에도 파트너 패트릭 슈마허가 이끄는 Zaha Hadid Architects가 활동을 잇고 있습니다. 서울 동대문디자인플라자(DDP, 2014)가 그녀의 작품입니다.",
 ],
 "why": "여성 · 아랍 출신이라는 이중의 벽을 넘어 여성 최초 프리츠커 수상자가 되었고, 그때까지 \"지을 수 없다\"고 여겨진 곡면 건축을 디지털 설계·시공 기술로 현실로 만들어 21세기 건축의 이미지를 바꿨습니다.",
 "nat": "영국 · 이라크", "person": "자하 하디드", "firm": "Zaha Hadid Architects",
 "theory": [
  {"h": "해체주의에서 유체(流體)로", "p": "말레비치의 절대주의 회화에서 영향을 받은 날카로운 파편의 초기작에서, 곡면이 흐르는 후기작으로 나아갔습니다."},
  {"h": "파라메트리시즘 (Parametricism)", "p": "슈마허가 이론화한 개념 — 컴퓨터 알고리즘으로 형태를 연속적으로 변화시켜 복잡한 장(場)을 만드는 양식."},
  {"h": "지형으로서의 건축", "p": "바닥·벽·지붕을 하나의 연속된 면으로 접어 땅처럼 흐르는 공간을 만듭니다."},
 ],
 "works": [
  {"t": "Vitra Fire Station", "ko": "비트라 소방서", "y": 1993, "at": "독일 바일암라인", "p": "날카로운 콘크리트 판들이 질주하는 첫 실현작", "wiki": "Vitra Fire Station"},
  {"t": "MAXXI National Museum of 21st Century Arts", "ko": "MAXXI 국립 21세기 미술관", "y": 2010, "at": "이탈리아 로마", "p": "흐르는 띠처럼 엮인 전시 공간", "wiki": "MAXXI"},
  {"t": "Heydar Aliyev Center", "ko": "헤이다르 알리예프 센터", "y": 2012, "at": "아제르바이잔 바쿠", "p": "땅에서 솟아오른 하얀 파도 같은 곡면", "wiki": "Heydar Aliyev Center"},
  {"t": "Dongdaemun Design Plaza", "ko": "동대문디자인플라자 (DDP)", "y": 2014, "at": "한국 서울", "p": "4만5천 장의 서로 다른 알루미늄 패널로 덮인 비정형 건축", "wiki": "Dongdaemun Design Plaza"},
  {"t": "London Aquatics Centre", "ko": "런던 아쿠아틱스 센터", "y": 2011, "at": "영국 런던", "p": "물결 모양 지붕의 2012 올림픽 수영장", "wiki": "London Aquatics Centre"},
 ],
},
{
 "id": "hdm", "name": "Herzog & de Meuron", "ko": "헤어초크 & 드 뫼롱", "kind": "사무소",
 "who": "Jacques Herzog · Pierre de Meuron (1950~)", "country": "스위스", "years": "1978 설립 (바젤)",
 "pritzker": 2001, "wiki": "Herzog & de Meuron",
 "life": [
  "자크 헤어초크와 피에르 드 뫼롱은 1950년 바젤에서 태어난 어린 시절 친구로, 함께 취리히 연방공대(ETH)에서 알도 로시에게 배웠습니다. 1978년 바젤에서 사무소를 열었습니다.",
  "작은 창고·주택에서 재료 실험을 거듭한 뒤 런던 테이트 모던(2000)으로 세계적 이름을 얻었고, 2001년 두 사람이 공동으로 프리츠커상을 받았습니다. 베이징 올림픽 주경기장 「새둥지」(2008), 함부르크 엘프필하모니(2017), 홍콩 M+(2021) 등 도시의 상징을 많이 지었습니다.",
 ],
 "why": "같은 스타일을 반복하지 않고 매번 재료와 표면을 새롭게 발명하는 실험성, 그리고 테이트 모던처럼 폐산업 시설을 도시의 문화 심장으로 바꾼 성공으로 \"건축가들의 건축가\"이자 대중적 랜드마크 제작자가 되었습니다.",
 "nat": "스위스", "person": "자크 헤어초크 · 피에르 드 뫼롱", "firm": "Herzog & de Meuron",
 "theory": [
  {"h": "재료와 표면의 실험", "p": "돌을 채운 철망(도미누스 와이너리), 사진을 인쇄한 콘크리트 등 익숙한 재료를 낯설게 써서 표면이 곧 건축이 되게 합니다."},
  {"h": "예술가와의 협업", "p": "토마스 루프 · 아이웨이웨이 등 미술가와 함께 작업하며 지각(perception)의 문제를 탐구합니다."},
  {"h": "고정된 양식이 없다", "p": "작품마다 전혀 다른 모습 — 장소와 프로그램에서 매번 새로 시작한다는 태도로 유명합니다."},
  {"h": "재생과 증축", "p": "테이트 모던(화력발전소), 엘프필하모니(창고 위 증축)처럼 기존 건물을 살려 도시의 기억을 잇습니다."},
 ],
 "works": [
  {"t": "Tate Modern", "ko": "테이트 모던", "y": 2000, "at": "영국 런던", "p": "뱅크사이드 화력발전소를 미술관으로 바꾼 재생의 상징", "wiki": "Tate Modern"},
  {"t": "Beijing National Stadium", "ko": "베이징 국가체육장 (새둥지)", "y": 2008, "at": "중국 베이징", "p": "강철 줄기가 얽힌 새둥지 구조", "wiki": "Beijing National Stadium"},
  {"t": "Elbphilharmonie", "ko": "엘프필하모니", "y": 2017, "at": "독일 함부르크", "p": "벽돌 창고 위에 유리 결정이 얹힌 콘서트홀", "wiki": "Elbphilharmonie"},
  {"t": "Allianz Arena", "ko": "알리안츠 아레나", "y": 2005, "at": "독일 뮌헨", "p": "색이 바뀌는 ETFE 쿠션 외피의 축구장", "wiki": "Allianz Arena"},
  {"t": "M+", "ko": "M+ 미술관", "y": 2021, "at": "홍콩", "p": "거대한 LED 파사드를 단 아시아 시각문화 미술관", "wiki": "M+"},
 ],
},
{
 "id": "foster", "name": "Foster + Partners · Norman Foster", "ko": "노먼 포스터", "kind": "인물",
 "who": "Norman Foster (1935~)", "country": "영국", "years": "1935 맨체스터 출생 · 1967 사무소 설립",
 "pritzker": 1999, "wiki": "Norman Foster",
 "life": [
  "1935년 맨체스터 노동자 가정에서 태어나 16세에 학교를 그만두고 시청 사무원으로 일하다 맨체스터 대학 건축과에 들어갔습니다. 예일대에서 리처드 로저스를 만나 「팀 4」를 함께 했습니다.",
  "1967년 Foster Associates(현 Foster + Partners)를 세웠고, 홍콩상하이은행 본사(1986)로 하이테크 건축의 대표가 되었습니다. 1999년 프리츠커상, 귀족 작위(Lord Foster)를 받았으며, 지금도 세계 최대 규모의 설계 사무소 중 하나를 이끌고 있습니다.",
 ],
 "why": "구조와 기술을 아름다움으로 드러낸 하이테크 건축의 대표 — 홍콩상하이은행으로 고층 건물의 구조를 다시 쓰고, 베를린 국회의사당 유리 돔으로 \"투명한 민주주의\"를 상징화했습니다. 일찍부터 에너지 효율을 디자인의 중심에 둔 선구자이기도 합니다.",
 "nat": "영국", "person": "노먼 포스터", "firm": "Foster + Partners",
 "theory": [
  {"h": "하이테크 건축", "p": "구조와 설비를 드러내고 공업화된 부재로 짓는 건축 — 기술의 아름다움을 표현합니다."},
  {"h": "환경과 에너지", "p": "자연 환기·채광을 위한 아트리움과 이중 외피(거킨, 커머츠방크 타워)로 일찍부터 친환경 고층을 이끌었습니다."},
  {"h": "투명성과 민주성", "p": "독일 국회의사당의 유리 돔처럼 시민이 권력 위를 걸으며 내려다보는 열린 공간을 만듭니다."},
 ],
 "works": [
  {"t": "HSBC Building (Hong Kong)", "ko": "홍콩상하이은행 본사", "y": 1986, "at": "홍콩", "p": "다리 구조로 매달린 층 — 하이테크의 걸작", "wiki": "HSBC Main Building, Hong Kong"},
  {"t": "Reichstag Dome", "ko": "독일 국회의사당 돔", "y": 1999, "at": "독일 베를린", "p": "시민이 의회 위를 걸어 오르는 유리 돔", "wiki": "Reichstag building"},
  {"t": "30 St Mary Axe (The Gherkin)", "ko": "30 세인트 메리 액스 (거킨)", "y": 2004, "at": "영국 런던", "p": "나선형 환기 공간을 품은 오이 모양 고층", "wiki": "30 St Mary Axe"},
  {"t": "Millau Viaduct", "ko": "미요 다리", "y": 2004, "at": "프랑스 미요", "p": "세계에서 가장 높은 사장교 (구조 미셸 비를로죄)", "wiki": "Millau Viaduct"},
  {"t": "Apple Park", "ko": "애플 파크", "y": 2017, "at": "미국 쿠퍼티노", "p": "지름 460m의 고리 모양 사옥", "wiki": "Apple Park"},
 ],
},
{
 "id": "mad", "name": "MAD Architects · Ma Yansong", "ko": "MAD · 마옌쑹", "kind": "사무소",
 "who": "Ma Yansong (1975~) · Dang Qun · Yosuke Hayano", "country": "중국", "years": "2004 설립 (베이징)",
 "pritzker": None, "wiki": "Ma Yansong",
 "life": [
  "마옌쑹은 1975년 베이징에서 태어나 베이징 건축공정대학과 예일대에서 공부했고, 자하 하디드 사무소에서 일했습니다. 2004년 베이징에서 MAD를 세웠습니다.",
  "캐나다 미시소거의 곡선 고층 「앱솔루트 타워」(2012) 국제 공모 당선으로 중국 건축가 최초로 해외 랜드마크 공모를 따냈습니다. 하얼빈 오페라하우스, 2025년 개관한 로스앤젤레스 루카스 내러티브 아트 박물관 등을 지었습니다.",
 ],
 "why": "중국 건축가 최초로 북미 랜드마크 국제 공모(앱솔루트 타워)를 따내 \"중국 건축의 세계 진출\"을 상징하게 되었고, 산수화의 정신을 현대 도시에 접목한 「산수 도시」 이론으로 동양적 미래 건축의 대표가 되었습니다.",
 "nat": "중국", "person": "마옌쑹", "firm": "MAD Architects",
 "theory": [
  {"h": "산수(山水) 도시 (Shanshui City)", "p": "중국 산수화의 정신 — 자연과 인간의 감정적 관계 — 를 현대 도시의 고밀 건축에 되살리자는 이론."},
  {"h": "유기적 미래주의", "p": "곡면으로 흐르는 형태로 자연의 지형(산·물·구름)을 떠올리게 합니다."},
  {"h": "모더니즘 격자에 대한 비판", "p": "기능과 효율 중심의 상자형 도시를 넘어, 감정과 정신을 담는 도시를 주장합니다."},
 ],
 "works": [
  {"t": "Absolute World Towers", "ko": "앱솔루트 월드 타워", "y": 2012, "at": "캐나다 미시소거", "p": "몸을 비튼 듯한 곡선 고층 (\"매릴린 먼로 타워\")", "wiki": "Absolute World"},
  {"t": "Harbin Opera House", "ko": "하얼빈 오페라하우스", "y": 2015, "at": "중국 하얼빈", "p": "눈 덮인 습지에서 솟은 하얀 곡면", "wiki": "Harbin Opera House"},
  {"t": "Lucas Museum of Narrative Art", "ko": "루카스 내러티브 아트 박물관", "y": 2025, "at": "미국 로스앤젤레스", "p": "공중에 뜬 우주선 같은 박물관", "wiki": "Lucas Museum of Narrative Art"},
  {"t": "Quzhou Sports Campus", "ko": "취저우 스포츠 캠퍼스", "y": 2022, "at": "중국 취저우", "p": "풍경 속에 묻힌 언덕형 경기장", "wiki": "MAD Architects"},
 ],
},
{
 "id": "gang", "name": "Studio Gang · Jeanne Gang", "ko": "스튜디오 갱 · 지니 갱", "kind": "사무소",
 "who": "Jeanne Gang (1964~)", "country": "미국", "years": "1997 설립 (시카고)",
 "pritzker": None, "wiki": "Jeanne Gang",
 "life": [
  "지니 갱은 1964년 일리노이에서 태어나 일리노이 대학과 하버드 GSD에서 공부했고, OMA에서 일했습니다. 1997년 시카고에 Studio Gang을 세웠습니다.",
  "물결치는 발코니의 시카고 아쿠아 타워(2010)는 당시 여성이 설계한 세계 최고층 건물이었습니다. 2011년 맥아더 펠로십을 받았고, 뉴욕 자연사박물관 길더 센터(2023) 등으로 미국을 대표하는 건축가가 되었습니다.",
 ],
 "why": "물결치는 아쿠아 타워로 \"여성이 설계한 세계 최고층\" 기록과 함께, 콘크리트 발코니만으로 고층을 조각처럼 만든 아이디어로 주목받았습니다. 생태와 사회 문제를 건축으로 풀려는 실천적 태도로 미국 건축계의 대표 목소리가 되었습니다.",
 "nat": "미국", "person": "지니 갱", "firm": "Studio Gang",
 "theory": [
  {"h": "액티비즘 건축 (Actionable Idea)", "p": "건축을 사회·생태 문제를 푸는 도구로 봅니다 — 경찰서를 동네 공동체 공간으로 바꾸는 「폴리스 스테이션」 연구 등."},
  {"h": "생태계의 원리", "p": "새·물·바람 같은 자연 체계를 관찰해 형태로 옮깁니다 (철새 충돌을 줄이는 유리, 수변 생태 복원)."},
  {"h": "구조와 재료에서 출발", "p": "돌의 압축, 콘크리트 슬래브 같은 재료의 성질을 직접 실험해 형태를 찾습니다."},
 ],
 "works": [
  {"t": "Aqua Tower", "ko": "아쿠아 타워", "y": 2010, "at": "미국 시카고", "p": "발코니 판의 굴곡으로 물결치는 82층 주거", "wiki": "Aqua (skyscraper)"},
  {"t": "St. Regis Chicago (Vista Tower)", "ko": "세인트 레지스 시카고", "y": 2020, "at": "미국 시카고", "p": "세 개의 절두체를 겹친 101층", "wiki": "St. Regis Chicago"},
  {"t": "Gilder Center, American Museum of Natural History", "ko": "자연사박물관 길더 센터", "y": 2023, "at": "미국 뉴욕", "p": "협곡처럼 깎인 숏크리트 아트리움", "wiki": "Richard Gilder Center for Science, Education, and Innovation"},
  {"t": "Writers Theatre", "ko": "라이터스 시어터", "y": 2016, "at": "미국 글렌코", "p": "목재 격자 회랑이 감싼 지역 극장", "wiki": "Writers Theatre"},
 ],
},
]

# 대표 저서 · 건축가/예술가 네트워크 (나중에 더함)
_X = {
 "snohetta": {"books": ["Snøhetta Works (2009)", "Snøhetta: Collective Intuition (2019)"],
  "net": [{"n": "오슬로 오페라하우스 조경 · 미술 협업 작가들", "r": "건축 · 조경 · 미술 통합 설계"},
          {"n": "크레이그 다이커스", "r": "공동 창립자 (미국 출신)"},
          {"n": "Powerhouse 연합", "r": "에너지 플러스 건물 연구 협업"}]},
 "oma": {"books": ["Delirious New York (1978)", "S,M,L,XL (1995, 브루스 마우와)", "Junkspace (2002)", "Content (2004)"],
  "net": [{"n": "엘리아 젠겔리스", "r": "AA 스승 · OMA 공동 창립"},
          {"n": "자하 하디드", "r": "AA 제자 · 초기 OMA 파트너", "id": "zaha"},
          {"n": "MVRDV (비니 마스)", "r": "OMA 출신", "id": "mvrdv"},
          {"n": "BIG (비아케 잉엘스)", "r": "OMA 출신", "id": "big"},
          {"n": "브루스 마우", "r": "그래픽 디자이너 — 『S,M,L,XL』 공저"},
          {"n": "세실 발몬드", "r": "구조 엔지니어 — 쿤스트할 · CCTV 협업"},
          {"n": "마리오 보타 · 장 누벨", "r": "리움 미술관 공동 설계", "id": "nouvel"}]},
 "mvrdv": {"books": ["FARMAX: Excursions on Density (1998)", "KM3: Excursions on Capacities (2005)", "The Vertical Village (2012)"],
  "net": [{"n": "렘 콜하스 · OMA", "r": "비니 마스 · 야코프 판레이스의 전 직장", "id": "oma"},
          {"n": "델프트 공대 · 「Why Factory」", "r": "비니 마스가 이끄는 연구소"}]},
 "big": {"books": ["Yes Is More: An Archicomic on Architectural Evolution (2009)", "Hot to Cold: An Odyssey of Architectural Adaptation (2015)", "Formgiving (2020)"],
  "net": [{"n": "렘 콜하스 · OMA", "r": "잉엘스의 전 직장", "id": "oma"},
          {"n": "JDS (율리앵 드 스메트)", "r": "PLOT 공동 창립 파트너"},
          {"n": "서펜타인 갤러리", "r": "2016 파빌리온"}]},
 "adjaye": {"books": ["Making Public Buildings (2006)", "African Metropolitan Architecture (2011)", "Adjaye: Form, Heft, Material (2015)"],
  "net": [{"n": "크리스 오필리 · 올라퍼 엘리아손 등 미술가", "r": "작업실 · 파빌리온 협업"},
          {"n": "데이비드 치퍼필드", "r": "초기 근무", "id": "chipperfield"},
          {"n": "에두아르두 소투 드 모라", "r": "초기 근무", "id": "soutodemoura"}]},
 "zaha": {"books": ["Zaha Hadid: The Complete Buildings and Projects (1998)", "Zaha Hadid Architects: Redefining Architecture and Design (2017)"],
  "net": [{"n": "렘 콜하스 · 엘리아 젠겔리스", "r": "AA 스승 · OMA 파트너", "id": "oma"},
          {"n": "카지미르 말레비치 · 러시아 구성주의", "r": "회화적 영감"},
          {"n": "파트리크 슈마허", "r": "파트너 · 「파라메트리시즘」 이론가"},
          {"n": "이소자키 아라타", "r": "홍콩 피크 공모 심사 — 발굴", "id": "isozaki"},
          {"n": "필립 존슨", "r": "1988 MoMA 「해체주의 건축」전", "id": "johnson"}]},
 "hdm": {"books": ["Natural History (2002)", "Herzog & de Meuron: The Complete Works (2005~)"],
  "net": [{"n": "알도 로시", "r": "ETH 취리히 스승", "id": "rossi"},
          {"n": "요제프 보이스", "r": "미술가 — 협업 · 재료관에 영향"},
          {"n": "아이웨이웨이", "r": "베이징 올림픽 주경기장 · 서펜타인 파빌리온 협업"},
          {"n": "토마스 루프 · 레미 초그", "r": "사진가 · 미술가 — 에베르스발데 도서관 등 외피 협업"}]},
 "foster": {"books": ["Norman Foster: Works (1~6권, 2002~)", "Foster: Catalogue (2001)"],
  "net": [{"n": "리처드 로저스", "r": "예일 동기 · 팀 4 공동 창립", "id": "rogers"},
          {"n": "버크민스터 풀러", "r": "멘토 · 협업자"},
          {"n": "폴 루돌프", "r": "예일 스승"},
          {"n": "오브 아럽 엔지니어링", "r": "구조 협업"}]},
 "mad": {"books": ["Shanshui City (2015)", "MAD Works (2016)"],
  "net": [{"n": "자하 하디드", "r": "마옌쑹의 전 직장", "id": "zaha"},
          {"n": "조지 루카스", "r": "루카스 서사예술박물관 건축주"},
          {"n": "중국 산수화 전통", "r": "「산수 도시」 개념의 뿌리"}]},
 "gang": {"books": ["Reverse Effect: Renewing Chicago's Waterways (2011)", "Building in the Shadows (2023)"],
  "net": [{"n": "렘 콜하스 · OMA", "r": "지니 갱의 전 직장", "id": "oma"},
          {"n": "하버드 GSD", "r": "모교 · 교수"},
          {"n": "시카고 시", "r": "강변 재생 연구 협업"}]},
}
for _a in A:
    _a.update(_X.get(_a["id"], {}))
